### ISSUE TITLE
Looking for beta testers 💣💥

### ISSUE THREAD

**Issue by liyasthomas** [hoppscotch/hoppscotch#1002]
# **Hoppscotch is looking for beta testers 👨‍💻👩‍💻**

Try to install and run new features, if you find bugs, please [open a dedicated issue](https://github.com/hoppscotch/hoppscotch/issues/new).

If you have general feedback, please reply here. In particular we're looking for high level feedback:

## Recommended Setup
There are 3 different builds. The differences between them are:

1. Production: [hoppscotch.io](https://hoppscotch.io).
2. Staging: nearly exact replica of a production environment but with new improvements for testing.
3. Local: proposed development environment for testing new feature branches.

You can find the latest release for Postwoman on the production build hosted on [hoppscotch.io](https://hoppscotch.io). First priority goes to this build. They're important and bugs should be reported ASAP.

[How to set up local development environment?](https://github.com/hoppscotch/hoppscotch#developing-)

_will update more informations soon_

## General testing
- Is there any feature you need that is missing?
- Can the interface be simplified?
- Do you have suggestions for better function/classes names?
- Can the docs be improved?
- Help with translations?

## Testing
While we love to see you using this in your everyday activity, at this point the team is looking for feedback that involves:

- Errors in common scenarios
- Errors that can be reproduced consistently
- Errors in new features/improvements/patches/bug fixes that can be shared with the contributors

So if you find something that breaks, a good bug report is invaluable to the contributors.

This will help the contributors view the repository in the right state and help with reproducing the problem.
With all those details in hand, please [file an issue here](https://github.com/hoppscotch/hoppscotch/issues/new).

## Translations
To provide a localized experience for users around the world, you can add you own translations.
Start here: [TRANSLATIONS.md](../blob/master/TRANSLATIONS.md)

## Thanks
_If you've read this far, thank you for taking time out to participate ❤️._

**Comment by amerireza** [comment]
Do you need beta testers to simply submit new issues? Don't you want them to consider the roadmap?
How will this issue be closed? What is the definition of done here?

**Comment by liyasthomas** [comment]
It's basically an announcement for beta testers with general instructions for testing. Development team follows roadmap and release them of experiments channel. The corresponding feature releases are announced in Discord server too. Discord is used for communication.

**Comment by bolajiscott** [comment]
is the testing still on?

**Comment by liyasthomas** [comment]
@bolajiscott yes, testing is an ongoing process. Feel free to test em out and report issues.

**Comment by liuxueyiTest** [comment]
我在的本地安装部署的，点击login 没有任何反应。不能实现接口的共享。

**Comment by liyasthomas** [comment]
@liuxueyiTest is there any errors in console logs?

**Comment by liuxueyiTest** [comment]
&nbsp;
&nbsp;I click login, and then I pop up a box, and then it's gone.


------------------&nbsp;Original&nbsp;------------------
