### ISSUE TITLE
iOS Home Bar covers content

### ISSUE THREAD

**Issue by NBTX** [hoppscotch/hoppscotch#1003]
**Describe the bug**
Currently on iOS the app content is partially obscured by the bar at the bottom of the screen used for gesture based navigation (known as the ‘Home Bar’).

![77F12CE4-893C-44A3-A8AF-98C8918333E7](https://user-images.githubusercontent.com/43181178/87842513-df9cac00-c8a4-11ea-8ca8-3172ada2cd02.png)

**To Reproduce**
Open the Postwoman PWA on a modern iOS device *without a physical home button.*

**Expected behavior**
Padding should be applied such that the home bar does not obscure the app.

**Additional context**
- Note(1): I have not included information about the specific browser or device as nearly all iOS devices run iOS 13 and **all browsers on iOS installed through the App Store** must use WebKit.
- Note(2): Information on the iOS SafeArea (the area of the screen that is not obscured or the padding that needs to be applied such that content is not obscured) is provided by Apple via their WebKit blog: https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by abhijeet-pathak** [comment]
I would like to take this up.

**Comment by liyasthomas** [comment]
Great! Assigning this to you.

**Comment by AndrewBastin** [comment]
@abhijeet-pathak how's it going ?

**Comment by liyasthomas** [comment]
@NBTX let me know if this deploy preview fixes the issue.
Deploy preview: https://hoppscotch-8rc2a54tx.vercel.app/

**Comment by tonybatty** [comment]
I have created a PR to fix this issue on #1221
