### ISSUE TITLE
JSON not showing up in the correct format

### ISSUE THREAD

**Issue by jaisharx** [hoppscotch/hoppscotch#1023]
**Describe the bug**
I am trying out the OMDb APIs with postwoman, and with every request there is invalid json message showing up and the json returned although correct isn't nicely formatted, it's all in one liner.

**To Reproduce**
1. Make an account on OMDb to get the api keys
2. Make any simple request, like I did https://www.omdbapi.com/?apikey=[your_api]&i=tt6333092
3. The JSON will be returned successfully, which although correct will be appended with an "Invalid JSON" message.
4. I've also tried the "Expand response" button as well, but it seems to do nothing. 

**Expected behavior**
Should show nicely formatted JSON in the view.

**Screenshots**
![invalid json](https://user-images.githubusercontent.com/55892116/88366612-3889aa00-cda7-11ea-8558-77239d60a852.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 V2004 | Build 19041
 - Browser : New MS Edge (based on chromium 84)
 - Version Edge 84

**Additional context**
I've the chrome ext for postwoman installed as well, if that's helpful. Thanks.

**Comment by jaisharx** [comment]
Oops. It's working now! idk how but sorry 🙇‍♀️

**Comment by jaisharx** [comment]
Actually it's still a problem. 

So what's happening is pairs of queries object are being appended sometimes in the fetch request. So for ex:

It's throwing error with url like: https://postwoman.io/?method=GET&url=http://www.omdbapi.com&path=/&params=%5B%7B%22key%22:%22apikey%22,%22value%22:%22[my_key]%22%7D,%7B%22key%22:%22i%22,%22value%22:%22tt1285016%22%7D%5D

Which when put into a url decoder is:
https://postwoman.io/?method=GET&url=http://www.omdbapi.com&path=/&params=[{"key":"apikey","value":"[my_key]"},{"key":"i","value":"tt1285016"}]

**Comment by liyasthomas** [comment]
Its an issue with the extension. Turn off extension from Settings > extension and try again.

@AndrewBastin

**Comment by AndrewBastin** [comment]
Yeah, I am reopening this issue because it is something I am working on finding on it.

I haven't pinned down the reason for this yet (maybe some issues with the communication in between), but it seems to only affect certain sites and not others.

**Comment by liyasthomas** [comment]
Same issue was there in Proxy mode #1070 after introducing Lenses.
Fix was in this commit: https://github.com/hoppscotch/proxyscotch/commit/8c338414a1d826b846f6d9689cbbb8b37e69ed8c

**Comment by AndrewBastin** [comment]
Well, I added a temporary hacky fix for the issue (explicitly remove the null characters from the end). Will get around with a proper fix once I get around that.

Meanwhile, closing this issue.
