### ISSUE TITLE
[website] use svg instead of font-icons

### ISSUE THREAD

**Issue by dym-sh** [hoppscotch/hoppscotch#1025]
not sure if that's a a bug report or a feature request, but it is existing and has negative impact, so its a bug.

![postwoman font-icons](https://user-images.githubusercontent.com/59403389/88475453-31da6e80-cf30-11ea-833d-d0134e878dfc.png)

not many places still use this technology, and for a good reason

**Comment by liyasthomas** [comment]
Oops. I noticed this glitch on very first load of app. From second load onwards, icon font will be used from cache. I guess it's possible to replace icon font with SVGs since we're already using SVGs for some custom icons. But is there any other effective implementations?

**Comment by liyasthomas** [comment]
@dym-sh Is this feature mandatory? I can't find any hard trouble with the initial 1 second delay for loading the icon font. This delay is not even noticeable after initial load because of pre-fetch and caching. If you insist I can work on a solution with [SVG module](https://github.com/nuxt-community/svg-module).

cc: @AndrewBastin

**Comment by dym-sh** [comment]
the problem is when 3rd-party fonts are disabled or unsupported – you'd get the thing on screenshot, no matter the delay

**Comment by dym-sh** [comment]
im gonna try to solve this issue now, should not take too long

**Comment by AndrewBastin** [comment]
Well, I think if we can get a proper implementation going, SVGs will be better than icon fonts.

Assigning to you @dym-sh !

**Comment by liyasthomas** [comment]
@dym-sh if you're interested in working on this feature, I've made a working starting point for you. Checkout https://github.com/hoppscotch/hoppscotch/pull/1091 and follow the steps described in it to change remaining instances for icon font.

Let me know if you've any doubts.
