### ISSUE TITLE
Spaces in the response caused parsing errors

### ISSUE THREAD

**Issue by se7en-eeen** [hoppscotch/hoppscotch#1070]
**Describe the bug**
Extra spaces cause parsing errors

**Screenshots**
[image](https://ae01.alicdn.com/kf/U1643df3fbf304fb5a09e586dd590b771x.jpg)

**Desktop (please complete the following information):**
 - OS: win10 1909
 - Browser chrome 84.0.4147.125
 - Version 1.9.9

**Comment by liyasthomas** [comment]
Can you check whether the extension is turned on from https://postwoman.io/settings > Extension

**Comment by se7en-eeen** [comment]
> Have you installed the browser extension?
> Can you check whether the extension is turned on from https://postwoman.io/settings > Extension

yes, extension installed
[image](https://ae01.alicdn.com/kf/U4951457589a5489395c28afd1b52681fQ.jpg)

**Comment by liyasthomas** [comment]
@AndrewBastin I guess there's an issue when extension is turned on — few spaces are appended in response which in turn caused parsing warning.

Sam also had this issue when proxy is turned on after introducing Lenses. He solved it by removing base64 padding. https://github.com/postwoman-io/proxywoman/commit/8c338414a1d826b846f6d9689cbbb8b37e69ed8c
