### ISSUE TITLE
Linter error is shown for response body if response is a JSON Array

### ISSUE THREAD

**Issue by amodmahajan2016** [hoppscotch/hoppscotch#1097]
I hit an API that gives a response in a JSON array. 
https://restful-booker.herokuapp.com/booking

Response - 
[{"bookingid":7},{"bookingid":4},{"bookingid":5},{"bookingid":6},{"bookingid":10},{"bookingid":9},{"bookingid":1},{"bookingid":12},{"bookingid":2},{"bookingid":3},{"bookingid":8},{"bookingid":11}]

But postWoman gives an error:-
![image](https://user-images.githubusercontent.com/20769876/90635834-5a136f80-e247-11ea-9a28-34226a30c3ad.png)

**Comment by liyasthomas** [comment]
Probably an issue with language selector in JSON lens.
https://github.com/hoppscotch/hoppscotch/blob/9734e4d859e46453fcd3ca3366c4f54a81354417/components/lenses/renderers/JSONLensRenderer.vue#L46

Will look into it ASAP.

**Comment by AndrewBastin** [comment]
@amodmahajan2016 it should be fixed now. But please feel free to reopen if it still persists ^_^
