### ISSUE TITLE
Character '%' is not accepted on query parameter value

### ISSUE THREAD

**Issue by blikblum** [hoppscotch/hoppscotch#1098]
**Describe the bug**
Adding a query parameter with character '%' gives an error "URIError: malformed URI sequence"

**To Reproduce**
1. Go to Request URL and add any valid URL (e.g. http://localhost/people)
2. Click on Parameters > Add new
3. Add a parameter with 'name' as name and value as 'ELIAS%'
4. Click send

**Expected behavior**
A request should be sent with the query param value encoded: e.g: http://localhost/people?name=ELIAS%25

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Firefox
 - Version 79

**Smartphone (please complete the following information):**
--

**Additional context**

**Comment by liyasthomas** [comment]
Must be an issue with `encodeURIComponent()`. Will look into it ASAP.

**Comment by liyasthomas** [comment]
This issue seems to be quite weird. I just tested this on my phone's browser and it is working as expected.

@blikblum can try to replicate this from your phone's browser?
