### ISSUE TITLE
Request that returns status code 500 is stuck

### ISSUE THREAD

**Issue by blikblum** [hoppscotch/hoppscotch#1105]
**Describe the bug**
A GET request that returns status code 500 is stuck (no result is displayed and not possible to cancel) when used in Firefox with the browser extension

**To Reproduce**
1. Send a request that returns status code 500 (e.g. https://postman-echo.com/status/500)

**Expected behavior**
The returned value should be displayed

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [79]

**Smartphone (please complete the following information):**

**Additional context**

EDIT: add info to about browser extension

**Comment by blikblum** [comment]
I did some more tests:

- Firefox 79 Desktop (windows 10): stuck
- Firefox Mobile (Android): works
- MS Edge (Chromium): works

So the issue is specific for Firefox in desktop

**Comment by blikblum** [comment]
Found the reason: if i disable the Hoppscotch Browser Extension, it works

**Comment by liyasthomas** [comment]
I think it's only a minor browser specific issue with Extension. On both mobile and PC there seems to be no issue. @AndrewBastin

**Comment by AndrewBastin** [comment]
@blikblum Thanks for the info, I will look into it.

**Comment by AndrewBastin** [comment]
Turns out it is an issue with the Firefox's strong memory ownership system. I have fixed it in the extension with commit https://github.com/hoppscotch/hoppscotch-extension/commit/c760da9ecbe587385ab8706d5c9cc59372f08c68

The fix will be rolled out to Firefox by the end of the day with the 0.17 extension update.

Closing the issue.

**Comment by blikblum** [comment]
Many thanks
