### ISSUE TITLE
Specific language on PWA 

### ISSUE THREAD

**Issue by abc1236762** [hoppscotch/hoppscotch#1108]
I am using Microsoft Edge (Chromium based) on Windows 10 to browse hoppscotch.
When I set the language of hoppscotch to 繁體中文, the url seems goto https://hoppscotch.io/tw.
And after I install hoppscotch as a PWA app in Microsoft Edge (Chromium based), I pin it to taskbar and close it.
After I clicked the icon that I just pinned to open hoppscotch as a PWA app, I got English interface, not 繁體中文.
It seems the browser just use https://hoppscotch.io to install hoppscotch but not https://hoppscotch.io/tw.

So, how can I install hoppscotch as a PWA app with specific language?
Or, just save the language in to localStorage and use `https://hoppscotch.io` to show specific language, not `https://hoppscotch.io/<lang>` #1062

**Comment by liyasthomas** [comment]
Let me look into this.
