### ISSUE TITLE
Collapsed Editor can be resized and dragging down doesn't increase code view

### ISSUE THREAD

**Issue by JoelJacobStephen** [hoppscotch/hoppscotch#1110]
**Describe the bug**
When I pull the resize button of the code editor, it doesn't the resize the code in the editor.

**To Reproduce**
1. Click the resize button on the code editor and drag it down
2. The code doesn't resize

**Expected behavior**
I expected the code to resize as I drag down the button.

**Screenshots**
<img width="1354" alt="Capture" src="https://user-images.githubusercontent.com/70131076/91014653-67de4180-e607-11ea-948f-6c8605b774dc.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
When I press the expand button, it works though.

**Comment by liyasthomas** [comment]
I'll look into it.

refer: https://jsfiddle.net/6b2tfspe/1/
https://stackoverflow.com/questions/27534263/making-ace-editor-resizable

**Comment by AndrewBastin** [comment]
I played around a bit to see what is causing it and found that the `maxLines` property might be relevant

Here is a snippet from JSON Lens Renderer:
https://github.com/hoppscotch/hoppscotch/blob/3cd2a2a0f9c9f507be6736b829f637dba336e10f/components/lenses/renderers/JSONLensRenderer.vue#L43-L57

**Comment by AndrewBastin** [comment]
Another possible option is to restart the efforts for moving to CodeMirror. I had attempted before, just that the only issue was that editor expanded the response panel.

Ace is really difficult to work with and pretty much impossible to test the functionality of due to its weird Webpack Resolution thingy and the codebase feels really legacy.

CodeMirror is pretty modern, supports mobile devices and we already have a sorta working implementation going.

You can check out the stale branch in my fork. https://github.com/AndrewBastin/hoppscotch/tree/feat/move-to-codemirror

**Comment by liyasthomas** [comment]
Let me check.

**Comment by LeoMartinDev** [comment]
> Another possible option is to restart the efforts for moving to CodeMirror. I had attempted before, just that the only issue was that editor expanded the response panel.
> 
> Ace is really difficult to work with and pretty much impossible to test the functionality of due to its weird Webpack Resolution thingy and the codebase feels really legacy.
> 
> CodeMirror is pretty modern, supports mobile devices and we already have a sorta working implementation going.
> 
> You can check out the stale branch in my fork. https://github.com/AndrewBastin/hoppscotch/tree/feat/move-to-codemirror

What about monaco ? It's the VSCode editor https://github.com/egoist/vue-monaco

**Comment by liyasthomas** [comment]
Hi @JoelJacobStephen ,
@AndrewBastin once implemented a [codemirror port](https://github.com/AndrewBastin/hoppscotch/tree/feat/move-to-codemirror). We refused monaco because it doesn't had mobile responsive support. We can consider it if it is responsive. ANdrew wdyt?

**Comment by LeoMartinDev** [comment]
> Hi @JoelJacobStephen ,
> @AndrewBastin once implemented a [codemirror port](https://github.com/AndrewBastin/hoppscotch/tree/feat/move-to-codemirror). We refused monaco because it doesn't had mobile responsive support. We can consider it if it is responsive. Andrew, wdyt? It looks like now there's a monaco editor component for Vue.

Indeed, from their Readme :

> ❓ Is the editor supported in mobile browsers or mobile web app frameworks?
> No.

**Comment by AndrewBastin** [comment]
> Hi @JoelJacobStephen ,
> @AndrewBastin once implemented a [codemirror port](https://github.com/AndrewBastin/hoppscotch/tree/feat/move-to-codemirror). We refused monaco because it doesn't had mobile responsive support. We can consider it if it is responsive. Andrew, wdyt? It looks like now there's a monaco editor component for Vue.

To be honest, I prefer Monaco as well as it is a lot more battle tested and advanced compared to CodeMirror, but Monaco doesn't support mobile devices as stated by @LeoMartinDev and we don't exactly have a definite plan to drop mobile devices just yet. But if that happens and we decide to drop mobile support for Hoppscotch, we can choose to move ahead with Monaco.
