### ISSUE TITLE
Support custom path on socket.io

### ISSUE THREAD

**Issue by HerbertChu** [hoppscotch/hoppscotch#1114]
**Describe the solution you'd like**
Unable to using specific custom path on socket.io, if server not using default path '/socket.io', need a extra column for user to input with custom path which default with '/socket.io' 
![image](https://user-images.githubusercontent.com/2661389/91135482-9e3bbf80-e6e0-11ea-854e-e79e9279ca61.png)

**Comment by liyasthomas** [comment]
Can you make use of the issue ticket template to create issue? At least give a clear and concise explanation of the issue you're facing.
