### ISSUE TITLE
[documentation module]:The collections file won't be imported twice(click the clear button or delete all the content manually)

### ISSUE THREAD

**Issue by kisscelia** [hoppscotch/hoppscotch#1124]
**Describe the bug**
The collections file won't be imported twice(click the clear button or delete all the content manually).

**To Reproduce**
1. Go to 'documentation page'
2. Click on 'import collections' and import a file  <---  OK.
3. Click clear button and import the file.   <--- Not imported

**Expected behavior**
File was imported successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/13063673/91425965-6c685b80-e88e-11ea-9247-ef8fe9579319.png)
![image](https://user-images.githubusercontent.com/13063673/91426078-96ba1900-e88e-11ea-9e76-bd17cb993f93.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser edge or chrome

**Comment by liyasthomas** [comment]
Oops, currently we detect the change in file input box which why selecting the same file doesn't fire import. Looking into it.
