### ISSUE TITLE
Implement HoppScotch on a personal AWS EC2

### ISSUE THREAD

**Issue by EinSoldiatGott** [hoppscotch/hoppscotch#1129]
Hi, is the project created with the idea of anybody to implement on his own server? can I store locally my collections?

I cloned the repo to my EC2 machine and it's working, I can access with my AWS IP URL, but I think that all my requests are being saved on your database. I think that because I didn't create any DB on my machine.

I opened the .env file but I don't know that to set in the FireBase project
I added a collection but I cannot find it in my local files
I modified some strings on ./store/state.js but they're not reflected on my dashboard
I modified some strings on nuxt.config.js like name: "aHoppscotch" and they are refelected correctly.

So some stuff seems to be read from my machine but other content is in your server?

![image](https://user-images.githubusercontent.com/11496215/91649903-54373e80-ea3e-11ea-918a-843e2b6e3d9e.png)

Thanks and my best regards

**Comment by AndrewBastin** [comment]
Hi there,

Right now, Hoppscotch isn't designed to allow for personal instances, we do have docker images and stuff. But the code right now is pretty tied to Firebase and to allow for personal instances requires a lot of reworking on the core code.

If this issue gets enough support though, we can consider it.

Thanks for using Hoppscotch!

**Comment by EinSoldiatGott** [comment]
Hi @AndrewBastin so the idea is to use the project in https://hoppscotch.io/ and to keep the request headers and credentials private we should log in using Google?

**Comment by liyasthomas** [comment]
Wiki on Hosting: https://github.com/hoppscotch/hoppscotch/wiki/Hosting#firebase-dependency

Here's how Hoppscotch works.
Front end: Vue / Nuxt
Database: Firebase Firestore
Authentication: Firebase Authentication
Hosting: JAM stack (static)

Basically you can host and use Hoppscotch in any server without any changes — but if you wish to have a private instance, the only required changes are in .env file where you've to provide your own Firebase Keys, Google Analytics and Tag manager IDs. If any of them are not provided/ missing Hoppscotch will use it's production environment value.
