### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by akshitkr** [hoppscotch/hoppscotch#1130]

**Comment by liyasthomas** [comment]
Hi there, we've move to hoppscotch.io

https://downforeveryoneorjustme.com/hoppscotch.io?proto=https

**Comment by akshitkr** [comment]
thanks a lot

**Comment by kisscelia** [comment]
It's time to remove all the keywords: postwoman, pw...etc...  :)

**Comment by liyasthomas** [comment]
No need for that  Hoppscotch was formerly Postwoman. Everybody knows that. And for those who don't, keywords helps. Moreover I guess crawlers doesn't give great importance to meta keywords now a days.

**Comment by ShenYj** [comment]
renamed?

**Comment by liyasthomas** [comment]
Yes project Postwoman has been renamed to Hoppscotch.

**Comment by WeslyG** [comment]
it's very interesting to see the tweet that blamed the author and forced him to change the name, but I think I'll live happily ever after)

**Comment by WeslyG** [comment]
it's very interesting to see the tweet that blamed the author and forced him to change the name, but I think I'll live happily ever after)

**Comment by ademidun** [comment]
> it's very interesting to see the tweet that blamed the author and forced him to change the name, but I think I'll live happily ever after)

@WeslyG I actually came to this issue looking for this. Do you have a link to the tweet or resources that give ore context on the name change please?

**Comment by liyasthomas** [comment]
@ademidun here's the link to announcement article I wrote a while back: https://dev.to/liyasthomas/postwoman-is-changing-name-igp
