### ISSUE TITLE
Make a Mobile port with vue-native

### ISSUE THREAD

**Issue by DGKSK8LIFE** [hoppscotch/hoppscotch#1131]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I'd like the app to be ported to mobile in a PWA-esque way (perhaps via vue native or ionic)

**Describe alternatives you've considered**
You could write native for better performance and more reliability

**Comment by liyasthomas** [comment]
PWA being very lightweight and effective I can't find any advantages for Native app over PWA in case of Hoppscotch. Fee free to discuss over this topic.

**Comment by DGKSK8LIFE** [comment]
Yeah that's fair. Perhaps you wanted AR functionality or just a UI Kit that's native specific. I'd definitely prefer PWA because it would be a lot easier to build/faster. What does the PWA ecosystem look like in vue? (I'm mainly a react person and haven't messed with vue much)

**Comment by AndrewBastin** [comment]
@DGKSK8LIFE I am kinda the person working with getting Hoppscotch to be native and we have discussed a lot about what we want from a native app.

We really don't want to maintain a separate codebase for the mobile app as of right now. We have more than enough in the plate with the current codebase 😅.

I am working on a system that allows for Hoppscotch to work on iOS and Android without the extra codebase but it is not a high priority right now as we don't seem to see much need for the mobile apps right now. But if and when there is, I will get into implementing it.

**Comment by DGKSK8LIFE** [comment]
Nice. But why not use vue-native? @AndrewBastin
