### ISSUE TITLE
Fix Firefox addon link

### ISSUE THREAD

**Issue by arshxyz** [hoppscotch/hoppscotch#1146]
The Firefox addon link in the header points to `https://addons.mozilla.org/en-US/firefox/addon/postwoman/` while I believe the correct addon URL is `https://addons.mozilla.org/en-US/firefox/addon/hoppscotch/` (published by @AndrewBastin )

I'm new to Github so my apologies if I made a mistake. I have a PR ready.

**Comment by liyasthomas** [comment]
@arshxyz Thanks for this PR.

cc: @AndrewBastin
