### ISSUE TITLE
Import cURL always fails

### ISSUE THREAD

**Issue by arjun-1** [hoppscotch/hoppscotch#1159]
## Description
Import cURL always fails (even for cURL produced from 'Generate code')

## To Reproduce

1. Go to hoppscotch.io
2. Click on 'import cURL'
3. Paste
```
curl -X GET \
  'https://hoppscotch.io/'
```
4. Click 'Import'
4. See error 'cURL is not formatted properly

## Expected behavior
Import of valid cURL should succeed

## Desktop
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. We're working on a fix.

**Comment by liyasthomas** [comment]
Issue was introduced in the latest `yargs-parser` dependency. I've pushed a fix, it would be great if you could check and verify: https://hoppscotch.io

**Comment by arjun-1** [comment]
The issue was fixed, though there seems to be trouble with other cURL commands. I'll open another issue for that

**Comment by savy-91** [comment]
I am experiencing this with the current v1.9.9 version online, both on latest Chrome and Firefox browser. I am unable to import any curl command while it does not show any error.

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. We're checking what's causing this behaviour.

**Comment by savy-91** [comment]
I just noticed that I am getting this error in console

![image](https://user-images.githubusercontent.com/6215122/103352864-b2853400-4aa7-11eb-99e6-9169c950e80e.png)

**Comment by liyasthomas** [comment]
Looks like this is caused by a recent refactor. I'm pushing a fix now. Fix will be live in about 5 mins.

**Comment by liyasthomas** [comment]
Issue has been fixed. Force refresh to take effect.

**Comment by bermudi** [comment]
I'm not able to import cURL command in https://hoppscotch.io/

some kind of regression?
