### ISSUE TITLE
Import cURL fails for single line commands

### ISSUE THREAD

**Issue by arjun-1** [hoppscotch/hoppscotch#1160]
## Description
Import cURL fails for single line commands
## To Reproduce

1. Go to hoppscotch.io
2. Click on 'import cURL'
3. Paste
```
curl -X GET 'https://hoppscotch.io/'
```
4. Click 'Import'
4. See error 'cURL is not formatted properly

## Expected behavior
Import of valid cURL should succeed

## Desktop
 - OS: Ubuntu 18.04.5 LTS
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by liyasthomas** [comment]
Oops, working on a fix.

Do update this issue for any other issues regarding cURL import feature — no need for seperate issues.
