### ISSUE TITLE
Easily restore from history

### ISSUE THREAD

**Issue by subins2000** [hoppscotch/hoppscotch#1161]
**Is your feature request related to a problem? Please describe.**
A one-click way to restore item from history

**Describe the solution you'd like**
Click on the item in history and restore it

**Describe alternatives you've considered**
Currently you need to click, then choose "Restore" which is not so quick

**Additional context**
Perhaps a restore button in the history item that when clicked restores.

**Comment by liyasthomas** [comment]
Yes — I agree. Current history restore flow sucks. Thanks for bringing this up. Will work on this.

**Comment by subins2000** [comment]
One more thing, it'd be better if the latest item should be on top in the history list not wayyy below

**Comment by subins2000** [comment]
Awesome! Much better now

**Comment by liyasthomas** [comment]
Let me know if there's any other ways we can improve the History section. Kindly comment in this issue itself.
