### ISSUE TITLE
Requests being replaced inside folder

### ISSUE THREAD

**Issue by IgorMaineti** [hoppscotch/hoppscotch#1184]
**Describe the bug**
Editing a folder path of a request will make it replace any requests inside the folder it was forwarded.

**To Reproduce**
Create a collection
Create one folder
Create two requests
Edit the path of the first request to go into the folder created earlier
Now edit the path of the second request to go into the same folder
Now the folder should have one request, it is the last one that you forwarded.

**Expected behavior**
The requests shouldnt replace any other requests previously on the folder.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Firefox
 - Version 1.9.9

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. Working on a fix now.

**Comment by liyasthomas** [comment]
This issue has been fixed in #1194
