### ISSUE TITLE
Error when requesting a get request to my Strapi API

### ISSUE THREAD

**Issue by dertrockx** [hoppscotch/hoppscotch#1193]
**Description**
So whenever I send a get request to my local strapi project (i.e. the default one, localhost:1337), it returns this response
```javascript
TypeError: B.a.currentSettings[2] is undefined
```
however when I visit the url, the response is okay. That is, just a normal JSON response

**Screenshots**
Here are screenshots pertaining to this bug.

*Screenshot of web app w/ response*
![Screenshot from 2020-09-28 21-15-29](https://user-images.githubusercontent.com/19862244/94437115-e5313f00-01cf-11eb-90a8-6068b142fc4f.png)

*Here's a screenshot of the console*
![Screenshot from 2020-09-28 21-16-01](https://user-images.githubusercontent.com/19862244/94437156-f5491e80-01cf-11eb-98e9-e79a9ebc4f04.png)

**Device Information**
OS: Ubuntu 20.04
Browser: Firefox for Ubuntu
Version: 81.0 ( 64-bit )

**Comment by liyasthomas** [comment]
Can you sign out and sign in again and try?

**Comment by dertrockx** [comment]
I did that, and it worked! 
But I dunno why tho. But still, it worked. Thanks!

**Comment by liyasthomas** [comment]
This happens when you initially sign up / log in to Hoppscotch, we check your Sync settings (you can find it on Settings > Account). If there's some network issue while signing in, data sync might've take a bit delay. Which caused this issue. Anyways, feel free to ping me for any doubts.
