### ISSUE TITLE
Exporting to cURL doesn't include JSON raw data

### ISSUE THREAD

**Issue by LuisMayo** [hoppscotch/hoppscotch#1195]
**Describe the bug**
When trying to generate cURL of a petition when the JSON has been specified without processing, the cURL-generated code doesn't include said JSON

**To Reproduce**
1. Go to https://hoppscotch.io/
2. Change petition method to POST
3. Enable the "unprocessed data" switch
4. Write a minimum JSON object on the text area. Something like this may work.
```JSON
{
    "test": 1
}
```
5. Click the "show code" button
6. Select "cURL" under petition type

**Expected behavior**
When generating the code, the argument to cURL's "-d" flag should be the JSON I typed, instead of an empty JSON*

*It isn't actual an empty JSON, it's a JSON made using the parameters list if you disable the unprocessed data switch

**Screenshots**
![image](https://user-images.githubusercontent.com/20229636/94543049-dab38b80-0249-11eb-89c3-4989809210e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge(chromium)
 - Version: 85.0.564.63

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. It seems like only key-value pair data is being take in to consideration for code gen. Will fix this ASAp.

**Comment by LuisMayo** [comment]
¡Thanks to you for answering so quickly!

**Comment by liyasthomas** [comment]
This issues was a result of a typo in codegen function. Instead of `rawInput` it was `rawInputs`. Pushing a fix now.
