### ISSUE TITLE
Javascript's code generation not working with body

### ISSUE THREAD

**Issue by LuisMayo** [hoppscotch/hoppscotch#1197]
**Describe the bug**
When trying to generate JS code for an HTTP method which requires a body (PUT-POST-PATCH) the code generation won't work. It won't change the content of the output generated code text-area.
In case JS was the latest selected method the "generate code" window won't even open

**To Reproduce**
1. Go to https://hoppscotch.io/
2. Change HTTP method to any of the described(like POST)
3. Click on "show the code" to open the code generator
4. Select any of the two JavaScript generators, you'll realize the textarea's content didn't change
5. (Optional) Close the code generation tool and try opening it again, it won't work unless you change back to a body-less method(like GET)

**Expected behavior**
I'd expect it to show the generated code, and even in the case it fails try not to block the code generation window from appearing again

**Screenshots**
![image](https://user-images.githubusercontent.com/20229636/94545231-91187000-024c-11eb-9622-20f868f6fa59.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS Edge (chromium)
 - Version:  85.0.564.63

**Additional context**
I really like this tool, keep the good job!

**Comment by liyasthomas** [comment]
This issues was introduced by latest updates in codegen. An utility function import has been skipped by mistake. Pushing a fix now.
