### ISSUE TITLE
Update pt-BR translations

### ISSUE THREAD

**Issue by lucasqueiroz** [hoppscotch/hoppscotch#1214]
# Description

The `pt-BR` translation file seem to be missing a lot of new strings included in `en-US`.

**Comment by liyasthomas** [comment]
@lucasqueiroz would you like to contribute to `pt-BR` translation? If yes please check [Translation instructions](https://github.com/hoppscotch/hoppscotch/blob/master/TRANSLATIONS.md).

**Comment by lucasqueiroz** [comment]
> @lucasqueiroz would you like to contribute to `pt-BR` translation? If yes please check [Translation instructions](https://github.com/hoppscotch/hoppscotch/blob/master/TRANSLATIONS.md).

Hi Liyas, I've already opened a Pull Request :)
Thanks!

**Comment by liyasthomas** [comment]
Fixed in #1217
