### ISSUE TITLE
HTTP PAGE : Headers suggestions are overlapped by the response section title

### ISSUE THREAD

**Issue by LeoMartinDev** [hoppscotch/hoppscotch#1222]
**Describe the bug**
The headers suggestion in the HTTP page are overlapped by the response section title

**To Reproduce**
1. Go to 'Home'
2. Click on 'Headers'
3. Click on 'Add new'
4. Click on the header name field
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/7238941/94997421-3a43cb00-05ab-11eb-917d-43cbf4bd513c.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 85

**Comment by tonybatty** [comment]
I have fixed this issue on PR #1223
