### ISSUE TITLE
Add a default Socket.io URL

### ISSUE THREAD

**Issue by LeoMartinDev** [hoppscotch/hoppscotch#1231]
It would be great to add a default Socket.io endpoint like it's done for the other protocols

**Comment by liyasthomas** [comment]
Actually I tried to find an open / public echo Socket.IO endpoint, but couldn't find one.

**Comment by LeoMartinDev** [comment]
I found one, in the Socket.io documentation, I can open a PR if you want

**Comment by liyasthomas** [comment]
Did you test it?

**Comment by LeoMartinDev** [comment]
Yup :) From https://socket.io/demos/chat/ `wss://socketio-chat-h9jt.herokuapp.com`

**Comment by LeoMartinDev** [comment]
Ew but it's not echoing, my bad

**Comment by liyasthomas** [comment]
I guess we can add this now. will update once we get an echo endpoint.
