### ISSUE TITLE
A search bar for collections

### ISSUE THREAD

**Issue by exussum12** [hoppscotch/hoppscotch#1236]
**Is your feature request related to a problem? Please describe.**
Have the search bar which exists in history also work on the collections page

**Describe the solution you'd like**
Type in all or part of a name and see only the requests which match

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LeoMartinDev** [comment]
If no one wants to / is working on it, I can give it a try

**Comment by liyasthomas** [comment]
You're welcome.

**Comment by pnpninja** [comment]
Can I try?

**Comment by liyasthomas** [comment]
> Can I try?

Go for it.

**Comment by liyasthomas** [comment]
@pnpninja do you need any help with this feature? Feel free to ask out here.

**Comment by pnpninja** [comment]
I'll start on it after Tuesday. I have an exam to prep for

**Comment by liyasthomas** [comment]
@pnpninja this feature has been implemented. Do check out other open issues for contribution.
