### ISSUE TITLE
Error: Network Error 

### ISSUE THREAD

**Issue by Siccity** [hoppscotch/hoppscotch#1251]
**Describe the bug**
Sent a basic GET request to https://www.google.com/ , got response Error: Network Error (F12 for details)

Console log:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://postwoman.apollosoftware.xyz/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6402525/95437609-7aad9b00-0955-11eb-9138-f3a08ca9d5e2.png)

**Comment by liyasthomas** [comment]
URLs such as www.google.com has CORS restrictions. Read more about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Not related to Hoppscotch hence closing.
