### ISSUE TITLE
PWA not working

### ISSUE THREAD

**Issue by msenol86** [hoppscotch/hoppscotch#1253]
I cannot install this on my Linux machine neither by Chrome nor by Firefox.
![image](https://user-images.githubusercontent.com/2547551/95518130-13cac900-09cb-11eb-8640-ab7c9b52efd2.png)

**Comment by liyasthomas** [comment]
Clear app data and follow these instructions: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen
