### ISSUE TITLE
Headers not replaced with Variables in the code export view

### ISSUE THREAD

**Issue by exussum12** [hoppscotch/hoppscotch#1257]
**Describe the bug**
Headers not replaced with Variables

**To Reproduce**
add `<<variable>>` as the value of a header, with `<<variable>>` set to something, press the export code button

**Expected behavior**
value should be something instead of `<<variable>>`

**Comment by liyasthomas** [comment]
As of now, env variables aren't supported in headers section. Will add to roadmap.

**Comment by exussum12** [comment]
@liyasthomas  I went to implement this, it actually works as intended. The reason I thought it didn't is the generated code. That doesn't get replaced. Ill update the issue and send a PR to make the code work the same way
