### ISSUE TITLE
I can't send an xml request. It also doesn't offer the desired title.

### ISSUE THREAD

**Issue by rytikovroman1994** [hoppscotch/hoppscotch#1263]
**Describe the bug**
I want to send an xml post request. It's not in your headlines. Also, when I write the header myself, the request still fails.

**To Reproduce**
Create a post request
Set Content-type to text/xml
To add to the xml body
Send a request

**Expected behavior**
The response should have been xml

**Screenshots**
![image](https://user-images.githubusercontent.com/42497012/95753574-7d3c2780-0caa-11eb-93d3-cde2dc90e357.png)
![image](https://user-images.githubusercontent.com/42497012/95754058-2aaf3b00-0cab-11eb-95fd-d47d5730885f.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]
 - Version [e.g. 84]

P.S In postman it works

**Comment by liyasthomas** [comment]
Please install Browser extension and try again.

Working XML example: https://hoppscotch.io/?method=GET&url=https://dev.to&path=/rss
