### ISSUE TITLE
Improve file / formData upload

### ISSUE THREAD

**Issue by onion-yz** [hoppscotch/hoppscotch#1273]
When the master is selected, files cannot be uploaded, and the number of files always shows no files. Checking the network payload, it is true that no files have been sent.
When selecting the release version v1.9.9, select application/x-www-form-urlencoded or application/json, the request payload is [object FormData], and the backend receives the string "[object FormData]". After parsing with tools, the format is found to be:

**------WebKitFormBoundarytpKqpaSAK4waEBzF
Content-Disposition: form-data; name="0"; filename="aaaaa.txt"
Content-Type: text/plain

------WebKitFormBoundarytpKqpaSAK4waEBzF
Content-Disposition: form-data; name="1"; filename="bbbb.txt"
Content-Type: text/plain

------WebKitFormBoundarytpKqpaSAK4waEBzF
Content-Disposition: form-data; **name="data"**

**{"ccc":"ccc"}**
------WebKitFormBoundarytpKqpaSAK4waEBzF--**

This format does not feel right, the correct one should be:

-----------------------------7e4cf3bac0c86
**Content-Disposition: form-data; name="ccc"**

**ccc**
-----------------------------7e4cf3bac0c86
**Content-Disposition: form-data; name="ddd"**

**ddd**
-----------------------------7e4cf3bac0c86
Content-Disposition: form-data; name="0"; filename="aaaaa.txt"
Content-Type: text/plain

aaaaaa

-----------------------------7e4cf3bac0c86
Content-Disposition: form-data; name="1"; filename="bbbb.txt"
Content-Type: text/plain

aaaaaa

-----------------------------7e4cf3bac0c86--

Otherwise,I hope that the file name can be modified on the front end, otherwise the file names received by the back end are all 0,1... These default names are not convenient for back-end debugging

**Comment by liyasthomas** [comment]
I've pushed a fix for this issue. Ability to rename files will be added ASAP.

**Comment by onion-yz** [comment]
> I've pushed a fix for this issue. Ability to rename files will be added ASAP.

thx

**Comment by nelsontky** [comment]
Any updates regarding this issue. If no I don't mind having a go at this feature!

**Comment by liyasthomas** [comment]
@nelsontky we would love to work with you on this. Feel free to ping me on [Discord](https://t.me/hoppscotch) or [Telegram](https://discord.gg/GAMWxmR) `@liyasthomas`.
