### ISSUE TITLE
TypeError: Cannot read property 'preference' of undefined

### ISSUE THREAD

**Issue by ChrisB85** [hoppscotch/hoppscotch#1275]
**Describe the bug**
When trying to open an app, only loading screen appears. There is an error in the console:
```
TypeError: Cannot read property 'preference' of undefined
    at Eo (f9910f0.js:1)
    at f9910f0.js:1
    at h (a93e484.js:2)
    at Generator._invoke (a93e484.js:2)
    at Generator.next (a93e484.js:2)
    at r (a93e484.js:2)
    at l (a93e484.js:2)
```

**To Reproduce**
1. Go to hoppscotch app URL
2. Open console in developer tools
3. See error

**Expected behavior**
An error in console should not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/792899/96081585-e776e700-0eb9-11eb-8f16-1831e6ae3b46.png)

**Desktop (please complete the following information):**
 - OS: Windows/Linux Mint
 - Browser Brave/Firefox

**Additional context**
I'm using docker version of hoppscotch. I have tried to clear site data in developer tools, but with no luck.

**Comment by liyasthomas** [comment]
Docker image seems to be having an issue. We're working on finding the root cause.

Investigation shows the color mode module is having an issue with accessing cookies when run via Docker. Kindly stay tuned while we rollout a patch ASAP.

**Comment by ChrisB85** [comment]
I have just upgraded my docker installation and it's working again :)
