### ISSUE TITLE
`npm run build` does not generate the `./dist` folder

### ISSUE THREAD

**Issue by debevv** [hoppscotch/hoppscotch#1295]
**Describe the bug**
Running `npm run build` does not generate the `./dist` folder, as expected by following the `Releasing` section of the readme.  
At the end of the build, this message is shown:
```
ℹ Ready to run nuxt generate
```
Running `npx nuxt generate` produces the `./dist` folder.
I attached a log of `npm run build`.
This happens on the current `master` but not on `v1.9.9`

**To Reproduce**
1. Run `npm run build`
2. `./dist` is absent

**Expected behavior**
The `./dist` folder should be created after running `npm run build`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Node: v12.19.0
 - Version: `21cf4392108e5b5791982904a18259807d6db6cd`
[npm run build.txt](https://github.com/hoppscotch/hoppscotch/files/5416031/npm.run.build.txt)

**Comment by liyasthomas** [comment]
Sorry for the incorrect command on **Releasing** section in `README`. It should've been `npm run generate`.

I'll be updating the `README` as soon as possible.

Refer: [Nuxt Commands Docs](https://nuxtjs.org/guide/commands)
