### ISSUE TITLE
Code snippets for Test scripts

### ISSUE THREAD

**Issue by liyasthomas** [hoppscotch/hoppscotch#1316]
**Is your feature request related to a problem? Please describe.**
[Post Requests Tests](https://github.com/hoppscotch/hoppscotch/wiki/Post-Requests-Tests) enable us to write and run test scripts after response. As of now, there's no ready-to-use code snippets available for test cases.

**Describe the solution you'd like**
It would be great if there's a pool of code snippets or Test script with general test scripts.

Example:
Test snippet: `Check if response is ok`
```
pw.test('Response is ok', () => {
    pw.expect(pw.response.status).toBe(200);
    pw.expect(pw.response.body).not.toHaveProperty('errors');
})
```

**Describe alternatives you've considered**
Go to [Wiki](https://github.com/hoppscotch/hoppscotch/wiki/Post-Requests-Tests) and figuring out what and how to write tests.

**Additional context**
Post request scripts are an experimental / incomplete feature. But has huge potential in terms of testing responses and automating stuffs to an extend. Also helps in integrations with 3rd party apps in future .

**Comment by carlos-ds** [comment]
@liyasthomas I'd like to work on this if that's ok with you. But I'm not sure if you are talking about updating [Post Requests Tests](https://github.com/hoppscotch/hoppscotch/wiki/Post-Requests-Tests) with more examples or whether you are talking about incorporating examples into the application itself?

**Comment by liyasthomas** [comment]
I was menrioning about adding ready-made script snippets for general testing purposes so that users don't have to write the testing script by themselves. Also I see you've already opened a gesture request to add more protocols to testing property in #1353 which is really appreciated. That's a good opportunity there.

**Comment by carlos-ds** [comment]
@liyasthomas I reviewed and updated the [Wiki page regarding testing](https://github.com/hoppscotch/hoppscotch/wiki/Post-Requests-Tests). I committed the changes directly since I read that pull requests aren't supported for Wiki pages. Could you review and let me know if it's ok?

**Comment by liyasthomas** [comment]
@carlos-ds looks good to me. Thanks.
