### ISSUE TITLE
Authentication not available for Websocket

### ISSUE THREAD

**Issue by arpanbag001** [hoppscotch/hoppscotch#1331]
**Describe the bug**
Feature to authenticate Websocket connection is missing, even though the Readme file says Basic and Bearer authentications are available for Websocket.

**To Reproduce**
1. Go to Realtime page
2. Go to "Websocket" tab
3. Can't find any section to use authentication or to add custom headers.

**Expected behavior**
In the Websocket tab, there should be a section to add authentication and also maybe custom headers, like the section available in Home page.

**Screenshots**
![image](https://user-images.githubusercontent.com/10957940/99366631-dff29580-28de-11eb-9bae-d93a33e4e744.png)

Faced on:
Windows 10, with PWA
Browsers: Chrome, Firefox
Hopscotch v1.9.9

**Comment by liyasthomas** [comment]
https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api

WebSocket doesn't support custom headers nor Authorization.

Even though you can use Basic Auth (deprecated) in WebSocket URL input.

Ex:

```
ws://username:password@example.com
```
