### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by camsvn** [hoppscotch/hoppscotch#1337]
https://hoppscotch.io renders a white screen with the error mentioned below:
Failed to load resource: the server responded with a status of 404 ()

Issue happens only with 'chrome browser'.

Affected device:
Desktop's and Mobiles

![Hoppscotch](https://user-images.githubusercontent.com/39452708/99867797-d28d2200-2be2-11eb-972e-b8a3e4d4ec0e.png)

**Comment by liyasthomas** [comment]
Looks like it's an issue with cached URLs.

Try a force reload (Ctrl + Shift + R). 

If it doesn't work, try clearing site's cache and do a force relod.
