### ISSUE TITLE
add new Environments have Bug

### ISSUE THREAD

**Issue by suzhaoyong** [hoppscotch/hoppscotch#1339]
**Describe the bug**
I want create new Environments and click save button show Environment added but refresh website is none;

**To Reproduce**
1. Go to 'https://hoppscotch.io/'
2. Click on 'Environments -> New'
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/26472847/99923799-59243980-2d72-11eb-9356-411265d9e4df.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 86.0.4240.198

**Comment by liyasthomas** [comment]
Not reproducible here at my end.

Did you allowed Hoppscotch to sync Environments?
Check Settings > Account and see if Sync Environments are turned on.
