### ISSUE TITLE
Blocked by firefox if I send a request to an IP address.

### ISSUE THREAD

**Issue by x-dongzi** [hoppscotch/hoppscotch#1344]
When I use the domain name to send the request, it can succeed. 
But if I change the domain name to the ip address, there would be a network error.
The browser is firefox 83.
I use F12 to check the console. It seems that the ip address request was blocked with the error message NS_ERROR_DOM_BAD_URI.
How could I send the request with IP address? Because in my local dev environment, I do not have the DNS service.

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. I'm looking into it.

**Comment by x-dongzi** [comment]
Sorry. I rechecked the details, and found that it's a CORS problem. After I enabled CORS request in my springboot website, it works very well.
I will close this issue.
