### ISSUE TITLE
Language support for Dutch (Belgium)

### ISSUE THREAD

**Issue by carlos-ds** [hoppscotch/hoppscotch#1347]
Hi,

First of all: great project! I currently work as a tester and it's great to see that there are open-source tools being built that can hopefully make my work easier and more effective. I'd like to contribute and have started off by adding a language file for Dutch (my native language) and I will open a pull request here.

Karel

**Comment by carlos-ds** [comment]
PR: https://github.com/hoppscotch/hoppscotch/pull/1348

**Comment by liyasthomas** [comment]
Hi @carlos-ds , you also need to add your `i18n` entry to the `nuxt.config.js` file.

Read [Step #4 in i18n contribution guidlines](https://github.com/hoppscotch/hoppscotch/blob/main/TRANSLATIONS.md)
