### ISSUE TITLE
Number of tests displayed is invalid

### ISSUE THREAD

**Issue by carlos-ds** [hoppscotch/hoppscotch#1349]
**Describe the bug**
The number of tests for a request, which is displayed in the tab label (after receiving the response), is invalid.

**To Reproduce**
Add following script as a test for a GET request:

`pw.test("Response is ok", () => {
    pw.expect(pw.response.status).toBe(200)
})`

**Expected behavior**
The label for the tests tab displays "Tests • 1"

**Screenshots**
![image](https://user-images.githubusercontent.com/20499950/100554317-2c9d7f80-3294-11eb-9b92-0e6c8da23022.png)

**Desktop (please complete the following information):**
 - OS: Windows
- Browser: Chrome

**Comment by liyasthomas** [comment]
Thanks for reporting the issue.

**Comment by liyasthomas** [comment]
Number of tests makes no sense to me.

It would be better if we show the number of passed / failed test cases. Also there's an option to assert named tests,  nested test functions etc. So currently there's no way to accumulate a proper test case number.

I'm temporarily removing the test case number shown on the tab label. Will look into this is there's a request for this feature.
