### ISSUE TITLE
GraphQL doc search returns error

### ISSUE THREAD

**Issue by connorwang** [hoppscotch/hoppscotch#1352]
TypeError: Cannot read property 'toLowerCase' of null
    at VueComponent.isTextFoundInGraphqlFieldObject (graphql.vue?c4f8:496)
    at eval (graphql.vue?c4f8:506)
    at Array.filter (<anonymous>)
    at VueComponent.getFilteredGraphqlFields (graphql.vue?c4f8:506)
    at VueComponent.filteredQueryFields (graphql.vue?c4f8:376)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4584)
    at VueComponent.computedGetter [as filteredQueryFields] (vue.runtime.esm.js?2b0e:4836)
    at Object.get (vue.runtime.esm.js?2b0e:2072)
    at Proxy.render (graphql.vue?c0f1:683)

**Comment by liyasthomas** [comment]
Looks like this is an issue with either browser compatibility or service worker cached page.
Try these:

**Fix 1: Force reload.** <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> in Chrome.

**Fix 2: Clean cookies and cache. Reload.**

_If issues still persists, report your browser version, OS build etc. Kindly use the bug template for reporting issue._

**Comment by connorwang** [comment]
Tried both incognito mode and with cleared cookie. Still having same issue.
Here is the browser information
CHrome - Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by liyasthomas** [comment]
Are you using the `latest ` tag?

**Comment by connorwang** [comment]
Here are all the docker-compose logs from the latest deployment

> web_1  |
web_1  | > hoppscotch@2.0.0 predev /app
web_1  | > node build.js --dev
web_1  |
web_1  |
web_1  | > hoppscotch@2.0.0 dev /app
web_1  | > nuxt
web_1  |
web_1  | ℹ Using Tailwind CSS from ~/assets/css/tailwind.css
web_1  | ℹ Merging Tailwind config from ~/tailwind.config.js
web_1  | ℹ Listening on: http://172.19.0.2:3000/
web_1  | ℹ Preparing project for development
web_1  | ℹ Initial build may take a while
web_1  | ✔ Builder initialized
web_1  | ✔ Nuxt files generated
web_1  | ℹ Warming up worker pools
web_1  | ✔ Worker pools ready
web_1  | ℹ Compiling Client
web_1  |
web_1  |  WARN
web_1  |
web_1  |
web_1  |  WARN  warn - You have enabled experimental features: uniformColorPalette, extendedSpacingScale, extendedFontSizeScale, applyComplexClasses, darkModeVariant, additionalBreakpoint
web_1  |
web_1  |
web_1  |  WARN  warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.
web_1  |
web_1  | ✔ Client: Compiled successfully in 1.48m
web_1  |
web_1  |  WARN  Compiled with 1 warnings
web_1  |
web_1  |
web_1  |  WARN  in ./node_modules/yargs-parser/build/lib/index.js
web_1  |
web_1  | Critical dependency: the request of a dependency is an expression
web_1  |
web_1  | ℹ Waiting for file changes
web_1  | ℹ Memory usage: 1.01 GB (RSS: 1.43 GB)
web_1  | ℹ Listening on: http://172.19.0.2:3000/

**Comment by connorwang** [comment]
We used the Dockerfile comes with the repo. It's a plain vanilla alpine 12.10.0.

**Comment by liyasthomas** [comment]
I can confirm this issue is happening only for endpoints which has `mutations`. Fixing this ASAP.
