### ISSUE TITLE
Add more test methods

### ISSUE THREAD

**Issue by carlos-ds** [hoppscotch/hoppscotch#1353]
I'd like to add some more built-in assertion methods to the tests section because that is currently limited to:

- toHaveProperty
- toBe
- toBeLevel2xx
- toBeLevel3xx
- toBeLevel4xx
- toBeLevel5xx

I'm thinking about adding at least:

- toHaveLengthOf
- toBeOfType

I'd also write some tests for both these methods and the currently existing methods.

Let me know if you have more ideas or remarks about this topic.

**Comment by liyasthomas** [comment]
Thanks for bringing this up. These are some essential additions. The testing part of Hoppscotch can be increased a lot more and have unmet potentials.

**Comment by carlos-ds** [comment]
PR: #1357

**Comment by liyasthomas** [comment]
Resolved in #1357.

**Comment by humbertoarizah** [comment]
Hi, I have been having problems with the method "toHaveProperty", for any reason I'm getting an error ('unknown property 'toHaveProperty'). Even when I try to replicate the following example, I get the error:

// This test will pass
pw.test("Response is ok", () => {
  pw.expect(pw.response.status).toBe(200);
  pw.expect(pw.response.body).not.toHaveProperty("errors");
});

So, I'm not sure what is happening?
I would appreciated any help.
