### ISSUE TITLE
Keyboard shortcut for "Reset request" is not working in Chrome

### ISSUE THREAD

**Issue by carlos-ds** [hoppscotch/hoppscotch#1356]
Current shortcut for "Reset request" is CTRL + L, however that is already an active shortcut in Chrome (on Windows only?) for selecting the address bar. The other shortcuts all seem to work as expected. 

![image](https://user-images.githubusercontent.com/20499950/100779212-54adef80-3408-11eb-9cc5-1cecc685356b.png)

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. We're looking into fixing it ASAP.

**Comment by liyasthomas** [comment]
Reset request shortcut changed to <kbd>Ctrl</kbd> + <kbd>I</kbd>

**Comment by carlos-ds** [comment]
@liyasthomas I also updated the [documentation regarding keyboard shortcuts](https://github.com/hoppscotch/hoppscotch/wiki/Shortcuts) to now show Ctrl + I
