### ISSUE TITLE
Install in isolated network

### ISSUE THREAD

**Issue by rluvaton** [hoppscotch/hoppscotch#1369]
Is there a way to use this in a private network without a connection to the outside world?
I know there is a PWA but I don't think you can install it on another computer cause it's not really an app.

**Comment by liyasthomas** [comment]
As of now there's no standalone production app other than PWA. That being said, you can try [Installing in local development environment](https://github.com/hoppscotch/hoppscotch#local-development-environment) or [from Docker](https://github.com/hoppscotch/hoppscotch#docker) to setup a isolated instance of app in development environment.
