### ISSUE TITLE
Extra headers on websocket requests

### ISSUE THREAD

**Issue by patrickhuijten** [hoppscotch/hoppscotch#1371]
**Is your feature request related to a problem? Please describe.**
In the project I'm working on we use a reverse proxy to connect to a socket.io server, however this requires a header to be sent. With Hoppscotch I can't send headers along with websocket requests.

**Describe the solution you'd like**
Ability to send headers along with websocket requests, just like the regular REST requests.

**Describe alternatives you've considered**
Not really seeing any alternatives. Is Hoppscotch being actively worked on or do I have better luck creating a pull request myself?

**Additional context**
I love Hoppscotch, it's exactly what I've been looking for. Obviously still under development but I love the fact that there's a REST client that support websockets, so I don't have to write scrappy html pages to test websocket connections 😅

**Comment by liyasthomas** [comment]
Oh, we had a detailed discussion on this feature in #933 - https://github.com/hoppscotch/hoppscotch/issues/933#issuecomment-722711714 and in #3062
