### ISSUE TITLE
hoppscotch fails on page load with ERROR in ./assets/md/docs.md

### ISSUE THREAD

**Issue by olsonjeffery** [hoppscotch/hoppscotch#1381]
**Describe the bug**
Hoppscotch fails to load/initialize with below error. I'm not doing dev on hoppscotch and have a clean clone of the repo that I run with docker-compose. Previously worked, but stopped after I did a `git pull`. Tried nuking/recloning repo, but get the same results.

**To Reproduce**
1. Windows 10, running chrome
2. clean clone of `hoppscotch/hoppscotch` and on `main` `858ab252`
3. do `docker-compose up -d`
4. navigate to localhost:3000 in abovementioned browser

**Expected behavior**
Expect app to appear/work without error

**Screenshots**
![image](https://user-images.githubusercontent.com/10408/101993323-3e612880-3c7f-11eb-90cb-61490a278fbb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome Version 87.0.4280.88 (Official Build) (64-bit) (tried on firefox, got same behavior)
 - `main` branch of `hoppscotch/hoppscotch` on `858ab252`

**UPDATE**: Here's my Docker Desktop about page:
![image](https://user-images.githubusercontent.com/10408/102018835-598e6f80-3d35-11eb-9858-1a490c29be14.png)

**Comment by liyasthomas** [comment]
Seems like an issue with installing `raw-loader`.
Cnn you try deleting `node_modules` and run `npm i` before `docker-compose`.

**Comment by olsonjeffery** [comment]
I went to the root of my hoppscotch clone and there was no `node_modules`, so I did `npm i` and then brought it back up with `docker-compose up -d`. No change :/
