### ISSUE TITLE
The request is sent correctly, but receive "Error: Network error" on the web page

### ISSUE THREAD

**Issue by uninstallHahaha** [hoppscotch/hoppscotch#1382]
**Describe the bug**
The request is sent correctly, but receive "Error: Network error" on the web page

**To Reproduce**
1. `git clone [this project]`
2. `npm install`
3. `npm run build`
4. `cd ./dist`
5. `npm run dev`
6. visit `localhost:3000` on the browser
7. open debug mode by F12
7. send test request with URL
8. receive "Error: Network error" on the web page
9. check console->network->request list->last requet->response, recover that the response code is 200, the request is sent by correctly.

**Screenshots**
the error on the web page
![Snipaste_2020-12-13_12-59-29](https://user-images.githubusercontent.com/36978593/102003492-29e66400-3d43-11eb-80cd-01f8a4b707d6.png)
but is sent by correctly
![Snipaste_2020-12-13_13-01-00](https://user-images.githubusercontent.com/36978593/102003502-4387ab80-3d43-11eb-9aab-d2695cfb8abe.png)

**Desktop:**
 - OS: win8.1 64bit
 - Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0

**Comment by liyasthomas** [comment]
For development environment steps 3 and 4 isn't required.
