### ISSUE TITLE
Support for Cookies

### ISSUE THREAD

**Issue by mulka** [hoppscotch/hoppscotch#1383]
**Is your feature request related to a problem? Please describe.**
I don't see a way to add cookies to requests. I'm using a session cookie to authenticate to an API, but I don't see a way to add a cookie to a request in Hoppscotch

**Describe the solution you'd like**
I'd like to have a place to put cookies so they can be sent with every request to an API in Hoppscotch

**Describe alternatives you've considered**
Use a different tool I guess.

**Additional context**

**Comment by AndrewBastin** [comment]
Umm, we have thought about this.

But the problem we are facing is that since Hoppscotch runs on the browser, we are faced with limitations which are set on the platform. Browsers currently don't provide an API that lets us set cookies for requests for security reasons (we can set for the cookies in a document space ofc, but not for XHRs).

**Comment by mulka** [comment]
Gotcha. I wonder how Postman does cookies

**Comment by AndrewBastin** [comment]
Postman can take advantage of the fact that it is running natively (it is an Electron app) which allows it to use the native APIs which do provide cookie support.

**Comment by Leodau** [comment]
You should close this issue, browsers would hopefully never be able to check _HttpOnly_ cookies. :pray:

**Comment by fr3fou** [comment]
> You should close this issue, browsers would hopefully never be able to check _HttpOnly_ cookies. 🙏
But how would one test an API that uses cookies?

**Comment by Hernandiaz035** [comment]
Is this the reasson why my API responses: 
```

**Comment by benjaminlaib** [comment]
Bump, since there is a Hoppscotch browser extension, shouldn't it be possible to let it solve our cookie issue?

**Comment by nelsontky** [comment]
This is interesting! May I try implementing this? I will open a PR in the extension repository if this functionality is possible.

**Comment by liyasthomas** [comment]
Hi @nelsontky, you're free to pick up this one. And yes - this is a trick one to implement.

**Comment by nelsontky** [comment]
Ok @liyasthomas I have opened a PR!

**Comment by vaaski** [comment]
what happened to this?

**Comment by AndrewBastin** [comment]
@vaaski With the merging of hoppscotch/hoppscotch-extension#88 we have merged the code for supporting cookies into the extension and it does sorta work as indicated and shown in the PR. We are actually working on having proper documentation and proper UX for Cookies which should be live in a couple of weeks.

**Comment by vaaski** [comment]
thanks for the swift reply, i just noticed i already commented on https://github.com/hoppscotch/hoppscotch-extension/pull/88 so apparently i was aware of it in the past and forgot

**Comment by LMCom** [comment]
> Umm, we have thought about this.
> 
> But the problem we are facing is that since Hoppscotch runs on the browser, we are faced with limitations which are set on the platform. Browsers currently don't provide an API that lets us set cookies for requests for security reasons (we can set for the cookies in a document space ofc, but not for XHRs).

I am currently using the standalone application in macOS. It does not seem to save the session cookie after login. This prevents me from being able to test most of my application.

**Comment by rishabmahesh** [comment]
@LMCom Did you find a workaround? I'm also facing the same issue

**Comment by nelsontky** [comment]
> @LMCom Did you find a workaround? I'm also facing the same issue

Was an old PR i wrote but if i remember correctly cookies will only work on the web version with the extension installed

**Comment by liyasthomas** [comment]
Hoppscotch Desktop App supports cookies: https://docs.hoppscotch.io/documentation/features/cookies

**Comment by rishabmahesh** [comment]
> > Hoppscotch Desktop App supports cookies: https://docs.hoppscotch.io/documentation/features/cookies
> 
> Sounds good! But my understanding is that the cookies have to be created manually.
> 
> My use-case is a login. After posting the correct credentials, the application responds with a cookie that should keep me logged in. I whitelisted the domain via the cookie settings but no cookie is being created after login. Subsequent GET-requests just redirect me to the login page. I tried copying the cookie string and setting it manually for the domain but it doesn't seem to have any effect.
> 
> ![grafik](https://private-user-images.githubusercontent.com/14162803/310029573-bc76af7f-69e6-4aa8-acb4-39d071a7a39f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTAxNzEsIm5iZiI6MTcwOTY0OTg3MSwicGF0aCI6Ii8xNDE2MjgwMy8zMTAwMjk1NzMtYmM3NmFmN2YtNjllNi00YWE4LWFjYjQtMzlkMDcxYTdhMzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE0NDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZWIyOTY4MjJmM2I1MTc0NjE3NzRjMjQxNzY4MWM1ZTk0ZmRkNmZiNDJkZTY1ZjBiOWY1MGQ3YTk4ZmU3MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4KVON9NHZmbJxmTYm7XiTvkQJeB-BBG2_J96zCJpPmI)

Yup, I have the exact same use case. The cookie doesn't get set automatically

**Comment by MexHigh** [comment]
> Was an old PR i wrote but if i remember correctly cookies will only work on the web version with the extension installed

I don't see any option to set cookies in the web version even with the extension in use. The documentation also states that cookies are only supported on Desktop.

@liyasthomas Why is that? Since using the extension bypasses the XHR limitations, this should be possible, right?
