### ISSUE TITLE
Hoppscotch does not host under path like /hoppscotch

### ISSUE THREAD

**Issue by cyberfox1** [hoppscotch/hoppscotch#1387]
Get a bunch of errors about expecting various JS files to be at root level. Why.

**Comment by liyasthomas** [comment]
Can you tell a bit more about the issue? May be use the issue template. It might help.

**Comment by cyberfox1** [comment]
What more do you want to know?

**Comment by liyasthomas** [comment]
@cyberfox1 
> Get a bunch of errors about expecting various JS files to be at root level.

What were the errors?
