### ISSUE TITLE
toBeLevelxxx() test functions are broken

### ISSUE THREAD

**Issue by carlos-ds** [hoppscotch/hoppscotch#1396]
I was working on writing some more unit tests for the test functions in the application. And in the process of doing so, I discovered that the function for toBeLevel2xx() and similarly toBeLevel3xx(), toBeLevel4xx(), toBeLevel5xx() aren't working as expected. 

Sticking to toBeLevel2xx(): given a 200 response status, it's indicating FAIL for the simplest of assertions:

![image](https://user-images.githubusercontent.com/20499950/102799343-b1228000-43b2-11eb-8efb-80e6ef9fdd87.png)

I'll create a PR to fix this.

**Comment by liyasthomas** [comment]
Thanks for noticing this issue and quick PR 🚀

**Comment by AndrewBastin** [comment]
Also a wonderful reasoning for why tests are important 🙃
