### ISSUE TITLE
Add import option of OpenAPI json/yaml

### ISSUE THREAD

**Issue by mnixry** [hoppscotch/hoppscotch#1406]
**Is your feature request related to a problem? Please describe.**
Some framework such as `fastapi` generated a `openapi.json`. I want to import this easily to hoppscotch

**Describe the solution you'd like**
Add a option to make import OpenAPI file possible

**Additional context**
related with #1182

**Comment by liyasthomas** [comment]
Duplicate of #1182 hence closing.
Don't create duplicates of existing feature request.
