### ISSUE TITLE
TypeError is returned when logged in

### ISSUE THREAD

**Issue by carlos-ds** [hoppscotch/hoppscotch#1409]
When logged in (in my case via Google), clicking on "Send request" returns a type error.

```
TypeError: Cannot read property 'value' of undefined
    at c5959e3.modern.js:1
    at c5959e3.modern.js:1
    at Generator.next (<anonymous>)
    at r (856170b.modern.js:2)
    at l (856170b.modern.js:2)
```

![image](https://user-images.githubusercontent.com/20499950/103485666-59dfcf00-4df8-11eb-97e0-8970c7042a50.png)

After logging out and making the exact same request, the response is what I expected. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by carlos-ds** [comment]
This seems to be pointing at the `if (fb.currentSettings[0].value)` (and [1], [2]) statements, where it can't access `value` since `currentSettings` is undefined. Probably because I don't have any settings yet? I'm not familiar with the Firebase internals.

As an example from collection.vue on line 134:

```
syncCollections() {
      if (fb.currentUser !== null) {
        if (fb.currentSettings[0].value) {
          fb.writeCollections(JSON.parse(JSON.stringify(this.$store.state.postwoman.collections)))
        }
      }
    }
```

I suspect it would be best to change it to:

```
syncCollections() {
      if (fb.currentUser !== null && fb.currentSettings[0]) {
        if (fb.currentSettings[0].value) {
          fb.writeCollections(JSON.parse(JSON.stringify(this.$store.state.postwoman.collections)))
        }
      }
    },
```

I have tested this locally and it seems to fix the problem.

**Comment by AndrewBastin** [comment]
I can't find a way to replicate this. Is it happening everytime after you login ?

**Comment by liyasthomas** [comment]
@ccarlos-ds this is exactly due to your Settings being empty. This happened when you don't turn on sync in settings. I liked your suggestion on abstracting if statements of helper functions feel free to open a PR — meanwhile I'll just fix this by checking existence of Settings key as you mentioned in the example.

**Comment by liyasthomas** [comment]
@carlos-ds let me know if this issue still persist. Do a force refresh before testing.

**Comment by carlos-ds** [comment]
@liyasthomas yes, this seems to be fixed now. I'll have a look at abstracting the if-statements next week.
