### ISSUE TITLE
Hope to support STOMP testing.

### ISSUE THREAD

**Issue by amaothree** [hoppscotch/hoppscotch#1417]
**Is your feature request related to a problem? Please describe.**
The normal websocket testing can not test the STOMP endpoint/URL.

**Describe the solution you'd like**
just add a subpanel in the websocket page

**Describe alternatives you've considered**
No more useful tools can help me to test STOMP, i am using apic.app but still not easy.

**Additional context**
What is STOMP? http://stomp.github.io/

**Comment by liyasthomas** [comment]
As of now we've not planned to implement `STOMP` endpoint support - since there's no enough requests for this feature. Even though We'll keep an eye out for this request.
