### ISSUE TITLE
Proxy server works in the url but not if in the settings

### ISSUE THREAD

**Issue by nathanielread** [hoppscotch/hoppscotch#1423]
I setup my own docker based proxy server. When I put the proxy server url into the hoppscotch request url, it works. Example:
https://cors.website.com/https://google.com

When I put the proxy server url (https://cors.website.com/) in the proxy config of hoppscotch and leave it out of the request url, it gives me this error:
```
TypeError: Cannot read property 'message' of undefined
    at e0cab83.modern.js:1
    at Generator.next (<anonymous>)
    at r (c0ab92f.modern.js:2)
    at l (c0ab92f.modern.js:2)
```

I'm running hoppscotch in docker, manually build through the Dockerfile, behind jwilder nginx-proxy. 

Not a huge deal, but any thoughts?

**Comment by liyasthomas** [comment]
In Settings > Proxy, under the hood Hoppscotch uses a [custom proxy server](https://github.com/hoppscotch/proxyscotch). You can build it and host it on your own to use it along with any Hoppscotch instances. Instructions can be found at [hoppscotch/proxyscotch](https://github.com/hoppscotch/proxyscotch). Also there's a docker container available: https://hub.docker.com/r/hoppscotch/proxyscotch.

**Comment by nathanielread** [comment]
Yes, I built my own, not based on proxyscotch, though. 
I built it based on this one: https://hub.docker.com/r/redocly/cors-anywhere

And when I put that proxy server url in the hoppscotch settings, it doesn't work. Is that because only the proxyscotch server works in that config?

**Comment by liyasthomas** [comment]
> Is that because only the proxyscotch server works in that config?

Yes

Hoppscotch Proxy mode is tailored to work only with Proxyscotch. Alternatively you can install it browser extension to bypass CORS restrictions.

**Comment by nathanielread** [comment]
Thanks! I pulled the docker image, put it behind jwilder nginx-proxy and the proxy settings in hoppscotch works.
Any advice on setting a proxyscotch token in docker-compose? Env variable?

**Comment by liyasthomas** [comment]
As per [Proxyscotch Docs](https://github.com/hoppscotch/proxyscotch#servers-), 
> - The host and token parameters are optional. The defaults are as follows:
> - host: localhost:9159
> - token: blank; allowing anyone to access (see below)
> - NOTE: When the token is blank it will allow anybody to access your proxy server. This may be what you want, but please be sure to consider the security implications.

I'm not a docker expert 🙏 but you can find a way to pass env variables in docker compose from [here](https://docs.docker.com/compose/environment-variables/) and [here](https://stackoverflow.com/questions/29377853/how-to-use-environment-variables-in-docker-compose).
