### ISSUE TITLE
Environment vars not working

### ISSUE THREAD

**Issue by cddm13** [hoppscotch/hoppscotch#1425]
**Describe the bug**
Fails to set a value to env var when using an endpoint.

**To Reproduce**
1. Create a new environment "Development"
2. Create a new env var called "bearerToken" and set initial value as "initial"
3. In the Test tab of the request `pw.env.set("bearerToken", "aNewToken");` I've also tried with `pw.environment.set("bearerToken", "aNewToken")` and the same for the pre-request scrip, however when I check the env var bearerToken it still contains the "initial" value.

**Expected behavior**
When the request is completed the bearerToken environment variable value should be changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/76781996/104330494-caf44600-54cc-11eb-915b-c3276f31246a.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 87

**Additional context**
am I doing anything wrong? how can I accomplish this?

**Comment by liyasthomas** [comment]
> 3. In the Test tab of the request pw.env.set("bearerToken", "aNewToken");

You cannot set an environment variable from `Tests` script - this feature is not available.  Tests are for verifying your API responses only - [read how](https://github.com/hoppscotch/hoppscotch/wiki/Post-Request-Tests).

To add environment variables you can either write a [`Pre-request script`](https://github.com/hoppscotch/hoppscotch/wiki/Pre-Request-Scripts) or use "Environments" tab in the sidebar.

---

#### **Add environment variable using pre-request script:**
Use `pw.env.set("env_variable","env_value")`

Example:
```
pw.env.set('bearerToken', 'initial value');
```

Once an environment variable is set, you need to switch environments from "Environments" tab to change it's value. For making use of multiple environments - you can create an environment with name "Globals" whose variables are accessible on every environments.

---

> **Expected behavior**
> When the request is completed the bearerToken environment variable value should be changed.

This is not the expected behavior.

Let me know if you've any doubts.

**Comment by cddm13** [comment]
In that case, how can I set my environment variable "bearerToken" to = a property of the response (data.token) after this request is completed? because what I want is perform login and then assign that token value into my "barierToken" env that is used in another endpoint on which I need to be authenticated

**Comment by liyasthomas** [comment]
Since this involves making two requests, adding token from first response to environment should be a manual process. Also you can make use of Authentication section to mention Bearer token after fetching the token first.

**Comment by jdelibas** [comment]
@liyasthomas This is a very useful feature when sharing collections to setup flows that other users can easily run through steps. Without manually having to set all the little bits up.

I get that the tests tab is for asserting tests but one of the main use cases ive seen this is for exactly what the OP is asking for.
Its very much a blocker for me as an example wanting to migrate away from postman.

This doesn't stop at just bearer tokens for example, think getting a USERID from a login the subsequent request may require.

Is the status of this ticket WONTFIX or up for debate? If the feature is a PR away then happy to have a go at it.

**Comment by liyasthomas** [comment]
This is one of our planned features. The already existing Hoppscotch APIs comes little short for all this features and some security concerns. We're working on an isolated JavaScript compiler along with a set of revamped Hoppscotch APIs that allows users to add/edot/delete environment variables from both pre-request and post-request scripts.

This first iteration of the MVP is expected to arrive in a week or so. Thank you for the patience, feel free to [jump into our communication channels to connect with the core team](https://github.com/hoppscotch/hoppscotch#contact). Feedbacks are welcome.

**Comment by kahennig** [comment]
> This is one of our planned features. The already existing Hoppscotch APIs comes little short for all this features and some security concerns. We're working on an isolated JavaScript compiler along with a set of revamped Hoppscotch APIs that allows users to add/edit/delete environment variables from both pre-request and post-request scripts.
> 
> This first iteration of the MVP is expected to arrive in a week or so. Thank you for the patience, feel free to [jump into our communication channels to connect with the core team](https://github.com/hoppscotch/hoppscotch#contact). Feedbacks are welcome.

Hi liyasthomas, 
this would be a great feature to have, I aws wondering if the setting of env vars from the post-request scripts is nearing arrival?
Thanks, 
Andi

**Comment by sergeidyga** [comment]
+1. Hi! I also find this feature to be widely used. And it looks like a blocker for our team to migrate from Postman to Hoppscotch.

**Comment by Xairoo** [comment]
> +1. Hi! I also find this feature to be widely used. And it looks like a blocker for our team to migrate from Postman to Hoppscotch.

100% agree. Makes things so easy.
Also missing `console.log` output for some debugging when writing tests or pre-request scripts.
