### ISSUE TITLE
Provide a visual editor for JSON/KV request bodies

### ISSUE THREAD

**Issue by kotx** [hoppscotch/hoppscotch#1435]
**Is your feature request related to a problem? Please describe.**
Users cannot send JSON to an endpoint if the endpoint requires numbers to be JSON numbers. Currently Hoppscotch serializes all parameters as JSON strings. 

**Describe the solution you'd like**
User input:
![image](https://user-images.githubusercontent.com/33439542/105427778-c03f5c80-5c02-11eb-8bb6-17435e08f742.png)
Expected behaviour: user can either select the parameter type and/or the value gets automatically converted into the proper type. 

**Describe alternatives you've considered**
Can always use the raw request bodies, but that is less convenient.

**Comment by liyasthomas** [comment]
> user can either select the parameter type

This is not a convenient way.

On the other hand, raw request body is especially made to address this issue. Let me know why raw request body is less convenient for you.

**Comment by kotx** [comment]
> > user can either select the parameter type
> 
> This is not a convenient way.
> 
> On the other hand, raw request body is especially made to address this issue. Let me know why raw request body is less convenient for you.

The process would be faster if the parameters were synchronized between raw and normal request bodies. Currently I have to rewrite the JSON entirely, unless that's a bug. 
Also, autodetection seems much more convenient than editing a raw request body. There aren't many edge cases where the server only accepts a number (or some other type) as a string AFAIK.

**Comment by Reflex-Gravity** [comment]
Can I take this issue?

**Comment by liyasthomas** [comment]
@Reflex-Gravity so, when you choose request method as `POST`, `PUT`, or `DELETE` you can add request body from request section. And it can be done in two ways. Key-value pairs and Raw input.

This feature enable syncing both of them. Whenever you add a key-value pair - it should reflect in Raw input and when you add a Raw input (JSON object) it should reflect in key-value pair.

1. Choose `POST` request method
2. Change URL to `https://httpbin.org/post`
3. Add request body / raw input
4. Send

**Key-value pair**

![Screenshot_20210323-055221__01](https://user-images.githubusercontent.com/10395817/112074961-7a205e00-8b9d-11eb-818f-cb1cc832dc63.jpg)

**Raw input**

![Screenshot_20210323-055501__01](https://user-images.githubusercontent.com/10395817/112075004-915f4b80-8b9d-11eb-8755-f384bfcb5c8f.jpg)

**Comment by Reflex-Gravity** [comment]
In the key:value view, what if its a nested JSON, should I set the 2nd level JSON as a value to the key?

**Comment by liyasthomas** [comment]
That won't be a desired behaviour. I guess we can only sync key-value pairs with simple JSON object and vice versa. If the raw JSON has nested arrays - I would not recommend using it in key value pairs.

Would like to know what @kotx think about this. Anyways @Reflex-Gravity you can just omit nested JSON for now.

**Comment by kotx** [comment]
> Would like to know what @kotx think about this.

This sounds good! It would be ideal for the JSON to be preserved when converted to key-value pairs, but seeing as they are just key-value pairs I think it is fine. There should probably be a warning before conversion though.

**Comment by liyasthomas** [comment]
@kotx does this deploy preview fits your use case: https://deploy-preview-1562--hoppscotch.netlify.app/

**Comment by kotx** [comment]
> @kotx does this deploy preview fits your use case: https://deploy-preview-1562--hoppscotch.netlify.app/

Yes, that is excellent.
