### ISSUE TITLE
Code generation feature encodes parameters twice

### ISSUE THREAD

**Issue by oshhh** [hoppscotch/hoppscotch#1437]
**On entering a parameter containing a space the space is encoded as "%2520" instead of "%20" because of being encoded twice**
On the main page while generating a cURL code for a get request, if a parameter contains a space the code generated contains "%2520" as the encoding of the space instead of "%20" because of being encoded twice (" " => "%20" => "%2520").

**To Reproduce**
1. Go to `https://hoppscotch.io/`
2. Enter URL and create a parameter. In the value of the parameter put words separated by space. 
3. Click on the Show Code button ("<>") and select cURL.

**Screenshots**
![Screenshot 2021-01-23 at 11 03 57 PM](https://user-images.githubusercontent.com/45964755/105609422-48725d00-5dcf-11eb-9d78-2a0b1c54ed15.png)
![Screenshot 2021-01-23 at 11 04 13 PM](https://user-images.githubusercontent.com/45964755/105609431-52945b80-5dcf-11eb-8ead-5bcb8df3a005.png)

**Comment by oshhh** [comment]
A small 2 liner fix I propose: https://github.com/oshhh/hoppscotch/commit/1e19bbc51a0fca259a57dee1d87cbc9a63c79b34

**Comment by liyasthomas** [comment]
Thanks for noticing this issue. It was not only effecting `cURL` but also all other frameworks / languages in codegen. A fix is on the way.
