### ISSUE TITLE
"<<" and ">>" surrounding a path parameter encoded on saving to collection

### ISSUE THREAD

**Issue by oshhh** [hoppscotch/hoppscotch#1451]
**Describe the bug**
On saving a request to a collection, it gets encoded. "<<" and ">>" around path_parameters also get encoded and hence a saved request is not usable directly if it contains path parameters.

**To Reproduce**
1. Create a request with URL "https://url.com/<<parameter>>" and create a path parameter. 
2. Save request to a collection.
3. Now open the saved request
4. See error: request URL is now "https://url.com/%3C%3Cparameter%3E%3E".

**Expected behavior**
URL should be "https://url.com/<<parameter>>".

**Screenshots**
![Screenshot 2021-01-30 at 2 04 24 AM](https://user-images.githubusercontent.com/45964755/106325057-321d4300-62a0-11eb-86c2-7a25bd44e6ff.png)

**Comment by liyasthomas** [comment]
Thanks for noticing that issue.
