### ISSUE TITLE
Deleting history UI bug

### ISSUE THREAD

**Issue by IshaGupta18** [hoppscotch/hoppscotch#1455]
**Describe the bug**
History is deleted on clicking on clear all, but change appears only after refreshing the page ie doesn't happen asynchronously and the page has to be updated to see the cleared history. 

**To Reproduce**
1. Go to https://hoppscotch.io/
2. Make a request
3. Click on "Clear All" in the history tab
4. Notification comes that "History Deleted", but the history tab is not cleared.

**Expected behavior**
The history tab should be cleared as soon as "Clear All" is clicked (asynchronously).

**Screenshots**
![image](https://user-images.githubusercontent.com/40794215/106376523-2757d080-63bc-11eb-94b6-61d12a6dfce8.png)

**Comment by liyasthomas** [comment]
Ahh, this looks like a _minor_ UX delay. I mean, yes UI should be updated instantaneously.

As of now, what we're doing is - when you click "Clear All", we loop every entry in history and delete it. This is the [recommended way on deleting all collection entries in  Firestore](https://stackoverflow.com/questions/53089517/how-to-delete-all-documents-in-collection-in-firestore-with-flutter). We can show an instantaneous response here by not waiting for Firebase micro-service to do it's job - but again it'll cause another _serious_ issue. If any error happens with Firebase delete operations - user is left with an incorrect UI response.

Also just mentioning that history section is different for both signed in mode and signed out mode. Deleting one doesn't effect the other.
