### ISSUE TITLE
Response section stays hidden on FireFox

### ISSUE THREAD

**Issue by rschristian** [hoppscotch/hoppscotch#1465]
**Describe the bug**

The entire "Response" section stays hidden right now on Firefox. 

Opening up dev tools, it seems to be because the only element within the Response section ('#response') has a "hidden" class. Removing the class displays the Response section once again, though this does involve opening up the dev tools and manually editing the content. Not sure why that class is there to begin with.

**To Reproduce**
1. Go to 'https://hoppscotch.io/' with FireFox
4. See that the "Response" section is missing

**Expected behavior**
I'd expect to see the Response section so I can see what the HTTP method returns

**Screenshots**
![temp](https://user-images.githubusercontent.com/33403762/106924702-f4238300-66d4-11eb-8f09-b71f29ac3927.png)
![temp2](https://user-images.githubusercontent.com/33403762/106924706-f5ed4680-66d4-11eb-8e52-1cb2a679ff8b.png)
![temp3](https://user-images.githubusercontent.com/33403762/106924709-f685dd00-66d4-11eb-99fa-4edcfd7d5968.png)

There's three images here. The first is when navigating to the page, the second is opening dev tools and highlighting the "hidden" element that seems to be the issue, the third is upon manually editing the element's class list so that "hidden" is no longer applied.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox (Developer Edition) 
 - Version: v85.0b9

**Additional context**
Opening this up in Chrome on another device works as expected.

**Comment by liyasthomas** [comment]
Noted. I'm inspecting this use case. Thanks for reporting the issue.

Can you reproduce this issue after doing a force refresh?

**Comment by rschristian** [comment]
Yes, I can still reproduce after a force refresh.

Was just able to test standard Firefox on Windows, and that's unaffected. That might narrow it down to the Arch build or the developer edition.

**Comment by liyasthomas** [comment]
Thanks for the detailed information. Hoping to fix this ASAP.

**Comment by rschristian** [comment]
After manually clearing cookies, storage, etc. it seems to have been corrected. Seems resolved, as I can't reproduce.

**Comment by liyasthomas** [comment]
About 3 weeks ago, we did a overhaul on UI - with more modern components and migrated to TailwindCSS.

I'm guessing - before this update you might've collapsed Response section. And came after UI overhaul. Anyways, feel free to open issue if this happens again.

**Comment by rschristian** [comment]
That sounds likely to have been the issue. Thanks for the quick response! Love the tool.
