### ISSUE TITLE
Improve layouts for mobile

### ISSUE THREAD

**Issue by AllanOricil** [hoppscotch/hoppscotch#1472]
**Describe the bug**
The  top and bottom menus are bigger than the view port width.

![Screenshot_20210208-094048_Chrome](https://user-images.githubusercontent.com/55927613/107202212-d5cdc800-69f1-11eb-84f6-3cbc79e5fead.jpg)

![Screenshot_20210208-094118_Chrome](https://user-images.githubusercontent.com/55927613/107202215-d9614f00-69f1-11eb-8244-d859d40b41e7.jpg)

**To Reproduce**
Just open the app on a phone

**Expected behavior**
Top and bottom menus should not be bigger than the phone width when oriented vertically

**Smartphone (please complete the following information):**
 - Device: Galaxy Note 10+
 - OS: Android 11
 - Browser Chrome

**Comment by liyasthomas** [comment]
Noted. Will fix this ASAP.

**Comment by AllanOricil** [comment]
> Noted. Will fix this ASAP.

Man you are so fast hahaha. I was still writing the issue haha

**Comment by AllanOricil** [comment]
Now it looks great!
