### ISSUE TITLE
Do we support APIs hitting from localhost?

### ISSUE THREAD

**Issue by saki-osive** [hoppscotch/hoppscotch#1483]
**Is your feature request related to a problem? Please describe.**

Do we support RPC calls that would enable hitting APIs from the local network as well?

**Describe the solution you'd like**

An RPC implementation can be used for this.

I found a similar thing in the [Polkadot Explorer](https://polkadot.js.org/apps/#/explorer) by choosing Development network.

**Comment by liyasthomas** [comment]
Hi @saki-osive, thanks for posting your question. We're using Axios HTTP client for Hoppscotch. I am afraid Axios does not offer any rpc support.

Refer: https://github.com/axios/axios/issues/1069
