### ISSUE TITLE
Extension and Webapp makes requests when enabled option of settings

### ISSUE THREAD

**Issue by joaoeudes7** [hoppscotch/hoppscotch#1489]
**Describe the bug**
The web app and the extension app makes the request

**To Reproduce**
1. Go to Setting
2. Enable option to use extension to request on Browser 
3. Install the extension on Browser
4. Make any request

**Expected behavior**
Only the extension makes the request

**Screenshots**
![image](https://user-images.githubusercontent.com/16367752/107995985-0bf4e400-6fbe-11eb-8cd1-5982fe4eb8b6.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 86b

**Additional context**
Version of extension is 0.2.0

**Comment by liyasthomas** [comment]
@AndrewBastin take a look at this.

**Comment by AndrewBastin** [comment]
So did you enable the extension and then install the extension for the multiple request fire to be caused ?

Because I can't seem to reproduce it from my end.

**Comment by liyasthomas** [comment]
Neither I can reproduce this behaviour.

**Comment by joaoeudes7** [comment]
When disabled the option with use of extension, the api receive only one request, when enabled receive two.

Do you need any more information that can help?
