### ISSUE TITLE
Address bar URL params do not update as expected

### ISSUE THREAD

**Issue by nelsontky** [hoppscotch/hoppscotch#1497]
**Describe the bug**
`POST` parameters do not update the URL params in the address bar as expected

**To Reproduce**
1. Create a new `POST` request.
2. Add a new parameter to the request body. (Non raw request body)
3. Set the key to some text.
4. Click on the value input field.
5. The address bar URL parameter does not update.
6. Type something in the param value input field.
7. The address bar URL finally updates.

**Expected behavior**
The address bar URL parameter should have updated to reflect the new key in step 5.

**Video**
https://user-images.githubusercontent.com/7272103/108542861-3e387580-731f-11eb-9bae-ef2b747586d2.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Additional context**
I could work on this too!

**Comment by LeoMartinDev** [comment]
I'll take a look

**Comment by LeoMartinDev** [comment]
Ok well, this code is super hard to read and there is too many entry points to the `setRouteQueryState` function (and a watcher) so I'm having a hard time fixing this issue. Maybe someone with more experience on this code will be able to find what's wrong 💪

**Comment by nelsontky** [comment]
> Ok well, this code is super hard to read and there is too many entry points to the `setRouteQueryState` function (and a watcher) so I'm having a hard time fixing this issue. Maybe someone with more experience on this code will be able to find what's wrong 💪

Ok I can probably can have a go at it tomorrow!

**Comment by JDevx97** [comment]
After reviewing the existing description, discussion and having a brief inspection, I do not believe there is an issue here as there may have been a slight misunderstanding with expectations that `body parameters` operate the same as `query parameters` in a HTTP request.

`Request body parameters` do **not** get appended to a URL in a HTTP request and are instead transmitted immediately after request header under the `body` options key.

`Request query parameters` are a set of parameters appended to the end of a URL which appears to be the expected outcome described by this issue.

The existing functionality of `request body parameters` and `request query parameters` both appear to be operating relatively as expected (I found a separate issue with request query parameters.).

Request body parameters are attached to the `request body`, and creating a new `GET` request and applying `query parameters` results in the parameters being appended to the request URL. (Though they are not appended correctly but that is a separate issue and requires a different issue write up.)

@nelsontky @LeoMartinDev

**Comment by liyasthomas** [comment]
@nelsontky  I can't reproduce this issue in [hoppscotch.io](https://hoppscotch.io) anymore. Can you verify this error exists?
