### ISSUE TITLE
Should be an easy/quick way to update/save a Request ?

### ISSUE THREAD

**Issue by rw3iss** [hoppscotch/hoppscotch#1498]
**Is your feature request related to a problem? Please describe.**
Not particularly. 

**Describe the solution you'd like**
When changing a request's parameters or anything, there isn't currently any clear way to "Save" or update the request (if it's already saved in a Collection). There is only the option to save it, which makes an entirely new request, and then we must delete the old request in the collection. Or am I missing something?
At least if saving to a collection with the same name or otherwise URL or something, it should overwrite by default, or just prompt the user to overwrite.

**Comment by liyasthomas** [comment]
You can actually select your "old request" while saving the updated one. This will overwrite the previous one.

**Screenshot:**

![IMG-20210221-WA0000](https://user-images.githubusercontent.com/10395817/108627886-c2a10a80-747d-11eb-8642-0102890f1e76.jpg)

**Comment by rw3iss** [comment]
Cool, thanks ;-p
