### ISSUE TITLE
auth/internal-error

### ISSUE THREAD

**Issue by GuoxinL** [hoppscotch/hoppscotch#1506]
**Describe the bug**
You can't log in to GitHub or Google after installation

Chrome Console error
```
{code: "auth/internal-error", message: "{"error":{"code":403,"message":"Requests from refe…son":"forbidden"}],"status":"PERMISSION_DENIED"}}", a: null}
```

**To Reproduce**
1. git clone git@github.com:hoppscotch/hoppscotch.git
2. docker-compose up
3. start http://localhost:3000

**Expected behavior**
Log on to GitHub as normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac 10.15.7 (19H2)
 - Browser Chrome 88.0.4324.96

**Comment by liyasthomas** [comment]
Authenticated features are disabled for URL origins other than `https://hoppscotch.io` due to security concerns. If you want to setup a self-hosted version, follow instructions on [Hosting Wiki page](https://github.com/hoppscotch/hoppscotch/wiki/Hosting).

> To enable authenticated features on self-hosted Hoppscotch instances, you'll need a Firebase account.
