### ISSUE TITLE
Apply syntax highlighting on generated code

### ISSUE THREAD

**Issue by GauthierPLM** [hoppscotch/hoppscotch#1507]
**Is your feature request related to a problem? Please describe.**
When generating code (for example a cURL command) from a request, the code does not uses syntax highlighting.
Having code well highlighted helps to understand what has been generated before copy-pasting it or using it as an example.

**Describe the solution you'd like**
I'd like the generated code to have syntax highlighting.

**Describe alternatives you've considered**
Copy pasting the generated code into an external text editor.

**Additional context**

![Capture d’écran 2021-02-23 à 14 29 17](https://user-images.githubusercontent.com/2579741/108850309-84256000-75e3-11eb-8182-c51cfa85d5a0.png)

**Comment by AndrewBastin** [comment]
Yeah. This seems like a no-brainer. I will get into it!

**Comment by akhilarjun** [comment]
Hey, Is anyone looking into this issue? As, is it being worked upon?
Or else I can take a dab at it and push a PR for you guys.

**Comment by liyasthomas** [comment]
That's cool. Thanks for showing interest in contributing to Hoppscotch. We use Ace editor under the hood for syntax highlighting all editor components. You can find a working example of ace component here: https://github.com/hoppscotch/hoppscotch/blob/main/components/lenses/renderers/JSONLensRenderer.vue#L43-L57

Feel free to [contact us](https://github.com/hoppscotch/hoppscotch#contact) for any help.

Ace editor: https://github.com/ajaxorg/ace

**Comment by iamtabrezkhan** [comment]
Hi guys, any update on this? Has this been addressed? I would like to help and contribute to this.

**Comment by liyasthomas** [comment]
Hi @iamtabrezkhan feel free to give it a try. Contributions are welcome 🙌.
