### ISSUE TITLE
Show folder path instead of folder name when saving a request

### ISSUE THREAD

**Issue by rohanrajpal** [hoppscotch/hoppscotch#1509]
**Describe the bug**
If two folders have the same name, then the user is confused about which folder belongs where
**To Reproduce**
1. Go to hoppscotch.io
2. Create two folders with the same name in collections tab
2. Click on `save request as`
3. Scroll down to 'folder'

**Expected behavior**
A path should be displayed instead of only the folder name.
**Screenshots**
![image](https://user-images.githubusercontent.com/7023147/108854853-5570af00-760e-11eb-8fc7-d1a77021a68a.png)

**Additional context**
I've solved the problem by modifying the code as follows

```diff
diff --git a/components/collections/save-request-as.vue b/components/collections/save-request-as.vue
index 3f9a9ee..9865916 100644
--- a/components/collections/save-request-as.vue
+++ b/components/collections/save-request-as.vue
@@ -187,12 +187,12 @@ export default {
   },
 }
 
-function getFolderNames(folders, namesList) {
+function getFolderNames(folders, namesList, folderName="") {
   if (folders.length) {
     folders.forEach((folder) => {
-      namesList.push(folder.name)
+      namesList.push(folderName+folder.name)
       if (folder.folders && folder.folders.length) {
-        getFolderNames(folder.folders, namesList)
+        getFolderNames(folder.folders, namesList, folder.name+"/")
       }
     })
   }
```
Now the view looks like
![image](https://user-images.githubusercontent.com/7023147/108861415-332e5f80-7615-11eb-8ae7-2f4e5df69b38.png)

Would be happy to make a PR if I'm assigned this issue

**Comment by liyasthomas** [comment]
This looks handy 👍 
Assigning this to you.
