### ISSUE TITLE
More than 1GB of memory used in idle

### ISSUE THREAD

**Issue by ABeltramo** [hoppscotch/hoppscotch#1513]
**Describe the bug**
Incredibly high memory usage just by running it, is 1GB+ considered normal?

**Additional context**

Running over Docker using hoppscotch/hoppscotch:latest

On startup this is logged:
```
ℹ Memory usage: 579 MB (RSS: 1.14 GB)
```

This is the result of top after leaving the image up and running (without even using it):
```
Mem: 7964896K used, 204984K free, 109544K shrd, 376316K buff, 2317880K cached
CPU:   3% usr   2% sys   0% nic  93% idle   0% io   0% irq   0% sirq
Load average: 0.21 0.18 0.24 2/1303 118
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
   24     1 root     S    1114m  14%   1   0% node /app/node_modules/.bin/nuxt
   40    24 root     S     320m   4%   2   0% /usr/local/bin/node /app/node_modules/thread-loader/dist/worker.js 20
   53    24 root     S     319m   4%   1   0% /usr/local/bin/node /app/node_modules/thread-loader/dist/worker.js 20
   46    24 root     S     317m   4%   1   0% /usr/local/bin/node /app/node_modules/thread-loader/dist/worker.js 20
   62    24 root     S     257m   3%   3   0% /usr/local/bin/node /app/node_modules/thread-loader/dist/worker.js 20
   61    24 root     S     256m   3%   3   0% /usr/local/bin/node /app/node_modules/thread-loader/dist/worker.js 20
   82    24 root     S     256m   3%   0   0% /usr/local/bin/node /app/node_modules/thread-loader/dist/worker.js 20
    1     0 root     S     256m   3%   2   0% npm
  111     0 root     S     1596   0%   1   0% sh
  118   111 root     R     1528   0%   0   0% top
```

I wasn't expecting such a high memory usage for a PWA.

**Comment by liyasthomas** [comment]
This doesn't seem to be an issue directly connected with Hoppscotch app, rather it seems like a performance issue with Nuxt.js dev env or Docker container tooling. While I'm investigating whether this much memory consumption for dev env is normal can you go through the instructions in this StackOverflow thread: [Nuxt js high CPU usage in dev environment](https://stackoverflow.com/questions/61910664/nuxt-js-high-cpu-usage-in-dev-environment).

**Comment by liyasthomas** [comment]
> ℹ Memory usage: 579 MB (RSS: 1.14 GB)

I can confirm this is an expected behavior in dev env. Hence closing this issue.

**Comment by ABeltramo** [comment]
I see your point but not everyone wants a dev environment, especially over docker which is also used for production and deployment. 
I'm not familiar with NuxtJS but I tried running your docker image with `npm run start`
```
docker run -p 3000:3000 hoppscotch/hoppscotch:latest npm run start

> hoppscotch@2.0.0 start /app
> nuxt start

ℹ Listening on: http://172.17.0.2:3000/
ℹ Serving static application from dist/
```

This gives me an environment which takes 40MB instead of 1GB+ and I can reach localhost:3000 just fine but I'm wondering:
Is the stuff in `dist/` everything that is needed? Should I execute something else?

Can you add this instructions to the README if they look fine or are you happy with a pull request?

**Comment by liyasthomas** [comment]
So Nuxt has mainly 3 commands for running the app
1. `nuxt dev` - Launch the development server.
2. `nuxt build` - Build and optimize your application with webpack for production.
3. `nuxt start` - Start the production server (after running nuxt build). Use it for Node.js hosting like Heroku, Digital Ocean, etc.

So `npm run start` works but not for dev env. You can build the app with `npm run build` once which will make create `dict/` with all static files eady for deployment and then running `npm run start` will start the production server from `/dist` which is obviously not an dev env but a production deployment.

Both works, I mentioned specifically that ~1GB memory usage is an expected behavior in dev env only. Production build is optimized.

**Comment by ABeltramo** [comment]
Thanks for the detailed reply, yes changing the Dockerfile will solve the issue (for my use case) but I can easily override the starting command, and I wonder if this will break other people usage.

Bare in mind that the [docker-compose.yml](https://github.com/hoppscotch/hoppscotch/blob/37bdd525ea318dd7a1da29324620d233d581f0c8/docker-compose.yml#L23) mounts the local files inside the container and specify `npm run dev` this seems like a good way to fire up a dev environment without installing any dependency locally.

IMHO there's not really a need to change the Dockerfile, just add a few good lines in the README.

**Comment by liyasthomas** [comment]
Sounds good to me. Will update readme with instruction on running both dev and prod server. 👍
