### ISSUE TITLE
Improve save request flow

### ISSUE THREAD

**Issue by Sun-FreePort** [hoppscotch/hoppscotch#1525]
1. create two api - "Edit user info" and "Delete user";
2. refesh page;
3. choice "Delete user" api and change something;
4. save use Ctrl + S, show me a **default panel**;
5. I'm trance and choice "Edit user info" and save.
6. congratulation! now, I has two "Delete user".... 😂

I think the tool has good, but in there, the feature puzzled me, and I want to work something, I think:

1. like Postman, in user save api, show the api panel -- if user want to "save as...", user can choice self need.
2. oher choice: if he want replace a old api, tool should show a confirm panel.

If has other suggestion, please tell me. and I want to write the feature, Can I?

**Comment by liyasthomas** [comment]
When saving a request if you want to replace / overwrite an existing one, you can choose the previous request in save modal. Let me which workflow works best for you. I didn't quite get what you meant by which operation that need to be corrected.

**Comment by Sun-FreePort** [comment]
I try to refresh page, the request hold in page, but not has "previous request" in save panel.
Now, I must choice collection、choice folder、choice request.....so hard, don't you think?

So, I suggest autoload previous request, When user need "Save as...", he/she manually choice "/"

In my work, "update request" is frequent, and "new request" is less.

Or add config? user can choice any mode.

**Comment by liyasthomas** [comment]
Thanks for your explanation. Now it makes sense. Flow of overwriting a request is somewhat confusing righ now. We're actually working on a parallel flow where you'll have a UI similar to sidebar Collections. And it'll be easy to choose a previous request in a glance.

Kindly be patient, hoping to get a working prototype by end of next week. I'll let you know when it's up.

**Comment by liyasthomas** [comment]
With the release of v2 - we've introduced "Save" and "Save as" features.

- You can now restore and save [ <kbd>Ctrl</kbd><kbd>S</kbd> ] updates to a request in collection.

- Click on the "save drop-down" to save as [ <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>S</kbd> ] another new request in collections.
