### ISSUE TITLE
单点登录

### ISSUE THREAD

**Issue by kitter960324** [hoppscotch/hoppscotch#1529]
希望可以增加其他单点登录，例如qq，微信等

**Comment by liyasthomas** [comment]
_Translated:_

我们使用Firebase进行身份验证。而且Firebase没有微信或QQ作为身份验证提供程序。因此它将不会实现。但是，如果您有兴趣，可以选择使用自定义OAuth方法。让我知道您想设置自定义Auth，我们将在另一个分支中添加有关如何实现它的说明。
