### ISSUE TITLE
Paginate / lazy load History entries

### ISSUE THREAD

**Issue by Sun-FreePort** [hoppscotch/hoppscotch#1530]
**Describe the bug**
I has hundreds request histroy, in open the hoppscotch.io, I will wating 20 ~ 40s (i7-10510U + 16G RAM -- I think not slow in my coding time).

When my clear all request history and reopen the page, only 1.5 sec consume...

**To Reproduce**
1. request more and more
2. press F5
3. chrome tell me: the page is locking!
4. wating....OK!
5. clear history
6. press F5
7. very fast open and use the hoppscotch.io!

**Desktop:**
 - OS: Windows 10 LTS
 - Browser Chrome 88.0.4324.190 (64x)

**Comment by liyasthomas** [comment]
Issue is acknowledged. So when the history has more than say 100 entries, page loading time is effectively higher than ~20s.
