### ISSUE TITLE
Getting warn after npm run dev

### ISSUE THREAD

**Issue by jerry4rahul** [hoppscotch/hoppscotch#1537]
WARN

` WARN  warn - You have enabled experimental features: uniformColorPalette, extendedSpacingScale, extendedFontSizeScale, applyComplexClasses, darkModeVariant, additionalBreakpoint`

` WARN  warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.`

[https://prnt.sc/10jtdgz)]

**Comment by liyasthomas** [comment]
You can completely ignore this `WARN` message since it is coming from TailwindCSS library. We're making use of some experimental stylings in TailwindCSS 1.x which will be absolute in TailwindCSS 2.x release. So don't worry 🙂

**Comment by jerry4rahul** [comment]
@liyasthomas Its not even working in http://192.168.0.6:3000/
What to do?

**Comment by liyasthomas** [comment]
Do you have any logs in dev console?

**Comment by jerry4rahul** [comment]
```
> hoppscotch@2.0.0 dev
> nuxt

i Using Tailwind CSS from ~/assets\css\tailwind.css
i Merging Tailwind config from ~/tailwind.config.js
i Listening on: http://192.168.0.6:3000/
i Preparing project for development
i Initial build may take a while
i Discovered Components: .nuxt/components/readme.md
√ Builder initialized
√ Nuxt files generated
i Warming up worker pools
√ Worker pools ready
i Compiling Client

 WARN


 WARN  warn - You have enabled experimental features: uniformColorPalette, extendedSpacingScale, extendedFontSizeScale, applyComplexClasses, darkModeVariant, additionalBreakpoint


 WARN  warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.

```

**Comment by liyasthomas** [comment]
Not this one. In browser console. Goto `localhost:8000` and click F12 on Chrome to open console.

**Comment by jerry4rahul** [comment]
It's working well now. I just want to know if any team functionality there.

**Comment by liyasthomas** [comment]
Team collaboration is a work in progress. Latest updates are in `teams-new-ui` branch. Follow the project here and hopefully Teams collaboration will be out for beta in couple of weeks.

**Comment by jerry4rahul** [comment]
Yeah ok... Thanks
