### ISSUE TITLE
建议字体内置

### ISSUE THREAD

**Issue by gclm** [hoppscotch/hoppscotch#1543]
**Is your feature request related to a problem? Please describe.**
目前国内部分地区访问谷歌字体网络不稳定，目前经常出现css加载字体错误，希望可以内置字体

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. I'll look into bundle fonts and host from same origin.

**Comment by gclm** [comment]
相关字体链接: https://fonts.googleapis.com/css2?family=Material+Icons&family=Poppins:wght@400;500;600;700;800&family=Roboto+Mono&display=swap

**Comment by liyasthomas** [comment]
@gclm I've made a hot fix (https://github.com/hoppscotch/hoppscotch/commit/61396cbb158e95aa6016ef8bdc03990100b0d6a6) just now. Please clear cookies and data and try again. Let me know if issues with fonts are fixed.

**Comment by liyasthomas** [comment]
Feel free to reopen if issue is persisting.
