### ISSUE TITLE
Refactor: CURL Generator 

### ISSUE THREAD

**Issue by JayceDugan** [hoppscotch/hoppscotch#1550]
This issue has been created to provide an isolated pull request for the refactoring of the `cURL` Codegen generator found in `/helpers/codegen/generators/curl.js`

To review the original issue with full descriptions related to the refactoring, [please click here.](https://github.com/hoppscotch/hoppscotch/issues/1544)

**Comment by liyasthomas** [comment]
Hi @JayceDugan,
you don't have to create separate issues for every codegen languages. Please mention #1544 for further PRs regarding codegen refactor.
