### ISSUE TITLE
Response block should be expanded by default

### ISSUE THREAD

**Issue by Xairoo** [hoppscotch/hoppscotch#1555]
`expandResponse` @ response results block should be `true` by default because it's more intuitive.

Scrolling over the full viewport is better than scrolling in a inline scroll block.

Clicking on "expand response" again and again after every request isn't cool ;-)

**Comment by liyasthomas** [comment]
@Xairoo thanks for the suggestion. We're planning on revamping the entire UI with less viewport scroll and more inline block scroll. That should resolve this issue, we're open to ideas on what all can be improved apart from scrolling. Let me know which part, components need improvements. I'm letting this issue stay untill we finalize e new UI proposal which fix some existing clutter.

**Comment by Xairoo** [comment]
Depends on how you handle this. The important part for me is the response and mainly the response body.

The `Parameters`, `Header`, ... block fits the content size, which is great.
To toggle the view of this block, we could just click again on the active tab title to hide the content (but keeps the tab titles of course).
And instead of the content like the parameters, ..., `+ Add new` button there could be a `Click to expand/toggle the view` button (and clicking the tab itself will toggle the content too).

Also the state should be saved.

**Comment by liyasthomas** [comment]
With the release of v2 - we made the response section to be expanded to full length by default.
