### ISSUE TITLE
Orange theme

### ISSUE THREAD

**Issue by KoHcoJlb** [hoppscotch/hoppscotch#1559]
Hello
Why did you remove orange theme? It was my favorite:smiley:
Could it be restored?

**Comment by liyasthomas** [comment]
Oh, sorry for that. Our UI framework TailwindCSS updated to v2.x and introduced some minor UI change in color codes. I'll add orange theme today.

**Comment by KoHcoJlb** [comment]
Thanks:thumbsup:

**Comment by liyasthomas** [comment]
![screely-1616431134673](https://user-images.githubusercontent.com/10395817/112025565-87344300-8af2-11eb-9459-fddb843881af.png)

_here you go :)_
