### ISSUE TITLE
Address Bar Updated Incorrectly

### ISSUE THREAD

**Issue by dob99** [hoppscotch/hoppscotch#1561]
**Description**
When the application is served from a directory other than root and a change is made to the URL or inputs, the path is removed from the URL.

**To Reproduce**
1. Edit the file nuxt.config.js
2. Add the following block inside _export default_:
`router: {
    base: '/hoppscotch/'
  },`
3. Run the application and go to http://localhost:3000/hoppscotch
4. Enter any URL (or change the input parameters)
=> The URL has been altered to reflect the changes, but "/hoppscotch" has been removed from it.

**Expected behavior**
Any path components in the URL will be maintained when updating it

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 89.0.4389.90

**Comment by liyasthomas** [comment]
Thanks for reporting this issue. We're working on a fix.

**Comment by liyasthomas** [comment]
@dob99 you should now be able to define a custom `router.base` property in in `nuxt.config.js` file and Hoppscotch will respect that while setting query parameters.

[Read more about Nuxt router property ->](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router/)
