### ISSUE TITLE
Importing curl doesn't add query parameters 

### ISSUE THREAD

**Issue by chakrihacker** [hoppscotch/hoppscotch#1582]
**Describe the bug**
Importing curl doesn't add query params to the URL

**To Reproduce**
1. From any chromium browser network inspect select any api request and choose copy as curl
2. Click on import curl
3. After importing query params are not available either on url or on params list

**Expected behavior**
Query params should get added to parameters list

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave
 - Version N/A

**Comment by liyasthomas** [comment]
Issues has been identified. We're working on a hot fix.

**Comment by liyasthomas** [comment]
I've made a quick fix. It might take few mins to reflect the changes on production. Let me know if this resolved your issue.

**Comment by snapeur82** [comment]
Yesss good

Le jeu. 8 avr. 2021 08 h 37, Liyas Thomas ***@***.***> a
écrit :
