### ISSUE TITLE
Getting Uncaught TypeError when importing postman json

### ISSUE THREAD

**Issue by jainal09** [hoppscotch/hoppscotch#1587]
**Describe the bug**
I was import a postman collection and got 
the following error
`Uncaught TypeError: Cannot read property 'raw' of null
    at f.parsePostmanRequest (3a861b0.modern.js:formatted:5573)
    at f.parsePostmanCollection (3a861b0.modern.js:formatted:5548)
    at FileReader.e.onload (3a861b0.modern.js:formatted:5486) 
`
[hoppscotch.io-1618064984578.log](https://github.com/hoppscotch/hoppscotch/files/6290017/hoppscotch.io-1618064984578.log)
possible error here 
`var r = o.url.raw.match(/^(.+:\/\/[^\/]+|{[^\/]+})(\/[^\?]+|).*$/)`

**To Reproduce**
1. Go to 'collection > import/export collection '
2. Click on '> import json'
3. Check Console 

**Expected behavior**
The Postman collection to be imported

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Comment by liyasthomas** [comment]
What was the Postman collection version?

**Comment by jainal09** [comment]
V 2.1

**Comment by jainal09** [comment]
Okay so when I imported the v2 collection this time there was nothing on console but there was a notification in the web app in red "Import Failed"

**Comment by jainal09** [comment]
This is a test collection (v2)
[test_collection.postman_collection.zip](https://github.com/hoppscotch/hoppscotch/files/6290623/test_collection.postman_collection.zip)
So, v2 fails to import of the above collection however 2.1 of this test collection is imported. But sadly my original collection fails to import.

**Comment by jainal09** [comment]
Okay, so upon further testing I have came to the root cause of the issue!

[test.postman_collection.zip](https://github.com/hoppscotch/hoppscotch/files/6290644/test.postman_collection.zip)
This above collection of V2.1 Fails too. The reason is because it has empty request inside it.
When I mean empty request I mean nothing inside the requests.
![image](https://user-images.githubusercontent.com/34179361/114282863-1a162c80-9a64-11eb-9ed3-2caab1be4b2b.png)
Also, the error in the console `Cannot read property 'raw' of null` matches my findings. So, I thing this is a bug that some people may have or may not (if they dont have any empty requests in their collection)

**Comment by jainal09** [comment]
So, this line https://github.com/hoppscotch/hoppscotch/blob/b9deec1487aadc4b7f14d69e7e70568c40c016e0/components/collections/ImportExport.vue#L337
Should first check if `url.raw` is not null.
Hence to prevent `Cannot read property 'raw' of null`.

**Comment by snapeur82** [comment]
Yesss

Le sam. 10 avr. 2021 16 h 58, Jainal Gosaliya ***@***.***> a
écrit :

**Comment by jainal09** [comment]
@snapeur82 didnt get you man?

**Comment by liyasthomas** [comment]
Looks like a spam account.

**Comment by liyasthomas** [comment]
> So, this line
> 
> https://github.com/hoppscotch/hoppscotch/blob/b9deec1487aadc4b7f14d69e7e70568c40c016e0/components/collections/ImportExport.vue#L337
> 
> 
> Should first check if `url.raw` is not null.
> Hence to prevent `Cannot read property 'raw' of null`.

@jainal09 can you verify and raise a PR with this fix.

**Comment by jainal09** [comment]
will try!

**Comment by jainal09** [comment]
https://github.com/hoppscotch/hoppscotch/pull/1593

Done
