### ISSUE TITLE
Environment variables do not bind into request parameters

### ISSUE THREAD

**Issue by haupv1m** [hoppscotch/hoppscotch#1603]
**Describe the bug**
I'm using hoppscotch and want to binding environment variable value into request query parameters. However, when using environment variable witth double angular brackets, it's not binded

**To Reproduce**
- Setup as ![image](https://i.imgur.com/sCUAvDF.png)
- Check request on server side

**Expected behavior**
- apiToken environment variable value is binded into `t` request parameter

**Screenshots**
![image](https://i.imgur.com/sCUAvDF.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser chrome
 - Version 89.0.4389.114

**Comment by liyasthomas** [comment]
You've to change `Parameter type` from `Query` to `Path`.

<img width="895" alt="Screenshot 2021-04-15 at 12 41 01 PM" src="https://user-images.githubusercontent.com/10395817/114828736-1a256d80-9d7f-11eb-9938-bb88d6eb7551.png">

**Comment by haupv1m** [comment]
@liyasthomas Sorry for missing context, I want to binding environment variable into request **query params** not **path params** (parameter type must be `Query`) (as you can see in picture)

**Comment by liyasthomas** [comment]
Did you add environments from sidebar?

**Comment by haupv1m** [comment]
@liyasthomas Yes, from my pre request-script
```
pw.env.set('endpoint', ' http://example.com');
pw.env.set('apiToken', 'xxxx');
```

**Comment by liyasthomas** [comment]
<img width="538" alt="Screenshot 2021-04-15 at 3 33 15 PM" src="https://user-images.githubusercontent.com/10395817/114851892-23223900-9d97-11eb-9171-d15ec9eaa277.png">
