### ISSUE TITLE
Installing as a PWA, Requests fail untill you install chrome extension

### ISSUE THREAD

**Issue by tygalive** [hoppscotch/hoppscotch#1606]
**Describe the bug**
All requests fail until you install the chrome extension and it doesn't tell you why the requests are failing, instead says:

Setup a proxy and press f12 to view the log

And the log doesn't have any useful information. This might give the impression to first time users that it does not work and might be better to first test for the chrome extension and show an appropriate message if it does not exist

**To Reproduce**
1. Goto hopscotch.io
2. Top left, url input click download and install
3. Open app and try a request
4. Just an error message without much useful information on how to proceed

**Expected behavior**
After entering url and hitting send. At least check if chrome extension is available and if not required set self up for that

**Screenshots**
Reproducible on windows, android and linux

**Desktop (please complete the following information):**
 - OS: Linux Manjaro
 - Browser chrome
 - Version 86

**Smartphone (please complete the following information):**
 - Device: Samsung a20
 - OS: android 10
 - Browser chrome
 - Version 10

**Additional context**
None

**Comment by liyasthomas** [comment]
By default, browser extension is not required to make API requests to hosted API endpoints. I guess you're requesting locally (`localhost`) served API endpoints which why request failed without browser extension.

We already have a similar issue ticket on #1376 where we're discussing better approaches to let the user know what went wrong and how to fix it. Please continue discussion on that thread and feel free to respond what you'd like to expect on such error cases. Thanks - closing this issue for #1376.

**Comment by tygalive** [comment]
![Screenshot from 2021-04-19 16 24 10](https://user-images.githubusercontent.com/19529979/115252759-0c2f6e00-a12c-11eb-840d-59fa82e3fc35.png)
Here is a screenshot to help clarify. no extension and that's the message i get plus the url to a remote server.

**Comment by liyasthomas** [comment]
You've to use `https://` (HTTPS) protocol. Oru else, try enabling Proxy mode from Settings > Proxy which allows you to request `http://` endpoints.

**Comment by tygalive** [comment]
Ok have noticed the other issue. the error messages are actually the same. Would have loved to test my api's through a mobile device when not near a pc, (guess won't be possible if extension is required).

Have attached a screenshot after clearing the console and hitting send with https
![Screenshot from 2021-04-19 16 30 44](https://user-images.githubusercontent.com/19529979/115254017-3e8d9b00-a12d-11eb-8683-080e92337c13.png)

**Comment by liyasthomas** [comment]
Extension is only required to access APIs hosted in local server. Everything else can be fix by turning on Proxy Mode from https://hoppscotch.io/settings

**Comment by tygalive** [comment]
Had tried with https.

Though looking at the bigger picture here, a user installs tries a url and gets above message. the first thing that comes to their mind is this extension does not work. The end result is most likely high downloads but low user retention. After going through [#1376](https://github.com/hoppscotch/hoppscotch/issues/1376) i realised there are a few things we can do to go around this

1. Ask user to install extension to proceed (somewhat forced)
2. Bring up a dialog telling user that either they are not connected to the internet and or ask them to install extension
3. Notify user some way that only https works without the extension

Though all this basically comes down to the extension. Most test requests are done in local enviroments as opposed to production and would be detrimental to this app to only work by default on production api.

This is not my first time trying this app, but failed on first attempt and had to find a quick alternative as i did not have the time to try and find where the issue was. Today i tried again and after going through the settings GUESSED that maybe i needed to install an extesion and that's when i was able to successfully make a request. Not sure most would make such a wild guess.

I don't think asking users to setup a proxy is going to work when they can already do requests through alternatives and most probably have never setup one, (I for one).

**Comment by liyasthomas** [comment]
As per the error message you got (https://github.com/hoppscotch/hoppscotch/issues/1606#issuecomment-822510787), the toast clearly shows to turn on Proxy mode for non https requests. Clicking on "Yes" will take you to Settings page from where you can turn on Proxy mode.

And turning on the Proxy would fix this instantaneous. As simple as that.

Also, you don't need to setup your own proxy for Proxy Mode. It does have a default proxy URL which is hosted by Hoppscotch itself and it's source code available under the organisation.

**Comment by tygalive** [comment]
Ok. guessing this issue will never be solved.

Just tried the proxy with extension disabled and another error message. Was just expressing my first impressions. Not sure how proxies work but i use a mobile connection and incoming requests are automatically blocked by my service provider.

Have a good a day. thanks for your time.
