### ISSUE TITLE
HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by thazsobral** [hoppscotch/hoppscotch#1609]
**Describe the bug**

**To Reproduce**
1. Go to URL: localhost:3000/
2. Click on Send

**Expected behavior**
expected the return of a GET request.

**Screenshots**
![image](https://user-images.githubusercontent.com/30708148/115333907-7239e680-a168-11eb-834d-963083144325.png)
![image](https://user-images.githubusercontent.com/30708148/115333422-9f39c980-a167-11eb-882d-978ba7d5fe66.png)

**Desktop:**
 - OS: Fedora 33
 - Browser chrome
 - Version 90.0.4430.72 (Official Build) (64-bit)

**Comment by liyasthomas** [comment]
To access `localhost`, you need to install [Hoppscotch Browser extension](https://github.com/hoppscotch/hoppscotch-extension). Let me know if it solves your issue.

**Comment by liyasthomas** [comment]
Feel free to re-open this issue if installing extension doesn't resolve tje above mentioned issue.
