### ISSUE TITLE
How do I use the environment variables? Is there a demo?

### ISSUE THREAD

**Issue by illeagalName** [hoppscotch/hoppscotch#1612]

**Comment by illeagalName** [comment]
aha,I know how to use it, I use this notation  {{}}   all the time, so I'm going to use this notation <<>>

**Comment by liyasthomas** [comment]
Glad you figured it out. Here's the Wiki page for pre-request scripts and hiw to set environments: https://github.com/hoppscotch/hoppscotch/wiki/Pre-Request-Scripts

Closing this issue.

**Comment by mhmda-83** [comment]
i have and Environment called "sample"
and this environment has one variable ("name")
how can i use name enviroment variable?
@liyasthomas

**Comment by liyasthomas** [comment]
You can use `<<sample>>` in the request section after selecting the created environment from right sidebar. [Demo](https://github.com/hoppscotch/hoppscotch/wiki/Pre-Request-Scripts)
