### ISSUE TITLE
Websocket (socket.io) not connecting

### ISSUE THREAD

**Issue by AllanOricil** [hoppscotch/hoppscotch#1614]
**Describe the bug**
I have a websocket running alongside an express app and when I click "connect" in hoppscotch it displays an error message, but in the express side I can see a "connected" log displayed. So it means hoppscotch is hitting the websocket but it fails to retain the connection

![image](https://user-images.githubusercontent.com/55927613/115769089-0ee7c880-a3a3-11eb-99ae-9bfada26f2e4.png)

Express Log

![image](https://user-images.githubusercontent.com/55927613/115769190-2c1c9700-a3a3-11eb-9d5d-67497e4160d8.png)

**To Reproduce**
1. Attach a websocket using socket.io in an express app
2. Open hoppscotch and hit "connect"

**Expected behavior**
It should connect

**Screenshots**
It is not connecting

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Additional context**
Express App dependencies

"dependencies": {
    "@types/vscode": "^1.53.0",
    "applicationinsights": "^1.8.2",
    "axios": "^0.21.1",
    "cors": "^2.8.5",
    "dateformat": "^4.5.1",
    "dotenv": "^8.2.0",
    "express": "^4.17.1",
    "fs-extra": "^9.0.1",
    "jsforce": "^2.0.0-beta.3",
    "morgan-body": "^2.6.4",
    "node-machine-id": "^1.1.12",
    "objects-to-csv": "^1.3.6",
    "open": "^8.0.2",
    "qs": "^6.9.4",
    "rotating-file-stream": "^2.1.3",
    "socket.io": "^2.4.1"
  }

**Comment by AllanOricil** [comment]
This other tool connects without a problem. Maybe it is because you are using socket.io 3? If so, there should be an option to choose socket.io version


![image](https://user-images.githubusercontent.com/55927613/115771416-cda4e800-a3a5-11eb-9e02-e0a79be2ad90.png)

**Comment by liyasthomas** [comment]
Thanks for reporting the issue. We'll take a look at it and get back to you.

**Comment by AllanOricil** [comment]
I think you will have three builds one for each socketio client version (2,3 4)  and then give the option for the user to switch between them. You can have routes like

../socketio/3
../socketio/2
../socketio/4

Then on your dns you configure a CNAME for each build when the user reaches that particular route. The downside I see is that it will require a page reload :/

**Comment by AllanOricil** [comment]
Oh I just found that we can have multiple versions of the same dependency using aliases. I just don't know if the imports will use the aliases or the lib.

**Comment by blenderskool** [comment]
@liyasthomas Can I experiment and try working on this?

**Comment by liyasthomas** [comment]
Hi @blenderskool, you're free to take a shot at this. Am assigning this issue to you, do let us know if you need any help understanding the codebase.

**Comment by abishekpp** [comment]
still not solved
