### ISSUE TITLE
Support setting the Sec-WebSocket-Protocol header on WebSocket connections

### ISSUE THREAD

**Issue by oshoham** [hoppscotch/hoppscotch#1620]
**Is your feature request related to a problem? Please describe.**
I sometimes use the `Sec-WebSocket-Protocol` header to authenticate WebSocket endpoints, and I think it'd be great if Hoppscotch supported setting that particular header on WebSocket connections.

I'm aware of the existing discussions around setting headers on WebSocket connections and that that's not likely to happen, but `Sec-WebSocket-Protocol` is the only header that the browser WebSocket API explicitly allows programmers to set (via the 2nd argument to the [WebSocket constructor](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket)).

Please consider making an exception for this particular header, as I think that it merits being considered separately from the question of whether to allow setting arbitrary headers on WebSocket connections.

**Describe the solution you'd like**
I'd like to see an additional field in the WebSocket pane that allows the user to input a value for the `Sec-WebSocket-Protocol` header to be set on the WebSocket connection when it is established.

**Describe alternatives you've considered**
I'm aware that there are other approaches to authenticating WebSocket connections, e.g. using a query parameter, but `Sec-WebSocket-Protocol` is a widely-supported part of the browser WebSocket API.

**Comment by liyasthomas** [comment]
Will look into this.

**Comment by liyasthomas** [comment]
Hoppscotch now supports Sec-WebSocket-Protocol headers on WebSocket connections.
