### ISSUE TITLE
html lang="en"

### ISSUE THREAD

**Issue by Tarrowren** [hoppscotch/hoppscotch#1628]
![image](https://user-images.githubusercontent.com/35626141/117232050-02f41000-ae53-11eb-903b-c9ae95c4ef1c.png)  

There are annoying popup when using other languages  

![image](https://user-images.githubusercontent.com/35626141/117231690-4bf79480-ae52-11eb-97f8-729cb5e2b7ed.png)

**Comment by liyasthomas** [comment]
This is not an Hoppscotch service, instead a service by Chrome browser. You can turn this off from Browser Settings. Please refer these threads on how to turn it off:

- [Chrome Disable “Translate This Page?” pop-up, but keep translation feature](https://superuser.com/questions/1418065/chrome-disable-translate-this-page-pop-up-but-keep-translation-feature)
- [How to disable the popup of Google translate in chrome while it still translates](https://superuser.com/questions/356819/how-to-disable-the-popup-of-google-translate-in-chrome-while-it-still-translates)
- http://pearsonsupport.helpserve.com/Knowledgebase/Article/View/898/202/myenglishlab-turn-off-google-chrome-auto-translation-feature-when-using-myenglishlab

Thanks for using Hoppscotch.
