### ISSUE TITLE
Add benchmarking to url routes

### ISSUE THREAD

**Issue by sourabhmandal** [hoppscotch/hoppscotch#1645]
While developing and testing I would also like to know various performance metrics response time, CPU Usage, Memory Usage, Request Per Minute (RPM), Average and Max Latency, etc

**Describe the solution you'd like**
Get benchmark metrics of various endpoints and visualize them in the graphs.

**Additional context**
A reference solution that i came accross - [bench-routes](https://github.com/bench-routes/bench-routes)

**Comment by liyasthomas** [comment]
Can you explain a little more about the features?
Like monitoring and analyzing performance etc need to be done at the server end right? How Hoppscotch can be of any help here?

**Comment by sourabhmandal** [comment]
since hopscotch is web-based we can add benchmarking on the server by calling server hosted routes

**Comment by sourabhmandal** [comment]
if API URL is hosted locally (localhost:8000) then the app shows limited stats like CPU usage, memory usage which we can get locally. but if hosted in server and a hosted API is called we app would give full-blown metrics.

**Comment by liyasthomas** [comment]
> since hopscotch is web-based we can add benchmarking on the server by calling server hosted routes

How? I mean Hoppscotch is a 100% client side application and makes requests to an API endpoint. I'm having trouble understanding how we get metrics like CPU Usage, Memory Usage, Request Per Minute (RPM), Average and Max Latency, etc without having access to server which is obviously not going to happen for an API client.
