### ISSUE TITLE
Feature [GitHub Externship]: Synthetically Generate Data

### ISSUE THREAD

**Issue by officalshubhamrawal** [hoppscotch/hoppscotch#1649]
**Is your feature request related to a problem? Please describe.**
It's difficult to test out API speed on a large data set or with real-time data with n rows and different types.

**Describe the solution you'd like**
We can boost data-driven testing by creating synthetic data like addresses, security numbers and more or we can import the data from a CSV file. Users can create the fields for the number of rows they want the data should have, what type it should be in. etc.

**Describe alternatives you've considered**
I tried postman once it's an excellent API collaboration tool, but it has limited functionality when it comes to API speed testing.

**Comment by liyasthomas** [comment]
Hi @officalshubhamrawal,
Kindly add your GitHub Externship proposal in [Discussions](https://github.com/hoppscotch/hoppscotch/discussions) > [GitHub Externship](https://github.com/hoppscotch/hoppscotch/discussions/categories/github-externship) category.

Refer our [proposal template](https://github.com/hoppscotch/hoppscotch/discussions/1616) for format.
