### ISSUE TITLE
Project not running on local machine.

### ISSUE THREAD

**Issue by rohit-raje-786** [hoppscotch/hoppscotch#1661]
Even after installing all the dependencies and following all the procedure for the running the project on local environment the project is not running on my local machine. Attaching the image of the same below.
![image](https://user-images.githubusercontent.com/61861303/118925242-03fd6500-b95c-11eb-8ff4-53f88dc159e0.png)
![image](https://user-images.githubusercontent.com/61861303/118925273-0eb7fa00-b95c-11eb-83c9-d575ad2a6fc2.png)

**Comment by liyasthomas** [comment]
Is there any logs in browser console?

I guess you missed the [first step](https://github.com/hoppscotch/hoppscotch#developing) which is to set-up environment variables for local development.

Rename `.env.sample` to `.env` and restart your local development server. Also feel free ro replace environment variables if you'd like to your own Firebase instance.

**Comment by codati** [comment]
ok thx i'm testing

**Comment by liyasthomas** [comment]
I'm checking whether is it possible to pack a `.env` in the docker image. I'll update once I get a successful result.

**Comment by codati** [comment]
thank you

**Comment by gandhisamay** [comment]
@liyasthomas packing the .env in the docker image doesn't work for me as well, even though the right environment variable values are displayed in docker desktop, it still uses the values mentioned in the .env.example file only

**Comment by liyasthomas** [comment]
Can you make sure you did a complete docker restart? Bring all existing docker images associated with Hoppscotch and spin up again to reflect `.env` file contents.

**Comment by gandhisamay** [comment]
yes, it doesn't work. I tried building my own image as well, still no luck
