### ISSUE TITLE
Environment name is not cleaned in "New environment" popup

### ISSUE THREAD

**Issue by GauthierPLM** [hoppscotch/hoppscotch#1662]
**Describe the bug**
When two environments are created one after the other, the "name" field is not reset between creation.

**To Reproduce**
1. Go to Environment page.
2. Create a new environment named "Test" and validate.
3. Click on the "new" button to create an environment: "Test" is already set as name.

**Expected behavior**
The field should be cleaned when the pop-up is opened.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 88.0.1 (64 bits)

**Comment by liyasthomas** [comment]
Thanks for this suggestion. I'm working on a fix.

**Comment by liyasthomas** [comment]
The fix should be live - please refresh to update the change.

**Comment by GauthierPLM** [comment]
I confirm it now works as expected. Thank you! 👍
