### ISSUE TITLE
Feature [GitHub Externship]: Graphical Interface for API Response Visualization

### ISSUE THREAD

**Issue by soumallyadev07** [hoppscotch/hoppscotch#1663]
**Is your feature request related to a problem? Please describe.**
When the response data is large and consists of multiple dictionaries and sub-dictionaries, it is very difficult to understand and use the data. Due to this, the subsequent development gets delayed or the code gets complicated to match the complexity of the response object.

**Describe the solution you'd like**
Since we can't change the response object as it will corrupt the data our user is trying to get or understand, we can try and make a beautiful visualization of the response using a hierarchical collapsable drawer-like graphical interface so that the user can minimize the necessary parts of the response and focus only on the parts important to them, this will also help them easily understand the relationship between different data points and their parenthood or children. 

**Describe alternatives you've considered**
I've seen on different websites like Postman where they try to visualize the data and display it as HTML but it has never really helped me understand the data better.

**Additional context**
Adding a visual component might help developers to accelerate their development and not spend much time making sense out of their data.
![74-2](https://user-images.githubusercontent.com/55331884/118976767-0202c880-b993-11eb-8696-d7f9070bd140.png)

**Comment by liyasthomas** [comment]
Please submit your proposal under Discussions > [GitHub category](https://github.com/hoppscotch/hoppscotch/discussions/categories/github-externship)
