### ISSUE TITLE
Docker container doesn't work ("Your API key is invalid, please check you have copied it correctly")

### ISSUE THREAD

**Issue by TranquilMarmot** [hoppscotch/hoppscotch#1671]
**Describe the bug**
Running hoppscotch in a docker container doesn't work.

**To Reproduce**
Following the steps here: https://github.com/hoppscotch/hoppscotch#docker
- `docker pull hoppscotch/hoppscotch`
- `docker build -t hoppscotch/hoppscotch:latest .`
- `docker run -p 3000:3000 hoppscotch/hoppscotch:latest`
- Visit `http://localhost:3000/`

**Expected behavior**
- See hoppscotch

**Actual behavior**
- Just a loading image

Error in JS console:

```js
{ code: "auth/invalid-api-key", message: "Your API key is invalid, please check you have copied it correctly.", a: null, stack: "" }
```

It looks like this is coming from firebase.

Is the `README` missing a step here?

**Comment by liyasthomas** [comment]
Hi @TranquilMarmot sorry this happened.
In readme there's ba Step 0: Settings up environment variables for local development set-up which you can [find here](https://github.com/hoppscotch/hoppscotch#developing)

Please follow how you can do it with Docker image in this issue comment: https://github.com/hoppscotch/hoppscotch/issues/1667#issuecomment-845238480

Let me know if you still have any issues with Docker image
