### ISSUE TITLE
run error  "npm run dev"

### ISSUE THREAD

**Issue by isiit** [hoppscotch/hoppscotch#1676]
ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\postwoman\hoppscotch-main\node_modules\ace-builds\src-noconflict\ace.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\postwoman\hoppscotch-main\node_modules\ace-builds\src-noconflict\worker-javascript.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\postwoman\hoppscotch-main\node_modules\ace-builds\src-noconflict\worker-xquery.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\postwoman\hoppscotch-main\node_modules\ace-builds\src-noconflict\mode-php_laravel_blade.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\postwoman\hoppscotch-main\node_modules\ace-builds\src-noconflict\mode-php.js as it exceeds the max of 500KB.

**Comment by liyasthomas** [comment]
Can you provide a full steps to reproduce the error and a screenshot of error?

Please use the issue template for reporting issues.
