### ISSUE TITLE
Why didn't I see the options in my hoppscotch? How to display the all functions like https://hoppscotch.io?

### ISSUE THREAD

**Issue by superFarmer** [hoppscotch/hoppscotch#1713]
![图片](https://user-images.githubusercontent.com/24667795/121626944-ffceee00-caa8-11eb-8759-84d82feadb2e.png)
![图片](https://user-images.githubusercontent.com/24667795/121626989-16754500-caa9-11eb-9a95-4560eac8eea3.png)

**Comment by liyasthomas** [comment]
Are there any errors in the browser console logs?

**Comment by superFarmer** [comment]
emm... Yeah，I see some error messages from the logs
![图片](https://user-images.githubusercontent.com/24667795/121627617-47a24500-caaa-11eb-9f1b-9cc29bd0823b.png)

**Comment by liyasthomas** [comment]
Can you do a force refresh <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd> and see if it solved this component caching issue?

**Comment by superFarmer** [comment]
ok,I'll try. Thank you very much

**Comment by liyasthomas** [comment]
Let me know if it solved your issue?

**Comment by superFarmer** [comment]
I've solved this issue by your method.It worked fine. Thanks!

**Comment by superFarmer** [comment]
I've solved this issue by your method.It worked fine. Thanks!
