### ISSUE TITLE
how to set credential true

### ISSUE THREAD

**Issue by tanay-pingalkar** [hoppscotch/hoppscotch#1714]
i am testing a graphql server that sets a cookie, but the server responded with 400 because my credentials are not set to true , how can i do that

**Comment by AndrewBastin** [comment]
Hi Tanay!

We don't offer cookie support right now due to technical limitations of what is available to us via the browser.

Please refer to this: #1383 

Thank you for using Hoppscotch!

Happy hacking!

**Comment by whinc** [comment]
add this line
