### ISSUE TITLE
Make right sidebar collapseble

### ISSUE THREAD

**Issue by sourabhmandal** [hoppscotch/hoppscotch#1716]
**Is your feature request related to a problem? Please describe.**
Right Side navbar is somewhat distracting.
**Describe the solution you'd like**
we can add a toggle button which will minimise the right sidenavbar to an Icon Navbar for (History, Collection, environments and notes).

**Additional context**

![Screenshot from 2021-06-12 15-12-05](https://user-images.githubusercontent.com/39632788/121772274-09805080-cb92-11eb-86d8-ee7a8749620b.png)

**Comment by liyasthomas** [comment]
Thanks for the feature request. You can now show/hide the sidebar.

![screely-1623495525106](https://user-images.githubusercontent.com/10395817/121773956-fe7eed80-cb9c-11eb-9915-17351ee7d1a1.png)
