### ISSUE TITLE
Auto scroll to Response Object

### ISSUE THREAD

**Issue by sourabhmandal** [hoppscotch/hoppscotch#1717]
**Is your feature request related to a problem? Please describe.**
I often use hoppscotch but since responses are at bottom of page its frustrating that i have to scroll down to the bottom of page, especially when using a mouse. 

**Describe the solution you'd like**
Would love to have an auto-scroll feature that points to the Response object after request completes.

**Additional context**
I would like to work on this feature

**Comment by liyasthomas** [comment]
We already have an auto-scroll to response feature on [Settings](https://hoppscotch.io/settings) page.

<img width="1440" alt="Screenshot 2021-06-12 at 4 43 49 PM" src="https://user-images.githubusercontent.com/10395817/121774024-8107ad00-cb9d-11eb-9f89-14885882965b.png">

Make sure you've turned on the feature toggle button. And of course, you're free to introduce any improvements to the current implementation 😄 .
