### ISSUE TITLE
Broken gql collection request editor

### ISSUE THREAD

**Issue by s-r-x** [hoppscotch/hoppscotch#1722]
**Describe the bug**
Gql collection request editor is broken.
The error raises here: https://github.com/hoppscotch/hoppscotch/blob/5246284e3299bff77c7304406cd727961d698d2f/newstore/collections.ts#L192

**To Reproduce**
https://user-images.githubusercontent.com/41614937/122032514-2498cd80-cde9-11eb-8509-2355d9574aad.mp4

**Expected behavior**
Expected not to be broken :)

**Comment by AndrewBastin** [comment]
Lol, the popup menu is not supposed to be enabled on the Save Request Modal. But since you already implemented it, I will figure out the remaining small stuff to make the integration work properly.
