### ISSUE TITLE
adjust font size

### ISSUE THREAD

**Issue by WLun001** [hoppscotch/hoppscotch#1731]
**Is your feature request related to a problem? Please describe.**
The default font size is a bit large to scroll through JSON responses

**Describe the solution you'd like**
Able to adjust font size in setting

**Describe alternatives you've considered**
Use browser zoom

**Additional context**
- Good to have feature, but feel free to reject if not necessary .

**Comment by liyasthomas** [comment]
I've decreased the font size from 16px to 15px on ace editors. Hope it helps.
