### ISSUE TITLE
Shortcut buttons are missing when switch to other language than English

### ISSUE THREAD

**Issue by WLun001** [hoppscotch/hoppscotch#1732]
**Describe the bug**
The following buttons are missing on the side bar (request, options, response)
![image](https://user-images.githubusercontent.com/23547929/122730544-ea2da580-d2ac-11eb-89c5-22cc0dfb6b21.png)

**To Reproduce**
1. Switch to other language than English

**Desktop (please complete the following information):**
 - Device: macOS 11.4
 - Browser: Chrome
 - Version: `91.0.4472.106 (Official Build) (x86_64)`

**Comment by liyasthomas** [comment]
Thanks for reporting this issue - we're working on a fix.
