### ISSUE TITLE
FireBase API key is required to run the application?

### ISSUE THREAD

**Issue by darkl0rd** [hoppscotch/hoppscotch#1733]
My intent is to self-host the application, previously (when it was still postwoman) this worked without too much hassle. After having recently upgraded to the latest version of Hoppscotch, I'm now finding out that I need an API key at FireBase to -run- the application, is this intended? If so, why?

**Comment by liyasthomas** [comment]
We've gradually add more features like cloud sync, teams collaboration etc which requires a backed provider ie: a Firebase instance.

You can use your own Firebase config keys or use the default one in .env.example file in the root.

**Comment by darkl0rd** [comment]
The follow up question I was going to raise, is that starting the application using the provided API keys in the example prevents the app from starting up (spinning ball on screen, console reports invalid api key).

**Comment by liyasthomas** [comment]
Possible duplicate of #1661.
Please refer to https://github.com/hoppscotch/hoppscotch/issues/1661#issuecomment-844741363.

**Comment by darkl0rd** [comment]
Yes, I have done that already. As per my previous post, the provided default API key (that is defined in .env.example) does not work and gives this error.

**Comment by liyasthomas** [comment]
I can confirm the default env keys are working.

- For development environment: rename `.env.example` to `.env`.
- For production/self-host environment: add environment variables from `.env.example` to build environment variables like Netlify, Vercel etc.
