### ISSUE TITLE
New environment not being saved

### ISSUE THREAD

**Issue by NickNish09** [hoppscotch/hoppscotch#1735]
**Describe the bug**
Environments not saving when I try to create a new one, either logged in or not.

**To Reproduce**
1. Go to home page https://hoppscotch.io/
2. Click on Environments tab
3. Create a new environment and save it
4. Refresh the page

**Expected behavior**
When I refresh the page I should still see the created environment.

**Screenshots**
Created a new environment named `My new env`
![hoppscotch1](https://user-images.githubusercontent.com/27820474/123567165-e8298200-d797-11eb-9f09-169ae3274219.png)

Refreshed the page, and it is gone
![hoppscotch2](https://user-images.githubusercontent.com/27820474/123567153-e3fd6480-d797-11eb-934a-fc5a60d0d277.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 91.0.4472.114

**Additional context**
Tried logged in and without logging in.
Also tried on a MacOS 10.15

I looked at the console and this error seems to be appearing, I dont know if maybe related:
```
Uncaught TypeError: Cannot read property 'environment' of undefined
```

**Great project by the way! Thanks for the attention**

**Comment by liyasthomas** [comment]
Thank you for reporting the issue, we're working on a quick fix.
