### ISSUE TITLE
 environment variables

### ISSUE THREAD

**Issue by mono2048** [hoppscotch/hoppscotch#1739]
**Is your feature request related to a problem? Please describe.**
I don't know how to use environment variables in PWA.

**Describe the solution you'd like**
After I read the document, I don't know how to use the environment variable syntax, I hope to see the detailed usage in the README file.

**Comment by liyasthomas** [comment]
You can use the environment variables in the request section by mentioning them enclosed in double angular brackets (`<<>>`).

Please read the [Environments Wiki page](https://github.com/hoppscotch/hoppscotch/wiki/Environments) on how to use environments. Let me know if this solves your issue.
