### ISSUE TITLE
[feature]: Collection runner (GUI, CLI or Both)

### ISSUE THREAD

**Issue by mihastele** [hoppscotch/hoppscotch#1740]
I was using this application a few times as an alternative to Postman. But I am not sure, is it possible to run all tests at once? It would be a really good feature, Postman supports it (also from CLI called Newman), but I had many issues with it.

It would be nice to run all the tests from the CLI using a simple command.

Another alternative could be a GUI runner, which would be more user friendly, but CLI I think is better because you can automate stuff.

**Comment by liyasthomas** [comment]
We're working on a similar implementation that allows you to run tests from the web app, CI, CLI, etc. Keep an eye on its public repository: https://github.com/hoppscotch/hopp-js-sandbox.

I will update here once it's production-ready.

**Comment by vibhuti019** [comment]
Can I work on this section? I would like to add a "automate" option where all the requests can be stored in the same way as we do in .rest vscode. Then once started it will request all the endpoints and return a JSON document.
Waiting for your reply..

**Comment by liyasthomas** [comment]
Hi @vibhuti019, you can pick up this feature if you're interested.

**Comment by liyasthomas** [comment]
We've [Hoppscotch CLI <sub>ALPHA</sub>](https://github.com/hoppscotch/hoppscotch/tree/main/packages/hoppscotch-cli)

**Comment by mihastele** [comment]
Thank you for notifying :)
