### ISSUE TITLE
npm install => npm run dev ，problems occurred。 npm 7.20.0 ,help me!!!

### ISSUE THREAD

**Issue by MeBetterMan** [hoppscotch/hoppscotch#1744]
`` ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\github-projects\hoppscotch\node_modules\ace-builds\src-noconflict\ace.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\github-projects\hoppscotch\node_modules\ace-builds\src-noconflict\worker-javascript.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\github-projects\hoppscotch\node_modules\ace-builds\src-noconflict\worker-xquery.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\github-projects\hoppscotch\node_modules\ace-builds\src-noconflict\mode-php.js as it exceeds the max of 500KB.

 ERROR  [BABEL] Note: The code generator has deoptimised the styling of D:\github-projects\hoppscotch\node_modules\ace-builds\src-noconflict\mode-php_laravel_blade.js as it exceeds the max of 500KB.`
![Snipaste_2021-07-19_17-28-46](https://user-images.githubusercontent.com/13814832/126137813-ec85a446-0396-4e27-aed6-c2773a321ac8.jpg)
![Snipaste_2021-07-19_17-28-59](https://user-images.githubusercontent.com/13814832/126137878-65f5bc70-277c-4dc6-bdbd-33d29eb4b5a5.jpg)

`

**Comment by liyasthomas** [comment]
Can you delete the node cache along with `node_modules` folder and then run `npm i` again.

1. `rm -rf node_modules`
2. `npm i`
3. `npm run dev`

Let me know if this solved your issue.

**Comment by MeBetterMan** [comment]
i delete all folders,and regit Hoppscotch . useless . i tried two days . hopeless.

**Comment by MeBetterMan** [comment]
![Snipaste_2021-07-19_17-28-46](https://user-images.githubusercontent.com/13814832/126164039-95bb8f47-6f22-4296-ba5c-5dbe1c485356.jpg)
happens always on Win7. how to solve it？

**Comment by liyasthomas** [comment]
Please share the screenshot of the browser console log (press F12 for Chrome browser).

Also, let me know the system's memory, processor, and RAM specifications.

**Comment by MeBetterMan** [comment]
![Snipaste_2021-07-19_21-11-13](https://user-images.githubusercontent.com/13814832/126165053-2e5b59ae-a85d-454a-9da9-aca84e7f87d4.jpg)
![Snipaste_2021-07-19_17-28-46](https://user-images.githubusercontent.com/13814832/126165058-54c2bf73-8dbb-46f8-a396-a43579b941a6.jpg)
other users encountered the problems before

**Comment by liyasthomas** [comment]
Thanks for sharing the screenshot, we're looking into this issue.

Thanks for your patience.

**Comment by MeBetterMan** [comment]
max os ，the same problem

<img width="1439" alt="微信图片_20210719212103" src="https://user-images.githubusercontent.com/13814832/126166293-31db56cc-eb2b-4dcd-94f3-c6ac36547191.png">
<img width="1437" alt="微信图片_20210719211955" src="https://user-images.githubusercontent.com/13814832/126166314-560042a6-9cbc-4c71-9b23-a4e66032d810.png">

**Comment by MeBetterMan** [comment]
Mac OS，same problem.
<img width="1437" alt="1" src="https://user-images.githubusercontent.com/13814832/126166572-ddfd4744-c910-4164-a76b-222ce1b78208.png">
<img width="1439" alt="2" src="https://user-images.githubusercontent.com/13814832/126166590-7bb85995-f2fb-4902-8479-c614c8e73468.png">

**Comment by liyasthomas** [comment]
Hi @MeBetterMan, thank you for your patience.

I was able to reproduce your issue. It has been due to the incorrect setup of environment variables for the local development server.

In the [developing instructions](https://github.com/hoppscotch/hoppscotch#developing) section, there's a step 0: Update `.env.example` file found in repository's root directory with your own keys and rename it to `.env`.

Please rename `.env.example` file found in root director to `.env` and restart the local server to fix this issue.

Let me know if this solves your issue.

**Comment by MeBetterMan** [comment]
ok ，solve the problem although the  ‘’it exceeds the max of 500KB.‘’Error still exists

**Comment by MeBetterMan** [comment]
ok ，solve the browser ‘’logEvent‘’ problem ，although the ‘’it exceeds the max of 500KB.‘’Error still exists

**Comment by AndrewBastin** [comment]
That error won't cause any issues if you run it actually. It is just an error from the optimizer and ace-editor code just messing up. You should still be able to access the site successfully.
