### ISSUE TITLE
npm run generate，error

### ISSUE THREAD

**Issue by MeBetterMan** [hoppscotch/hoppscotch#1746]
**Describe the bug**
npm install => npm run generate => put dist folders into tomcat webapps =>error happens
![Snipaste_2021-07-19_17-28-46](https://user-images.githubusercontent.com/13814832/126272712-efe66dd6-a831-4be9-95f3-f29e5e29f0c2.jpg)

**Comment by AndrewBastin** [comment]
I cannot reproduce this in my end. Make sure your folder structures are all good and you copied the contents of the dist folder correctly over.
