### ISSUE TITLE
Centos 7 Installation Issue

### ISSUE THREAD

**Issue by pizu** [hoppscotch/hoppscotch#1747]
[root@tst01nettools01 hoppscotch]# npm i 
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated apollo-tracing@0.15.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
npm WARN deprecated graphql-extensions@0.15.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
npm WARN deprecated apollo-cache-control@0.14.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated @types/browserslist@4.15.0: This is a stub types definition. browserslist provides its own type definitions, so you do not need this installed.
npm WARN deprecated @types/anymatch@3.0.0: This is a stub types definition. anymatch provides its own type definitions, so you do not need this installed.
[      ............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/@typescript-eslint%2feslint-plugin
<--- Last few GCs --->

  310189 ms: Mark-sweep 1078.3 (1440.1) -> 1084.9 (1438.1) MB, 1078.0 / 0.0 ms [allocation failure] [GC in old space requested].
  311205 ms: Mark-sweep 1084.9 (1438.1) -> 1084.2 (1438.1) MB, 1015.6 / 0.0 ms [allocation failure] [GC in old space requested].
  312316 ms: Mark-sweep 1084.2 (1438.1) -> 1103.6 (1399.1) MB, 1110.9 / 0.0 ms [last resort gc].
  313409 ms: Mark-sweep 1103.6 (1399.1) -> 1103.5 (1369.1) MB, 1092.9 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1838c1dcf781 <JS Object>
    1: fromString(aka fromString) [buffer.js:~186] [pc=0x350326266619] (this=0x1838c1d04381 <undefined>,string=0x26ab05bf17e1 <Very long string[40902274]>,encoding=0x1838c1ddd149 <String[4]: utf8>)
    2: from [buffer.js:~91] [pc=0x35031e23e7d6] (this=0x136021291211 <JS Function Buffer (SharedFunctionInfo 0x136021204ef9)>,value=0x26ab05bf17e1 <Very long string[40902274]>,encodingOrOffset=0x1838...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [npm]
 2: 0x710fec [npm]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [npm]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [npm]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [npm]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [npm]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [npm]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [npm]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [npm]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [npm]
11: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [npm]
12: 0x35032625bdb8
Aborted
[root@tst01nettools01 hoppscotch]#

**Comment by liyasthomas** [comment]
Can you provide a screenshot?

**Comment by pizu** [comment]
![image](https://user-images.githubusercontent.com/7047326/126359197-c4ee3450-2cd9-4cea-83e8-4351131228c5.png)

**Comment by liyasthomas** [comment]
Thank you, we'll look into it.

**Comment by pizu** [comment]
Thanks

**Comment by AndrewBastin** [comment]
I have seen this happen in some old Node versions, can you try running this command before running `npm i` ?
```bash
export NODE_OPTIONS=--max_old_space_size=4096
```
If this fixes your issue, then you might want to consider updating your installed Node.js version to something a bit more recent.
