### ISSUE TITLE
Cannot read property  'content-type' of undefined

### ISSUE THREAD

**Issue by woodliu** [hoppscotch/hoppscotch#1749]
**Describe the bug**
When i send a Post request through hoppscotch ,it return 500.

**To Reproduce**
Just send a Post request to my local server. 
I have checked the network inside the hoppscotch docker,  the connection is ok.
And the proxy of hoppscotch has beed turn off.

**Expected behavior**
Return the right response

**Screenshots**
This is the error
![image](https://user-images.githubusercontent.com/9976943/127104633-f3ed793e-2b71-4576-9b7f-673fd1e25c0c.png)
This is the request
![image](https://user-images.githubusercontent.com/9976943/127104752-9592efed-c9fc-45b4-93d5-dda553a7cc3a.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [92.0.4515.107]

**Comment by liyasthomas** [comment]
Can you see any errors in the browser's console log? Please share a screenshot of the console log.

**Comment by woodliu** [comment]
> Can you see any errors in the browser's console log? Please share a screenshot of the console log.

Hi, it's just a request ,nothing else
![image](https://user-images.githubusercontent.com/9976943/127106026-f18ddc19-e971-4ccb-8e11-75da4fd10b6e.png)

**Comment by liyasthomas** [comment]
Please provide the screenshot of the "console" tab. Not the network tab.

**Comment by woodliu** [comment]
> Please provide the screenshot of the "console" tab. Not the network tab.

Sorry, this is the screenshot
![image](https://user-images.githubusercontent.com/9976943/127109259-a37fe559-d44b-42fe-9070-64967c73a3ac.png)

**Comment by liyasthomas** [comment]
Turn on "**Proxy mode**" from settings to fix `CORS` issue. Let me know it if solved your issue.

**Comment by woodliu** [comment]
> Turn on "**Proxy mode**" from settings to fix `CORS` issue. Let me know it if solved your issue.

Hi, there has no CORS issue, but the `content-type` still undefined...
![image](https://user-images.githubusercontent.com/9976943/127111854-8b038716-2f3c-43e6-b18a-23698381fa57.png)

**Comment by HEI-cloud** [comment]
have same error, just come from postwoman.  few days ago, it has privacy problem, so turn to this hoppscotch.

**Comment by AndrewBastin** [comment]
@woodliu  @HEI-cloud  This error should only appear when the app is running on dev mode (`npm run dev`). But anyways, I have patched it up in commit d5cb9f1. If you still experience this issue, feel free to reopen the issue. The current solution is temporary as a revamped is taking place with the core architecture of the app.
