### ISSUE TITLE
Feature as Duplicate a Request, Multiple Tabs

### ISSUE THREAD

**Issue by mhsiddiqui** [hoppscotch/hoppscotch#1751]
I have been using Postman for many years and following are the features which I would love in hoppscotch.

1. Duplicate a request as many times there are many settings which we have configured with one endpoint and we do not want to configure again with new endpoint. So we usually duplicate previous one and change url, name and data. I could not found duplicate request option here. 
2. Multiple tabs as most of the time we are using multiple requests and multiple tabs like in postman will b e good.
3. Hover on environment variable to get its value
4. Set environment variable through tests as I often use it to set auth token.

**Comment by liyasthomas** [comment]
Hi @mhsiddiqui, thank you for your feature requests. All of them are in our roadmap. Stay tuned for the upcoming updates.

**Comment by bdsmlovingmarriedcouple** [comment]
how do we record and send our footage?

**Comment by Kaushal-Dhungel** [comment]
Hello. is this issue beginner-friendly? If yes then I would like to work on it.

**Comment by liyasthomas** [comment]
Hi @Kaushal-Dhungel, this is quite easily possible yo implement. So let us know uf you got stuck. You're free to take up this issue

**Comment by sims-keshri** [comment]
Can I sign up for this?

**Comment by liyasthomas** [comment]
Hi @sims-keshri , thanks for showing interest to contribute to Hoppscotch. You can surely take a look into this. @Kaushal-Dhungel, you can share any progress regarding this feature.

**Comment by sims-keshri** [comment]
> Hi @sims-keshri , thanks for showing interest to contribute to Hoppscotch. You can surely take a look into this. @Kaushal-Dhungel, you can share any progress regarding this feature.

Can you help me get started on this issue @liyasthomas ? Can you share some ACs and details about how I can get started?

**Comment by 0xc0Der** [comment]
is it ok if i work on this. the duplication part?

**Comment by liyasthomas** [comment]
Hi @0xc0Der, we're glad if you can pick this up. Do let us know if you need any help.

**Comment by liyasthomas** [comment]
"Duplicating requests" have been implemented in #1941 and the "multiple tabs" feature is tracked in #690, hence closing this issue.
