### ISSUE TITLE
Contributors cannot translate text in some places

### ISSUE THREAD

**Issue by brageryz** [hoppscotch/hoppscotch#1761]
Hello,
I have found places where **contributors cannot translate text**. 

## Problem description
When a user changes current language to another, many places are translated, but we can find places where **text is not possible to translate**. It does not look good in my opinion. Users want to have translated everything in the specific language.

---

## Preferred solution
I prefer to add keys with translations, then contributors will be able to update them.

---

## Examples
I leave below **a few examples** to understand better my problem.

https://github.com/hoppscotch/hoppscotch/blob/b0b758a9c640a4cf09d8e08083320e5ae9a36b7f/components/teams/Edit.vue#L79
https://github.com/hoppscotch/hoppscotch/blob/b0b758a9c640a4cf09d8e08083320e5ae9a36b7f/components/collections/ImportExport.vue#L144
https://github.com/hoppscotch/hoppscotch/blob/b0b758a9c640a4cf09d8e08083320e5ae9a36b7f/components/collections/ChooseType.vue#L36

**Comment by liyasthomas** [comment]
Thanks for pointing out these untranslated strings in the app. We'll cover these strings for translations in the next release.

**Comment by juzhiyuan** [comment]
@liyasthomas Could I help to translate them?

**Comment by liyasthomas** [comment]
@juzhiyuan please follow our [translation guide](https://github.com/hoppscotch/hoppscotch/blob/main/TRANSLATIONS.md) for contributing.

**Comment by juzhiyuan** [comment]
got it

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/128619121-edf17808-3d83-4d1c-9ed7-da92f518fa6f.png)

After using `yarn && yarn dev`, it shows this error from `analytics` 🤔

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/128619145-d57b88e8-ef91-4b86-ba18-def1526c1bcc.png)

Just adding this patch to check if `analytics` exist

**Comment by liyasthomas** [comment]
In the [developing instructions](https://github.com/hoppscotch/hoppscotch#developing) section, there's a step 0: Update `.env.example` file found in repository's root directory with your own keys and rename it to `.env`.

Please rename `.env.example` file found in root director to `.env` and restart the local server to fix this issue.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/128619625-ec0fccec-1326-4944-80cf-c5c1c04babe7.png)

After setting up the Firebase App & GitHub OAuth App, I have no idea how to get the correct configuration data for local development, would better have a Guide on this.

**Comment by liyasthomas** [comment]
For local development you just need to rename .env.example file found in root director to .env and restart the local server to fix this issue.

**Comment by liyasthomas** [comment]
With the release of v2 - we've introduced a community-driven translations system with the help of [Git Localize](https://gitlocalize.com).

Read our [TRANSLATIONS](https://github.com/hoppscotch/hoppscotch/blob/main/TRANSLATIONS.md) guide for more info on how to make contribution to translations.
