### ISSUE TITLE
Auto translate as per browser locale

### ISSUE THREAD

**Issue by varadp2000** [hoppscotch/hoppscotch#1782]
I was wondering if the page could open in the website the web browser of the user uses. 
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
If I open the site with Hindi as my web browser's language, the default language on the hoppscotch.io should be Hindi

**Describe alternatives you've considered**
Getting the language from the navigator object of the browser and setting it as site language will work

**Additional context**

**Comment by varadp2000** [comment]
If contributors don't mind, I would love to take this issue

**Comment by liyasthomas** [comment]
Hi @varadp2000, thanks for the feature request. FYI: we have this feature already implemented.

We use [`nuxtjs/i18n`](https://i18n.nuxtjs.org) for localization and in `nuxt.config.js`, there's a flag that detects and browser language by default: https://github.com/hoppscotch/hoppscotch/blob/main/nuxt.config.js#L345.

So, this must've been a minor error - would appreciate it if you can take a look into it.
Feel free to ask if you've any doubts.

**Comment by varadp2000** [comment]
Sure, I'll try it

**Comment by liyasthomas** [comment]
With the release of v2 - you can change your default locale from [Settings](https://hoppscotch.io/settings) and Hoppscotch will remember the chosen locale in local storage and use it as default.
