### ISSUE TITLE
[feature]: Ability to disable Google Analytics

### ISSUE THREAD

**Issue by GAS85** [hoppscotch/hoppscotch#1786]
**Is your feature request related to a problem? Please describe.**
Currently if I would like to deploy Hoppscotch to my customers, google Analytics could not be disable completely, only reconfigured. This is not always in sync with Customers TOS.

**Describe the solution you'd like**
A configuration only way to disable google analytics completely.

**Describe alternatives you've considered**
Cut out piece of code with google analytics is not the way, also reconfigure it to the own google analytics is not suitable for some customers.

**Comment by liyasthomas** [comment]
Self-hostable Hoppscotch instances are in our roadmap. At the moment you cannot disable Google Analytics. Thanks for your patience - will let you know once self-host capabilities are live.

**Comment by ntimo** [comment]
@liyasthomas do you have any news for this? If its possible to disable analytics when self hosting.

**Comment by fractalf** [comment]
@liyasthomas Just came across this project, great stuff, but please remove Google from self-hosting, it's a show stopper. Thank you

**Comment by liyasthomas** [comment]
Thank you for bringing this to our attention. We completely understand your concern and are happy to inform you that we have already released Hoppscotch self-hosted instance support on Apr 11, 2023 which has stripped out both Google Analytics and Tag Manager. We hope this change will make our project even more accessible to all users.
