### ISSUE TITLE
Bulk edit for HTTP Headers

### ISSUE THREAD

**Issue by joe223** [hoppscotch/hoppscotch#1791]
**Is your feature request related to a problem? Please describe.**
We edit several headers usually when testing APIs, it's would be more convenient to support bulk edit if we copy the whole http request header from browser. 

**Describe the solution you'd like**
Add a new mode for headers modification, we can call it 'bulk edit'. In this mode, we can paste string to input field, it'll be convert to HTTP header by line break 

As an example:

```
Accept: */*
Accept-Encoding: gzip, deflate
Content-Type: application/json;charset=UTF-8
```

will be separate by new line character into three headers

```
Accept: */*
```
```
Accept-Encoding: gzip, deflate
```
```
Content-Type: application/json;charset=UTF-8
```

**Comment by liyasthomas** [comment]
Bulk editing is a planned feature. Watch this space for updates. Thank you for the feature request.

**Comment by liyasthomas** [comment]
Hi @joe223,

I've deployed an MVP of bulk edit feature for Headers and Parameters sections on [beta.hoppscotch.io](https://beta.hoppscotch.io).

**Step 1: Switch to "Bulk edit" mode**

![screely-1630314552201](https://user-images.githubusercontent.com/10395817/131315763-a2ade9ad-c687-4274-9486-f7b69acab9c3.png)

**Step 2: Paste bulk content - entries are separated by newlines, key and value are separated by `:`**

![screely-1630314799404](https://user-images.githubusercontent.com/10395817/131316266-7a2e4473-180e-43eb-a461-155648995397.png)

**Step 3: Send the request or switch to "Key-value edit" mode.**

![screely-1630314890261](https://user-images.githubusercontent.com/10395817/131316466-71745f6b-47f9-4229-80e4-08aa5dd0966a.png)

Track the progress in https://github.com/hoppscotch/hoppscotch/tree/feat/bulk-edit branch. Let us know if this resolves your features request. Feedbacks and contributions are welcome.

**Comment by joe223** [comment]
Amazing work! Really appreciate! @liyasthomas
