### ISSUE TITLE
languege changing error

### ISSUE THREAD

**Issue by 1tang2bang92** [hoppscotch/hoppscotch#1793]
**Describe the bug**
i changed languege korean to english.
but, not change nav bar's lang

**To Reproduce**
1. change languege to korean
2. send few request
3. change languege to english

**Screenshots**
![image](https://user-images.githubusercontent.com/20069720/131430398-a877bce1-621b-4c62-ba49-b65ae2949e12.png)

**Desktop (please complete the following information):**
 - OS: win10 19043.1165
 - Browser Chrome
 - Version 92.0.4515.159 (offical build) (64bit) (cohort: Stable)
 - use pwa

**Additional context**
sorry my english level
and i want contribute korean translating
what can i do?

**Comment by liyasthomas** [comment]
Please refresh the browser to take effect the changes to layouts.
