### ISSUE TITLE
Translation for REST

### ISSUE THREAD

**Issue by kolbma** [hoppscotch/hoppscotch#1795]
Why do you translate REST with stuff like "make a rest"/"Sich ausruhen" (de)?
Should this be a joke? Do you really want to translate this technical term?

**Comment by liyasthomas** [comment]
Sorry about that. Technical terms doesn't have to be translated. `REST` should've been kept as it is.

All translations except English are community contributed - and probably will have some inconsistencies. Please feel free to open a fix pull request. Thank you.
