### ISSUE TITLE
Authorization parameters are doubled when showing/generating code

### ISSUE THREAD

**Issue by siroccal** [hoppscotch/hoppscotch#1798]
**Describe the bug**
Two authorization parameters appear if you click on `Show code` (next to `Send`). They are doubled for any language and any type of authorization.

**To Reproduce**
1. Go to `Authorization` and select any option besides `None`
2. Click on `Show code` (next to `Send`)

**Expected behavior**
One authorization parameter in the code.

**Screenshots**
![Screenshot 2021-09-01 at 18-50-25 Hoppscotch - Open source API development ecosystem-or8](https://user-images.githubusercontent.com/41478263/131712069-9bb6dbb7-f28c-4502-bb03-59f1359bd2c2.png)

**Environment and versions**
 - Linux 5.13.12 (Fedora 34)
 - Firefox 92
 - Hoppscotch v2.0.0-28-gf357c4f1 (built with `npm run generate` and run with `npm run start`)

**Comment by liyasthomas** [comment]
We're looking into get this fixed ASAP.
