### ISSUE TITLE
"REST" should not be translated (Spanish translation)

### ISSUE THREAD

**Issue by JorgeFerrer** [hoppscotch/hoppscotch#1799]
**Describe the bug**
With the new UI, I've noticed some terms that are not properly translated. The most visible of all is "REST" which is translated as "Descanso" which "appropriately" means "rest" XD

**To Reproduce**
1. Go to the app with a Browser set up to use Spanish as the language
2. See how the first icon in the left menu says "Descanso"

**Expected behavior**
"REST" is an acronym for "REpresentational State Transfer" and should not be translated

Other translations could be improved

**Comment by liyasthomas** [comment]
Thanks for your quick PR - really appreciate it.

Sorry about the existing translations. `REST` should've been kept as it is. All translations except English are community contributed - and probably will have some inconsistencies. Thank you for understanding.

**Comment by JorgeFerrer** [comment]
Happy to help :)
Thanks for the quick review!
