### ISSUE TITLE
[feature]: Private self hosted Hoppscotch instances

### ISSUE THREAD

**Issue by dansjackson** [hoppscotch/hoppscotch#1817]
**Is your feature request related to a problem? Please describe.**
I can imagine a use case for organisations who want to self host Hoppscotch on their own infrastructure but want to limit their instance to their employees. 

Reasons for this might be that the Hoppscotch instance might contain a default token for a private proxy server that would be required to access restricted API endpoints. 

**Describe the solution you'd like**
Ideally, Hoppscotch could include support for authentication mechanisms. Accessing Hoppscotch would not be possible on private self hosted instances unless the authentication was passed.

These could include:

- OpenID/Oauth2
- SAML
- LDAP

Using existing external authentication systems will allow administrators to easily create permissions in their existing system that they can use to grant members of their organisation access to their Hoppscotch system. 

I can imagine this being used amongst development companies who currently may have to rollout something like Postman to all of their employees and also have to be responsible for updating all of these different installed systems. Having a single instance of Hoppscotch solves this.

**Describe alternatives you've considered**
Personally, I am planning to use Vouch Proxy for this purpose since Hoppscotch does not natively have this ability. Other methods include HTTP Basic Auth however some self hosted applications such as Nextcloud and Bookstack have the Oauth2 ability built right into them.

**Comment by bblumenwiese** [comment]
Hi, I would love to see this become a reality. Because I know how easy it is to screw up keys and other secrets in Postman when working in a corporate environment and this seems to be the perfect solution I was looking for :) I have a strong interest in the intersection of security and usability, as in: Make it easy for the user to do the right thing in the right moment, and hard to do the wrong thing. Therefore I would really like to collaborate on this issue! 

I would need some more actionable tasks to start working on this feature, though, and would be happy to brainstorm together with some more experienced folks on what needs to be done exactly :) 

E.g.:
1. How would we handle the two variants with auth vs. no auth? (feature toggle?)
2. What should the UI look like for the auth page?

**Comment by liyasthomas** [comment]
A selfhost ready Hoppscotch instance is in our future roadmap. This will surely have configurable auth, backend, even toggles of feature set. We're planning to introduce a `hopp.config` file in root for any in-app settings and providers. This is at ALPHA stage at the moment, but would love to hear more thoughts on this.

**Comment by stuzer05** [comment]
Swapping firebase alone would be a major step into self hosted direction

**Comment by exussum12** [comment]
We self host hoppscotch currently, our build process is as follows
```
        - git clone --depth 1 --branch v1.12.0 https://github.com/hoppscotch/hoppscotch.git
        - cd hoppscotch
        - sed -i 's/"~\/plugins\/vuex-persist", //' nuxt.config.js
        - cp ../../store/hoppscotch-collection.json store/hoppscotch-collection.json
        - cp ../../store/hoppscotch-environment.json store/hoppscotch-environment.json
        - cp ../../store/postwoman.js store/postwoman.js
        - npm install
        - npm run generate
```
        
 then copy the generated files to the hosting platform. You lose features like being able to edit and auto save, as you need a PR for them, but all of the collections and environments work.

Basically stop the persistence, and the files copied in are mostly the collections and environments separated for ease of PR and viewing.

We also need a custom browser build as the URL of the instance needs whitelisting, it seems to work well, the change to v2 has been a big enough change to stop this working though, but teams support looks great in the current version!

**Comment by freddiN** [comment]
I am also very much interested in this feature, I would like to set up a self hosted hoppscotch that uses our own gitlab instance for authentication.

I will keep an eye on any news regarding this topic.

**Comment by deepakprabhakara** [comment]
@liyasthomas I'd love to integrate SAML for you if you like, please do let me know. We have built an OSS SAML service at BoxyHQ - https://github.com/boxyhq/jackson

**Comment by tomaszkane** [comment]
I also want to have self hosted hoppscotch without firebase and any third party dependencies.

**Comment by uzaxirr** [comment]
Hey @liyasthomas 
Any progress on this one?

**Comment by liyasthomas** [comment]
We're deferring self-hostable Hoppscotch instances to Q2-Q3 2022.

**Comment by WilliamPeralta** [comment]
> We self host hoppscotch currently, our build process is as follows
> 
> ```
>         - git clone --depth 1 --branch v1.12.0 https://github.com/hoppscotch/hoppscotch.git
>         - cd hoppscotch
>         - sed -i 's/"~\/plugins\/vuex-persist", //' nuxt.config.js
>         - cp ../../store/hoppscotch-collection.json store/hoppscotch-collection.json
>         - cp ../../store/hoppscotch-environment.json store/hoppscotch-environment.json
>         - cp ../../store/postwoman.js store/postwoman.js
>         - npm install
>         - npm run generate
> ```
> 
> then copy the generated files to the hosting platform. You lose features like being able to edit and auto save, as you need a PR for them, but all of the collections and environments work.
> 
> Basically stop the persistence, and the files copied in are mostly the collections and environments separated for ease of PR and viewing.
> 
> We also need a custom browser build as the URL of the instance needs whitelisting, it seems to work well, the change to v2 has been a big enough change to stop this working though, but teams support looks great in the current version!


I leave you a little idea of ​​how to start with an openapi file,

I added this function on the "import / export" file where I load a docs.json file and using the "OpenApi" importer I load it and set it on the store.

it's a very crude solution, but just mount the edited file and the doc.json on the docker-compose and it works.

as soon as I have more time I look for a better solution.
Good work and thanks for this great project!

```js
// ImportExport.vue
const fetchFile = () => {
  fetch("/docs.json")
    .then((response) => response.json())
    .then(async (data) => {
      const result = await RESTCollectionImporters[1]?.importer([
        JSON.stringify(data),
      ])()
      console.log("result", result)
      if (E.isLeft(result)) {
        failedImport()
        console.error("error", result.left)
      } else if (E.isRight(result)) {
        if (props.collectionsType.type === "team-collections") {
          importToTeams(result.right)
          fileImported()
        } else {
          setRESTCollections(result.right)
          fileImported()
        }
      }
    })
}

setTimeout(() => {
  fetchFile()
}, 1000)

```

**Comment by vichle** [comment]
Very interested in this feature, can you give some kind of indication of when this will be released?

**Comment by jerbob92** [comment]
I'd like to deploy the current version with some minor changes for custom auth through Firebase. 
It looks like the only part that's missing right now is the source of `api.hoppscotch.io`. Would it be possible to open-source that?

**Comment by jerbob92** [comment]
Since Hoppscotch is not going to release the backend API, and these features will probably be behind a license model in the future, I have decided to make my own implementation of the Hoppscotch Backend API.

It's available here: https://github.com/jerbob92/hoppscotch-backend
All features have been implemented that are currently in use by the frontend.

Some notes:

- The frontend requires some changes to talk to a self-hosted API, see required changes [here](https://github.com/jerbob92/hoppscotch/commit/2c98d6f8471691156c99a4a3bdd37ab95286fb21) (these changes can also be merged into Hoppscotch, the defaults work with the production environment)
- The backend that I have created doesn't use Firebase for storage, but a MySQL server (it does use Firebase for user authentication)
- You will need a mail server to get the Team invite system to work
- The code isn't very pretty, and doesn't contain any unit tests
- I'm not too happy with the GraphQL Subscription/WebSockets code, I'm not sure about the performance and whether it's very stable

**Comment by whichdew** [comment]
keep watching

**Comment by abhaychaware** [comment]
Watching.....

**Comment by cloudomatic** [comment]
I would echo the need for a feature toggle for the teams capability (i..e to turn it off) on a self-hosted instance.  I believe many self-hosters would like to use a Git back-end for storage in place of a database, and right now turning off the teams capability means removing various code blocks with a scalpel, although creating a mocker of api.hoppscotch.io with no actual implementation seems like an option.

**Comment by huozhenzhen** [comment]
Watching.....

**Comment by semiherdogan** [comment]
Hi,
any update on this?

**Comment by suyar** [comment]
Waiting...

**Comment by vichle** [comment]
To anyone just commenting with "watching..." or similar: just hit the 👍 button unless you have anything constructive to add to the discussion. You are triggering useless notifications to everyone who is watching this thread, including myself. PLEASE!

**Comment by huozhenzhen** [comment]
有一个不钳充钱就能玩的游戏，http://www.0vslu5.cn ，听说信用很好的，我们去玩两把吧，反正没有风险。<狄/p>

**Comment by suyar** [comment]
> To anyone just commenting with "watching..." or similar: just hit the 👍 button unless you have anything constructive to add to the discussion. You are triggering useless notifications to everyone who is watching this thread, including myself. PLEASE!

I'm sorry I didn't realise this, I'll take care of it next time.

**Comment by binaryfire** [comment]
Until this feature is released, you might want to check out Yaade: https://github.com/EsperoTech/yaade. It’s fully open source, has user groups and Oauth2 and uses an embedded H2 database. Just started playing with it today - looks promising so far.

**Comment by binaryfire** [comment]
Hi guys. Just curious why you deleted my comment?

**Comment by tomaszkane** [comment]
> Hi guys. Just curious why you deleted my comment?

Good question.
BTW, Yaade looks not bad. I'll probably test it.

**Comment by AndrewBastin** [comment]
Fully Self Hostable Hoppscotch Instances are now available as a Beta. Read more at: https://docs.hoppscotch.io/documentation/self-host/getting-started
