### ISSUE TITLE
npm run generate error

### ISSUE THREAD

**Issue by 1-bytes** [hoppscotch/hoppscotch#1823]
**Describe the bug**
I'm trying to compile hoppscotch, but it reports an error, see the Screenshots below for details.

**To Reproduce**
1. git clone https://github.com/hoppscotch/hoppscotch.git
2. cd hoppscotch
3. npm install
4. npm run generate

**Expected behavior**
npm build done. 0 error.

**Screenshots**
![image](https://user-images.githubusercontent.com/17564454/132997114-e216ebb9-1622-4da1-a1ae-314349112604.png)

**Desktop (please complete the following information):**
- LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
- Distributor ID: Ubuntu
- Description:    Ubuntu 20.04.3 LTS
- Release:        20.04
- Codename:       focal

**Additional context**

**Comment by 1-bytes** [comment]
root@Cloud:/home/wwwroot/hoppscotch# nodejs -v
v10.19.0
root@Cloud:/home/wwwroot/hoppscotch# npm -v
6.14.4

**Comment by AndrewBastin** [comment]
Hi there, Hoppscotch needs Node version >= 14 to build.
Also make sure you run `npm install` before running the generate command.

Please close this issue, if the above steps fix your issue.

**Comment by 1-bytes** [comment]
I upgraded NodeJS and npm, the problem is solved
thanks :)
