### ISSUE TITLE
Better error messages for Graphql

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#1828]
**Is your feature request related to a problem? Please describe.**
Currently the application only says to press F12 to see the error, but the error is not readable.

# hoppscotch
![image](https://user-images.githubusercontent.com/56084970/133028055-f17bf29b-b641-4e60-a758-7e4fc49f849d.png)

# Graphql Playground
![image](https://user-images.githubusercontent.com/56084970/133028177-e6093d7e-18ef-45eb-b43f-597c36b37def.png)

With the Graphql Playground error message you can easily know what is wrong, while with the hoppscotch error message you don't know what is wrong because the error is not readable.

**Describe the solution you'd like**
Display a more readable error message to understand what is going wrong.

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by H-thompson** [comment]
I would like to take this feature on if it's not already being worked on. As part of the process of pulling through the error data I will ensure that it fits with the current localisation structure.

**Comment by liyasthomas** [comment]
Hi @H-thompson thank for showing the interest to work on this.

**Comment by StephaneBischoff** [comment]
Hi @H-thompson @liyasthomas proposed a very simple fix. Let me know if you want some more improvements.

**Comment by kaname-png** [comment]
No, that's fine, thanks!
