### ISSUE TITLE
Error saving / loading request in graphql (Beta)

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#1829]
**Describe the bug**
When I want to make a request for graphql the headers do not work, so I get the error "Not authorized" because the authorization header I have set was not sent.

Also I can't save any request, it is saved incorrectly, it always gives error. As well as trying to load the saved request again.

**To Reproduce**
1. Go to 'Graphql'
2. Create petition
2. Click on 'Save'

**Expected behavior**
A correct and functional request, since Graphql Playground works fine.

**Screenshots**
https://user-images.githubusercontent.com/56084970/133132933-1786561d-d44b-492d-9895-0bc27f4eba0a.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 93.0.961.47

**Additional context**
Also the error is that the headers are not sent in the request to graphql.

**Comment by liyasthomas** [comment]
This was a known bug and has been patched in #1822 and #1820 respectively. So it's most probably a offline cache issue. Please force reload (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>) the Hoppscotch app to take effect the changes.

Let me know if this doesn't resolve this bug at your end.

**Comment by kaname-png** [comment]
@liyasthomas It did not work, the problem persists.

**Comment by liyasthomas** [comment]
Please reproduce the issue and see if there's any errors in browser's console log / send a screenshot of console log.

**Comment by kaname-png** [comment]
But I already did it in the attached video.

**Comment by liyasthomas** [comment]
I'll try to reproduce this same here at my end and let you know the updates. Thanks for reporting the issue.

**Comment by liyasthomas** [comment]
[beta.hoppscotch.io](http://beta.hoppscotch.io) is not the production build and may be behind the `main` branch. Please navigate to production deployment on [https://hoppscotch.io](https://hoppscotch.io). Thank you.
