### ISSUE TITLE
pnpm run generate error 

### ISSUE THREAD

**Issue by gclm** [hoppscotch/hoppscotch#1830]
**Describe the bug**
I'm trying to compile hoppscotch, but it reports an error, see the Screenshots below for details.

**To Reproduce**
1.  git clone https://github.com/hoppscotch/hoppscotch.git
2. cd hoppscotch
3. pnpm install
4. npm run generate

**Expected behavior**
```
ℹ Generating sitemaps
│  FATAL  [sitemap-module] The hostname option is mandatory in your config on spa or generate build mode 
│ {
│   "path": "/sitemap.xml",
│   "exclude": [],
│   "routes": [],
│   "cacheTime": 900000,
│   "etag": {
│     "weak": false
│   },
│   "gzip": false,
│   "trailingSlash": false,
│   "defaults": {},
│   "pathGzip": "/sitemap.xml"
│ }
│ ╭──────────────────────────────────────────────────────────────────────────────╮│                                                                   
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 18.2s
```
**Screenshots**
![image](https://user-images.githubusercontent.com/27618687/133871129-f370dd96-4d20-4e2c-8edb-30b584268d0a.png)
![image](https://user-images.githubusercontent.com/27618687/133871088-365b55cd-e67d-4946-8c54-9769f9609a4e.png)

**Desktop (please complete the following information):**
 - OS:  MacOS 11.6
 - Browser chrome
 - Version  node: v14.17.6/npm: 6.14.15/pnpm:6.15.1

**Comment by liyasthomas** [comment]
This seems like an issue of not having a `.env` file in `packages/hoppscotch-app` directory.

Rename the default `.env.example` file found in `packages/hoppscotch-app` to `.env` and run the generate command again.

For self-hosting, you can provide your own environment keys in `.env`.

Let me know if this doesn't fix your issue.
