### ISSUE TITLE
The fields of a request with body type multipart/form-data do not follow the order configured in the request

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#1833]
**Describe the bug**
I have noticed that when sending a request, the order of the fields set in the request body configuration is not followed, and this can cause failures in applications where a specific order must be followed in the body fields.

I noticed that because with hoppscotch when I try to send this request to my graphql server with graphql-upload, I get this error, and that error is because the file fields are not followed by the map field, so the error appears.

And I don't think it is graphql-upload error because I make exactly the same request with postman and it works correctly.

**To Reproduce**
1. Go to 'rest section'
2. Create a request with body of type multipart/form-data
3. Click on 'Send'

**Expected behavior**
That the body fields have the same order as configured in the request when sending the request to the server.

**Screenshots**

https://user-images.githubusercontent.com/56084970/133948340-8b6f9fb4-d80b-4d5c-b049-8d582d51126c.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: edge
 - Version 93.0.961.52

**Additional context**
I don't know if the same is true for other types of request body.

**Comment by liyasthomas** [comment]
Thanks for reporting this issue. We're working on a fix. Will update here once it lands on production.

**Comment by mandaputtra** [comment]
Hi, @kaname-png could you recall the wrong order? I test the step and I got same order as the request. Or maybe I was wrong on testing it?

![Screenshot from 2021-10-01 09-09-48](https://user-images.githubusercontent.com/23342943/135554918-02ac745f-b4af-4063-ac36-941319647fb5.png)

**Comment by kaname-png** [comment]
As you can see I execute the same request in both applications and I get that error in hoppscotch and in postman I don't get the error I mention.

For what it's worth, I'm using nestjs with graphql and the graphql-upload plugin.

**Comment by mandaputtra** [comment]
If you could make some simple repo nestjs + graphql + graphql-upload demonstrating this error. I could work on this issue. I'm just not fond with graphql.

**Comment by mandaputtra** [comment]
ifyou can reproduce go ahead i never work with graphql

**Comment by sonaljain067** [comment]
I would like to work on this issue.

**Comment by kyteinsky** [comment]
It is an issue similar to [this one](https://stackoverflow.com/questions/49771811/postman-ordering-of-fields-in-form-data-request/53756457), that was posted for postman originally. So essentially `0` is alphabetically ordered and placed before `map` in the request, which causes the issue here.

It can be a simple fix to work on, just ensuring all file fields come after the `map parameter`.

Do I have your green flag @liyasthomas to work on this?

**Comment by liyasthomas** [comment]
Hi @kyteinsky, you can give this a try. Do let us know if you've any doubts on the source code.

**Comment by kyteinsky** [comment]
Sure thing. Thanks!

**Comment by AndrewBastin** [comment]
@kaname-png does the implementation in the PR #2067 fix the issues for you ?

You can test the implementation using this Deploy Preview URL: https://deploy-preview-2067--hoppscotch.netlify.app/

**Comment by kaname-png** [comment]
@AndrewBastin I can confirm that the problem has indeed been solved.

**Comment by AndrewBastin** [comment]
No worries! Thank you for confirming the fix and your continued contribution to the project! ♥️
