### ISSUE TITLE
can't use an environment variable in request body

### ISSUE THREAD

**Issue by zecrazytux** [hoppscotch/hoppscotch#1834]
**Describe the bug**
environment <<variable>> should be useable within a raw request body, but it isn't

**To Reproduce**
create an env variable, eg "user"
use it (<<user>>) into url: it works
use it (<<user>>) into the raw request body textarea: it is not replaced with var content

**Expected behavior**
<<user>> should be replaced with env var content

**Screenshots**
![image](https://user-images.githubusercontent.com/929169/134485341-41ac29aa-e420-40e9-8237-f8e83339143a.png)

**Desktop (please complete the following information):**
chrome

**Comment by liyasthomas** [comment]
@zecrazytux thank you reporting this behaviour. We'll be taking a look into this as soon as possible.

**Comment by dhivyasreedhar** [comment]
Hi, can I work on this issue?

**Comment by liyasthomas** [comment]
Hi @dhivyasreedhar, thanks for showing interest in working on this issue. You're free to take up this. I'm assigning it to you, [contact us](https://github.com/hoppscotch/hoppscotch#support) if you need any help.

**Comment by rishabhkalra96** [comment]
Hi @liyasthomas, Is this issue still been looked into? 
I'd like to take this up if @dhivyasreedhar is no longer working on it.

**Comment by liyasthomas** [comment]
Hi @rishabhkalra96, I guess you can pick up this, thanks for showing interest on contributing to Hoppscotch.

**Comment by 0xc0Der** [comment]
shouldn't this be closed?

**Comment by widdlepaws** [comment]
hello :) when can we expect it to be delivered ? really looking forward to it ! 
Last release got packaged too early :') https://github.com/hoppscotch/hoppscotch/releases/tag/v2.1.0

**Comment by liyasthomas** [comment]
This feature is already live on the production deployment: Hoppscotch.io. You can fetch the `latest` tag if you're on Docker or fetch the latest `main` branch from Git to enjoy the latest changes.

**Comment by humbertoarizah** [comment]
Hi, I know this issue is already closed, but I tried to access to env variables within the body and it has been impossible. I have this notation in the body, for example:
{"account" : {
    "username": "<<new-username>>",
    "email": "<<new-email>>"
}}
And my response is not taking the env variables but the string (<<new-username>>).
I don´t know if I´m doing anything wrong.
I would appreciated any help.

**Comment by n-alonso** [comment]
It looks like highlighting of variables in the body takes the font lettering from the json formatting as opposed to changing it to white like everywhere else, making it difficult to read.
Variables in any other place:
![image](https://user-images.githubusercontent.com/63936366/161014200-98087a34-0954-4b86-884d-3afdb020af40.png)
Variables in the json body:
![image](https://user-images.githubusercontent.com/63936366/161014264-24bd944d-a7f8-4fd3-aafc-08713798b9be.png)
I guess the style needs some tweaking.
Adding @liyasthomas for visibility.

**Comment by AndrewBastin** [comment]
@humbertoarizah you have gotten the syntax wrong. Environment Substituions are represented by using `<<ENV>>` where `ENV` is the desired environment variable.

**Comment by tripol** [comment]
> @humbertoarizah you have gotten the syntax wrong. Environment Substituions are represented by using `<<ENV>>` where `ENV` is the desired environment variable.

Hi I tried following the `<< ENV >>` syntax and even though the color code confirms it is correct, I don't get the desired result.

![image](https://user-images.githubusercontent.com/27914557/162378960-48a7a06b-2465-4a10-aa4d-7df23d92617e.png)

When I type out the full URL instead (that is without the `<< ENV >>` syntax, I get the correct result.

Any idea why?

**Comment by GuilhermeViterboGalvao** [comment]
Same problem as @tripol !
