### ISSUE TITLE
Body is not stored at query vars when using "Copy link" feature

### ISSUE THREAD

**Issue by manuman94** [hoppscotch/hoppscotch#1842]
**Describe the bug**
I would like to use the Hoppscotch query string API to build Hoppscotch links in my application so we can debug REST calls from our HTTP test reports. 

The idea behind is to make a "Play" button in our reports that link to a pre-filled Hoppscotch API tester. We already can do this but we can only fill "parameters" (query string), "headers", "method", and "endpoint". There is no such "body" parameter to pre-fill the body of the request. 

**To Reproduce**
Open a new Hoppscotch session and fill endpoint, method, headers, parameters and body. You will see that the link at the address bar will include all of those information but the body part.

**Expected behavior**
Include "body" parameter with the url-encoded body value. 

**Additional context**
I don't know if this is a bug report or a feature request since I don't know if this is made on purpose. But it seems weird for us that such as an important part as the body is not present at the Hoppscotch query vars API.

Thank you, greetings.

**Comment by liyasthomas** [comment]
Hi @manuman94, thanks for reporting this issue. We'll be looking into fixing this as soon as possible.

**Comment by mandaputtra** [comment]
I can take this issue if no one already work on this.

**Comment by liyasthomas** [comment]
Hi @mandaputtra, you're free to take this issue. I'm assigning it to you, do let us know if you need any help.

**Comment by mandaputtra** [comment]
Can you point me where you parse and set the query param on url bar?, I've lost track of it in [here](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/components/http/Parameters.vue) I can't find the code who responsible for updating the url bar.

**Comment by liyasthomas** [comment]
Hi @mandaputtra, check out the below file on setting the request object to query parameters.
https://github.com/hoppscotch/hoppscotch/blob/0f39d54c3c669089e6639dd91904fb62b911945e/packages/hoppscotch-app/helpers/types/HoppRESTRequest.ts#L83

**Comment by mandaputtra** [comment]
Sorry to bother you again @liyasthomas  :smile: I'm still confuse how do you change the query params on url bar here. 

![Screenshot from 2021-10-01 16-21-34](https://user-images.githubusercontent.com/23342943/135597008-8fb59a92-e6bb-4cc3-803e-aad514fb89ab.png)

I see it binds on `params$` but I dont see why It change the query parameters on the bar.

**Comment by liyasthomas** [comment]
Hi @mandaputtra, the code block you're looking for is this:

https://github.com/hoppscotch/hoppscotch/blob/8f0538c886e5fe00e4db2cf24c842a4d8d9f744c/packages/hoppscotch-app/pages/index.vue#L165-L171

**Comment by manuman94** [comment]
Thank you guys! This is awesome. Working pretty well and so fast!

Greetings.
