### ISSUE TITLE
Enable copy/duplicate menu option for environments

### ISSUE THREAD

**Issue by StephaneBischoff** [hoppscotch/hoppscotch#1847]
**Is your feature request related to a problem? Please describe.**
Its a bit of a pain to manage environments usually. You sometime start off writing a few variables for an environment and then need to do the same for the PROD, QA and other environments. 

Why require users to rewrite the same variable name all over again?

**Describe the solution you'd like**
I would like to see an option that copies/duplicate your environment.

**Describe alternatives you've considered**
None for the moment

**Additional context**
Here is what I am thinking:

- Add a duplicate option in the context menu
- When click, creates a new copy of the environment with a different name '{Old name} Copy 1'
    - If copied again then name '{Old name} Copy 2'

![copy-paste](https://user-images.githubusercontent.com/9750058/135728960-ba29b9d9-6ba4-41bd-b42e-b65dc9ffcb97.png)

**Comment by StephaneBischoff** [comment]
Hi. I would like to add this feature if its ok?

**Comment by liyasthomas** [comment]
Hi @StephaneBischoff, you're free to pick up this feature. Do let us know if you got stuck.
