### ISSUE TITLE
Uncaught FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp()

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#1849]
**Describe the bug**
Apparently it is an error with the firebase configuration, I don't know if this has anything to do with it but I think it is the reason why the request history is not always complete, there are always missing entries.

**To Reproduce**
1. Go to 'https://hoppscotch.io'
2. Click on 'F12'
3. See error

**Expected behavior**
No console errors on firebase.

**Screenshots**
![image](https://user-images.githubusercontent.com/56084970/135735000-c68cd229-5df1-414b-a019-2efbb99635e3.png)

```js
Uncaught FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at x (7c71db2.modern.js:2)
    at Wo (7c71db2.modern.js:2)
    at d6ef2e6.modern.js:1
    at Object.next (7c71db2.modern.js:2)
    at e._next (7c71db2.modern.js:2)
    at e.next (7c71db2.modern.js:2)
    at 7c71db2.modern.js:2
    at c (7c71db2.modern.js:2)
    at e.next (7c71db2.modern.js:2)
    at e.next (7c71db2.modern.js:2)
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft edge
 - Version: 94.0.992.38

**Additional context**
I do not know if this is the case with other browsers.

**Comment by liyasthomas** [comment]
Hi @kaname-png, thanks for reporting this issue. We're aware of this error - but it doesn't seems to have any effect on the app's functionalities. If you think "History entries" aren't working properly - please mention how to reproduce that particular behaviour and we'll take a look into it.

Regarding this error - it seems like a race condition caused while initiating Firebase App configuration. Hopefully it'll be resolved in latest dependencies bump.

**Comment by kaname-png** [comment]
Hi @liyasthomas 
Reply to the topic about the missing items from the request history, I do nothing, they just disappear, but there is something that does appear, the message appears that if I want to confirm that I want to synchronize the history of repetitions, after that items disappear from the history, to ask me the same thing again some time later and the same thing happens. Taking into account that I have not deleted cache, cookies or closed session when making new requests.

**Comment by liyasthomas** [comment]
I am afraid I didn't fully understand what you mean by "I want to synchronize the history of repetitions". Please provide steps to reproduce this issue or a screenshot would be helpful.

Btw, if you turn off Syncing History from the Settings page, deleting History entries won't affect the cloud sync, also no new entries will be added to the cloud, instead, all entries will be only available in local storage only.

**Comment by kaname-png** [comment]
I mean I get a notification saying that message. "Do you want to synchronize the request history?"

**Comment by liyasthomas** [comment]
This happens when your local storage has entries that don't match with that of the last synced cloud history.

Choose yes to upload the latest (un-synced) local changes to cloud, once it complete sync - you wont be asked again to sync history.

**Comment by kaname-png** [comment]
That's the problem, when I hit "yes" everything seems to be fine, but then hours later the message reappears and then some history items disappear.

**Comment by liyasthomas** [comment]
Have your History entries set to be synced in the [Settings page](https://hoppscotch.io/settings)?

**Comment by kaname-png** [comment]
Yes, I always have it that way, that's why I wonder why hoppscotch asks me that question again if I supposedly already have it activated.

**Comment by liyasthomas** [comment]
Noted. We'll look into this.
