### ISSUE TITLE
Navigation shortcuts remove the language part of the URL

### ISSUE THREAD

**Issue by bokub** [hoppscotch/hoppscotch#1859]
**Describe the bug**
Navigation shortcuts remove the language part of the URL

**To Reproduce**
1. Go to 'https://hoppscotch.io/fr' (french version)
2. Press ALT+Q to go to the GraphQL tab
3. Language is **changed to english** in all app **except the left sidebar** (the `/fr` part of the URL isremoved).

Note: Pressing `/` then clicking on any navigation link has the same effect.

**Expected behavior**
App stays translated in french

**Screenshots**

![image](https://user-images.githubusercontent.com/17952318/136003112-97f3e925-9ab0-4bc7-9b0c-08703244b30f.png)

![image](https://user-images.githubusercontent.com/17952318/136002961-24f6fa96-463d-425b-aa37-5f6447d6e77d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by liyasthomas** [comment]
Hi, @bokub thanks for reporting this behavior - we'll look into it as soon as possible.

**Comment by himanshu007-creator** [comment]
Hi! would like to work on this issue. Can you help me get started ^_^ ?!

**Comment by liyasthomas** [comment]
Hi @himanshu007-creator, you're free to pick up this. Feel free to cont us here on any doubt.

**Comment by liyasthomas** [comment]
Hi @himanshu007-creator, I've patched this issue since it's a critical bug in production. Feel free to pick up another issue/feature.
