### ISSUE TITLE
Support SignalR connections on Realtime page

### ISSUE THREAD

**Issue by sixpeteunder** [hoppscotch/hoppscotch#1861]
**Is your feature request related to a problem? Please describe.**
[SignalR](https://signalr.net) is an open-source library for ASP.NET that allows real-time server-client communication. Hoppscotch does not support SignalR at the moment.

**Describe the solution you'd like**
A SignalR tab on the Realtime page with minimal configuration from which I can test SignalR services.

**Describe alternatives you've considered**
Until a few days ago, I had not heard of any viable solutions for this, but I recently bumped into [this project](https://github.com/gourav-d/SignalR-Web-Client). I'm yet to try it out.

**Additional context**
I would like to assist where I can to add support for this, but I have limited knowledge of SignalR internals and may not be of much help.

**Comment by liyasthomas** [comment]
Hi @sixpeteunder, thanks for reporting this feature request. As of now, support for SignalR connections are not in our roadmap and don't have an adequate number of requests to implement this in realtime page. We'll watch this space for further requests and discussion from the community and think over it on a later period. Thank you.
