### ISSUE TITLE
When can use Teams feature?

### ISSUE THREAD

**Issue by Sun-FreePort** [hoppscotch/hoppscotch#1874]
**Is your feature request related to a problem? Please describe.**

I write a text online game in web site, and open source the site, Now i use postman to share API file, I want to replace it to Hoppscotch teams feature.

So can we has a roadmap and show me the progress?

**Comment by liyasthomas** [comment]
Teams feature is in closed beta - [sign up for beta](https://hoppscotch.io/beta).

Checkout the [Teams wiki page](https://github.com/hoppscotch/hoppscotch/wiki/Teams) for usage and screenshots.

You can expect the public beta release of Teams by end of this month.

**Comment by liyasthomas** [comment]
### Hoppscotch for Teams is now out of closed beta.

✅   Unlimited teams

✅   Unlimited shared collections

✅   Unlimited team members

✅   Role-based access control

✅   Cloud sync

✅   Multiple devices

[Read more](https://liyasthomas.hashnode.dev/create-teams-for-collaboration-in-hoppscotch)

**Comment by Sun-FreePort** [comment]
@liyasthomas Hurry!!! very thank you and your team work!
