### ISSUE TITLE
[feature]: Ability to save API response

### ISSUE THREAD

**Issue by bhav15h** [hoppscotch/hoppscotch#1875]
**Is your feature request related to a problem? Please describe.**
I would like to be able to save an API response similar to the feature in postman. 
1. This will then allow us to preview the API instead of having to do a request to get the response. 
2. Also this is helpful whereby if you use a token to authenticate and the token has expired, instead of reauthenticate to view a response you get to quickly see the structure and response of the API.

**Describe the solution you'd like**
The solution for this is when a request to an API has returned a result we have a new button to save the response. This would be nested under the saved API request. 
We should be able to rename the saved response as there could be different responses from 1 request. e.g if an exception was raised in the api we could receive a different response.

**Describe alternatives you've considered**
At the moment the only alternative is to save the response in a file locally, but this is very hectic and not easily sharable to other people in the team as we may have a long list of 100 APIs. 

**Additional context**
Postman seem to have done it very well.

**Comment by sguzmanm** [comment]
Hi, this seems interesting, mind if I look into it?

**Comment by liyasthomas** [comment]
@sguzmanm yes, feel free to pick this up.

**Comment by Selvestr1** [comment]
> **Is your feature request related to a problem? Please describe.** I would like to be able to save an API response similar to the feature in postman.
> 
> 1. This will then allow us to preview the API instead of having to do a request to get the response.
> 2. Also this is helpful whereby if you use a token to authenticate and the token has expired, instead of reauthenticate to view a response you get to quickly see the structure and response of the API.
> 
> **Describe the solution you'd like** The solution for this is when a request to an API has returned a result we have a new button to save the response. This would be nested under the saved API request. We should be able to rename the saved response as there could be different responses from 1 request. e.g if an exception was raised in the api we could receive a different response.
> 
> **Describe alternatives you've considered** At the moment the only alternative is to save the response in a file locally, but this is very hectic and not easily sharable to other people in the team as we may have a long list of 100 APIs.
> 
> **Additional context** Postman seem to have done it very well.

**Comment by m-roberts** [comment]
+1 for this feature. Postman has the ability to save an API response as an "example" under requests in a collection.

**Comment by AndrewBastin** [comment]
This is something we have debated a lot on whether or not to implement, even had the PR in. But what we think is "Examples" as a thing within requests are more of a documentation thing and not exactly a "Testing" thing.

We are really vary and careful with the things we want to the REST Testing pages because **we do not want to build Hoppscotch into an open-source Postman**. This doesn't mean we will not tackle this issue (this issue is still open and will remain open until a solution is pushed), but we are planning on a solution we think is more better suited for the documentation way of doing things, this will take some time though as we are focused on other things to tackle before going for this.

**Comment by Elghazal** [comment]
+1 for this feature

**Comment by mojerro** [comment]
I think this feature is connected with  #1598. If we have the mock ability, then this feature is very convenient and can be a part of mock feature

**Comment by Msiavashi** [comment]
I'd like to look into implementing this feature.

@AndrewBastin Have you been able to find a solution yet? I agree that examples are more of a documentation, though having both integrated seamlessly works nicely sometimes. The way Postman handles it is quick easy to access and reproduce.

Please let me know if there has been any progress in this regard.

Thanks

**Comment by DarkPhoenix2704** [comment]
+1 For this Feature

**Comment by rohit-serri** [comment]
Recently Switched to HoppScotch from postman, this feature would be a important addition. Any Updates on this? can i help in any way by contributing to the repo? i might need some guidance if anyone is able to help

**Comment by Hamma111** [comment]
I came across HoppScotch to find it as a lovely open source project, and it really is. But the only thing holding me back from migrating my projects to HoppScotch is ability save responses/mock/examples. 

It is very convenient to save API response, right with the actual API, with certain payloads etc to give idea to team about different scenarios.

+1 to this feature please

**Comment by JayJayDee** [comment]
+1 For this Feature

**Comment by lixh00** [comment]
+1 For this Feature

**Comment by SamJakob** [comment]
See also #2018 with respect to being able to save responses as 'examples'.

**Comment by tranghaviet** [comment]
+1 For this Feature

**Comment by tomasztomys** [comment]
+1

**Comment by RussianProtein** [comment]
+1

**Comment by CMFerrer** [comment]
+1 for this feature

**Comment by umaraziz0** [comment]
+1 for this feature

**Comment by sarankumar-ns** [comment]
+1

**Comment by lakuapik** [comment]
+1

**Comment by ricardomedina98** [comment]
+1

**Comment by yaseeen96** [comment]
+1

**Comment by LeulAria** [comment]
can we have this feature plz 💯

**Comment by AlirezaAbsolution** [comment]
+1

**Comment by kumarahul98** [comment]
+1

**Comment by stavan-vc** [comment]
+1! 
Please add soon.

**Comment by Kimilhee** [comment]
+1 For this Feature. 
Please.

**Comment by cheol-95** [comment]
+1 For this Feature.

**Comment by AayushTaneja** [comment]
+1

**Comment by nupis-DanielS** [comment]
+1

**Comment by GuidoHeintz** [comment]
+1

**Comment by khanakia** [comment]
+1

**Comment by lifang218c** [comment]
+1 need to. mock  response examples! thanks

**Comment by BlackMocca** [comment]
+1

**Comment by niloy-netcom** [comment]
+1

**Comment by ebbdebrincat** [comment]
+1

**Comment by gautam-diwan-hcode** [comment]
Considering Hoppscotch has an unlimited workspaces and teams limit, this feature seems like a no brainer to add. Will be glad to contribute for this feature with some help if considered.

**Comment by Gautam-Diwan** [comment]
Considering Hoppscotch has an unlimited workspaces and teams limit, this feature seems like a no brainer to add. Will be glad to contribute for this feature with some help if considered.

**Comment by Espleth** [comment]
+1

**Comment by hussamgamal** [comment]
+1

**Comment by marcelo-mozena** [comment]
+1

**Comment by miarond** [comment]
+1 - Would really like this feature as well.

**Comment by nivedin** [comment]
this feature has been implemented with latest release

**Comment by abatishchev** [comment]
I'm using v2024.11.0 and when click on a request in history, it doesn't contain the original response, it's empty instead.

When the feature will be released?

**Comment by liyasthomas** [comment]
Hi @abatishchev, just a heads up - this feature is available from version 2024.9.0.

By the way, I wanted to clarify that the API response won’t be saved in the History entries. Instead, it’s part of the requests that you save to Collections. Make sure you’ve saved the response as an example to a collection so you can use it again and again. Please refer to documentation to learn how to [Save a response as an Example](https://docs.hoppscotch.io/documentation/getting-started/rest/response-handling#save-a-response-as-an-example).

**Comment by abatishchev** [comment]
I see. Is there a feature request to save responses into the history? I'd like to +1 it.

For the context, I'm migrating from Postman and I'm making this feature.

It's a potential security loophole and the reason to stop using Postman, but with proper safeguards (such as automatic timely cleanup) it can be made usable and secure, imo.

**Comment by ahanprojects** [comment]
Is there any updates on this? I think this will be an excellent feature. But I have a different question, why is my "save the request to create example" button greyed out?
