### ISSUE TITLE
UI Hangs when fetching "big" response

### ISSUE THREAD

**Issue by fabricio7p** [hoppscotch/hoppscotch#1890]
Big responses hangs the UI. It doesn't completely freeze but it turns out to be unusable.
This happens either as PWA or in the browser

1. Open the webapp
2. Make a request with a big JSON response, (my case it shows 200kb but not sure this is accurate) 
3. It hangs

**Expected behavior**
UI should warn that the payload is too big to display and not hang

**Screenshots**
![image](https://user-images.githubusercontent.com/46208058/137951174-7500476d-d6f0-4d0e-bf1a-680161d9eb36.png)

**Desktop:**
 - OS: Windows 10
 - Browser Brave (with all ads/script blocking disabled)
 - Chromium 94

**Comment by fabricio7p** [comment]
Yea it is about right. it's ~200kb

**Comment by liyasthomas** [comment]
We've updated the [CodeMirror](https://codemirror.net/6) editor (the library which we use in Hoppscotch) to v6. This has bought several performances boost to the render engine and now handles responses with more than 200kb. Hence closing.
