### ISSUE TITLE
Html preview view area is not full height

### ISSUE THREAD

**Issue by iagormoraes** [hoppscotch/hoppscotch#1891]
**Describe the bug**
By getting a HTML response from any endpoint call, the preview is not getting the full height of available space as shown in the screenshot.

**To Reproduce**
1. Make request to `https://github.com/hoppscotch/hoppscotch/issues`
2. Click on `Show Preview`
3. You should see the height of the preview not fitting the available space

**Expected behavior**
The users should be able to see the preview in full height of available space.

**Screenshots**
<img width="1679" alt="Screen Shot 2021-10-21 at 08 18 35" src="https://user-images.githubusercontent.com/13892132/138268136-4dd0953e-34cb-4d35-8837-deed57b40e57.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 2.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by liyasthomas** [comment]
Hi @rishabhkalra96, let me know if you've any trouble with this issue. Would love to help you out.

**Comment by iagormoraes** [comment]
I can help also in this issue, just let me know 🙂

**Comment by AndrewBastin** [comment]
@iagormoraes sure you can work on this!

**Comment by iagormoraes** [comment]
I can't run dev due to some error of package, I saw we use workspaces for it but it seems to be not recognizing it:

```
packages/hoppscotch-app do-dev$ pnpm run dev
[99 lines collapsed]
│ [dev:nuxt       ]  WARN  in /workspace/hoppscotch/node_modules/.pnpm/yargs-parser@20.2.9/node_modules/yargs-parser/build/lib/index.js
│ [dev:nuxt       ] 
│ [dev:nuxt       ] 
│ [dev:nuxt       ]  ERROR  Failed to compile with 1 errors
│ [dev:nuxt       ] 
│ [dev:nuxt       ] This dependency was not found:
│ [dev:nuxt       ] 
│ [dev:nuxt       ] * @hoppscotch/js-sandbox in ./helpers/RequestRunner.ts
│ [dev:nuxt       ] 
│ [dev:nuxt       ] To install it, you can run: npm install --save @hoppscotch/js-sandbox
└─ Running...
```

It happens both local and in cloud with Gitpod, someone knows that?

**Comment by liyasthomas** [comment]
This seems like an issue with the Node environment. To set up Hoppscotch development you might need to upgrade the Node version to v14.x or above. Let me know if this doesn't help - try cleaning the `node_modules` directory and reinstalling dependencies.

**Comment by iagormoraes** [comment]
> This seems like an issue with the Node environment. To set up Hoppscotch development you might need to upgrade the Node version to v14.x or above. Let me know if this doesn't help - try cleaning the `node_modules` directory and reinstalling dependencies.
> 
> EDIT: By the way, you'll need to install the dependencies and run `pnpm run dev` from root directory probably `hoppscotch`, not `hoppscotch/packages/hoppscotch-app`.

Hey @liyasthomas I've just tried that and still complains the missing package, is interesting because in `node_modules` I can see the folder there but it seems to not being recognized, even in Webstorm IDE, any tips?

**Comment by liyasthomas** [comment]
There was an issue in Windows OS which might've caused this behavior. This has been patched - pull the latest `main` branch or reclone the repository and try again. Let us know if the issue persists.

**Comment by iagormoraes** [comment]
> There was an issue in Windows OS which might've caused this behavior. This has been patched - pull the latest `main` branch or reclone the repository and try again. Let us know if the issue persists.

I pulled and is working now.
