### ISSUE TITLE
Generalize changes to lenses renderers

### ISSUE THREAD

**Issue by sguzmanm** [hoppscotch/hoppscotch#1896]
**Is your feature request related to a problem? Please describe.**
Mostly maintainability and code readability. When you make a change to any of these renderers you are forced to copy the same code more than three times 

**Describe the solution you'd like**
A global component for rendering the response that receives as inputs: 
- The response
- List of actions and a callback for each of these actions
- List of renderers. We could standardize these renderers by using an interface for specifying how to render the data received as input

**Describe alternatives you've considered**
- Use v-ifs based on a specific type on a global component

**Additional context**
Currently these are the renderers of the repo: 
![image](https://user-images.githubusercontent.com/25377562/138614458-7c5894fc-04d3-4d61-b8aa-f6aa1466cf80.png)

**Comment by RishabhAgarwal-2001** [comment]
Hello! 
I was looking to take up the task of refactoring lenses. I am initially planning to create an abstract text-based renderer as per the previous comment. 
Can I get this issue assigned to me?

**Comment by AndrewBastin** [comment]
@RishabhAgarwal-2001 sure!

But just to make sure you get what I have in mind:

Generally our code is moving to take advantage of Vue 3 Composables and Composition API more along with TypeScript. So abstracting out the lens renderers to a composable we can apply easily.
Second of all, lenses should work for non-text content, for example we have the ImageLensRenderer and maybe in the future we might add other binary formats as well. So, we need to keep support for them.

Anyways, feel free to ping me on Discord or Telegram if you want any help!


Assigning!
