### ISSUE TITLE
Persist the environment selection

### ISSUE THREAD

**Issue by ZvonimirSun** [hoppscotch/hoppscotch#1905]
**Is your feature request related to a problem? Please describe.**

I need to select the environment every time I refresh the website. And I have several environments, I cannot set all the variables in the global environment.

**Describe the solution you'd like**

I do wish the environment selection to be persisted somewhere, and do not need to select it everytime.

**Comment by 0xc0Der** [comment]
would like to work on this issue.

**Comment by liyasthomas** [comment]
Hi @0xc0Der, feel free to give this a try. Do let us know if you get stuck with anything in the codebase.

**Comment by 0xc0Der** [comment]
ok I will. :+1:

**Comment by AndrewBastin** [comment]
fixed in #1925
