### ISSUE TITLE
Can we save local database instead of browser cookie?

### ISSUE THREAD

**Issue by amraappvolution** [hoppscotch/hoppscotch#1915]
I have to store collection on local server.
Currently when we save collection it will sync in firebase database or browser cookie.
If I can store data on local database or mysql server, Tools will really help for me.

**Comment by danialbehzadi** [comment]
That would be awesome, since using of firebase is blocker for us.

**Comment by smilence86** [comment]
Hope to support it, In china mainland, we couldn't use google's services without proxy.

**Comment by berlinsaint** [comment]
Hope to support it

**Comment by ctrlaltdan** [comment]
Agreed. Any sort of filesystem support would be great so we can host internally and share collections among the team.
