### ISSUE TITLE
Hoppscotch can't be launched

### ISSUE THREAD

**Issue by michaelwittwer** [hoppscotch/hoppscotch#1921]
**Describe the bug**
Just tried to open the PWA and website https://hoppscotch.io with no luck.

**To Reproduce**
1. Go to 'https://hoppscotch.io/'
2. Open up Console and check on error

**Expected behavior**
Opens without exception. 

**Screenshots**
<img width="1326" alt="Screenshot 2021-11-01 at 07 50 33" src="https://user-images.githubusercontent.com/8394182/139632889-3da705ab-3545-4197-a95c-da9e301a86c0.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6
 - Browser: Chrome
 - Version: 95.0.4638.54
 (same happens in Safari - tested with v.15)

**Comment by liyasthomas** [comment]
Please refresh the application to take the latest changes.

We've rollbacked the last deployment. Hoppscotch.io should be online now. Will fix the latest build and re-deploy again. Thanks for reporting the downtime.

Do let me know if anyone is facing any issues with opening the application.
