### ISSUE TITLE
When l click "Bulk edit", the params l input in "key-value edit" will not be showed.

### ISSUE THREAD

**Issue by renmu123** [hoppscotch/hoppscotch#1928]
**Describe the bug**
When l click "Bulk edit", the params l input in "key-value edit" will be not showed.

**Expected behavior**
Params l inputed in "key-value edit" can be edited in "Bulk edit" just like postman

**Screenshots**
![image](https://user-images.githubusercontent.com/26896790/139840409-7021a782-16b7-43c1-af5d-a63252a17b2b.png)
![image](https://user-images.githubusercontent.com/26896790/139840504-7a225fbe-d765-43ba-b59c-777174b932e3.png)

**Desktop (please complete the following information):**
 - OS: Win01
 - Browser Chrome PWA
 - Version 2.0

**Comment by liyasthomas** [comment]
Hi @renmu123, thanks for requesting this feature.

We're aware of this behaviour and will try to improve Bulk Editor with two-way binded data support in near future.
