### ISSUE TITLE
Is it possible to relocate the collections sidebar to the left side? And is it possible to have the collections sidebar not get reset any time the page reloads?

### ISSUE THREAD

**Issue by edgariscoding** [hoppscotch/hoppscotch#1933]
I feel like having the collections sidebar on the left is more natural, that's where the folder tree is located in File Explorer, thats where I have my Solution Explorer set in VS, same for VSCode, and basically any app with a navigation menu tree.

It feels unnatural accessing it on the right side of the page. Is there an option to move it to the left?

Also, any time I'm working in a teams collection and i refresh the page, the collections sidebar resets to my personal collection. I then have to switch to the Team Collections tab, and then click the dropdown to choose my shared collection, and then i have to drill all the way down into the endpoint i was working with. Seems like a lot of wasted time.

**Comment by liyasthomas** [comment]
Will look into implementing these.

**Comment by liyasthomas** [comment]
Introduced a toggle button in the [Settings page](https://hoppscotch.io/settings) > Experiments to move the sidebar to the left.

![screely-1636000252651](https://user-images.githubusercontent.com/10395817/140258272-a2d6807d-5739-4697-ab6c-7a3e109fdb5d.png)

<img width="1440" alt="Screenshot 2021-11-04 at 10 03 15 AM" src="https://user-images.githubusercontent.com/10395817/140258449-6c00383b-76ee-4e6d-8794-c474f3ff9467.png">

Persisting the selected Tab will be implemented in the next release.

**Comment by edgariscoding** [comment]
Whoa that was fast! Thank you!
