### ISSUE TITLE
Self hosted version, not seeing the teams feature

### ISSUE THREAD

**Issue by kani** [hoppscotch/hoppscotch#1937]
I closed the main branch and the latest commit shows this. I followed the steps here https://github.com/hoppscotch/hoppscotch#releasing and uploaded the files to my webserver and I do not see the teams feature. Please help! 

```
commit dbd39ba0d8d47b12975cec457644423e18924767 (HEAD -> main, origin/main, origin/HEAD)
Author: liyasthomas <liyascthomas@gmail.com>
Date:   Thu Nov 4 20:59:01 2021 +0530

    fix: ignore vue files from stylelint
```

**Comment by liyasthomas** [comment]
Teams are not available for self-hosted Hoppscotch instances.
Use the [Hoppscotch.io](https://hoppscotch.io) to enjoy Teams.

We'll be providing a self-hostable community edition in near future, meanwhile it's advice to use public build.

**Comment by kani** [comment]
ok thanks!
