### ISSUE TITLE
Cannot install from behind proxy

### ISSUE THREAD

**Issue by cloudomatic** [hoppscotch/hoppscotch#1945]
**Describe the bug**
Attempted to build and run Hoppscotch, but build failed, possibly due to gql-codegen not being able to navigate outbound proxy

**To Reproduce**
  git clone https://github.com/hoppscotch/hoppscotch
   cd hoppscotch
   git checkout -b test_build
   sudo docker run -it --rm  -v $(pwd):/app:Z registry.acme.com/node:lts-alpine sh
   ### Inside the container's shell, set the proxy variables
   export HTTPS_PROXY=http://http.proxy.acme.com 
   export HTTP_PROXY=http://http.proxy.acme.com 
   export https_proxy=http://http.proxy.acme.com 
   export http_proxy=http://http.proxy.acme.com 
   ### Install packages
   apk update
   apk add --update --no-cache   git
   cd /app
   npm install -g pnpm
   pnpm i --unsafe-perm=true

   ### Error text ##########################
```
│ > hoppscotch-app@2.1.0 gql-codegen /app/packages/hoppscotch-app
│ > graphql-codegen --config gql-codegen.yml
│ [22:16:45] Parse configuration [started]
│ [22:16:45] Parse configuration [completed]
│ [22:16:45] Generate outputs [started]
│ [22:16:45] Generate helpers/backend/graphql.ts [started]
│ [22:16:45] Generate helpers/backend/backend-schema.json [started]
│ [22:16:45] Load GraphQL schemas [started]
│ [22:16:45] Load GraphQL schemas [started]
│ (node:210) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
│ (Use `node --trace-warnings ...` to show where the warning was created)
│ [22:16:45] Load GraphQL schemas [failed]
│ [22:16:45] → Failed to load schema
│ [22:16:45] Generate helpers/backend/graphql.ts [failed]
│ [22:16:45] → Failed to load schema
│ [22:16:45] Load GraphQL schemas [failed]
│ [22:16:45] → Failed to load schema
│ [22:16:45] Generate helpers/backend/backend-schema.json [failed]
│ [22:16:45] → Failed to load schema
│ [22:16:45] Generate outputs [failed]
│ Something went wrong
│  ELIFECYCLE  Command failed with exit code 1.
```

   ### Attempt to run this command again
   cd /app/packages/hoppscotch-app
   pnpm run gql-codegen

### More detailed error
```
 Found 2 errors

  helpers/backend/graphql.ts
    Failed to load schema from https://api.hoppscotch.io/graphql:

        fetch failed
        TypeError: fetch failed
    at Object.processResponse (/app/node_modules/.pnpm/undici@4.9.5/node_modules/undici/lib/fetch/index.js:176:23)
    at fetchFinale (/app/node_modules/.pnpm/undici@4.9.5/node_modules/undici/lib/fetch/index.js:720:17)
    at EventEmitter.mainFetch (/app/node_modules/.pnpm/undici@4.9.5/node_modules/undici/lib/fetch/index.js:695:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

 Tried putting a custom fetch module into into ./gql-codegen.yml
 as described here: https://github.com/dotansimha/graphql-code-generator/issues/2271
 and here: https://www.graphql-code-generator.com/docs/getting-started/schema-field
 
  pnpm install   omni-fetch
   cat gql-codegen.yml
```
overwrite: true
schema:
  - https://api.hoppscotch.io/graphql:
      customFetch: 'omni-fetch'
```

    ### Try again
    pnpm run gql-codegen
    
    ### Error is now

```
 Found 2 errors

    helpers/backend/graphql.ts
    Failed to load schema from https://api.hoppscotch.io/graphql:

        Cannot set property default of #<Object> which has only a getter
        TypeError: Cannot set property default of #<Object> which has only a getter
    at _interopNamespace (/app/node_modules/.pnpm/@graphql-tools+url-loader@7.5.1_graphql@15.7.2/node_modules/@graphql-tools/url-loader/index.js:21:22)
    at /app/node_modules/.pnpm/@graphql-tools+url-loader@7.5.1_graphql@15.7.2/node_modules/@graphql-tools/url-loader/index.js:264:78
```
**Expected behavior**
Expected that the pnpm install would navigate the http_proxy environment variable(s) and no additional configuration would be required for install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux  5.4.0-1046-kvm #48-Ubuntu SMP 
- Docker v20.10.7
- docker-compose version 1.25.0

**Additional context**
Running the pre-built (docker.io) Hoppscotch container in same environment does work
Got the same error when using the Compose file to perform the build

**Comment by liyasthomas** [comment]
`https://api.hoppscotch.io/graphql` is restricted to Hoppscotch production instance only due to security reasons. Use the public cloud instance to enjoy Teams and upcoming features.
