### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by Shohzod97** [hoppscotch/hoppscotch#1949]
1. Go to 'app.cors.bridged.cc/settings/' by Google Chrome.
2. Click on 'Login with Google' - browser showed pop-window for a second and closed it.
3. Click on 'Login with Github' - browser showed pop-window for a second and closed it.
4. I tried to login from other browsers.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome, opera, edge

**Comment by liyasthomas** [comment]
`https://app.cors.bridged.cc` is not affiliated with Hoppscotch.


Use [Hoppscotch.io](https://hoppscotch.io) for latest features.
