### ISSUE TITLE
Socket.io auth

### ISSUE THREAD

**Issue by PortStone** [hoppscotch/hoppscotch#1953]
It would be awesome to set a bearer token on a socket.io request just like you can do it on a rest request.

**Comment by Duck-sri** [comment]
I am willing to contribute to this, but not sure how to do.
I will try if someone can point me how

**Comment by GeneralChauhan** [comment]
can you tell me how to get started with it?

**Comment by liyasthomas** [comment]
[This thread could be a good starting point](https://stackoverflow.com/questions/36788831/authenticating-socket-io-connections-using-jwt)

**Comment by rakshit087** [comment]
@PortStone can you please share a SocketIO url with bearer I am working on this feature, but unable to test it.

**Comment by PortStone** [comment]
> @PortStone can you please share a SocketIO url with bearer I am working on this feature, but unable to test it.

Yes, I am working on it.

**Comment by rakshit087** [comment]
> > @PortStone can you please share a SocketIO url with bearer I am working on this feature, but unable to test it.
> 
> Yes, I am working on it.

PR? or Token?

**Comment by PortStone** [comment]
> > > @PortStone can you please share a SocketIO url with bearer I am working on this feature, but unable to test it.
> > 
> > 
> > Yes, I am working on it.
> 
> PR? or Token?

Token so you can test it out.

**Comment by PortStone** [comment]
I have made a simple Node.js server that won't accept your socket connection unless you are authorized. It will work if you send a bearer token: `Authorization: Bearer password`. You should now be able to test it out.

https://github.com/PortStone/socketio-test

**Comment by rakshit087** [comment]
Great Thank you so much!
