### ISSUE TITLE
Body content issue , it should support same api request used in different projects with different body content

### ISSUE THREAD

**Issue by elaoshi** [hoppscotch/hoppscotch#1954]
**Describe the bug**
Body content in same api address issue , it should support same api request with different body content used in different projects / folders

**To Reproduce**
1. Go to 'folder A'
2. Create a request and add some body content
3. Save api request "R1" to folder A
4. Created folder B
5. duplicate "R1" to folder B , names "B1"
6. update the body content in B1
7.  Save B1
8. View R1, and see the body was be changed to the same in B1.  Bug happened.  

**Expected behavior**
As picture explained.

The body should not depended to the api address. 
It should support same api used in different projects with different body content.

**Screenshots**
![image](https://user-images.githubusercontent.com/62131525/141932258-4be30a08-613c-40cc-b6cd-48ece1c7a42b.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 95.0.4638.69

**Smartphone (please complete the following information):**

**Additional context**

**Comment by liyasthomas** [comment]
Thanks for reporting the issue, we're able to reproduce this behaviour - looking into fixing this as soon as possible.
