### ISSUE TITLE
Can't type GraphQL query in Safari

### ISSUE THREAD

**Issue by t1** [hoppscotch/hoppscotch#1960]
**Describe the bug**
The GraphQL query field doesn't accept any input. Only the backspace key seems to work.

**To Reproduce**
1. Go to 'https://hoppscotch.io/graphql'
2. Click inside the 'query' field
3. Start to type

**Expected behavior**
Characters should appear

**Desktop (please complete the following information):**
 - OS: MacOS (M1)
 - Browser: safari
 - Version: 15.1

**Comment by t1** [comment]
The console shows `[Error] WebSocket connection to 'wss://api.hoppscotch.io/graphql' failed: WebSocket is closed before the connection is established.`, but nothing else.

**Comment by liyasthomas** [comment]
We're looking into fixing this issue as soon as possible.

**Comment by liyasthomas** [comment]
I've temporarily rolled back to our latest stable release - the editor should work as expected now. Will investigate what went wrong and update here.

**Comment by t1** [comment]
Yeah, that helped! Thanks a lot. I'm curious what caused it.

**Comment by liyasthomas** [comment]
I've patched this issue. This was due to an editor styling that basically disabled cursor focus/selection in the editor instance, especially in the Safari browser.
