### ISSUE TITLE
[bug]: Handling request to empty url

### ISSUE THREAD

**Issue by devblin** [hoppscotch/hoppscotch#1968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When, I send request to empty url I see below message in response area.
![image](https://user-images.githubusercontent.com/55559527/142842414-d92f2cbf-d0a1-4464-9681-be86107e7ac5.png)

What we should get is a warning message that request url can't be empty.

### Steps to reproduce

1. Go to https://hoppscotch.io
2. Send request with empty url

### Environment

Production

### Version

Cloud

**Comment by devblin** [comment]
If the bug is confirmed, I am willing to submit a PR to fix the issue

**Comment by liyasthomas** [comment]
Hi @devblin, thanks for reporting this behaviour. I can confirm this bug exists in the app. Feel free to pick this up. Do let us know if you've any doubts understanding the codebase.

**Comment by devblin** [comment]
@liyasthomas Yeah, sure I will work on this.

**Comment by shtakai** [comment]
Hi. :)

I've captured reproducing.
Captures are followings.

- reproduced with `http://` only

![http](https://user-images.githubusercontent.com/2187465/142967094-3a3926e8-6bb9-4820-a89f-c5326428094f.gif)

- reproduced with `https://` only


![https](https://user-images.githubusercontent.com/2187465/142967414-d09494f2-f4d0-4c77-8d25-8e8c3697302c.gif)

- not reproduced with `empty url`, but returns Hoppscotch's page I think...


![empty_on_url](https://user-images.githubusercontent.com/2187465/142967308-d63e0a2d-7d9e-4bbe-be79-14cb9772a314.gif)

Thank you. :)
