### ISSUE TITLE
[bug]: Unable to send requests without proxy interceptor

### ISSUE THREAD

**Issue by lalitindoria** [hoppscotch/hoppscotch#1969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I just tried sending a request to https://www.google.com from https://hoppscotch.io/ and it doesn't work. I went and turned on the proxy interceptor in the settings and that made the request work.****

### Steps to reproduce

Just send a request on hoppscotch.io

![image](https://user-images.githubusercontent.com/7344511/142854427-8dcd794c-0d56-423b-8d14-74fef5719e2f.png)

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This is an expected behaviour. Endpoint with CORS are restricted on client sode API calls. To fix this, we introduce a proxy middleware which generates request from server and thus resolves CORS restrictions.

Read more about CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by lalitindoria** [comment]
Oh wow how could I not guess that, thanks @liyasthomas
