### ISSUE TITLE
[small UI change request]: Placeholder Font and border size of input box 

### ISSUE THREAD

**Issue by Devesh21700Kumar** [hoppscotch/hoppscotch#1974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

While looking at the hoppscotch webapp, I came across some instances 

![image](https://user-images.githubusercontent.com/59202075/143044385-5f23bf41-cf7e-42b2-b044-59a67d148b2d.png)

![image](https://user-images.githubusercontent.com/59202075/143044440-09aa5b97-bbf0-4dc1-bef3-e5cee9c5b051.png)

The font used as placeholder and the input box border of these boxes are very light with respect to the UI used.

![image](https://user-images.githubusercontent.com/59202075/143044993-5db7588a-fb77-45b6-9520-cfbc67c83913.png)

Font as used in the above pic could be used so as to slightly improve the experience., as used in the above pic,

### Why should this be worked on?

As the screenshots suggest, the font used and the border thickness of the input box are very light and don't go well with the UI.

**Comment by liyasthomas** [comment]
I've updated the placeholders' opacity to improve reliability. This should look fine now.
