### ISSUE TITLE
[bug]: FirebaseError: Function setDoc() called with invalid data. Unsupported field value: undefined

### ISSUE THREAD

**Issue by dsileikaevry** [hoppscotch/hoppscotch#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![bilde](https://user-images.githubusercontent.com/49481646/143410163-0bdbcca3-75fa-47a5-8f8a-842cabe9a91d.png)
Hi, I'm getting this error in console when try run some call of API.

### Steps to reproduce

1. Select Team Collections
2. Select Team
3. Select any API call from collection 
5. Click 'Send'

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
I can't reproduce this error in the production environment. Please be more specific on how to reproduce the error. On the request setup any specific endpoint, parameters, request body etc.
