### ISSUE TITLE
[feature]: Import Insomnia collection to Hoppscotch like Postman

### ISSUE THREAD

**Issue by anwarulislam** [hoppscotch/hoppscotch#1978]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need a feature for importing the Insomnia collection to Hoppscotch like how we do the Postman collection. Currently, when I try to import the Insomnia collection it says import failed.

### Why should this be worked on?

Many programmers prefer using Insomnia over Postman. When they try switching to Hoppscotch they can't import their existing collection from Insomnia.

**Comment by kritikmodi** [comment]
Hey @anwarulislam , are you currently working on this feature?

**Comment by anwarulislam** [comment]
Hello @kritikmodi, Yes, I'm working on this feature now.
