### ISSUE TITLE
[bug]: body is being changed for multiple collections

### ISSUE THREAD

**Issue by MustafaHi** [hoppscotch/hoppscotch#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I expect it to change only for the current collection(request) and not the rest (unselected ones)

### Steps to reproduce

create request and save it
save as new collection and switch to the new
changing the new will change the old.

### Environment

Release

### Version

Cloud

**Comment by liyasthomas** [comment]
>Steps to reproduce
create request and save it
save as new collection and switch to the new
changing the new will change the old.

I can't reproduce this at my end, can you produce a screen record to understand the issue accurately.

**Comment by MustafaHi** [comment]
![yJKZzlzj4K](https://user-images.githubusercontent.com/5108884/144584944-9f1ef03d-9b30-4bcf-946f-7c96e614a330.gif)

**Comment by liyasthomas** [comment]
Thanks for providing the screen record. We were able to reproduce this behavior. Working on a fix now.

**Comment by AndrewBastin** [comment]
@MustafaHi please wait for like 5-10 minutes and then let me know if the issue is resolved.

**Comment by MustafaHi** [comment]
The issue is Not resolved.
A work around is to refresh after every change/save.

**Comment by liyasthomas** [comment]
Seems like the production deployment took a little bit longer than expected. I flushed the cache and redeployed the fix. I can confirm this issue has been solved in production.

Feel free to reopen if the issue still persists. Force reload the application to take effect the latest changes.
