### ISSUE TITLE
[improvement]: Too big icon when dock in macOS is resized down

### ISSUE THREAD

**Issue by twistezo** [hoppscotch/hoppscotch#1997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When macOS dock is resized down from its default height hoppscotch icon is too big.

<img width="228" alt="Screenshot 2021-12-06 at 15 24 11" src="https://user-images.githubusercontent.com/23572157/144863293-87e3b445-b5c0-40f5-a31d-c02c5c0b338d.png">

### Steps to reproduce

Just place app in macOS dock.

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
![screely-1638801708058](https://user-images.githubusercontent.com/10395817/144865868-d5c8fadc-785d-4277-b53f-b01bba4752c0.png)

I guess that's a common style applied to all Progressive Web Apps' icons installed on macOS.

I will see if it's possible to shrink the app icon to match the dock icon size on macOS, but most probably it'll cause other operating systems to have an irregular icon size.
