### ISSUE TITLE
[bug]: Importing cURL with --url does not work

### ISSUE THREAD

**Issue by LeCodeCo** [hoppscotch/hoppscotch#2004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try and import a cURL request which uses --url, Hoppscotch fails to import it. This format is what's used by Insomnia when copying a request as cURL.

### Steps to reproduce

Import cURL with Send (dropdown) -> Import cURL

```bash
curl --request POST \
  --url http://localhost:3000/auth/login \
  --header 'Content-Type: application/json' \
  --data '{
	"email": "example@example.com",
	"password": "password"
}'
```

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Merging this issue with an existing similar issue: #927.
