### ISSUE TITLE
[feature]: Port "drag and drop requests" feature to "Team collections" and introduce right click context menu for "Collections"

### ISSUE THREAD

**Issue by LeCodeCo** [hoppscotch/hoppscotch#2005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Right now, after a request is saved into a collection there the only way (I believe) to move it into a different folder within the collection is by restoring it and saving it again, which is slow and tedious.

I think dragging and dropping requests into different folders should be possible.

Furthermore, I think that right-clicking a request inside the sidebar should open the same context menu as `...`.

### Why should this be worked on?

This streamlines the UX of collections.

**Comment by liyasthomas** [comment]
You can drag-and-drop requests from a collection/folder to another collection/folder. Do let me know/reopen this issue if it doesn't work for you. I can provide a screen record if you need to see a demo.

Right-click context menu is something we'd like to implement platform-wide, not only for the "Collections" section. We'll be adding this in the near future as we've secondary action on the remaining section too.

**Comment by LeCodeCo** [comment]
Thanks for such a quick response!

I've tried dragging and dropping on a request stored in a team collection and it doesn't seem to work for me. I can't "pickup" the request when I click and drag it. Microsoft Edge on the cloud version, version 2.0 (according to Help & feedback at the bottom).

**Comment by liyasthomas** [comment]
I acknowledge drag-and-drop isn't implemented in the Teams section. Will be porting the feature set to the Teams section as well as soon as possible.
