### ISSUE TITLE
[feature]: Show existing name while renaming collections / folders / requests

### ISSUE THREAD

**Issue by LeCodeCo** [hoppscotch/hoppscotch#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to rename a request/folder in the collections sidebar, the existing name isn't populated. 
![image](https://user-images.githubusercontent.com/20425781/145512074-c35310b2-6a7c-4b56-b039-718c02e164b7.png)

### Steps to reproduce

1. Go to collections sidebar
2. Click `...` and then `Edit` on a request or folder

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This could be a nice enhancement, thank you for the suggestion.
