### ISSUE TITLE
[feature]: Allow connection to WAMP servers

### ISSUE THREAD

**Issue by trbodev** [hoppscotch/hoppscotch#2007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow connections to WAMP servers via the [WAMP Protocol](https://wamp-proto.org/index.html) in the Realtime section.

### Why should this be worked on?

I am looking into using WAMP for a project and cannot find any online tools/testers for it.

**Comment by liyasthomas** [comment]
We don't have plans to add support to the `WAMP` protocol. Though we'll track this request to discuss more on this feature.
