### ISSUE TITLE
[bug]: add http header token param over remove the header,cookie not remove

### ISSUE THREAD

**Issue by night2049** [hoppscotch/hoppscotch#2012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

add http header token=xxxxxxxxxxxxxxxx
request to http server
remove the header "token"
http token is remove 
http cookie remove token value
![image](https://user-images.githubusercontent.com/69810127/145793657-80236575-979a-4e7c-8250-353acb8be3f9.png)

### Steps to reproduce

version: v2.0

![image](https://user-images.githubusercontent.com/69810127/145793957-817f5660-6eb9-43a8-a590-7e2f14bceb38.png)
![image](https://user-images.githubusercontent.com/69810127/145793978-52674079-93c8-4073-bfff-843eff975245.png)

remove http header "token" value
![image](https://user-images.githubusercontent.com/69810127/145794047-0afa1339-e177-4735-b098-af529a5f84f7.png)
![image](https://user-images.githubusercontent.com/69810127/145794147-fc00f8e2-c956-42e0-9f7c-22ab846c27d2.png)

the token field in cookie exist

### Environment

Release

### Version

Local

**Comment by liyasthomas** [comment]
I can't understand the bug reproduction steps.

As per my current understanding, you were saying that even if you remove the `token` field from headers, it was shown at the server end - right?

**Can you provide a screen record of your specific behavior**

I tried removing the `token` header and it worked properly on our echo server endpoint: `https://echo.hoppscotch.io`.

<sub>You might want to turn on the Proxy mode from [Settings](https://hoppscotch.io/settings)</sub>

**Comment by night2049** [comment]
> I can't understand the bug reproduction steps.
> 
> As per my current understanding, you were saying that even if you remove the field from headers, it was shown at the server end - right?`token`
> 
> **Can you provide a screen record of your specific behavior**
> 
> I tried removing the header and it worked properly on our echo server endpoint: .`token``https://echo.hoppscotch.io`
> 
> You might want to turn on the Proxy mode from [Settings](https://hoppscotch.io/settings)

hello,I want to say,if you remove the header "token", the tool hoppscotch auto add in cookie "token" field,i want cookie not add "token" field,you can see last image,show cookie join "token" field

**Comment by liyasthomas** [comment]
Hoppscotch doesn't add the `Cookie` field to headers automatically. I still can't reproduce the error.

Here's my request setup: https://hopp.sh/r/JzyAMZLDXxrj with a valid `Cookie` field and I've turned off the `token` field - Hoppscotch doesn't set the `Cookie` field to headers automatically.

Please provide a screen record or reproduction link:
1. Click the drop-down menu next to "Save" in the request section.
2. Click "Copy link"

<img width="1440" alt="Screenshot 2021-12-14 at 8 49 30 AM" src="https://user-images.githubusercontent.com/10395817/145927025-5eb02235-3a14-4069-8550-d2a29a37dfaa.png">
