### ISSUE TITLE
[feature]: Add an Authorization tab on GraphQL

### ISSUE THREAD

**Issue by acolombier** [hoppscotch/hoppscotch#2019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It would be amazing to have an Authorization tab on GraphQL, as it is for REST. 

### Why should this be worked on?

Authorization is also a thing in GQL and having automated OAuth mechanism would be :+1:

**Comment by EdwinFajardoBarrera** [comment]
I would like to contribute, can you help me with giving background and if necessary expectations?

**Comment by acolombier** [comment]
It would be great if it could work like the one in REST - I'm mostly looking after an OIDC integration
It would also be great if could work like [Insomnia](https://docs.insomnia.rest/insomnia/chaining-requests) and so we can chain the token

I'd be very happy to help on that one too in case you think it is worth decoupling in multiple steps :)

**Comment by AndrewBastin** [comment]
@EdwinFajardoBarrera  @acolombier 

We are keeping this issue open for students under [Github Externship](https://externship.github.in/) to contribute to.
If this issue isn't assigned to anyone by the end of the month, you can pick this up!

**Comment by PSY27** [comment]
I would like to do this issue for externship

**Comment by EdwinFajardoBarrera** [comment]
I see, if there is another one to contribute to, let me know @AndrewBastin

**Comment by AndrewBastin** [comment]
Assigning this to @RishabhAgarwal-2001

**Comment by RishabhAgarwal-2001** [comment]
Sure!
