### ISSUE TITLE
[feature]: Import collection from URL

### ISSUE THREAD

**Issue by joshxyzhimself** [hoppscotch/hoppscotch#2020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- allow api providers to link to https://hoppscotch.io/import?url=https://example.com/hoppscotch-collection.json

### Why should this be worked on?

- lets api providers to hotlink their collections easily

**Comment by GwendalBroudin-Emoko** [comment]
Hi is there any documentation about this feature? I can't find how to achieve it.

**Comment by luoxufeiyan** [comment]
@GwendalBroudin-Emoko  I cannot locate any documents either; However, there is a small archive button beneath the workspace list, which allows for the import or export of collections.

![image](https://github.com/hoppscotch/hoppscotch/assets/6621172/fc27e694-3764-4816-bbe6-dd267dae4f6b)

**Comment by GwendalBroudin-Emoko** [comment]
Hi @luoxufeiyan,
Thank for your answer. I already use it for OpenAPi json files but there is no option for url imports.

**Comment by amk-dev** [comment]
hey @GwendalBroudin-Emoko 

you can import your json files like this, 

`https://hoppscotch.io/import?type=<type_of_file_import>&url=<your_url>`

the value of <type_of_file_imports> can be `hoppscotch`, `postman`, `insomnia`, `openapi`
