### ISSUE TITLE
[bug]: Error while importing collection from Postman

### ISSUE THREAD

**Issue by anwarulislam** [hoppscotch/hoppscotch#2030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Requests with Postman variable can't be imported in Hoppscotch. 

### Steps to reproduce

I searched in the project why this is occurring and found this regex. The regex is validating URL and adding URL to Hoppscotch request based on this condition below. Since, URL with variable doesn't have any `://` that's why it doesn't pass the condition. And the result is empty URL for the request. I'm trying to fix this and will commit if it fixed.

![image](https://user-images.githubusercontent.com/26295990/146688764-7ac72f04-159c-46f6-92a3-7db57889fcc5.png)

### Environment

Production

### Version

Cloud

**Comment by anwarulislam** [comment]
@AndrewBastin can I work on this issue, now?

**Comment by AndrewBastin** [comment]
Umm, sure. But not right now. We are doing a refactor to the Import/Export system which should be done in a couple of days. Please wait until then.

**Comment by anwarulislam** [comment]
Sounds good you're refactoring the whole import/export system. 

Would be great if you bring these features:

- Drag and Drop for importing JSON, YML, or any other format (It would be nice if you parse everything to OpenAPI JSON first and then parse that to Hoppscotch standard)
- Environment Importing and binding to that specific collection
- Export to multiple format including YML, JSON, Insomnia, Postman and so on.

**Comment by liyasthomas** [comment]
We're using #2030 to track "Issues with importing Postman collections" and the upcoming refactor on the import/export system. Hence closing this issue.
