### ISSUE TITLE
[bug]: Teams:: Self hosted instance sending team add request to api.hoppscotch.io/graphql and fails

### ISSUE THREAD

**Issue by ziaulrehman40** [hoppscotch/hoppscotch#2035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On self hosted custom instance, create team request is sent to `api.hoppscotch.io/graphql` with payload:
```
{"query":"mutation CreateTeam($name: String!) {\n  createTeam(name: $name) {\n    id\n    name\n    members {\n      membershipID\n      role\n      user {\n        uid\n        displayName\n        email\n        photoURL\n        __typename\n      }\n      __typename\n    }\n    myRole\n    ownersCount\n    editorsCount\n    viewersCount\n    __typename\n  }\n}\n","operationName":"CreateTeam","variables":{"name":"Team12345"}}
```

Which fails and gives:
```
{"errors":[{"message":"auth/fail","locations":[{"line":2,"column":3}],"path":["createTeam"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null}
```

### Steps to reproduce

1. Configure a custom instance, following official guides, setup all new keys in `.env`, build and deploy
2. Try to create a new team, no error pops on forntend
3. Inspecting the network calls i see above behavior

### Environment

Production

### Version

Self-hosted

**Comment by AndrewBastin** [comment]
Hi there,

Teams currently is only available for users of the official Hoppscotch instance ([https://hoppscotch.io](https://hoppscotch.io)). We are working on a fully self hosted solution.

**Comment by ziaulrehman40** [comment]
Thanks @AndrewBastin , is there any issue or PR i can track, or anyway i can help speed this process up.
BTW, only reason we are not using official instance is to avoid putting a lot of load on it, and we don't know if there are any limits on usage there, as we intend to use it extensively. So if you can help me understand this aspect as well, would be great.

Thanks.

**Comment by AndrewBastin** [comment]
@ziaulrehman40 the issue is tracked here #1817.

I don't exactly get by what you meant by not putting more load on it. What do you mean by using it extensively ?

**Comment by ziaulrehman40** [comment]
@AndrewBastin like collection size limits, users in a team limits etc. As we have huge collections we would like to import from postman to hoppscotch.
