### ISSUE TITLE
[feature]: import request from cURL onpaste in the url field

### ISSUE THREAD

**Issue by anwarulislam** [hoppscotch/hoppscotch#2036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we copy cURL from the network and want to import it as a request in Hoppscotch we click on the dropdown and select Import from cURL now. And we paste the cURL hit the confirm button and cURL is importing nicely. 

But, it would be nice if we paste the complete string in the default URL field and detect if it cURL or not after detecting we can import that by the same process.

### Why should this be worked on?

In my opinion, it would be a nice feature for 10x developers.

**Comment by anwarulislam** [comment]
@liyasthomas I'm working on this.

**Comment by AndrewBastin** [comment]
fixed by #2037
