### ISSUE TITLE
[bug]: page style not correct when serve dist of `yarn generate`

### ISSUE THREAD

**Issue by liudonghua123** [hoppscotch/hoppscotch#2038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I just clone the latest code, following the guidence, then execute `yarn generate` and `serve packages\hoppscotch-app\dist`, open browser to navigate http://localhost:3000/.

![image](https://user-images.githubusercontent.com/2276718/147200595-302bf00b-b7f4-4a70-8efe-603eaf8df83a.png)

![image](https://user-images.githubusercontent.com/2276718/147200556-538c0f38-863c-4a54-aa3b-eb33ad4f8143.png)

If I checkout v2.1.0, then the styles are ok.

### Steps to reproduce

1. git clone https://github.com/hoppscotch/hoppscotch
2. cd hoppscotch
3. npm install -g pnpm serve
4. pnpm install
5. cp packages/hoppscotch-app/.env.example packages/hoppscotch-app/.env
6. yarn generate
7. serve packages\hoppscotch-app\dist
8. browser http://localhost:3000/

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Seems like only the sidebar component is broken - not the pages. Can you check if this happens in other browsers (Chrome, Firefox) as well?

cc: @AndrewBastin can you see if this issue persists on IE's latest version?

**Comment by liyasthomas** [comment]
@liudonghua123, we tried reproducing the issue but `yarn generate` produced dist folder was working as expected. I suggest you delete the current `dist` folder and re-run `pnpm run build` from the root folder. And see if the issue persists or not.

**Comment by liudonghua123** [comment]
@liyasthomas Thanks, I tried to remove all the `node_modules`, `/.pnpm-store`, `packages/hoppscotch-app/dist` and tried `pnpm install`/`pnpm run generate` again, it seemed ok now. Maybe the files in my node_modules are corrupted.
