### ISSUE TITLE
[bug]: 参数无法填写中文 使用搜狗输入法会把拼音和中文都添加上

### ISSUE THREAD

**Issue by maidou883** [hoppscotch/hoppscotch#2039]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

输入中文时会把拼音也输入上去
![image](https://user-images.githubusercontent.com/48854556/147205733-46666505-919d-4c4d-ac09-00af18359cd2.png)
![image](https://user-images.githubusercontent.com/48854556/147205775-9baaeba8-980f-46df-9511-77398bdb91c6.png)

### Steps to reproduce

1.打开hoppscotch
2.填写参数
3.使用输入法填写中文
4.会出现拼音也输入上去

### Environment

Release

### Version

v2.1.0 Latest

**Comment by liyasthomas** [comment]
@maidou883, what I've understood is: "Parameters cannot be filled in Chinese. Using Sogou input method will add both Pinyin and Chinese."

Since I don't have access to Chinese or Pinyin input tools, I am afraid I can't reproduce this behavior at my end.

Let me know if this behavior true to all input field in Hoppscotch or just for Parameters?

**Comment by hdwubinw** [comment]
> @maidou883, what I've understood is: "Parameters cannot be filled in Chinese. Using Sogou input method will add both Pinyin and Chinese."
> 
> Since I don't have access to Chinese or Pinyin input tools, I am afraid I can't reproduce this behavior at my end.
> 
> Let me know if this behavior is true to all input fields in Hoppscotch or just for Parameters?

**Comment by maidou883** [comment]
> @maidou883, what I've understood is: "Parameters cannot be filled in Chinese. Using Sogou input method will add both Pinyin and Chinese."
> 
> Since I don't have access to Chinese or Pinyin input tools, I am afraid I can't reproduce this behavior at my end.
> 
> Let me know if this behavior is true to all input fields in Hoppscotch or just for Parameters?
Try to fill in other parameters, you will encounter the same problem.

**Comment by maidou883** [comment]
@liyasthomas Try to fill in other parameters, you will encounter the same problem.

**Comment by liyasthomas** [comment]
May I know if this happens in other input fields like `URL`, `Headers` sections etc?

**Comment by maidou883** [comment]
@liyasthomas 
URL, Headers Same error.
All positions that can be entered are this error.

**Comment by liyasthomas** [comment]
@maidou883 I can't find any evidence why this is happening. Hoppscotch doesn't have any such functions to auto translate/parse any of user's inputs. Either this got something to do with your browser (any 3rd party extensions maybe?) or your input tool.

I afraid I can't provide any help with a behaviour I cannot reproduce at my end. Moreover, I haven't received any such bug reports from our users.

Let me know if you can reproduce this issue in any other device just to confirm it got something to do with Hoppscotch.

**Comment by maidou883** [comment]
@liyasthomas 
It's OK to enter Chinese in Google and GitHub, but hopscotch can't. I can't input it when I open it on other computers. You can find a Chinese who should help you reproduce your mistakes.

**Comment by maidou883** [comment]
@liyasthomas 
![image](https://user-images.githubusercontent.com/48854556/147261293-8d819ec6-6932-4a39-99a1-264158bdac50.png)
The content in the red box is redundant. When I input the content in the green box, I will automatically fill in the content in the red box. I only need the content in the green box, not the content in the red box

**Comment by maidou883** [comment]
@liyasthomas 
It's already 11:00 p.m. on my side. I'll have a rest first. If there's a problem, I'll continue to communicate tomorrow

**Comment by maidou883** [comment]
Why use div instead of input here

**Comment by liyasthomas** [comment]
Native `input` fields don't support enabling features like style for environments etc.

<img width="1098" alt="Screenshot 2021-12-24 at 7 11 34 AM" src="https://user-images.githubusercontent.com/10395817/147305486-171c47ab-1d76-4659-a58c-2367c8e84aa4.png">

**Comment by maidou883** [comment]
I'll send you an email and a video later. You'll see the recurrence of the error.

**Comment by maidou883** [comment]
@liyasthomas The mail has been sent successfully.
Title Recurrence error.

**Comment by zsxeee** [comment]
Reproduced with Microsoft IME with Chinese and Japanese.
![image](https://user-images.githubusercontent.com/18413220/147308834-c68f48f2-3faf-4664-b334-2e6bc10476d5.png)
![image](https://user-images.githubusercontent.com/18413220/147309008-da33ebb9-a1c5-4f30-8802-b6268eecd5fc.png)

**Comment by liyasthomas** [comment]
> @liyasthomas The mail has been sent successfully. Title Recurrence error.

I've not received the mail. You can share the video here in comments or send it to support@hoppscotch.io

**Comment by liyasthomas** [comment]
> Reproduced with Microsoft IME with Chinese and Japanese. ![image](https://user-images.githubusercontent.com/18413220/147308834-c68f48f2-3faf-4664-b334-2e6bc10476d5.png) ![image](https://user-images.githubusercontent.com/18413220/147309008-da33ebb9-a1c5-4f30-8802-b6268eecd5fc.png)

I'd appreciate if you can give proper steps to reproduce it.

**Comment by maidou883** [comment]
Sent successfully support@hoppscotch.io

**Comment by zsxeee** [comment]
> > Reproduced with Microsoft IME with Chinese and Japanese. ![image](https://user-images.githubusercontent.com/18413220/147308834-c68f48f2-3faf-4664-b334-2e6bc10476d5.png) ![image](https://user-images.githubusercontent.com/18413220/147309008-da33ebb9-a1c5-4f30-8802-b6268eecd5fc.png)
> 
> I'd appreciate if you can give proper steps to reproduce it.

If you are using Windows, you can add a keyboard with:

> Windows Settings | Time & Language | Language | Add a Language | Search & select "Chinese（Any）" or "Japanese"
> Then input in "中" mode in Chinese or "あ"/"ア" mode in Japanese

**Comment by liyasthomas** [comment]
cc @AndrewBastin can you check if it's reproducible at your end? Refer above steps.

If it's reproducible, then it got something to do with the `EnvInput`comment and the way we parse UTF-8 characters in it.

**Comment by kidonng** [comment]
I was about to report the same issue and almost ignored this one due to its title being written in Chinese but for I can read it.
Back to the topic, this seems to be related to the fact that [`<SmartEnvInput>`](https://github.com/hoppscotch/hoppscotch/blob/724e1e4c8f8e60d7e7e381cc0f1f7cb7e8388221/packages/hoppscotch-app/components/smart/EnvInput.vue)

**Comment by kidonng** [comment]
FYI, you don't have to use an actual CJK IMEs to reproduce the bug. Regular. IMEs on mobile should trigger it pretty easily.

This is how the prediction/pre-edit/composition should look like normally:

https://user-images.githubusercontent.com/44045911/147529525-37406a43-ce3b-46af-ab78-6f40a72ffd87.mp4

In `<SmartEnvInput>`, the prediction is interruptted and resumed on every keystroke, and it can even result in inputted texts being duplicated:

https://user-images.githubusercontent.com/44045911/147529692-110ca73d-1d6f-4761-b2d8-0dff5aa796e4.mp4

**Comment by AndrewBastin** [comment]
@kidonng thank you for the detailed info!

The EnvInput system is a bit complex system so this might take a bit of time to get fixed.

Meanwhile will a toggle setting to disable EnvInput suffice for the meantime ? (cc: @liyasthomas)

Also, we would really love help if you are able to fix it as I personally don't have experience working with IMEs.

**Comment by liyasthomas** [comment]
It would be great if you can test this deploy preview and see if the error persists or not: https://61d6d0188edaf8000885e501--hoppscotch.netlify.app/

cc: @maidou883, @zsxeee, @kidonng

**Comment by zsxeee** [comment]
> It would be great if you can test this deploy preview and see if the error persists or not: https://deploy-preview-2057--hoppscotch.netlify.app

LGTM on Microsoft IMEs

**Comment by kidonng** [comment]
Late for replying but unfortunately I was busy and didn't got the time to submit a fix myself.

The related PR works great, however one issue still remains: backspace key on IMEs can still be funky:

https://user-images.githubusercontent.com/44045911/148494668-7e0f693d-da80-491f-b5d8-0a1f4897d37d.mp4
