### ISSUE TITLE
[bug]: Team registration is not working

### ISSUE THREAD

**Issue by adityakoushikr11** [hoppscotch/hoppscotch#2043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I logged into the hoppscotch account and went to my profile section and tried to create team, i am getting the below error.
`{
  "errors": [
    {
      "message": "auth/fail",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createTeam"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}`

I am also attaching the screenshot of the error.
![Screenshot (39)](https://user-images.githubusercontent.com/33486608/147468079-2c468d3e-0b0b-4dc3-a296-4cb641675d75.png)

we are using `https://api.hoppscotch.io/graphql` URL to connect to graphql server.

### Steps to reproduce

1. https://apidocs-4608a.firebaseapp.com/
2. Create a new account and login with your email.
3. Go to profile and select teams tab and click on create new team button, a popup will appear and ask you to enter team name, provide a name and click on Save, you will see that team is not getting created.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Teams feature is not available for self hosted instance at the moment, hence closing. Stay tuned for the Hoppscotch self-hostable insurance support is feel free to use the cloud version on Hoppscotch.io.

**Comment by adityakoushikr11** [comment]
@liyasthomas Where do we get the cloud version of hoppscotch

**Comment by liyasthomas** [comment]
On [Hoppscotch.io](https://hoppscotch.io). Sign  up and enjoy the Team features.

**Comment by leandro-toledo-uux** [comment]
@liyasthomas , is there a plan to have teams feature for self-hosted instance?

**Comment by liyasthomas** [comment]
We do have plans to support collaborative features like Teams to our self-hostable instances. Follow the project on GitHub for the product updates.
