### ISSUE TITLE
[bug]: Websocket Server is not working

### ISSUE THREAD

**Issue by rakshit087** [hoppscotch/hoppscotch#2049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I am trying to connect to Websocket connection on
```wss://hoppscotch-websocket.herokuapp.com```
It is giving me error
![image](https://user-images.githubusercontent.com/50898928/147690279-efcd7f39-a07b-494b-807e-50032cebc4b4.png)

### Steps to reproduce

1. Go to [Hoppscotch](https://hoppscotch.io/).
2. Select Realtime.
3. Select WebSocket or Socket.IO.
4. Click Connect.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This was possibly due to our Heroku server being idle for a while. This has been resolved now.
