### ISSUE TITLE
[bug]: Cannot read properties of undefined

### ISSUE THREAD

**Issue by nesar77** [hoppscotch/hoppscotch#2055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using the web client I try to send a GET or POST I'm not able to get a response

### Steps to reproduce

1. Open the web client
2. Set an environment
3. Open a collection
4. Create a Request
5. Check settings 
6. Send the Request
7. On the browser console I get 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Object.K [as lengthBytesUTF8] (377b56c.modern.js:2)
    at A.newHeapCharPointer (377b56c.modern.js:2)
    at A.evalCode (377b56c.modern.js:2)
    at 377b56c.modern.js:2
    at 377b56c.modern.js:2
    at 377b56c.modern.js:2

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Can you share your request setup to reproduce this error?

**Comment by nesar77** [comment]
Hi @liyasthomas,
the endpoint value is https://geo.portalecomuni.net/devrest and the request is https://hopp.sh/r/449ETKC8dOdz

**Comment by AndrewBastin** [comment]
Should be fixed in https://github.com/hoppscotch/hoppscotch/commit/ac979239e851ce30653e26004833231dde48756c
