### ISSUE TITLE
[feature]: explicit UI for protocol (e.g. http / https)

### ISSUE THREAD

**Issue by slifty** [hoppscotch/hoppscotch#2058]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Thank you for the wonderful project!

As a new user it took me a little while to figure out why my calls to `localhost` or `127.0.0.1` weren't working, even with the browser extension installed.  I eventually tried typing `http://` before the domain and it worked.

I think of the URL input the same way as I think of the browser URL input (but with the ability to specify method, body, header, etc).  Given that, I was expecting the request to work even without an explicit specification of `http://`.

I appreciate there may be a use case for explicitly not having a protocol specified in a request, so maybe this could be accomplished with a new UX element that provides a select dropdown, defaulting to http, providing `http` and `https` as pre-provided values, but also capable of freeform input and editing as a text field?

### Why should this be worked on?

It seems safe to bet that 99.99% of the time your users are going to want either http or https prefixed to their URLs.  A reasonable portion of new users (and even veteran users) will probably not realize / remember that `http` has to be manually entered as part of the URL the first time they try.

The space will have to be taken up regardless (since http:// will have to be manually typed), so having a UX element would:

1) Save keystrokes.
2) Communicate the requirement of a protocol selection.
3) Achieve that requirement without user input.

This will also help new users verify their setup faster -- right now a new user would have reasonable cause to assume that the failed call is due to misconfiguration of the browser extension (or server) as opposed to realizing that the request itself has simply been improperly formed.

**Comment by liyasthomas** [comment]
This seems like a genuine UX improvement though, I'd suggest not to introduce a drop-down for `http` and `https`. Instead, appending `https` by default to URLs without a protocol and or unless it's mentioned `http`. What do you think?

**Comment by slifty** [comment]
That makes sense (I was absolutely just spitballing regarding the drop down)

Regarding default of HTTP vs HTTPS -- phewf this is a tough one.

I appreciate the merit of HTTPS default from a security perspective.  That said if a primary use case is testing development environments I don't know if prepending https by default would address the concern raised by the issue. I think it's a common pattern to develop services over plain HTTP and rely on the production / deployment to provide an HTTPS wrapper / proxy around that service.

All this is to say that I don't think invisibly prepending an HTTPS default would fix the "I don't usually think to type http://localhost" problem.

---

Maybe *some* visual element would let us have both?

The benefit of some form of visual element is that it is explicit -- the user knows this will be served over http or https and therefore would be less likely to be (A) confused why it doesn't work or (B) unaware if a less secure protocol were the default <-- depending on which the default would be.

So, ditch the dropdown, but what about some kind of visual indication that a call is being performed over HTTPS similar to how browser URL bars function already? For instance when HTTPS is being used, a lock that when hovered over says "this request will be sent over https" <-- and in cases where a protocol wasn't specified it could include an extra line saying something like "(https is used when no protocol is specified)"

And an unlocked lock when HTTP is being used (also warning the user that their network traffic is not being encrypted, which might be a good note anyway).

^^ If you happened to pick `http` as the default you could do the same type of "http is used when no protocol is specified" message.

Any of that sound like it has potential?

**Comment by AndrewBastin** [comment]
@slifty @liyasthomas 

I am not a big fan of things like this being implicit. So what about a behaviour like this:

[The UI has no changes from the current UI]

1) User inputs the URL without a protocol definition
2) User clicks the send button

3) Hoppscotch checks the URL string and looks for the presence of the Protocol Definition
    - Nothing happens if a protocol is already defined
    - If a protocol is not defined
        - Check if the domain is a localhost domain (localhost/127.0.0.1) if so, append `http` protocol definition to the URL entry field
        - If not a localhost domain, append `https` protocol definition to the URL entry field

4) Hoppscotch runs the request with the updated URL entry

**Comment by liyasthomas** [comment]
Sounds good to me

**Comment by slifty** [comment]
Thank you @AndrewBastin that is a perfect improvement (and I appreciate the desire to not touch universal UI without really really good reason; thank you!)

**Comment by AndrewBastin** [comment]
@RishabhAgarwal-2001 you can work on this

**Comment by RishabhAgarwal-2001** [comment]
Sure!
