### ISSUE TITLE
[bug]: pasting stops working after repeating several times

### ISSUE THREAD

**Issue by kidonng** [hoppscotch/hoppscotch#2059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Pasting stops working after repeating several times. I can not verify if this only limited to mobile IMEs at the moment.

https://user-images.githubusercontent.com/44045911/148478542-0c48e582-67c2-4ba8-8a2f-c618649ad63a.mp4

### Steps to reproduce

1. Open Hoppscotch
2. Input some text
3. Select all text in the input
4. Paste
5. Repeat 3 4
6. Pasting eventually stopped working

Note: the IME in the screencast is Gboard (for Android), if it's worth mentioning. 

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This doesn't seem to be an issue directly related to Hoppscotch. I can reproduce this behavior in other websites (fox ex: GitHub's search bar etc). Most probably this had something to do with Gboard or the client-side IMEs.

There's no error while I used another IME on Android. Hence closing.

**Comment by kidonng** [comment]
Thanks for investigating! I just noticed this seems to happen on websites only, not for inputs in native apps. Will try report to Gboard.
