### ISSUE TITLE
Unable to load https://hoppscotch.io/ Microsoft Edge

### ISSUE THREAD

**Issue by eaccmk** [hoppscotch/hoppscotch#2062]
I am unable to load https://hoppscotch.io/ Microsoft Edge 
- MS Edge Version 96.0.1054.62 (Official build) (64-bit) 👎 
- On Chrome, it works like a charm 👍 

![image](https://user-images.githubusercontent.com/19251569/148632350-60e4b866-110c-45e6-b3b3-3ecf2383f428.png)

> Here are the compressed logs 

```javascript
Navigated to https://hoppscotch.io/
03fafdf.modern.js:1 
        
       WebSocket connection to 'wss://api.hoppscotch.io/graphql' failed: WebSocket is closed before the connection is established.
(anonymous) @ 03fafdf.modern.js:1
(anonymous) @ c51e877.modern.js:2
.......
a03f6db.modern.js:2 no native wasm support detected
a03f6db.modern.js:2 
        
       no native wasm support detected
....
ReferenceError: WebAssembly is not defined
    at eA (a03f6db.modern.js:2)
    at Object.o [as default] (a03f6db.modern.js:2)
    at Object.<anonymous> (a03f6db.modern.js:2)
    at n (077ff70.modern.js:1)
    at Module.<anonymous> (a03f6db.modern.js:2)
    at n (077ff70.modern.js:1)
    at Module.<anonymous> (a03f6db.modern.js:2)
    at n (077ff70.modern.js:1)
Promise.catch (async)
...
(anonymous) @ 03fafdf.modern.js:1
03fafdf.modern.js:1 
        
       WebSocket connection to 'wss://api.hoppscotch.io/graphql' failed: WebSocket is closed before the connection is established.
..
        
       GET https://www.googletagmanager.com/gtag/js?l=dataLayer&id=G-BBJ3R80PJT net::ERR_NAME_NOT_RESOLVED
(anonymous) @ c51e877.modern.js:2

(anonymous) @ 03fafdf.modern.js:1
```

**Comment by liyasthomas** [comment]
I can't reproduce this behavior in the latest Edge version `97.0.1072.55 (Official build) (arm64)` on the macOS M1 machine. Try to clean the cache of `hoppscotch.io` and reload again. If the issue persists, try updating the browser to the latest version.

cc: @AndrewBastin is this reproducible in Windows OS at your end?

Screenshot:

<img width="1440" alt="Screenshot 2022-01-09 at 1 52 42 PM" src="https://user-images.githubusercontent.com/10395817/148674838-9c7006f1-fdba-48ef-9b1f-9ec334275b6f.png">

**Comment by AndrewBastin** [comment]
This issue is due to the fact that by default Edge's "Secure Mode" disables WebAssembly to the pages.

Hoppscotch uses WebAssembly to implement it's scripting sandbox.

More info and ways to resolve it are documented here: https://github.com/microsoft/vscode/issues/137704

**Comment by AndrewBastin** [comment]
@eaccmk if the above solution works for you then we can close this issue.

Although a failsafe for WASM might be cool in the future.

cc: @liyasthomas

**Comment by eaccmk** [comment]
Thanks for super fast response 🚀  @AndrewBastin  and @liyasthomas 

- It seems like a MS Edge issue for Windows users

> Workaround and it works:
- Go to `edge://settings/privacy/secureModeExceptions` on your MS Edge browser (Windows)
- Click **Add a site** button and add `https://hoppscotch.io/` to List of Exceptions

![image](https://user-images.githubusercontent.com/19251569/148678367-eb983c45-7293-4fef-9a7b-a1a2cfa4c34e.png)

and then it works cool ! 🎉  

Let's `CLOSE` this nasty Issue ❌

**Comment by AndrewBastin** [comment]
@eaccmk thank you! Means a lot!

But just for letting users know what is the issue and to handle this error more gracefully, we are planning to add support for proper in app errors and a failsafe to let the users know of the issue.
