### ISSUE TITLE
[feature]: curl can't parse the url without the protocol header correctly.

### ISSUE THREAD

**Issue by watchingfun** [hoppscotch/hoppscotch#2066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

anwarulislam:bug/body-missing-onimport https://github.com/hoppscotch/hoppscotch/pull/2048
I have cleared the cache and reloaded, but I still can't parse the request body. In addition, I can't parse the url without the protocol header correctly.

### Why should this be worked on?

curl -X PUT "localhost:9200/megacorp/employee/1?pretty" -H 'Content-Type: application/json' -d'
{
    "first_name" : "John",
    "last_name" :  "Smith",
    "age" :        25,
    "about" :      "I love to go rock climbing",
    "interests": [ "sports", "music" ]
}
'

**Comment by liyasthomas** [comment]
I guess you should add a space between `-d` and `'`.

This cURL works for me:
```
curl -X PUT "localhost:9200/megacorp/employee/1?pretty" \
-H 'Content-Type: application/json' \
-d '{
"first_name" : "John",
"last_name" : "Smith",
"age" : 25,
"about" : "I love to go rock climbing",
"interests": [ "sports", "music" ]
}'
```

Keeping this issue open to fix protocol being `null` if empty.

**Comment by watchingfun** [comment]
sorry, my bad,miss space

**Comment by AndrewBastin** [comment]
@kyteinsky do you want to pick this issue up ?

**Comment by kyteinsky** [comment]
> @kyteinsky do you want to pick this issue up ?

@AndrewBastin

With pleasure.<br>Just to make sure I understand the issue here, the protocol has to be inferred and prepended if not given, right?

If it's
- localhost (and local ip?) => http
- anything else (not mentioned) => https

<br>

> Keeping this issue open to fix origin being null if empty.

And which origin is being talked about here?

**Comment by AndrewBastin** [comment]
@kyteinsky 

> And which origin is being talked about here?
Its: https://developer.mozilla.org/en-US/docs/Web/API/URL/origin

We use the URL API to parse the URL which gets imported from cURL but it seems to not be working correctly.


Also another possible implementation, we could rewrite the entire cURL Importer system under [insomnia-importers](https://www.npmjs.com/package/insomnia-importers) which will be more better overall. We can implement it as a separate importer in our new Importer system (refer: https://github.com/hoppscotch/hoppscotch/tree/main/packages/hoppscotch-app/helpers/import-export). If you have any doubts, feel free to ping me!

Assuming you are picking this up, I am assigning it to you
