### ISSUE TITLE
[bug]: Unable to Create Teams 

### ISSUE THREAD

**Issue by shanushawanjha** [hoppscotch/hoppscotch#2068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have deployed the Hoppscotch on my server using docker compose, as mentioned I have changed google's credentials in .env file, Created firestore database, and everything else is working fine but when to try to load teams or create a team it not working it is showing "something went wrong" message. When I checked in the console I got an error " Uncaught (in promise) FirebaseError: Missing or insufficient permissions." and also their error in the network tab while calling an  API:

URL: https://api.hoppscotch.io/graphql

Request: {"query":"query MyTeams {\n  myTeams {\n    id\n    name\n    myRole\n    ownersCount\n    teamMembers {\n      membershipID\n      user {\n        photoURL\n        displayName\n        email\n        uid\n        __typename\n      }\n      role\n      __typename\n    }\n    __typename\n  }\n}\n","operationName":"MyTeams"}

Response: {"errors":[{"message":"auth/fail","locations":[{"line":2,"column":3}],"path":["myTeams"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null}

It is fine that separate deployment is calling this API (https://api.hoppscotch.io/graphql).

To fix the permission error I tried changing the rule still it is not working.
Can someone please help

### Steps to reproduce

1. Click on the profile
2. Go to the teams tab

### Environment

Deploy preview

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Collaborative feature like Teams is not available for self-hosted instances of Hoppscotch yet. Follow the project on GitHub to get product updates fit the upcoming self-hostable Hoppscotch instances.

**Comment by mcelotti** [comment]
I have the same problem. I was wondering if it would be possible to get the code you're running for https://api.hoppscotch.io/graphql. Thanks

**Comment by Sand33pSrinivasan** [comment]
@liyasthomas Is the collection feature available for self-hosted hopscotch instances?

**Comment by ecke78** [comment]
Is there any progress on this issue. Just deployed my own instance but it was really the team feature that made this a compelling solution.
