### ISSUE TITLE
[bug]: application/x-ww-form-urlencoded body gets an unexpected =undefined appended at its end

### ISSUE THREAD

**Issue by mateusmlo** [hoppscotch/hoppscotch#2070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to send a POST request that requires an application/x-ww-form-urlencoded body, it gets appended an =undefined at its end, which makes the request fail. 
![image](https://user-images.githubusercontent.com/13263031/149969870-fd4f31b1-968b-42a6-97c6-4ff8658efaf0.png)

### Steps to reproduce

Make a POST request that requires the informed content type and check its code. It may be happening on other request types too.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Fixed in https://github.com/hoppscotch/hoppscotch/commit/10a54d14c220f55874d0d482bfe3a9fd1e3b678d
