### ISSUE TITLE
[bug]: Untranslated string

### ISSUE THREAD

**Issue by urbalazs** [hoppscotch/hoppscotch#2075]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

The string "Untitled request" is not marked as translatable. It appears [6 places](https://github.com/hoppscotch/hoppscotch/search?q=%22Untitled+request%22) in the source code.

### Steps to reproduce

On the GUI, click the "Save" button. The default name of the new request is "Untitled request". No matter which language is set as interface language.

### Environment

Production

### Version

Cloud

**Comment by rakshit087** [comment]
Shall I add the translation under "error" of `en.json`? or something else?
