### ISSUE TITLE
[feature]: use env variables in environments

### ISSUE THREAD

**Issue by Schloemicher** [hoppscotch/hoppscotch#2076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![image](https://user-images.githubusercontent.com/17760063/150327069-15b67398-c86e-499d-b9a8-ca500a95b62c.png)

![image](https://user-images.githubusercontent.com/17760063/150327205-4ca4da4d-7c3f-4636-adb7-7c6b185d3bca.png)

result: `<<base>>` resolves "test.example.org" if environment "Host 1" is chosen
result: `<<base>>` resolves to ".example.org" if environment "Global" or no environment is chosen

### Why should this be worked on?

- The other environments are much easier to maintain
- No workaround with Pre-request skripts in each Request needed

**Comment by liyasthomas** [comment]
Hi @Schloemicher, thank you for this feature request. This sounds like a good-to-have feature.

**Comment by liyasthomas** [comment]
Implemented in https://github.com/hoppscotch/hoppscotch/commit/7fc757d79469d7bb72d8737aa87387fc693e4ac5, hence closing.
