### ISSUE TITLE
[feature]: Support exporting single collection

### ISSUE THREAD

**Issue by kitch** [hoppscotch/hoppscotch#2078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Today when you do an export it exports JSON for ALL of the requests/collections in hoppscotch. It would be nice to be able to export just a single collection.

### Why should this be worked on?

It's a common use case to share collections between team members. However, it's tedious to export all collections and then edit the json to just pull the collection of interest when sharing with others.

**Comment by liyasthomas** [comment]
Users can now export and import a single collection. Implemented in https://github.com/hoppscotch/hoppscotch/commit/93ccf5dcf653f59aff69b46d4524cd125aa96768.

Click on the "Options" menu on any Collection / Folder > "Export"

Here's a screenshot:

![localhost_3000_](https://user-images.githubusercontent.com/10395817/152894316-bcc6e1e7-519a-4c65-a332-b7b6ca81012f.png)
