### ISSUE TITLE
[bug]: Tests not updating with faulty code

### ISSUE THREAD

**Issue by Xairoo** [hoppscotch/hoppscotch#2079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I add a faulty test condition, it won't get updated.

```js
pw.test("Status code is 200", ()=> {
    pw.expect(pw.response.status).toBe(200);
});

pw.test("Response is an array", () => {
  const tasks = pw.response.body.json();
  pw.expect(tasks).toBeType("array");
});
```

Results in an outdated (previous, previous, previous, ...) title and test condition.
For example above code shows me twice `Expected '200' to be '200'` (I had `pw.expect(pw.response.status).toBe(200);` in the second test before).

### Steps to reproduce

- Add 2 tests
- Run the request
- Check the test results
- Edit the second test
- Run the request
- Check the test result

### Environment

Production

### Version

Cloud

**Comment by Xairoo** [comment]
That was caused because of a bad written test condition.

This works:
```
pw.test("Response is an object", () => {
  const tasks = pw.response.body;
  pw.expect(tasks).toBeType("object");
});
```

But having a faulty test will trigger this issue, handling such issues could be improved.

**Comment by AndrewBastin** [comment]
Acknowledged, we will be looking into this issue.

**Comment by AndrewBastin** [comment]
@RishabhAgarwal-2001 do you want to pick this up ?

**Comment by RishabhAgarwal-2001** [comment]
Sure! You can assign it to me.
