### ISSUE TITLE
Import into team collection error "request entity too large"

### ISSUE THREAD

**Issue by pedromvu** [hoppscotch/hoppscotch#2085]
Hi, I am hoping this might be due to something on my side as I couldn't find anyone else with the problem, but for me this is happening when trying to import collections from as low as 145Kb (haven't tested at what point it starts working)

I can import the files to my collections, but if I want to import be it from my collections, postman, github gist or hoppscotch file it's always the same error, I don't get any error on the UI, but the dev tools show: 

`{"statusCode":413,"message":"request entity too large"}`

Tried with both Chrome and Firefox

**Comment by AndrewBastin** [comment]
This issue happens when you are dealing with Hoppscotch for Teams right ?

Can you also let me know the number of collections/requests/folders which you have in the collection you are trying to import

**Comment by pedromvu** [comment]
Yes only on Teams,

The smallest file I have failing is just one collection, 9 folders, 43 endpoints, 145Kb in size

**Comment by AndrewBastin** [comment]
@pedromvu  Sorry for the delay. But, on the bright side we believe we have resolved this issue with a recent update.

Please check if your issue still persists.

Meanwhile, I am closing this issue.

**Comment by pedromvu** [comment]
I just tried and it worked, thanks a lot
