### ISSUE TITLE
[feature]: Support for Path Variables

### ISSUE THREAD

**Issue by christopheblin** [hoppscotch/hoppscotch#2086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I import the petstore collection and I try to use a method with a path variable inside, the app does not provide an easy way to provide them

![Capture d’écran 2022-01-25 133509](https://user-images.githubusercontent.com/11044877/150978031-33b2b514-3756-49e0-8bb0-45f2c14d11fd.png)

I know I can simply override the url in the request, but this is not the "goal" 

What I'd like is that if I setup a parameter with the same name as in the path, it is used instead of being used as an additional query param

### Steps to reproduce

Import petstore openapi
Load the uploadFile request
Add a baseUrl env var (this will turn the baseUrl variable blue in the path)

=> when I provide a parameter with the name petId, it should be used in the path (and marked as blue)

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
@christopheblin Thank you for opening the issue. We need a mechanism for Path Variables. (Currently we have none).
We will have a look at this soon.

**Comment by ace-n** [comment]
Hey @AndrewBastin,

I might have some time to hack on this. 🙂 

One question though - do we know what the UI should look like? A few options come to mind:
- A section for **Query Parameters** at the top, _followed by_ a section for **Path Parameters**
- A single parameter section, with a new column that states (via words or an icon) whether something is a `query` or `path` parameter

Side note: for my team's use case, I may also need to add _environment variable_ support. (We need to switch between [not-entirely-deterministic] `DEV` and `PROD` URLs easily.) Happy to file another issue for that, but I wanted to **make sure it's in line with your vision for the project** before I start work on anything.

Note to self: [this file](https://github.com/hoppscotch/hoppscotch/blob/8197458a4bb32da1737e13bff4d0010a3be3a119/packages/hoppscotch-app/components/http/Parameters.vue) and `parameter_list` seem relevant.

**Comment by AndrewBastin** [comment]
Heyyo @ace-n!

Yeah, I guess, in terms of files you are right.

Although, in terms of UI, I think having them separated as separate lists in the same Parameters Tab makes more sense as it segregates both the Query Params and Params clearly. (@liyasthomas  thoughts ?)

We need to update the REST Request structure to allow for that option though, which it doesn't currently, so you will have to consider that as well.

**Comment by arthurspa** [comment]
Would be nice to have this feature impletented.

**Comment by shivamkj** [comment]
Waiting for this feature

**Comment by greguz** [comment]
Waiting for this. :eyes: 
May I help with something to speed up the release?

**Comment by odie5533** [comment]
Would love to see this get added!

**Comment by azvyae** [comment]
Bump this thread, still waiting this feature to be added in the UI

**Comment by azvyae** [comment]
@mwkcoding probably because that was the old UI, they refactored the UI for hoppscotch, so, we just have to wait

**Comment by Chinoman10** [comment]
Our team just migrated from Postman to Hoppscotch only to find out that this feature didn't exist on Hoppscotch yet...
The PR someone made in 2022 got merged into an internal branch and since then it's been ignored for over an entire year.

Apart from this missing feature, Hoppscotch has been great so far, but tbh was quite surprised about this.

Hoping this can become prioritized by the team since it's on their hands now 🤞

**Comment by carsonbird** [comment]
Ho-ly snap, I'm blown away that this isn't a feature. No negativity here, I appreciate what you guys are doing. I just wasn't expecting it. Anything I can do to help?

**Comment by liyasthomas** [comment]
We've prioritized this feature for the next major release candidate scheduled for the first week. Thanks for the feedback.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in a previous release candidate.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Comment by woutervanranst** [comment]
hi @liyasthomas  when will this go into the main release?

**Comment by Chinoman10** [comment]
> hi @liyasthomas when will this go into the main release?

It is already on the main release.

Here's an example:
![image](https://github.com/hoppscotch/hoppscotch/assets/8300763/c475db3f-0c55-4af2-a5e2-1114a4498de5)

**Comment by woutervanranst** [comment]
brilliant - apologies for the oversight

**Comment by sopi20** [comment]
Is this implementend only for rest endpoints and unavailable for graphql ? 😳

**Comment by MCterra10** [comment]
ty for adding this guys
