### ISSUE TITLE
[bug]: Unable to login via GitHub or Google - Selfhosted (Docker)

### ISSUE THREAD

**Issue by ChadDa3mon** [hoppscotch/hoppscotch#2089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have installed a new instance of Hoppscotch using the docker run command in the [documentation](https://github.com/hoppscotch/hoppscotch#docker). When I try to log in with GitHub or Google, it fails. Email also fails, but that is to be expected in this environment. 

With GitHub or Google, a window pops open and closes immediately, then I just get an error that says "Something went wrong"

I have tried this in Firefox, Firefox using incognito mode (to disable my addons) and in Edge (stock install with no addons). The issue is the same across all 3 instances. I've searched through your bugs and found similar issues but they were using Brave or Vivaldi. 

If I try to use the email option to login, I get the following error: "Firebase: Error (auth/requests-from-referer-http://10.X.Y.Z:3000-are-blocked.)."

This feels like it could be relevant, but again, I don't get that error when I try GitHub or Google. 

Looking at the logs in docker doesn't show anything useful either. 

```
> hoppscotch-app@2.2.1 start /app
> pnpm -r do-prod-start

Scope: all 5 workspace projects
packages/hoppscotch-app do-prod-start$ pnpm run start
packages/hoppscotch-app do-prod-start: > hoppscotch-app@2.2.1 start /app/packages/hoppscotch-app
packages/hoppscotch-app do-prod-start: > nuxt start
packages/hoppscotch-app do-prod-start: ℹ Listening on: http://172.17.0.2:3000/
packages/hoppscotch-app do-prod-start: ℹ Serving static application from dist/
```

### Steps to reproduce

Install from Docker (docker run --rm --name hoppscotch -p 3000:3000 hoppscotch/hoppscotch:latest)
Access main page at http://<ip>:3000
Try to login using GitHub or Google

Browsers: Firefox and Edge

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
As mentioned in our [development guidlines](https://github.com/hoppscotch/hoppscotch#developing), environment variables need to be updated with your own Firebase keys to make the Authentication system work - sample environment variables only work for the production channel.

[Read more about hosting Hoppscotch](https://github.com/hoppscotch/hoppscotch/wiki/Hosting#firebase-dependency).
