### ISSUE TITLE
[bug/feature]: Please dont use google translate for translations (fx danish)

### ISSUE THREAD

**Issue by lsv** [hoppscotch/hoppscotch#2090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Please dont allow google translated translations, google can not translate english to correct danish without context.

As you know, "body" can be multiple things on english, and yes, when google translated it uses body (as in human body), but that doesnt mean the same thing on danish. Actually there is no danish words for "body" (in HTTP body) - because most documentation for those things in danish, is just plain english.

"Send" and "Save" is also not correct translated.

It would be fine, if there was a place where you could actually change the language, but its auto redirects to danish, even when i try to remove /da from the url.

And as 99% of all danish developers speaks/reads english - it really doesnt need to be translated to danish, and seeing danish being used on this way, it is really laughable - and that just shows how little to none effort there are in danish translations.

So now im wondering, how is this on other languages - is that the same... Should I take this app serious, even if its looks pretty well? - Or should I just use the alternatives?

### Steps to reproduce

https://hoppscotch.io/da/

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Thank you for noticing the mistakes in our i18n translations. I'd appreciate it if you can help us to translate Hoppscotch into Danish. Please read [TRANSLATIONS guide](https://github.com/hoppscotch/hoppscotch/blob/main/TRANSLATIONS.md) for details on our [CODE OF CONDUCT](https://github.com/hoppscotch/hoppscotch/blob/main/CODE_OF_CONDUCT.md), and the process for submitting pull requests to us.

[Read our documentation on translating a language](https://docs.hoppscotch.io/i18n).
