### ISSUE TITLE
[feature]: DB-less and Declarative Configuration

### ISSUE THREAD

**Issue by WilliamPeralta** [hoppscotch/hoppscotch#2091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

DB-less and Declarative Configuration

### Why should this be worked on?

Hi Guys, I was looking through the documentation and I did not find anything, it would be nice to have the possibility through environment variable / config file or other to be able to initialize "hoppscotch" statically without db and in readonly mode (insert / update / delete collection disabled), very useful for API demos, documentation with playgroud etc. and to generate the config file from other projects.

Thank you.

PS. Idea taken from the "Kong" project
[Kong declarative config](https://docs.konghq.com/gateway-oss/2.4.x/db-less-and-declarative-config/)

**Comment by liyasthomas** [comment]
We've plans to decouple our DB instances and allow developers to use their own DB and back-end providers on a self-hostable instance. We have an active issue ticket on #1817.
https://github.com/hoppscotch/hoppscotch/issues/1817#issuecomment-1019733192
