### ISSUE TITLE
[feature]: More info from time / duration 

### ISSUE THREAD

**Issue by VladBullet** [hoppscotch/hoppscotch#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

More info from time / duration of request.
In postman, when you hover over the "time" label you will get a pop-up panel that shows you more details related to the time the request took to finish.
Check bellow picture for more info: 

![postman_duration_example](https://user-images.githubusercontent.com/50328451/151231688-4b8df01c-6e5e-4644-b9c9-ad78de8d07cc.png)

### Why should this be worked on?

I think this feature is very useful in Postman and it will be a great addition to Hoppscotch. Getting more information from the request can help you understand if there are bottlenecks "along the way".

**Comment by AndrewBastin** [comment]
Unlike Postman, Hoppscotch needs to run in the browser and hence we are limited by the platform restrictions that put forth to us. Hence we are not going to be tackling this until the platform allows for it.
