### ISSUE TITLE
Request body with content type [x-www-form-urlencoded] doesn't read variables as values

### ISSUE THREAD

**Issue by jopijuco** [hoppscotch/hoppscotch#2094]
Scenario:
Doing a POST request passing values on the request body and hoppscotch does not accept the variables.

<img width="977" alt="Screenshot 2022-01-28 at 11 01 59" src="https://user-images.githubusercontent.com/25496954/151536077-6192c276-0189-4a20-b4bd-72e5b2531cfd.png">

If I remove the variables and use the values directly the request is made.
Thank you.

**Comment by AndrewBastin** [comment]
@jopijuco this should be fixed in the latest update, let me know if it still persists
