### ISSUE TITLE
[bug]: Importing file into team collections is limited to 10 folders at any given level

### ISSUE THREAD

**Issue by pedromvu** [hoppscotch/hoppscotch#2096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I import a collection from any source into my team collections, I noticed that if I have more than 10 folders at any given level, they are cutoff at 10, I included a simple collection to reproduce it, it has 11 folders, importing to my collections is correct, but to teams is missing folder 11.

### Steps to reproduce

1. go to team collections
2. choose import from hoppscotch
3. add attached file [3a604d1b-cc3a-4978-aea0-79206b6e57f5.zip](https://github.com/hoppscotch/hoppscotch/files/7962865/3a604d1b-cc3a-4978-aea0-79206b6e57f5.zip)
4. Test collection is added with folders from 1 to 10
5. Inspect attachment, has folders from 1 to 11

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
We have identified this as a bug related to the way Team Collection Adapter works and we are working on fixing this issue. In the coming days.

Acknowledged.
