### ISSUE TITLE
[bug]: Search not working on team collections

### ISSUE THREAD

**Issue by pedromvu** [hoppscotch/hoppscotch#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have the same collection as My Collections and Team Collections, but when I type any letter in Team Collections everything is filtered out, as opposed to the search on My Collections tab

### Steps to reproduce

1. Add some test folder to teams collections
2. Add a test endpoint to the test collection
3. Try to search for it

### Environment

Production

### Version

Cloud

**Comment by ngocthua830** [comment]
I got the same problem, any update on this?

**Comment by smarteertech** [comment]
It would be great to have team collection search feature.

**Comment by jaysoni-ash42** [comment]
@pedromvu  can you add a video or a snapshot to illustrate the bug?

**Comment by brahadeeswaran** [comment]
Any update on the search collection feature? @liyasthomas

**Comment by arafth** [comment]
@liyasthomas please fix this bug. We want to use hoppscotch in our team.

**Comment by liyasthomas** [comment]
We're working on this feature. Expect the availability of Search in Team Collections in the next major release candidate.

**Comment by pankajmyt** [comment]
+1 Is there any date for this release candidate?
If its available as a PR will like to merge it into the last tagged release `2023.8.2`

**Comment by JoaoCipriano** [comment]
Hey @liyasthomas, is there any update on this bug?

**Comment by richardowijaya** [comment]
is it still disabled or not? cuz i pull it from docker and it is still disabled.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
