### ISSUE TITLE
[bug]: On minimizing, Team Collections are not able to view

### ISSUE THREAD

**Issue by rakeshkr22** [hoppscotch/hoppscotch#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On minimizing, Team Collections are not able to view. 

Full view SS :

![image](https://user-images.githubusercontent.com/10681753/151690516-4adb5fb1-fa7a-445d-b5e5-f6e7e61119f1.png)

Minimized view SS 1 :

![image](https://user-images.githubusercontent.com/10681753/151690546-fb129294-aeae-4cc5-88fc-dcbeb33ef1f0.png)

Minimized view SS 2 : 

![image](https://user-images.githubusercontent.com/10681753/151690561-6f1a21a1-aa3c-42ac-af02-d256d042d06b.png)

### Steps to reproduce

1. Minimize the PWA.
2. Resize the PWA.
3. Check Team Collections tab is able to view or not.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
You should select a Team from the drop down to view it's collections. And on mobile screens you can scroll horizontally to switch to Teams tab completely whenever it's overflowing the UI space.

**Comment by rakeshkr22** [comment]
@liyasthomas Thanks for the response. Yes, we can able to choose the team from drop down. But the case is that, the Team Collection tab name is not able to view on minimizing. 

**Steps to reproduce** (with SS)
Working on Team Collection in full view. 
![image](https://user-images.githubusercontent.com/10681753/151691533-072beecf-32a4-4d62-a5e3-041182ccae72.png)

Due to XYZ reason, minimized the PWA.
![image](https://user-images.githubusercontent.com/10681753/151691578-fb7fb2f0-08ce-4356-90d2-53157f3e0b7b.png)

Switched to My Collection testing in the same minimized view.
![image](https://user-images.githubusercontent.com/10681753/151691635-c44d97e1-7ba8-466a-b99a-baa032784894.png)

Wanted to continue testing on Team Collection from this minimized view. But not able to view the Team Collection in this case.

Note :- Yes, if we make it full screen we can able to access the Team collection tab.

**Comment by liyasthomas** [comment]
You can horizontally scroll on the tabs section, namely "My collections" and switch to Teams Collections.

**Comment by rakeshkr22** [comment]
@liyasthomas Hope you mentioned below section for a horizontal tab. 
![image](https://user-images.githubusercontent.com/10681753/151691910-3348503b-64a8-442e-a433-863d3c7b3c49.png)
But not able to find any horizontal tab there.

**Comment by liyasthomas** [comment]
Here's a demo on how to scroll horizontally on tabs:

https://user-images.githubusercontent.com/10395817/151692765-870a2ce6-5e1a-4013-bf8a-4f65cbe34548.mp4

**Comment by rakeshkr22** [comment]
@liyasthomas Thanks for the response with a video demo. 
Closing the bug.
