### ISSUE TITLE
POST body does not allow URL as a parameter [bug]: 

### ISSUE THREAD

**Issue by Zaffer** [hoppscotch/hoppscotch#2099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I send a POST with a URL encoded parameter the api rejects it as the Hoppscotch encode it a second time.
![image](https://user-images.githubusercontent.com/51871197/151714410-0f142210-a1cb-48c6-8a18-7c714eb78cbc.png)

Given this set of input: 

![image](https://user-images.githubusercontent.com/51871197/151714313-61f654a7-7f66-4e5a-a04f-d1b3afc55be7.png)

The problem is that a URL has semi colon ":" so this gets removed from the paramater as it treats it like a key: value symbol.

I would expect there to be RAW input for posting and allow to make a perfectly reasonable POST such as the following:

`// Line breaks are for legibility only.

POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id=535fb089-9ff3-47b6-9bfb-4f1264799865
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret=qWgdYAmab0YSkuL1qKv5bPX
&grant_type=client_credentials`

### Steps to reproduce

> POST
> Body
> Content-Type: application/x-www-form-urlencoded
> param = 'test' : value = "https://example.com"

the value field with automatically remove the semi-colon

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Fixed in https://github.com/hoppscotch/hoppscotch/commit/819b111383b85592aa2cf3dc83f3c41ad851f8eb, hence closing.
