### ISSUE TITLE
[bug]: XSS TRIGGERED

### ISSUE THREAD

**Issue by krishnadevpmelevila** [hoppscotch/hoppscotch#2103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I add ```<img src=x onerror=prompt(9)>``` on the [profile page](https://hoppscotch.io/profile) as profile name, It will trigger XSS. 

![image](https://user-images.githubusercontent.com/66047990/151747496-ea698a74-0dd8-44ce-ad47-02007a3656c0.png)

![image](https://user-images.githubusercontent.com/66047990/151747599-bdf0fb3c-0f6a-4b0a-8331-d5632562f45b.png)

Anyway, it is not a security issue as it is happening inside the user profile and no other user will affect it.But still, it is a bug.

### Steps to reproduce

1. Login
2. Go to [profile page](https://hoppscotch.io/profile)
3. Enter name as  ```<img src=x onerror=prompt(9)>```
4. Refresh the page

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
Thank you for the report @krishnadevpmelevila !

We have patched it in the latest build which should be live soon.

By the way seeing that you are a security researcher, for vulnerability disclosure it is the best to reach out to us over at [support@hoppscotch.io](mailto:support.hoppscotch.io) so we can resolve this easily and quickly.

**Comment by krishnadevpmelevila** [comment]
Sure, Thank you for accepting my report, If I found any more bugs I will directly mail to the above-mentioned mail id
