### ISSUE TITLE
[bug]: when use paste an url with existing field, and undo it url comes besides the url instead of replacing the existing one

### ISSUE THREAD

**Issue by pkshefi** [hoppscotch/hoppscotch#2107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![Uploading Screen Shot 2022-02-06 at 12.21.22 PM.png…]()

### Steps to reproduce

1. Got to panel
2. Test with some GET https://www.anapioficeandfire.com/api/books
3. Delete the url and try some other test
4. Undo the current request 

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
The screenshot is not visible, and I'm having trouble understanding this issue. Please re-open and describe the issue with a screenshot.
