### ISSUE TITLE
[feature]: New request button 

### ISSUE THREAD

**Issue by pkshefi** [hoppscotch/hoppscotch#2108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As a user i will be able to add a new request with a button

### Why should this be worked on?

As a user i will be able to add a new request with a button, 
while tapping the button i will get to see cleared fields.  
- easy of use
- can have quick query request as fast

**Comment by liyasthomas** [comment]
You can reset the current request setup to default state (`GET https:echo.hoppscotch.io`) by clicking the "Clear all" button under "Send options (send drop-down)". Attached is the screenshot.
![Screenshot 2022-02-06 at 3 44 45 PM](https://user-images.githubusercontent.com/10395817/152676270-542b85d5-312b-48f5-b273-a7aee2bffac6.png)
 
You cal also use the shortcuts:

<kbd>⌘</kbd> + <kbd>I</kbd> in Mac

<kbd>Ctrl</kbd> + <kbd>I</kbd> in PC
