### ISSUE TITLE
env variables not working in Authorization Type OAuth 2.0

### ISSUE THREAD

**Issue by dschmucki** [hoppscotch/hoppscotch#2113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to use env variables to configure the OAuth 2.0 authorization type, the variables will only be recognized for the field "Token".

See:
![image](https://user-images.githubusercontent.com/1675109/152766979-e7167db5-0792-48af-9ae4-f74b9f01f87f.png)

### Steps to reproduce

1. Set up a new environment
2. Add variables
3. Configure Authorization with type OAuth 2.0
4. Use variables in all fields

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Seems like you have not chosen an environment. Please go to the environments section and click on "No environment" drop-down to choose the environment that contains the `token` variable.

Here's a screenshot:

![Screenshot 2022-02-07 at 3 43 38 PM](https://user-images.githubusercontent.com/10395817/152768369-d10e6e57-c215-4e9a-af92-110ca60731b4.png)

**Comment by dschmucki** [comment]
Same with an active environment:

![image](https://user-images.githubusercontent.com/1675109/152769399-cacce3de-30eb-4c65-8131-0e952e6b8313.png)

**Comment by MartThijssenIExperts** [comment]
Hi, what is the current status of this issue?
