### ISSUE TITLE
[feature]: Support rsocket.js

### ISSUE THREAD

**Issue by sudongyuer** [hoppscotch/hoppscotch#2114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Support rsocket.js
I write a web devtool to support roskcet.js , but i think this repo to support it is better~
rsocket.js web devtool repo:https://github.com/HaiyaoTec/rsocketMan
![image](https://user-images.githubusercontent.com/76603360/153713126-bdcdc116-bcf4-46c8-a639-bd015fd4622d.png)

### Why should this be worked on?

 Rsocket.js is hard to debug and there are no good Web devtools,i write one,but  i thought it would be good to integrate devtool of rsocket.js into this project

**Comment by liyasthomas** [comment]
Hi @sudongyuer, your tool looks interesting and seems like a nice utility to debug `rsocket.js` connections. However, we don't have plans to add support to rsocket.js in Hoppscotch. I'll keep an eye out for this issue ticket and see if there are enough requests from the community to start working on this. Meanwhile, I'll close this issue.
