### ISSUE TITLE
[bug]: cannot override Content-Type

### ISSUE THREAD

**Issue by lapo-luchini** [hoppscotch/hoppscotch#2121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I need to send a WSDL request as `text/xml`, but that's not available from the drop-down types, so I chose `application/xml` and tried overriding it in the Headers section. The request is still sent as `application/xml` and not with the header I requested.

### Steps to reproduce

1. create a POST request
2. under "body" select `application/xml` and paste an XML content
3. under "headers" add `Content-Type: text/xml`
4. send request
5. check Network to see that `application/xml` was still used as a type

### Environment

Production

### Version

Cloud

**Comment by mogarick** [comment]
I'm in a similar situation.

I've just discovered Hoppscotch but the first test was for getting an AWS Cognito token.

For that purpose I need to send a `Content-Type: application/x-amz-json-1.1`. 
Sadly Hoppsotch overrides my header with the on the Body tab (In my case `Content-Type: application/json` so I get a Cognito error:

```
{
  "Output": {
    "__type": "com.amazon.coral.service#UnknownOperationException"
  },
  "Version": "1.0"
}
```

Is this considered a high priority bug to solve or I better get back to Postman and come back in a few weeks/months?

Thank you in advance for the attention :)

**Comment by leoryu** [comment]
I also met this issue.

In my case, I want to send with header `Content-Type: application/merge-patch+json`, but this header will be overwritten with the header in `Body` section.
