### ISSUE TITLE
[feature]: template in URL like {{hostname}}

### ISSUE THREAD

**Issue by igor-betin** [hoppscotch/hoppscotch#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It works in postman

### Why should this be worked on?

It's an obvious feature, to change server name with changing environment
It's the only missing feature preventing me from migrating from Postman at the moment

**Comment by igor-betin** [comment]
@liyasthomas 
Then it's a different issue - when importing collections from postman, such URLs are blank

**Comment by liyasthomas** [comment]
Can you provide a sample file and instructions to reproduce the issue?

**Comment by igor-betin** [comment]
@liyasthomas opened bug for it, will provide sample collection soon
