### ISSUE TITLE
[bug]: Team member see team collection if email is not lowercase

### ISSUE THREAD

**Issue by binamkayastha** [hoppscotch/hoppscotch#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Added my friend to a team collection with an uppercase email, but they couldn't see it until I re-added them with all lowercase values.

### Steps to reproduce

Invite new team member with uppercase email

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
@AndrewBastin, `GetInviteDetailsQuery` gives `team_invite/not_valid_viewer` error even if email is same but case-sensitive in `join-team.vue`.

**Comment by AndrewBastin** [comment]
Fixed in the latest backend patch.
