### ISSUE TITLE
[feature]: Add support for PATCH method to OpenAPI importer

### ISSUE THREAD

**Issue by kkk669** [hoppscotch/hoppscotch#2138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The current implementation of the OpenAPI importer seems to ignore PATCH requests when importing collections from an OpenAPI specification file. Please support it.

### Why should this be worked on?

Because the PATCH method is popular. For example, it's used by GitHub REST API, Google Cloud APIs, and LXD REST API.

**Comment by AndrewBastin** [comment]
Should be fixed in https://github.com/hoppscotch/hoppscotch/commit/fda9f2e84246c0c267621e6ffc5b6862c5fbd10f.

Closing the issue.

@kkk669 can you verify ?

**Comment by kkk669** [comment]
@AndrewBastin Sorry for the delay in replying. I've confirmed that it was now fixed. Thank you so much!
