### ISSUE TITLE
[bug]: Downloaded PDF files are malformed

### ISSUE THREAD

**Issue by micthiesen** [hoppscotch/hoppscotch#2139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I attempt to download a PDF response, the downloaded PDF cannot be rendered (it is blank). Compare this to downloading the PDF directly from the browser, and it works.

### Steps to reproduce

1. Make a GET request for a PDF file, like `https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf`
2. The raw response shown is the binary data
3. Download the response
4. When attempting to download the response, the PDF cannot be rendered (it is blank)

I've tried to compare the downloaded response to the actual PDF, and there are some slight differences, but I couldn't determine what the exact difference was. There might be some slight encoding difference or something.

Side note but it would be nice if instead of showing the raw binary data, a rendered PDF was shown.

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@micthiesen Can you confirm which interceptor are you using ? Are you using None ? Proxy or the Browser Extension ?

**Comment by micthiesen** [comment]
I tried with both the Browser Extension (FireFox) and also with it disabled

**Comment by micthiesen** [comment]
I also just tested with Chrome (no extension) and it has the same issue. I'm using MacOS

**Comment by AndrewBastin** [comment]
Should be fixed in e9dc7769ac5d9e05e8a664ec702958e8726a67e0

@micthiesen please confirm on your end and let me know. <3

Closing the issue.

**Comment by micthiesen** [comment]
@AndrewBastin it works! Thank you very much for the quick fix
