### ISSUE TITLE
Can't login via google, not any other way.

### ISSUE THREAD

**Issue by morfin** [hoppscotch/hoppscotch#2141]
hoppscotch-app@2.2.1
Using node v14.15.5
Mac High Sierra 10.13.6

Hi,

Running hoppscotch with 
`pnpm run dev` runs just fine but, I can't login with Google nor any other method. It throws this error:
`
FirebaseError: Firebase: Error (auth/invalid-api-key).
    FirebaseError webpack-internal:///../../node_modules/.pnpm/@firebase+util@1.4.3/node_modules/@firebase/util/dist/index.esm2017.js:850
    create webpack-internal:///../../node_modules/.pnpm/@firebase+util@1.4.3/node_modules/@firebase/util/dist/index.esm2017.js:878
    createErrorInternal webpack-internal:///../../node_modules/.pnpm/@firebase+auth@0.19.9_@firebase+app@0.7.17/node_modules/@firebase/auth/dist/esm2017/index-585b6059.js:581
    _assert webpack-internal:///../../node_modules/.pnpm/@firebase+auth@0.19.9_@firebase+app@0.7.17/node_modules/@firebase/auth/dist/esm2017/index-585b6059.js:585
    registerAuth webpack-internal:///../../node_modules/.pnpm/@firebase+auth@0.19.9_@firebase+app@0.7.17/node_modules/@firebase/auth/dist/esm2017/index-585b6059.js:9350
    registerAuth webpack-internal:///../../node_modules/.pnpm/@firebase+auth@0.19.9_@firebase+app@0.7.17/node_modules/@firebase/auth/dist/esm2017/index-585b6059.js:9367
    getOrInitializeService webpack-internal:///../../node_modules/.pnpm/@firebase+component@0.5.10/node_modules/@firebase/component/dist/esm/index.esm2017.js:295
    initialize webpack-internal:///../../node_modules/.pnpm/@firebase+component@0.5.10/node_modules/@firebase/component/dist/esm/index.esm2017.js:239
    initializeAuth webpack-internal:///../../node_modules/.pnpm/@firebase+auth@0.19.9_@firebase+app@0.7.17/node_modules/@firebase/auth/dist/esm2017/index-585b6059.js:699
    getAuth webpack-internal:///../../node_modules/.pnpm/@firebase+auth@0.19.9_@firebase+app@0.7.17/node_modules/@firebase/auth/dist/esm2017/index-585b6059.js:9420
 `

**Comment by liyasthomas** [comment]
Make sure you've followed the [development guidelines in readme](https://github.com/hoppscotch/hoppscotch#developing).

You need to rename [`.env.example`](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/.env.example) file found in packages/hoppscotch-app to `.env`

And restart the local server.

Closing this issue, kindly re-open if the issue still persists.
