### ISSUE TITLE
[bug]: Chrome page is no response

### ISSUE THREAD

**Issue by Sun-FreePort** [hoppscotch/hoppscotch#2144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, look at:

![147023CC-2E62-452c-98C6-2EE10E655CF9](https://user-images.githubusercontent.com/19473984/156287967-241eddb0-8422-47fb-a3e9-66d02709a03c.png)

The error has occasionally happening.

### Steps to reproduce

Nop, I not find any settled step, has some thread:

1. the error show when edit api \ use team -- maybe, because I only use team.
2. the error not show “open page and no do anything”.
3. the error is memory weak bug, this more info:

when page start time, the memory occupy is 150k, cpu use is 20 value, so....this is CPU occupy bug?

![Dingtalk_20220302115630](https://user-images.githubusercontent.com/19473984/156292183-b4f92091-b122-41b1-b5a0-8f4e2068ef86.jpg)

### Environment

Production

### Version

Cloud

**Comment by Sun-FreePort** [comment]
And if you only choice API and open/close collection, the memory will up.

I restart page, and testing it, now is 330k memory occupy.....

**Comment by liyasthomas** [comment]
We're looking into this.

**Comment by AndrewBastin** [comment]
@Sun-FreePort If you could take a Performance snapshot and Memory heap snapshot through DevTools and could share it in the given email `support [at] hoppscotch [dot] io`. We can use that info to find the target more easily.

Here is an article on how to create a heap snapshot using DevTools [it is a bit old though]: [https://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art038](https://commandlinefanatic.com/cgi-bin/showarticle.cgi?article=art038)

This is how you can create a Performance Snapshot: [https://www.debugbear.com/blog/devtools-performance](https://www.debugbear.com/blog/devtools-performance)

**Comment by Sun-FreePort** [comment]
i try it, and the bug fixed.
