### ISSUE TITLE
[feature]: Remember selected collection and its state between launches

### ISSUE THREAD

**Issue by JacekAndrzejewski** [hoppscotch/hoppscotch#2146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Whenever I close PWA and open it again later I must reopen collection and expand all subfolders I'm working with every time.

### Why should this be worked on?

Clicking over multiple tabs (go from History to Collections, go to Team Collections, pick the collection) with every start is quite annoying. Especially when I have only one collection at all. Additionally I have to expand all folders every single time, which is even more annoying.

**Comment by anwarulislam** [comment]
@AndrewBastin can we implement this?

**Comment by AndrewBastin** [comment]
yup :)

**Comment by Tobychidi** [comment]
I support this feature as well. I noticed this almost immediately
