### ISSUE TITLE
[bug]: Firebase requests return 400

### ISSUE THREAD

**Issue by manu-urba** [hoppscotch/hoppscotch#2151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm running hoppscotch via docker-compose in a ubuntu server:
login via github or google doesn't work, although I've set correctly all the enviroment variables for firebase, I notice these network errors when I go on the web app:
![image](https://user-images.githubusercontent.com/39467342/157026883-b6a3d97a-ad9b-4741-9215-3fe9be08e453.png)
which seems just to be a request on 
- method: GET
- url: `https://firebase.googleapis.com/v1alpha/projects/-/apps/1:139411750115web:347f90192361efd70e99d6/webConfig`
- header: `x-goog-api-key`: `my-api-key`
here's the response
```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```

another error request:
- method: POST
- url: `https://firebaseinstallations.googleapis.com/v1/projects/postwoman-f96b6/installations`
- header: `x-goog-api-key`: `my-api-key
it gets the same response.

### Steps to reproduce

Firebase login doesn't work: I open the app on the browser and see network traffic.

### Environment

Deploy preview

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Self-hosting Hoppscotch instances are not supported at the moment. Follow the project on GitHub to stay updated with the product updates. Meanwhile kindly use our production deployment on [hoppscotch.io](https://hoppscotch.io).

Track the progress of self-hosting features on #1817, hence closing this issue.
