### ISSUE TITLE
[feature]: 希望能支持多个标签

### ISSUE THREAD

**Issue by zouliming** [hoppscotch/hoppscotch#2154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

希望能支持多个标签页，方便同时使用多个请求。
目前postman是有这个特性的，希望hoppscotch也支持。
Wish supuport Multiple tabs.

### Why should this be worked on?

work in multiple tabs is needed

**Comment by liyasthomas** [comment]
Hi @zouliming, thank you for raising this feature request. We already have another issue ticket to track the same feature with more discussions here: #690. Hence closing this issue.

Meanwhile, you can open two tabs in your browser and visit Hoppscotch.io, and access two different instances/requests in Hoppscotch at once.

<img width="1440" alt="Screenshot 2022-03-10 at 8 09 17 AM" src="https://user-images.githubusercontent.com/10395817/157577555-b8ea1493-43dc-44bc-b539-ad3bd47bea28.png">
