### ISSUE TITLE
[feature]: Add 'new request' at collection level

### ISSUE THREAD

**Issue by chaithanyaMarripati** [hoppscotch/hoppscotch#2156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- Add 'new request' at collection.
- Right now only a folder can be created inside of another collection.
- Would be nice have a new feature to add an empty request at collection level.

### Why should this be worked on?

- It is confusing at times while saving the request.
- It would be great if a new empty request would be instantiated when working on a new request.

**Comment by AndrewBastin** [comment]
@chaithanyaMarripati 

I am a bit confused with this feature request.

> Add 'new request' at collection.
You can already do this, you can save a request by clicking on the Save button and on the picker you can select a collection.

> Right now only a folder can be created inside of another collection.
Nope, as mentioned above you can save requests inside a collection as well.

> Would be nice have a new feature to add an empty request at collection level.
I don't exactly understand what you mean by this.

> It is confusing at times while saving the request.
I am not really sure about that, there is a Save button in the request right there near the "Send" button.

> It would be great if a new empty request would be instantiated when working on a new request.
I can't exactly understand what you mean by this. Empty Request ? Instatiated Where ?

Currently all request save operations happen through the Save Button (or the relevant shortcut/action). Maybe a button to create a New Request (similar to how a New Folder button) in the kebab menu in the collection tree can create a better visibility ? (@liyasthomas opinions ?)

**Comment by chaithanyaMarripati** [comment]
> Currently all request save operations happen through the Save Button (or the relevant shortcut/action). Maybe a button to create a New Request (similar to how a New Folder button) in the kebab menu in the collection tree can create a better visibility ?

yes this is what i mean, just like in postman.

**Comment by liyasthomas** [comment]
Introducing a "New request" action in collections/folders that save the current request setup to the corresponding location seems like a handy feature to me.

We'll track this issue to implement the same.
