### ISSUE TITLE
[bug]: Large numbers are wrong/rounded in JSON response view

### ISSUE THREAD

**Issue by arm32x** [hoppscotch/hoppscotch#2166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When JSON data containing large numbers is shown in the JSON response view, the numbers are incorrect (rounded).

JSON sent by server:
```json
{"an_integer":555555555555555555,"a_float":555555555555555555.555}
```
Shown in JSON view in Hoppscotch:
```json
{
  "an_integer": 555555555555555600,
  "a_float": 555555555555555600
}
```
What is expected to be shown:
```json
{
  "an_integer": 555555555555555555,
  "a_float": 555555555555555555.555
}
```

### Steps to reproduce

1. Create a JSON file with the following content:
    ```json
    {"an_integer":555555555555555555,"a_float":555555555555555555.555}
    ```
2. Run a static HTTP server (your choice)
3. Send a GET request to fetch your JSON file
4. Open the JSON response view and see incorrect numbers

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Seems like JavaScript is rounding off large numbers in `JSON.parse()` and `JSON.stringify()` operations. Guess it'd be better to use any libs like [losslesshjson](https://github.com/josdejong/lossless-json) on responses.

cc: @AndrewBastin
