### ISSUE TITLE
[bug]: Cannot send request using Brave browser + Chrome extension

### ISSUE THREAD

**Issue by lucie-cupcakes** [hoppscotch/hoppscotch#2170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I open the site and try to do a get call against my local [Python's http server](https://docs.python.org/3/library/http.server.html), the request cannot be sent.

![image](https://user-images.githubusercontent.com/16143806/158660786-e88b3aa1-9ec2-4389-9276-22cc3b384bc1.png)

Here is the configuration for the extension.
![image](https://user-images.githubusercontent.com/16143806/158660946-bdc96937-ecad-4cac-b5ab-5b2d39df57e1.png)

As you can see the end-point is indeed working.
![image](https://user-images.githubusercontent.com/16143806/158661026-a4cb4d6a-4e51-4310-a743-2752a9275937.png)

Developer console:
![image](https://user-images.githubusercontent.com/16143806/158661724-ff8e5426-51a0-4f88-98e7-800fcc2efade.png)

Here is an error log, that I could gather using dev tools:
![image](https://user-images.githubusercontent.com/16143806/158661753-7f57b618-c462-44fc-8c8d-a6528c2e945f.png)

`{"message":"Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '' is not a valid HTTP header field name.","name":"SyntaxError","stack":"Error: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': '' is not a valid HTTP header field name.\\n    at chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:32:1948\\n    at Object.g [as forEach] (chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:4:1516)\\n    at chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:32:1865\\n    at new Promise (<anonymous>)\\n    at module.exports (chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:32:379)\\n    at module.exports (chrome-extension://amknoiejhlmhancpahfcfcfhllgkpbld/index.js:44:584)"}`

### Steps to reproduce

1. Open terminal, create a new folder, make a text file called "hello.txt".
2. Use python to invoke a simple http server on port 8000.  `python -m http.server --bind 127.0.0.1 8000`
3. Open the hoppscotch application using the [Brave browser](https://brave.com/)  (Don't forget to install the Hopscotch Chrome extension)
4. Try to do a request to the end-point `http://localhost:8000/hello.txt`
5. Error should appear.

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@lucie-cupcakes I am unable to reproduce this in my end, could be some weird type mismatch issue.

Can you switch to the Headers tab and completely clear all the headers defined in it ?

Or you can click on the Arrow to the side of the Send Icon and click on `Clear all`. This button clears the request configuration to the default one and should fix that in the mean time.

![image](https://user-images.githubusercontent.com/9131943/158692038-8e0c16b3-7444-40a1-a054-4d81d816c860.png)

**Comment by lucie-cupcakes** [comment]
@[AndrewBastin](https://github.com/AndrewBastin) Thanks, that fixed my issue!
Maybe it was a bad cache or something.

![image](https://user-images.githubusercontent.com/16143806/158693697-f3f635f8-cddc-4d35-87c8-2d0e99e2088d.png)
