### ISSUE TITLE
[bug]: Deployment issues

### ISSUE THREAD

**Issue by juandl** [hoppscotch/hoppscotch#2173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Is not possible to use "docker image hub" because the env is already set on build time, I think the best way to allow users who want to use "docker" in production is to move [nuxt.config.js](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/nuxt.config.js) to use env on runtime and also update the docker file to build using an example env but allow nuxt.js to read on runtime too. 

I believe you can specify "publicRuntimeConfig" all envs variables to catch envs on runtime

### Steps to reproduce

1. docker run --rm --name hoppscotch -p 3000:3000  hoppscotch/hoppscotch:latest

### Environment

Production

### Version

Cloud

**Comment by TheBeachMaster** [comment]
I got this to work by manually copying my own `.env` file into `packages/hoppscotch-app` using Docker

**Comment by juandl** [comment]
> I got this to work by manually copying my own `.env` file into `packages/hoppscotch-app` using Docker

That's great, but I think it should be implemented instead of workaround 😕

**Comment by juandl** [comment]
@liyasthomas this should not be closed, at this point, there's no wait to use a custom env if you use "docker-compose" example. 

version: "3"

services:
  hoppscotch:
    image: hoppscotch/hoppscotch:latest
    container_name: hoppscotch
    pull_policy: always
    ports:
      - "4000:3000"
    restart: on-failure
    volumes:
      - ./app/.env:/app/packages/hoppscotch-app/.env
