### ISSUE TITLE
[feature]: Workspace feature

### ISSUE THREAD

**Issue by repiatx** [hoppscotch/hoppscotch#2184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi. In postman there is workspace feature. Perhaps people want to use this feature too. Thx for your hard work.

### Why should this be worked on?

Because Lot's of request will be there for the sake of simplicity  ( Dividing env,collection,requests ) would be great.

**Comment by liyasthomas** [comment]
Track the discussions and progress of workspace feature in #690.
