### ISSUE TITLE
[feature]: tabs in code/json editors

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#2185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently when you press the Tab key on the keyboard what hoppscotch does is to jump to another input and then it would be great if instead of doing that it would be like the code editors like VS Code, Sublime, etc. that what they do is add a space and do not select another text input.

Also that you could choose whether to add Tabs or Spaces and how many of each in number.

### Why should this be worked on?

Because it would be very convenient when it comes to writing code and not having to press the prettify button every time to have a tidy code.

**Comment by liyasthomas** [comment]
I've added these key press events on editors:

- <kbd>Tab</kbd> = insert tab space
- Selection + <kbd>Tab</kbd> = indent more
- <kbd>Shift</kbd> + <kbd>Tab</kbd> = indent less

**Comment by kaname-png** [comment]
@liyasthomas how is it activated?

https://user-images.githubusercontent.com/56084970/159401722-a246d865-8d32-4c8b-9ad5-8f89d0e11e22.mp4

**Comment by liyasthomas** [comment]
Hi @kaname-png, please wait a few more minutes to finish our build processes and pipelines that will push the latest code to our production server. 10 mins max.

Here's our ongoing actions: https://github.com/hoppscotch/hoppscotch/actions
