### ISSUE TITLE
[feature]: Arm64 / Raspberry Pi build for Docker image

### ISSUE THREAD

**Issue by mvdkleijn** [hoppscotch/hoppscotch#2192]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

An ARM64 / Raspberry Pi supporting Docker image.

### Why should this be worked on?

ARM64 is an increasingly common use case. People self host at home using Raspberry Pi which are increasingly more powerfull and with the new ARM based Macs it would only make more sense.

**Comment by piraces** [comment]
Now available for ARM64 and ARMv7: https://hub.docker.com/r/hoppscotch/hoppscotch/tags?page=1&name=latest
Feature added in PR #2719, closing the issue #2524.

I think this issue can be closed.

**Comment by chenlcacentury** [comment]
Just wonder has  the arm support been abandoned , no arm release for the latest version.

**Comment by sawa-ko** [comment]
no arm support

**Comment by AndrewBastin** [comment]
Hi there, we had a couple of problems with CI we wanted to sort out, this is resolved in the 2023.8.1 release which now has both `linux/amd64` and `linux/arm64` releases supported.
