### ISSUE TITLE
Don't work with localhost

### ISSUE THREAD

**Issue by melsiir** [hoppscotch/hoppscotch#2193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I make a request to localhost it just doesn't work 

### Steps to reproduce

Just type localhost:3000 and hit send

### Environment

Release

### Version

Local

**Comment by liyasthomas** [comment]
Hi @melsiir, please read this discussion thread on how to test API endpoints hosted locally: https://github.com/hoppscotch/hoppscotch/discussions/2051#discussioncomment-1887545
