### ISSUE TITLE
[bug]: selecting text with mouse causes modal to close

### ISSUE THREAD

**Issue by H4kt** [hoppscotch/hoppscotch#2195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While selecting text in modal save window if cursor ends up outside of modal before mouse up modal window will close upon mouse up event. Sometimes I really like to select text in inputs using mouse instead of just pressing `CTRL+A`, so this issue is really annoying. [Video](https://user-images.githubusercontent.com/50774419/159767367-e19af01c-1366-4540-bef3-a5c5897089a0.mp4)

### Steps to reproduce

1. Open any modal window (e.g. save request)
2. Select text inside "Request name" field using your mouse
3. Without releasing your mouse button move your cursor outside of the modal window
4. Release the mouse button

Current behavior: modal window closes
Expected behavior: modal window should stay opened with text being selected

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
Thank you for the submission @H4kt. We will look into this.

cc: @liyasthomas

**Comment by H4kt** [comment]
Just gave it a test. Works fine.
Thank you <3
