### ISSUE TITLE
[bug]: settings do not show the name of chosen accent color

### ISSUE THREAD

**Issue by H4kt** [hoppscotch/hoppscotch#2196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you change accent color in settings it still appears as "Blue" under the title.

![image](https://user-images.githubusercontent.com/50774419/159771002-0a12aef4-87a1-42bd-bc05-e70445e255ed.png)

### Steps to reproduce

1. Go to settings
2. Set your accent color to anything but blue

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@H4kt nice catch, thank you for letting us know.
This should be fixed in the latest update which should roll out in 15-20mins.
