### ISSUE TITLE
[bug]: Rquest body is not imported when using OpenApi 3 import

### ISSUE THREAD

**Issue by alcalyn** [hoppscotch/hoppscotch#2201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I import an openapi v3 json collection, requests are imported, but all bodies in POST, PUT... are empty

### Steps to reproduce

1. Download this openapi v3 sample: https://petstore3.swagger.io/api/v3/openapi.json (I get same result with my own collections)
2. Go to hoppscotch > collections > Import > Import from Openapi
3. Select the downloaded openapi.json
4. Go to a POST or PUT request, then go to the body

Expected:
- I can see the form parameters, like in postman
![image](https://user-images.githubusercontent.com/1588144/160099256-724b8ee2-47a5-4b9f-8aac-c554e7bed8b9.png)

Actual:
- Body is set to json, empty
![image](https://user-images.githubusercontent.com/1588144/160099320-7a57a2fd-396d-4d9b-b929-1e37ce6945d2.png)

Also, I get same result with json body, always empty

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This is a known issue, please track the progress on #2087, hence closing.
