### ISSUE TITLE
[feature]: Function to send request from pre-request script

### ISSUE THREAD

**Issue by greg-vstorm** [hoppscotch/hoppscotch#2205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Postman provides method `sendRequest` to make AJAX request from pre-request script. For example:
```js
pm.sendRequest({
    url: 'http://example.localhost/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, {cookies}) {
    if (!error) {
        pm.environment.set('xsrf-token', cookies.get('XSRF-TOKEN'))
    }
})
```
This feature is useful when you need to get for example xsrf-token, 

### Why should this be worked on?

Allow testing API's build with Laravel Scout to get xsrf-token. I think it's much more use cases than this one.

**Comment by AndrewBastin** [comment]
Thank you for reporting.

We will consider this during the planned revamp of the Scripting System.

**Comment by AndrewBastin** [comment]
Yup, I am working on a solution for this, stay tuned!

**Comment by 987Nabil** [comment]
@AndrewBastin Any news on this?

**Comment by lslavuj** [comment]
Any news?

**Comment by AndrewBastin** [comment]
Please discuss about this in the RFC discussion #2292 for the scripting API revamp.

We are working on a scripting API revamp to support for more complex use cases.

**Comment by lathindu1** [comment]
Any update guys. can we get CSRF token in Pre-request scripts now ? We really need it's to test Laravel

**Comment by laDanz** [comment]
Still waiting for this, would really improve my user experience...
I guess it should not be closed, even if it is mentioned on #2292 ?
All other mentioned features on #2292 are not closed...

**Comment by bforbis** [comment]
Would like to add my +1 support for this feature, as it is making it difficult for me to migrate from Postman.

**My Use Case**: A pre-request script that handles creation of OAuth 2.0 client_credentials grant access token before the request, then stores both the access token and expiration in environment variables.

I have been using this in postman before Postman even added OAuth 2 support, and it's a great way to get around the lack of Hoppscotch support for OAuth 2.0 client_credentials grant (see https://github.com/hoppscotch/hoppscotch/issues/874)

It would be really great if these pre-request scripts could then be stored at the collection level and shared.

**Comment by nandi95** [comment]
Why was this issue closed?

**Comment by andras-gyarmati** [comment]
id also need this feature. please update us

**Comment by FarhanShares** [comment]
Aug 19, 2024: Any updates? This is a much needed feature.

**Comment by dreamscached** [comment]
Bumping, is that a thing yet?

**Comment by Nackophilz** [comment]
Bump, 2025 still need this feature .. ^^

**Comment by laDanz** [comment]
leaving hopscotch for bruno.

**Comment by jamesgeorge007** [comment]
Hi, we have an [updated RFC](https://github.com/hoppscotch/hoppscotch/discussions/5221) for the revamped scripting system that covers the above scope. We’d appreciate reviews and feedback directly on the RFC itself, so we can keep the discussion focused and productive.
