### ISSUE TITLE
[bug]: No horizontal scroll on Team Collections folder tree

### ISSUE THREAD

**Issue by rakeshkr22** [hoppscotch/hoppscotch#2206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i added around 13 sub folders in teams collection section, the folder tree view is scrollable only vertically. No new sub folder is able to create.

Sample SS :- 

<img width="406" alt="image" src="https://user-images.githubusercontent.com/10681753/160232090-8cb8e4f7-a582-4082-af86-07ceb13ae66e.png">

### Steps to reproduce

1. Go to Team Collections section
2. Select a team
3. Add sub folders ( around 13)
4. Not able add new sub folders

### Environment

Production

### Version

Cloud

**Comment by Gautam-Arora24** [comment]
Would like to work on this issue.

**Comment by liyasthomas** [comment]
Hi @Gautam-Arora24, feel free to pick this up. Do let us know if you've any doubts understanding the source code.

**Comment by Gautam-Arora24** [comment]
Would it be a good idea to add a horizontal scrollbar so that we can view the folders which are being cut off?

**Comment by rakeshkr22** [comment]
@liyasthomas @Gautam-Arora24 Still the issue persists. 

<img width="358" alt="image" src="https://user-images.githubusercontent.com/10681753/194643617-00f845cb-f348-42da-8b03-a50f07f0893a.png">
