### ISSUE TITLE
[feature]: When importing a postman collection, don't automatically add `http://`

### ISSUE THREAD

**Issue by revosw** [hoppscotch/hoppscotch#2208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The way we set up our postman routes is like this:
```
{{ApiBase}}/route
```
instead of
```
http://{{ApiBase}}/route
```

This makes it really easy to switch from plain text `http://localhost:3000` to TLS `https://api.service.com`

### Why should this be worked on?

When importing a postman collection, now we have to manually go through all the requests and remove the automatically inserted `http://`. Implementing this feature means _n_ less operations before being up and running with hoppscotch

**Comment by Tobychidi** [comment]
This was a problem for me as well. I believe in 3 months I will be uninstalling Postman. 😋. I like green stuff.

**Comment by AndrewBastin** [comment]
@revosw I have pushed a small update (should be live in 10-15 mins) which should fix the issue hopefully. Let me know and reopen this issue if it doesn't.
