### ISSUE TITLE
[feature]: Preview final REST request before sending

### ISSUE THREAD

**Issue by n-alonso** [hoppscotch/hoppscotch#2218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I tried to find in the documentation if this was possible, plus checked the opened issues to see if it was already raised but I could not find, please forgive me if I missed it.

Essentially it becomes a bit difficult to troubleshoot why your request fails if you cannot verify what are you actually sending, therefore the ability to preview the final request (with already parsed variables and so on) that will get sent before sending it would be massively helpful.

### Why should this be worked on?

It would speed up efficiency and troubleshooting when things don't work as expected.

**Comment by liyasthomas** [comment]
Hi @n-alonso, I'd like to know what you meant by "preview of final request". If you're referring to how the request would look like in any languages/frameworks like cURL, JavaScript Fetch, Axios, etc.. we have a feature in Hoppscotch which allows you to preview and generate the source code to make the final request.

**Click on drop-down menu right next to "Send" > "Show code"**

<img width="1440" alt="Screenshot 2022-03-31 at 2 40 40 PM" src="https://user-images.githubusercontent.com/10395817/161020213-1fb6bc41-804a-4e31-bfd0-c20eee733004.png">

<img width="1440" alt="Screenshot 2022-03-31 at 2 42 02 PM" src="https://user-images.githubusercontent.com/10395817/161020497-3ff7db31-d2ee-4001-acc0-f7e805b3ffab.png">

Let me know if this resolves your request, if not we'd like to know more about your use case.

**Comment by n-alonso** [comment]
Yes, that is exactly what I was looking for.
Sorry for raising an issue for this and thank you for the prompt response!
Feel free to close this.
