### ISSUE TITLE
[feature]: Reorder folders

### ISSUE THREAD

**Issue by benbagley** [hoppscotch/hoppscotch#2220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow users to re-structure collection folders/sub folders.

### Why should this be worked on?

Having moved from Postman too hoppscotch, one of the things that was really useful was the ability to reorder the collections folder structure. This is a really small feature but something. which seemed to of been overlooked.

**Comment by AyushChothe** [comment]
Also make Requests Reorderable

**Comment by guidospadavecchia** [comment]
This feature would be really useful!

**Comment by TeamPIDU** [comment]
Yes Folder and Request reordering are very important in terms of managing - Also please add the functionality to import/move folders into other folders - this will be very helpful when many people are working on api of different modules and finally one can provide the exported file and all of then can be imported into a single folder at one place making a central project sort (just a usecase)

**Comment by liyasthomas** [comment]
Hi @TeamPIDU, we’ve prioritised collections and folders reordering feature for next major release.

Fyi, you can move folders or collections by drag and dropping them to desired collection.

**Comment by kr-tukimi** [comment]
Very excited for this feature! Any update?

**Comment by AndrewBastin** [comment]
We are testing the implementation internally for Teams to support reorders, once that is done, we will be implementing be including this in #2406.

**Comment by liyasthomas** [comment]
We recently released an improved version of Hoppscotch which supports reordering collections and folders. You can check out the latest updates on our website at https://hoppscotch.io. We hope this update will provide a better experience for our users and fix any issues you may have encountered with the previous version. Thanks for your support!
