### ISSUE TITLE
[feature]: Add expect().toInclude([string]) method

### ISSUE THREAD

**Issue by ace-n** [hoppscotch/hoppscotch#2221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a `toInclude()` method to `pw.expect()`

(`toContain()` could work too, but [JS itself](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) uses `includes()`, not `contains()`.)

### Why should this be worked on?

I want to assert that an unstructured page contains a certain string of text.

(For example, I want to assert that `/attractions?q=egypt` should contain `Pyramids of Giza`)

### Current workaround

Currently, you can do the following:
```
pw.expect(pw.response.body.includes("example")).toBe(true)
```

This is suboptimal for two reasons:
1) It doesn't produce a detailed assertion message.
2) It's a bit verbose. 🙂 

### Contribution notes

I'm happy to take a first-pass at an implementation myself, if a maintainer is OK with it! 😄

**Comment by liyasthomas** [comment]
Hi @ace-n, feel free to pick up this feature request. Do let us know if you've any trouble understanding the source code. Assigning this to you.
