### ISSUE TITLE
[feature]: multiples tabs

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#2229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I think it would be great to be able to have multiple tabs for example rest, graphql, etc as it helps to do more things without having to cancel everything you were doing before.

This can help make multiple requests easily.

### Why should this be worked on?

As well as postman tabs.

**Comment by liyasthomas** [comment]
Hi @kaname-png, we have a similar issue ticket to track the progress of "Tabs" feature on #690, hence closing this issue. Kindly share your comments on it.
