### ISSUE TITLE
[feature]: macos Big Sur icon support

### ISSUE THREAD

**Issue by pys1992** [hoppscotch/hoppscotch#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The icon size is too large.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/44765369/161693542-65b6f3dc-9e6a-454a-9f9f-a1d2677928d4.png">

### Why should this be worked on?

update the icon size to fit macos big sur.

**Comment by liyasthomas** [comment]
https://github.com/hoppscotch/hoppscotch/issues/1997#issuecomment-986841444

> ![screely-1638801708058](https://user-images.githubusercontent.com/10395817/144865868-d5c8fadc-785d-4277-b53f-b01bba4752c0.png)
> 
> I guess that's a common style applied to all Progressive Web Apps' icons installed on macOS.
> 
> I will see if it's possible to shrink the app icon to match the dock icon size on macOS, but most probably it'll cause other operating systems to have an irregular icon size.

**Comment by liyasthomas** [comment]
Her's a screenshot of latest release of [Hoppscotch desktop app](https://hoppscotch.com/download) on macOS Sequoia (latest).

<img width="320" alt="Image" src="https://github.com/user-attachments/assets/7a5af87c-fb5c-4a2d-a990-7fe8639bd8ce" />

**Comment by borisyurkevich** [comment]
Thanks, happy to see yours looks good.
Hmm, I am using our enterprise build, I wonder is it behind the official release. Version 24.11.0 (20241218.120018)
