### ISSUE TITLE
[feature]: create custom keybindings

### ISSUE THREAD

**Issue by js182** [hoppscotch/hoppscotch#2236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The default keybindings, e.g. 'Send request', are set constant. It should be possible for me to modify the existing ones and even create new ones to execute macros.

### Why should this be worked on?

To increse productivity I want to set keybindings to my amenity and the way I'm used to. Also, I want to resolve issues with already existing keybindings that other programs are already listening to and are also used by hoppscotch. To allow disabling these in hoppscotch would be the first workaround to solve conflicting keybindings.

**Comment by liyasthomas** [comment]
#3401 has a recent discussion on this topic hence I'd encourage you to track progress over there.
