### ISSUE TITLE
[bug]: Building locally fails due to hostname error

### ISSUE THREAD

**Issue by DanBurkhardt** [hoppscotch/hoppscotch#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have followed all instructions to build the application to run locally without Docker according to the README under section titled "release".

upon running the 2nd to last command `pnpm run generate`, it takes a while and seems to be succeeding, but when it reaches the sitemap generation step it fails with the error: `FATAL  [sitemap-module] The hostname option is mandatory in your config on spa or generate build`

I have attached a screenshot of the error.

There is no indication of where I would need to setup this hostname, and if this is needed, it also needs to be added to the README instructions.

Thanks, 
Dan

### Steps to reproduce

Go to the README on this repository and follow steps to build locally under "release".

My system info:
16" MBP running 12.2.1 (Monterey)
NPM Version: 6.14.13
Node Version: 14.17.1 

### Environment

Production

### Version

Local

Error:
![Screen Shot 2022-04-05 at 3 59 21 PM](https://user-images.githubusercontent.com/14014682/161840464-45f1e944-014d-4856-bc5a-5ea3a6b509c7.png)

**Comment by liyasthomas** [comment]
Seems like you missed the `Step: 0` in [local development guide](https://github.com/hoppscotch/hoppscotch#developing).

> 0. Update [`.env.example`](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/.env.example) file found in `packages/hoppscotch-app` with your own keys and rename it to `.env`.

You should provide the essential environment variables in the `.env` file. Let me know if it doesn't fix your build process.

**Comment by DanBurkhardt** [comment]
Perfect, will attempt after updating according to the README, thanks for the quick action!
