### ISSUE TITLE
[bug]: HTTP requests are blocked by default and behavior is not documented

### ISSUE THREAD

**Issue by sjsadowski** [hoppscotch/hoppscotch#2246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

This is an extension of #1376, however that issue does not properly address the behavior as identified.

By default, the PWA runs as an https-loaded site. Modern browser do not allow mixed content (HTTP/HTTPS). Requests made in the PWA to *any* http:// address fail (as of 2022-04-08) by default unless proxied through the browser extension. I have not checked whether or not this is functional for an actual socks proxy.

I have no issue with this - it is expected browser behavior and as of now, at least chromium/chrome have disabled the flags that would allow this to function. With that being said, the behavior should be documented. If acceptable, I'll submit a PR for updating the README noting this. 

I am unaware of there being another fix, however with the original issue being open almost a year and a half, I am guessing there's not an easy one.

**Replicated on:**
Fedora 34, 35/Chrome 99; Chrome 100
MacOS 12.3, 12.3.1/Chrome 99; Chrome 100

### Steps to reproduce

1. Open https://hoppscotch.io
2. Install PWA
3. Attempt to access any site using http://

### Environment

Production

### Version

Local

**Comment by balub** [comment]
Have you tried installing the Chrome Extension and trying then?
https://chrome.google.com/webstore/detail/hoppscotch-browser-extens/amknoiejhlmhancpahfcfcfhllgkpbld?hl=en
