### ISSUE TITLE
Does the privacy policy apply if I don't use the proxy?

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [hoppscotch/hoppscotch#2248]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

Title 

### Why should this be worked on?

Idk. Just a question

**Comment by liyasthomas** [comment]
- [Privacy policy](https://docs.hoppscotch.io/privacy) for hoppscotch.io
- [Privacy policy](https://github.com/hoppscotch/proxyscotch/wiki/Privacy-policy) for proxy.hoppscotch.io
