### ISSUE TITLE
[bug]: GitHub account login failed, prompting some errors

### ISSUE THREAD

**Issue by Zouxuejun** [hoppscotch/hoppscotch#2254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="935" alt="image" src="https://user-images.githubusercontent.com/41265142/162698070-f3eb8f57-0c0f-424b-a759-3ea9ff1cb9cc.png">

### Steps to reproduce

<img width="935" alt="image" src="https://user-images.githubusercontent.com/41265142/162698142-e23cdc8e-673b-4cc2-9f56-1f832efac44a.png">

### Environment

Release

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Authenticated features are not available in the self-hosted Hoppscotch instance at the moment. Please track the issue: #1817 for the progress on this feature, hence closing.
