### ISSUE TITLE
[bug]: "Could not send request", but request was sent, and a response has been received

### ISSUE THREAD

**Issue by syrm** [hoppscotch/hoppscotch#2255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i do a GET on "https://api.publicapis.org/entriesWRONGPATH"
The Response panel should be shown with detail informations, its a 404 error etc.

Instead I see "Could not send request"

### Steps to reproduce

1. Go to REST
2. Set method to GET
3. Set URL to https://api.publicapis.org/entriesWRONGPATH
4. Hit the Send button
5. I can see "Could not send request"

But in Chrome console i can see the response of the request : Status code 404

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Seems like you were trying to hit an API endpoint with `CORS` restrictions.

To fix `CORS` restrictions and access responses, goto [Hoppscotch Settings](https://hoppscotch.io/settings) > Interceptor section > Turn on Proxy mode.

Feel free to reopen the issue if issue still persist.

**Comment by syrm** [comment]
Same problem with proxy turned on.
The problem is not related to CORS.

I mean even if CORS block the request, we should see this in Response section

**Comment by Imtiaz-Ali17314** [comment]
I am trying to send a patch request with content type form urlencoded form hoppscotch on this url  : http://localhost:8080/posts/d6cf2f68-acff-4a00-a5ca-8104ae3f346f
The request sent and status is 200, But its request body shown undefined.
How to resolve this Problem?
