### ISSUE TITLE
[feature]: Authorization setting at Collection level

### ISSUE THREAD

**Issue by minhnguyen-ew** [hoppscotch/hoppscotch#2259]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

In Postman, you can set up an authorization method at the Collection level and all of the requests in that collection will inherit that authorization method (unless you override that in the endpoints themself). We can try to provide a similar mechanism here.

### Why should this be worked on?

This is useful for a collection with many different requests (for example, I am working on one which has nearly 100 requests) so you don't need to set up the same authorization method request by request.

Yes, I acknowledged that we can duplicate an endpoint to create another one. But in my case, I imported my collection from Postman. And since I set up the authorization method at the Collection level on Postman, all the requests in the collection don't have one on their own. That means I will need to go and config the authorization method for each request after importing (which is too much work).

**Comment by stratosgear** [comment]
Just wanted to add that conceptually, since all API calls in a collection refer to a single API server (otherwise they would not be in that collection) the Authorization method should be common to all of them. No need to duplicate it in all API calls of the collection.

This is one of the most critical missing features that prevents us from adoption of Hoppscotch... :)

**Comment by stratosgear** [comment]
We have had great success with the Thunderclient VS Code extension.  We really liked Hopscotch but we had to actually choose a tool and that's where we ended up.  A nice plus is that all requests/collections are saved withing the project repo so they are always locally available and never lost...

**Comment by radekpribyl** [comment]
I'd like to understand the status too - we are also evaluating Hopscotch and this missing feature might be a blocker

**Comment by liyasthomas** [comment]
We've prioritized this feature for the next major release, which should happen in December.

**Comment by iam-vatha** [comment]
> We've prioritized this feature for the next major release, which should happen in December.

Thanks.. My team is in the same boat as previous posters. Looking forward to an update as your application is quite good alternative to Postman otherwise.

**Comment by pavelicii** [comment]
@liyasthomas Will it be possible to also define pre-request script at collection level?

**Comment by bforbis** [comment]
This seems related to #1741

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.

Documentation: https://docs.hoppscotch.io/documentation/features/collections#collection-properties
