### ISSUE TITLE
[feature]: Import Swagger APIs from an URL

### ISSUE THREAD

**Issue by o1lab** [hoppscotch/hoppscotch#2260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem : 
- [NocoDB](github.com/nocodb/nocodb) generates collaborative spreadsheets & REST APIs for any database (a lot of them - probably in millions)
- And for these APIs we also [generate](https://www.youtube.com/watch?v=1unQAEGDz8U) - swagger APIs 
- Swagger is not the best way to consume APIs.
- We want an intuitive way for APIs to be consumed. 

### Proposed feature : 
- A nocodb user should be able to click on a button and export all swagger APIs to hoppscotch. (and if it can remain in sync later - that would be awesome)
- hoppscoth.io?import_from_url=URL 

### Why should this be worked on?

- This is not just a good opportunity to export swagger APIs via an URL from NocoDB but also any swagger APIs from anywhere on internet :)

**Comment by AndrewBastin** [comment]
@o1lab This seems to be a bit more expanded version of #2020. (Which we are actually working on right now).
So shall we close this and consolidate this issue to the above mentioned one ?

Btw, we are big fans and supporters of NocoDB here at Hoppscotch! Best wishes! <3
We should have a chat some time ^_^

**Comment by o1lab** [comment]
@AndrewBastin : oops missed that issue while searching - I will close it.

We should have a chat - I can expand more on the idea. And likewise, love the work you people have been doing. We look up to hoppscotch.
