### ISSUE TITLE
[feature]: Sidebar is not visible when the window size is small

### ISSUE THREAD

**Issue by jvinis** [hoppscotch/hoppscotch#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Sidebar is not visible when the window size is small, it used to work in previous versions work as:
1) when size was enough, display the sidebar on the right 
2) when size was not enough, display the sidebar bellow

now work as:
1) when size was enough, display the sidebar on the right 
2) when size was not enough, hide the sidebar

### Why should this be worked on?

I work in a screen, where on the left I have the vscode and on the right i have the hoppscotch about 10% of the screen (you can think it as mobile screen size). How can I choose requests from collection, or set environment variables ?
I have to expand the hoppscotch choose the request and the bring it back to small size.

**Comment by liyasthomas** [comment]
You can make the sidebar visible on small screens by clicking on the "Options" button in the top header > "Expand Collection Panel".

<table>
<tr>
	<td>Step 1. Click on the "Options" button</td>
	<td>Step 2. Click "Expand Collection Panel"</td>
<tr/>
<tr>
	<td>

![hoppscotch io_](https://user-images.githubusercontent.com/10395817/163394566-3db64e06-2da3-4045-8441-07d1a6168e6a.png)
    </td>
	<td>

![hoppscotch io_ (1)](https://user-images.githubusercontent.com/10395817/163394557-c7bdc3bb-b0e6-4aa3-b177-7c5461cd9de0.png)
    </td>
</table>

**Comment by jvinis** [comment]
Thanks,
my problem was that 
1. I work in zen mode and the options icon is tied to zen mode.
2. the support icon button in large screen is transformed to options icon button in small screen !!

Why the options and settings is two different screens?

My suggestion is 
1. the support icon button, should remain support icon button
1. combine options and settings into one screen, where can be opened by click on settings
3. the setting [expand collection panel] should be saved between screen changes
