### ISSUE TITLE
[bug]: Hoppscotch can't access the github api

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [hoppscotch/hoppscotch#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to access the github api and click connect it just keeps loading without connecting

### Steps to reproduce

1. Get yourself a personal access token for your github account and copy it to your clipboard
2. in hoppscotch, go to the graphql tab
3. type api.github.com/graphql
4. in authorization, select bearer token and paste the token from step 1
6. click connect

### Environment

Production

### Version

Local

**Comment by A-childs-encyclopedia** [comment]
Uhh

**Comment by A-childs-encyclopedia** [comment]
Someone please take a look at this

**Comment by anwarulislam** [comment]
@A-childs-encyclopedia Thanks for letting us know. We're figuring this out why is this happening.

**Comment by A-childs-encyclopedia** [comment]
The connect button doesn't work but the run button does.
