### ISSUE TITLE
[feature]: Option to store sessions and cookies

### ISSUE THREAD

**Issue by VAISHAKH-GK** [hoppscotch/hoppscotch#2314]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

# Options to store sessions in Hoppscotch .

Currently in Hoppscotch cant send requests with session or cookies . Needed feature to store cookies and sessoins in Hoppscotch. 

### Why should this be worked on?

It would be really helpfull for development if there is a option to store Sessions and Cookies .

**Comment by MexHigh** [comment]
Why was this closed without clarification? This would be a neat feature
