### ISSUE TITLE
[bug]: The `Save request` popups too many times

### ISSUE THREAD

**Issue by isgj** [hoppscotch/hoppscotch#2318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I save the current request and I click to another request the pop up will ask me to save the request. But I already saved from the save button. Most of the times if I click save it will create a new request

This happens almost every time I change from one request to another

### Steps to reproduce

1. Make request 1
2. Click `Save` to save the request
3. Click on another request 
4. The pop up is shown
![image](https://user-images.githubusercontent.com/20517048/166465646-9e1ba917-984e-4d7e-88f4-af588f1dd42e.png)

### Environment

Release

### Version

Self-hosted

**Comment by TeamPIDU** [comment]
Facing the same issue, every time leaving a request and going to another request the Save popup comes up, even if the previous request has already been saved.

**This issue is also coming in the latest Cloud Version which is live currently**
