### ISSUE TITLE
[feature]: have an option to pipe request through backend 

### ISSUE THREAD

**Issue by Truth1984** [hoppscotch/hoppscotch#2319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Need to have an option to switch requests sent through by web API or a backend server, since a backend server does not have to deal with the cors issues.

### Why should this be worked on?

1. Am using the docker version, and having issues with cors: seems like my requests and proxy servers are both blocked by the cors policy.

2. postman does not have to deal with the cors issues.

3. send requests from self-hosted sites with HTTPS enabled to an HTTP destination is most likely impossible due to web security policy.

**Comment by AndrewBastin** [comment]
You can use the [official browser extension](https://github.com/hoppscotch/hoppscotch-extension) if your only goal is to override CORS. Else, you can use the proxy interceptor as well.

For more info, see: https://docs.hoppscotch.io/features/interceptor

If this solves your problem, please close this issue.
