### ISSUE TITLE
[feature]: Add ability to filter JSON response to just wanted fields

### ISSUE THREAD

**Issue by CosmicTiger** [hoppscotch/hoppscotch#2334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

@CosmicTiger NOTE: The stuff below should be moved to a separate issue - <3 @AndrewBastin
@AndrewBastin NOTE: The previous stuff that points to a new issue has been address at [[feature]: Segmentation of choice about type of body requests to send on endpoint](https://github.com/hoppscotch/hoppscotch/issues/2344)

The way of filter responses from some endpoint and if possible extends a little bit more to make it a little bit more complete in terms of using some pseudocode or JS even in order to find things outs as shown below:
![image](https://user-images.githubusercontent.com/30613501/168167646-8982fd1e-9156-4af7-8f6e-3c8336f4bd4e.png)

I would really interested in beginning this features if is possible but I would need some guidance upon the project to understand how I'm able to implemented it.

### Why should this be worked on?

I hope soon response to this I believe could be a game changer for us, users of this awesome tool. This helps to save time in the making of creating body requests, find out some responses value just to make sure things are working out fine or even better, do some further assessment in terms of going rapidly over your responses and checking an specific data you would like to test out through the test api module similar to Postman that we already have. The high value upon this features are quite big. 🎇

**Comment by AndrewBastin** [comment]
@CosmicTiger Please only focus on a single thing on a single issue.

I am editing out the "Filter Body Responses" part of your feature request, please open a new feature request (or I will move it).

Meanwhile, I am just renaming this issue to just reflect the first request.

**Comment by CosmicTiger** [comment]
@AndrewBastin I have already create the new feature that you suggest to segment as a new task. I would really like to keep in check in this two issues because I'm personally interested to it. If I could be of help in any of those two, let me know and I would onboard to collaborate with you guys ASAP.

**Comment by liyasthomas** [comment]
Hi @CosmicTiger, you can simply rename the `.env.example` file to `.env` and restart the server to spin up the local development environment.

**Comment by CosmicTiger** [comment]
There are some related keys that is mentioned in your README.md of the project that I would need. With that would be suffice just by the renaming on the file? Also, should the file stay where the `.env.example` is located or should be in the `root` directory? Just confirming things out.

**Comment by AndrewBastin** [comment]
@CosmicTiger, this looks really weird, we build Hoppscotch on LTS versions of Node, see if this issue persists there.

This StackOverflow Question might be relevant: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

And as for the `.env.example` thing, yes, creating a copy and naming it `.env` should give you a running instance.

**Comment by nivedin** [comment]
@CosmicTiger, you should run `pnpm install` in hoppscotch file directory after that `pnpm run dev` in the same directory. I think you have run `pnpm run dev` inside hoppscotch/packages/hoppscotch-app.
If this error still persists then try updating node and pnpm to the latest version.

**Comment by CosmicTiger** [comment]
Sorry for being a little bit lost. I had issues in my dev work dealing with a module development. Back on track, you were certainly right I had to downgrade using nvm. 
![image](https://user-images.githubusercontent.com/30613501/170635601-523c0be7-abe4-4650-9669-a41e33195bfd.png)

Now I would like to confirm if with the DATABASE_URL env I'm able to connect to production data main reason for this is to use my account as testing for this feature in which I do not consider could be harmless at all. Let me know if you have any issue regarding this. 

Also, If you guys could provide me a mention of where I do need to check up just for the Best Practices concepts that you apply for the project in order to mantain a good development on this feature :) Once again, thank you for letting me onboard! @nivedin @AndrewBastin @liyasthomas

**Comment by AndrewBastin** [comment]
> Now I would like to confirm if with the DATABASE_URL env I'm able to connect to production data main reason for this is to use my account as testing for this feature in which I do not consider could be harmless at all. Let me know if you have any issue regarding this.

You can use the production url, no worries, but it shouldn't matter anyways as you are not working on a feature related to that.

> Also, If you guys could provide me a mention of where I do need to check up just for the Best Practices concepts that you apply for the project in order to mantain a good development on this feature :)

We use NuxtJS 2 and TypeScript with some Vue 3 stuff sprinkled in. As long as your code is valid TypeScript and follows the Vue 3 Composition API style, you should be fine.
