### ISSUE TITLE
[bug]: docker-compose install error

### ISSUE THREAD

**Issue by zhangyenull** [hoppscotch/hoppscotch#2337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/13203670/168469499-f6d72a74-c1f6-498b-a8f1-daa6f577031f.png">

### Steps to reproduce

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/13203670/168469499-f6d72a74-c1f6-498b-a8f1-daa6f577031f.png">

### Environment

Release

### Version

Local

**Comment by liyasthomas** [comment]
Can't reproduce this issue. Seems it was a temporary issue with Alpine CDN.
Make sure you use the following command to pull the official Hoppscotch Docker image:
```yaml
docker run --rm --name hoppscotch -p 3000:3000 hoppscotch/hoppscotch:latest
```
