### ISSUE TITLE
[feature]: Automatically parse the parameters of the GET request URL into param

### ISSUE THREAD

**Issue by dislazy** [hoppscotch/hoppscotch#2353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Automatically parse the parameters of the GET request URL into param

### Why should this be worked on?

![image](https://user-images.githubusercontent.com/30426054/169676610-70c10863-63d5-4bdb-9f8c-63232773a292.png)

like thar When the parameters are more and longer, it is not an easy thing to change directly in the url。

but now is:

![image](https://user-images.githubusercontent.com/30426054/169676662-645238bd-2af3-4058-af6b-e20e125f9e81.png)

**Comment by AndrewBastin** [comment]
We have had a lot of discussions about this before.
Our idea with the params section and the URL is that, we consider the params defined in the URL bar as constants and params defined in the params section as things that should be modified.

We can think of maybe adding a way to easily move them back and forth, if that is the intention, please open a new issue stating that intention alone. The way it is implemented right now is a design decision and we won't be changing this.

Hence, closing.
