### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by aswinsegwitz** [hoppscotch/hoppscotch#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

currenyly new version doent provide the emit data on live for socket io test..older version provide the emit data as live

### Steps to reproduce

please find a solution for it

### Environment

Production

### Version

Self-hosted

**Comment by AndrewBastin** [comment]
Can you explain what is the issue exactly?

**Comment by AndrewBastin** [comment]
Closing due to no response.
