### ISSUE TITLE
[feature]: Move Folder

### ISSUE THREAD

**Issue by TeamPIDU** [hoppscotch/hoppscotch#2393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Functionality to import folders into other folders and move folder into other folder by drag and drop

### Why should this be worked on?

this will be very helpful when many people are working on api of different modules and everyone can provide the exported folder file , the relevant folder can be shared with other developers and moved/imported into a single folder for better project management all of them can be imported into a single folder at one place making a central project sort

**Comment by TeamPIDU** [comment]
Hi any update with this as, without basic features of Folder Management and Response Grouping - the whole tool of Hoppscotch is becoming non-usable. Its a beautiful tool and is helping thousands of developers worldwide, but without basic management of the Folder and limited Export and Import Functionality, it becomes very hard to use this tool even if somebody wants to. We understand this is an opensource project and free to use the tool by the hoppscotch dev team, kudos to the development and efforts - but basic functions would be more desired rather than adding new functionalities @hoppscotchteam

**Comment by guidospadavecchia** [comment]
+1

This is a basic feature that would be really useful to have. I have a folder with +20 subfolders and countless requests inside and I'm waiting for this feature to be able to move the folder where I want to, so that my team can manage and find the collection easily.

**Comment by devanghingu** [comment]
i waiting for this feature :hand:

**Comment by liyasthomas** [comment]
We recently released an improved version of Hoppscotch which supports reordering collections and drag-and-drop folders to move between collections. You can check out the latest updates on our website at https://hoppscotch.io/.

We hope this update will provide a better experience for our users and fix any issues you may have encountered with the previous version. Thanks for your support!

**Comment by Amir-16** [comment]
can not reorder folder upper to lower or lower folder to upper..
