### ISSUE TITLE
[feature]: Add auto generated docs + schemas to graphql APIs

### ISSUE THREAD

**Issue by Explosion-Scratch** [hoppscotch/hoppscotch#2407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add autocomplete for fields after connecting, and show schemas. Like apollo studio does.

### Why should this be worked on?

Very helpful for contructing queries

**Comment by liyasthomas** [comment]
GraphQL documentation and schema can be viewed from Hoppscotch GraphQL Playground right after successfully connecting to a GraphQL endpoint.
