### ISSUE TITLE
[feature]: Team specific environment variables

### ISSUE THREAD

**Issue by kiriti-iselect** [hoppscotch/hoppscotch#2429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Please provide team specific environment variables for team collections. Currently, the collections are synced between teams but not the environment variables so basically collection is broken if environment variables doesn't sync.

Currently, environment variables are only for local collection.

![image](https://user-images.githubusercontent.com/105347056/174003873-ddcd0dff-5053-456d-84f0-316156d901ee.png)

![image](https://user-images.githubusercontent.com/105347056/174003922-24fd6c47-8ecb-475e-ad6a-0d06816cf5d5.png)

### Why should this be worked on?

Team collections can't be leveraged to its full capacity unless environments can be synced between team members. Most of time, the collections are dynamic with the use of environment variables. 

Example: 

Prod stage might have different api endpoint and api key
`<<url>>/shortfunnel-health?apiKey=<<apiKey>>` where value of `url` will be `/prod/path`
Dev stage might have different api endpoint and api key 
`<<url>>/shortfunnel-health?apiKey=<<apiKey>>` where value of `url` will be `/dev/path`

Also one may be generated different environment variable using `pre-request-script` specific to the state/env

**Comment by AndrewBastin** [comment]
We are actually working on this and hope to ship this in the coming weeks!

For the Hoppscotch team:
Internally tracked by hoppscotch/internal-issues#1
