### ISSUE TITLE
[bug]: Generate Documentation does not work

### ISSUE THREAD

**Issue by bricker** [hoppscotch/hoppscotch#2435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On the "Docs" tab, when I import a collection that I previously exported from Hoppscotch, and click "Generate Documentation", I see a few folders called "None" with no information. I have tried this with a few collections. Here's an example with the default "Echo" request:

I expect the documentation to be generated and show in the UI.

### Steps to reproduce

1. Go to hoppscotch.io
2. Create a new collection
3. Add the default "echo" request
4. Export and download the collection JSON file
5. Go to the "Docs" tab
6. Import the collection JSON file
7. Click "Generate Documentation"
8. Observe that the documentation is not generated and the UI shows a few empty folders.

![image](https://user-images.githubusercontent.com/978899/174394664-a1cf847c-08d8-4a07-a3e5-84c7e58b2305.png)

There are no errors in Console or Network tabs in Developer Tools.

### System Information

- OS: Ubuntu 21.10
- Browsers:
  - Chromium: Version 102.0.5005.115 (Official Build) snap (64-bit)
  - Google Chrome: Version 102.0.5005.115 (Official Build) (64-bit)
  - Firefox: Version 101.0.1 (64-bit) Mozilla Firefox Snap for Ubuntu

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@liyasthomas I think we have to consider removing the page if we are not intent on maintaining it :/

**Comment by liyasthomas** [comment]
@bricker we’ll be removing this feature and entirely the /docs page as we’re planing on introducing a completely revamped API documentation generation feature in the next quarter.

sorry for the inconvenience, keeping this issue open until the Documentation page is removed in production.
