### ISSUE TITLE
[bug]: Scroll Freeze

### ISSUE THREAD

**Issue by khusroohayat** [hoppscotch/hoppscotch#2449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i scroll on request and response tabs i.e (body, JSON) the scroll up and down should work fine

### Steps to reproduce

1. Create a GET/POST Request
2. Click on Send Button
3. After Getting Response When you Scroll down the JSON tab it works
4. After Scroll up the JSON tab it freezes

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
I can't reproduce this issue on my end. @khusroohayat can you send me a screenrecord of the issue?

**Comment by khusroohayat** [comment]
Here is a screen record
https://user-images.githubusercontent.com/5275996/178822855-2740995e-c2e2-4c43-aa12-7d85f3c565c8.mp4
