### ISSUE TITLE
[feature]: support multiple graphql operations

### ISSUE THREAD

**Issue by ezracelli** [hoppscotch/hoppscotch#2451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In GraphiQL, I can specify multiple queries/mutations, like so:

```graphql
query Query0 {
  version
}

query Query1 {
  version
}
```

Then, when I click "Run", GraphiQL prompts me for which operation I'd like to select. Additionally, pressing the keyboard shortcut for "Run" will automatically select the operation under the cursor.

The name of the selected operation is then sent in the `operationName` property of the POST body, as specified here: https://graphql.org/learn/serving-over-http/#post-request

### Why should this be worked on?

Without this feature, I need to comment/uncomment blocks of operations as needed. If I try to send a request to a GraphQL server with multiple operations specified, I get this error in response:

```json
{
  "data": null,
  "errors": [
    {
      "message": "Operation name required in request."
    }
  ]
}
```

This isn't the end of the world, but it would be nice to have an easier way to manage multiple operations!

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.
