### ISSUE TITLE
[bug]: Multiple request created

### ISSUE THREAD

**Issue by umesh27kukreti** [hoppscotch/hoppscotch#2455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when I'm trying to create a new request it will make multiple requests with the same name.  

### Steps to reproduce

1. Go to team collection.
2. create a new collection.
3. create a new request.

### Environment

Release

### Version

Cloud

**Comment by liyasthomas** [comment]
Can you explain a bit more about the issue you’ve faced? Do produce a screen record of the bug.

**Comment by mateo-m** [comment]
I still have this issue when creating requests in a Team I created a few months back.
https://user-images.githubusercontent.com/23667794/188489149-b259e887-ebb7-448b-bc17-59e71ba9efd8.mp4

I can't reproduce the issue in a newly-created Team.

**Comment by mateo-m** [comment]
Would you mind re-opening this issue please @nivedin ?

**Comment by mateo-m** [comment]
I still have this issue when creating requests in a Team I created a few months back.
[user-images.githubusercontent.com/23667794/188489149-b259e887-ebb7-448b-bc17-59e71ba9efd8.mp4](https://user-images.githubusercontent.com/23667794/188489149-b259e887-ebb7-448b-bc17-59e71ba9efd8.mp4)

I can't reproduce the issue in a newly-created Team.

Would you mind re-opening this issue please @nivedin ?

**Comment by nivedin** [comment]
@mateo-m is this happening when saving a request from the 'save as' popup ?

**Comment by mateo-m** [comment]
> @mateo-m is this happening when saving a request from the 'save as' popup ?

Yes @nivedin, it happens when using the "Save as" popup, but it also happens when clicking the "New request" icon (which opens a popup) and saving said new request.

Strangely enough, it doesn't seem to happen when duplicating an existing request, **and refreshing the website/PWA** makes the _non-existant_ duplicates disappear.

**Comment by AndrewBastin** [comment]
@mateo-m I have implemented an intermittent patch for it, which should hopefully stop this from happening.
Please do confirm and feel free to reopen the issue if this still persists.
