### ISSUE TITLE
[feature]: Remember pane sizes

### ISSUE THREAD

**Issue by guidospadavecchia** [hoppscotch/hoppscotch#2456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Nowadays, when you launch Hoppscotch, you need to resize the different panes to your liking every time.
It would be a nice feature to save the different pane sizes (for instance, in local storage) in order to restore the visual configuration the next time the app is opened:

![hoppscotch](https://user-images.githubusercontent.com/16108318/175562946-ccb3581a-7d32-4bb9-8c0a-5c63d6151855.png)

### Why should this be worked on?

Every time the app is opened from scratch, the panes need to be resized manually. This small **QoL** improvement solves this issue.

**Comment by anwarulislam** [comment]
Thanks for your suggestion. We will consider this feature.

**Comment by AndrewBastin** [comment]
You can take it on @sagar290! Assigning.
