### ISSUE TITLE
[feature]: CI/CD integration for tests (like Postman)

### ISSUE THREAD

**Issue by binaryfire** [hoppscotch/hoppscotch#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hi guys

We're using Postman and would love to move to Hoppscotch.

We rely heavily on Postman's ability to integrate with our  CI/CD pipeline: https://www.postman.com/use-cases/api-testing-automation/

Is there any way to do this with Hoppscotch? I.e. write all our tests in Hoppscotch and run them via webhooks or a cli

Thanks!

### Why should this be worked on?

CI/CD integration is a popular Postman feature that a lot of companies rely on

**Comment by liyasthomas** [comment]
[Hoppscotch CLI](https://www.npmjs.com/package/@hoppscotch/cli) allows you to integrate automated tests of Hoppscotch Collections in CI/CD pipelines.

> **Warning**: Hoppscotch CLI is currently in alpha. [Please report any issues you encounter.](https://github.com/hoppscotch/hoppscotch/issues/new/choose)

[Read Documentatiion](https://docs.hoppscotch.io/cli)

**Comment by AndrewBastin** [comment]
Closing.
