### ISSUE TITLE
[feature]: Duplicate folder

### ISSUE THREAD

**Issue by JVillator0** [hoppscotch/hoppscotch#2475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Duplicate folder... with all requests inside

### Why should this be worked on?

To make the most of time, be more productive and improve the user experience

**Comment by kyteinsky** [comment]
@AndrewBastin Green flag to work on this one?

**Comment by AndrewBastin** [comment]
@kyteinsky yeah. sure!

**Comment by kyteinsky** [comment]
@AndrewBastin 

For team collections, where can I add the body for new mutations, declarations were in `helpers/backend/gql/mutations`? 
Running a mutation for every request is not ideal :)

**Comment by jamesgeorge007** [comment]
Support for duplicating collections has been added in the [latest release](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.7.0).

Please note that it is currently disabled under the personal workspace in the self-hosted instance. Closing this issue. Feel free to share any feedback.
