### ISSUE TITLE
[bug]: Failed fetching teams list

### ISSUE THREAD

**Issue by ngocthua830** [hoppscotch/hoppscotch#2478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/21144351/176985278-52c59682-72a8-4aca-90f2-b0b5bc17899e.png)

I got this error after deploy source code and load page

### Steps to reproduce

Clone git repo
docker-compose build
docker-compose up
Load website

### Environment

Deploy preview

### Version

Local

**Comment by liyasthomas** [comment]
Authentication, Cloud Sync and Team collaboration features are restricted on URLs other than official `hoppscotch.io`.

While we’re planing to release self-hostable Hoppscotch instance support by end of this year, kindly be patient and follow the project on GitHub for future product updates.

Meanwhile, feel free to use Hoppscotch.io for team collaborative features.

**Comment by deepaksinghcs14** [comment]
is this done ?
