### ISSUE TITLE
[feature]: application that can be installed on the pc (maybe with ElectronJS?)

### ISSUE THREAD

**Issue by mcorbelli** [hoppscotch/hoppscotch#2480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://www.electronjs.org/

### Why should this be worked on?

it would be useful to implement hoppscotch in a desktop application via ElectronJS so that it can be independent of chrome, even in terms of occupied resources.

**Comment by theabhayprajapati** [comment]
actually, it's PWA, you can install it as a browser app.

**Comment by DarkKnight1992** [comment]
that is not a good solution, since this approach requires https://hoppscotch.io to be whitelisted.
