### ISSUE TITLE
[feature]: Better debugging support on hoppscotch.io: sourcemaps and vue-devtools

### ISSUE THREAD

**Issue by KartikSoneji** [hoppscotch/hoppscotch#2509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Make hoppscotch.io easier to debug by enabling CSS and JS sourcemaps and vude-devtools support.

For example:
```diff
diff --git a/packages/hoppscotch-app/nuxt.config.js b/packages/hoppscotch-app/nuxt.config.js
index 4a32366..de45ec3 100644
--- a/packages/hoppscotch-app/nuxt.config.js
+++ b/packages/hoppscotch-app/nuxt.config.js
@@ -96,6 +96,12 @@ export default {
   // Global CSS (https://go.nuxtjs.dev/config-css)
   css: ["~/assets/scss/styles.scss", "~/assets/scss/themes.scss"],
 
+  // Always enable CSS sourcemaps
+  cssSourceMap: true,
+
+  // Allow inspection with vue-devtools
+  devtools: true,
+
   // Plugins to run before rendering page (https://go.nuxtjs.dev/config-plugins)
   plugins: [
     "~/plugins/v-tippy",
@@ -264,6 +270,11 @@ export default {
         config.mode = "development"
       }
 
+      // Enable sourcemaps in production build
+      if (isClient) {
+        config.devtool = "source-map"
+      }
+
       config.node = {
         fs: "empty",
       }
```

I'll be happy to open an PR.

### Why should this be worked on?

Sometimes it's faster to add a breakpoint or analyse hoppscotch.io than spinning up a full debug server.
It will also provide better stacktraces while reporting errors.

**Comment by AndrewBastin** [comment]
We are migrating out of Nuxt to Vue 3 (+ Vite). It is long ways off from stable, but that will be our priority for a while.

I will keep the issue open for reconsideration once #2508 gets eventually merged.

But even then, I am fine with code source maps. But I am against allowing devtools for production, as devtools code has performance impacts and presence in the bundle.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in a prior release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.

**Comment by KartikSoneji** [comment]
Can confirm, sourcemaps do work on https://hoppscotch.io/
Thanks!
