### ISSUE TITLE
[feature]: ARM based docker image

### ISSUE THREAD

**Issue by kunduarnab** [hoppscotch/hoppscotch#2524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Current version is supported for linux/amd64 only.  Arm based version will be helpful for those with arm based systems. Currently i'm using M1 mac for development and Arm based server for production.

### Why should this be worked on?

ARM based systems are increasing rapidly, whether for self hosting or in production.

**Comment by piraces** [comment]
Hi! I can work on this. I have been analizyng the actual docker image and it can be built for other platforms, will try modifying the action in my fork and then open the PR 👍
