### ISSUE TITLE
[feature]: Better error handling

### ISSUE THREAD

**Issue by FranMaric** [hoppscotch/hoppscotch#2542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I use environment variables in Hoppscotch. When using an environment variable in your path without previously choosing your environment the user interface doesn't give an obvious error that environment is missing or that environment variable is missing it just says "Could not send request". It took me some time to realise what was going on. I think this deserves attention because it's bad user experience. You should a better error that says you are missing an environment variable.

### Why should this be worked on?

Better error handling is always gladly accepted by users. This is sub optimal UI/UX

**Comment by aitchnyu** [comment]
Few other contexts where better error message will help.

Doing `POST https://mockbin.com` just shows "Could not send request". It should inform the user it was a CORS error.

Console shows:

```
Access to XMLHttpRequest at 'https://mockbin.com/' from origin 'http://192.168.1.6:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js?d0e7:210          
POST https://mockbin.com/ net::ERR_FAILED
```

Doing `https://fakefakefdasfsafa.com` (non existing site)  just shows "Could not send request". It should inform the user it was a DNS failure.

Console shows:
```
POST https://fakefakefdasfsafa.com/ net::ERR_NAME_NOT_RESOLVED
```

**Comment by liyasthomas** [comment]
When using an environment variable where no environment is selected; will gives you a red background color on it. The same happens when the selected environment doesn’t have a the specified variables.
