### ISSUE TITLE
`Same command for different work. Alt + 'k'`[bug]: 

### ISSUE THREAD

**Issue by theabhayprajapati** [hoppscotch/hoppscotch#2543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Alt + k has two different works. 😔
<img width="243" alt="image" src="https://user-images.githubusercontent.com/88815641/181916096-8068d343-6ee5-44bc-9500-8cde6122c31e.png">

- Alt works properly for **selecting post method**.
- but not for navigating to the **profile page**.

## How can be fixed 👷
Updating the command for any one of the functions can resolve the issue, mostly updating the command for **navigating profile**.

### Steps to reproduce

1. Press `Alt + K`
2. it will only activate POST METHOD and won't navigate to the profile page.

### Environment

Production

### Version

Cloud

**Comment by khusroohayat** [comment]
@anwarulislam can i work on this?

**Comment by anwarulislam** [comment]
@khusroohayat yeah, sure. you can work on this. Just let us know which command you're defining.

**Comment by theabhayprajapati** [comment]
should we update commands for navigation so that it wouldn't cause any confusion in future too?
I mean like for all commands that are used to navigate between pages like _/settings_, _/profile_ should use the same initial commands something like  **h+ s** for going to **settings** and **h+ p** for navigating for **profile** page as one.
In this way, there will be consistency in design.

## Suggestion
For Navigating to 
1. Profile Page should** be **h+p** here _h for hoppscotch_ and p for the profile.
2. Documentation should be **h+d** _d for documentation_
3. Realtime Page should be **h+w** as the w is used currently with **alt + w** so **h+w** is a great combination.
4. GraphQL --> **h+q** 
5. Settings --> **h+s**
6. REST --> **h+r**

----
how was the idea?
i am open for suggestion and recommendation .
#### Recommendation try to use [**twitter's**](https://twitter.com/) shortcuts it idea is inspire from there.

**Comment by anwarulislam** [comment]
@AndrewBastin I have checked that commands with the `alt` key aren't working in our app currently. What do you think about his suggestions?
