### ISSUE TITLE
[feature]: Built a VS code extension for hoppscotch.

### ISSUE THREAD

**Issue by ravi-sankarp** [hoppscotch/hoppscotch#2555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I personally think VS code is the most used IDE for web development by both newcomers and other senior developers.So it would be nice to have a VS code extension for testing web API . Currently there is an extension called Thunder Client.But the UI is not so good.So It would be good if Hoppscotch was available for vs code.Also I think everybody would't like to open up a browser and use an API tester.So it would be good for both Hoppscotch and we developers.
Also I think in VS code you guys could implement cookie support.It would be well added feature.

### Why should this be worked on?

I think this would be good for both hoppscotch and we developers

**Comment by liyasthomas** [comment]
https://github.com/hoppscotch/hoppscotch/issues/313#issuecomment-607557925

**Comment by ravi-sankarp** [comment]
I see that you are not planning on implementing such a feature.It would have been more easier for developers if they are able to sent requests and see the console output in the same application.The reason I opened this is because I felt so.Anyways good luck ahead.Wishing you guys all the best
