### ISSUE TITLE
[bug]: lost team after long time not login

### ISSUE THREAD

**Issue by ngocthua830** [hoppscotch/hoppscotch#2570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was been kick out of my team by no one, after 7 days not use hoppscotch.

### Steps to reproduce

Not use hoppscotch after long time (about 7 days)

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
This is not possible generally and I can't triage it with just the given info. Make sure you signed in using the correct auth system again (sometimes, signing in with Google and then signing in with Github later may create separate accounts).

I will still keep this issue open to see if anybody else got the same issue.

**Comment by anwarulislam** [comment]
@AndrewBastin I faced the same issue once when I used hoppscotch team. I think your assumption is right. signing in with a different method creates the problem even if we have the same email connected to Github and Google. If this is the case we can merge the account from the backend.

**Comment by ngocthua830** [comment]
I only lost one of three team I joined, so I think that's not a problem with login method.

**Comment by khiemledev** [comment]
![image](https://user-images.githubusercontent.com/28501389/185837728-52a6434f-2488-4f8f-a34d-01159268c805.png)


I faced the same issue. After a while (about 5 days) not using hoppscotch, all teams that I have joined are gone. Further more, my teammates (still in the team) cannot invite me because I already in that team.

![image](https://user-images.githubusercontent.com/28501389/185837690-494f9f07-8140-4e1b-a540-ee28a5afcd1e.png)

**Comment by AndrewBastin** [comment]
@hoppscotch/backend take a look at this ?

**Comment by AndrewBastin** [comment]
@ngocthua830 @khiemledev 

We would love to work with you to fix this weird issue.

Can you reach out to me via email on andrew [at] hoppscotch [dot] io ?

**Comment by Sun-FreePort** [comment]
@khiemledev Hi, Are you not found team by the "Select a team" choice?

When I more time not login, the defaut choice is loss, but can rechoice in the "Select a team" and go in.

**Comment by khiemledev** [comment]
No, I click on "Select a team" but there's no team on the list

**Comment by AndrewBastin** [comment]
@khiemledev I tried to reach out to you on Discord about updates and didn't get any updates.

We had patched this issue a while back. Please do report if this is still an issue.

**Comment by khiemledev** [comment]
@AndrewBastin I'm so sorry for the late response. So far so good, I'm not facing with the problem anymore

**Comment by AndrewBastin** [comment]
Okay, I am closing this issue assuming we have fixed this.
