### ISSUE TITLE
[feature]: Document build request from url params 

### ISSUE THREAD

**Issue by tzvc** [hoppscotch/hoppscotch#2576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I figured that building a request from url params is possible (ex. `hoppscotch.io?url=<url>&method=<method>`) but I couldn't find name for other url parameters in the documentation. For ex., what is the param name to say the req. will have a body encoded in `application/json`?

### Why should this be worked on?

I feel like building a hoppscotch request directly from a URL is a solid feature. For ex. in some API documentation, a link "Try it on Hoppscotch" could take you to hoppscotch with the request already ready. I would personally use it on https://chunk.run to give an easy way for users to try out their endpoint.

**Comment by liyasthomas** [comment]
Building requests from URL parameters were deprecated. Instead, now you can create shortcodes for any request setup and share them with your team or friends.

Here's the announcement post: https://twitter.com/liyasthomas/status/1462732159274217475
Here's a demo of shortcodes: https://twitter.com/liyasthomas/status/1462732175757828097

**Comment by tzvc** [comment]
Thanks for the prompt reply @liyasthomas
Shortcodes look great, but can they be built programmatically (for ex. to build a hopp.sh link with the user's info prefilled)?

**Comment by mst** [comment]
I'd be interested in this too. While the short link is a nice feature for sharing static requests, I'd love be able to build pre-filled requests without any additional code, just by applying a template. 

Was there a specific concern why this got feature removed?

**Comment by mst** [comment]
It looks like this is still possible, even being maintained.

https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-common/src/helpers/RESTExtURLParams.ts. 

I verified and it works like a charm. 

E.g. 
```
http://127.0.0.1:3000/?url=https://httpbin.org&path=put&headers=[{"key":"x","value":"y"}]&contentType=application/json&rawParams={"key":"1","value":{"x":"2"}}
```
