### ISSUE TITLE
[bug]: Fatal error with install Local development environment (Deploy with main Branch)

### ISSUE THREAD

**Issue by FirstDev0ps** [hoppscotch/hoppscotch#2605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
**_Deployed with main Branch_**
**_I'm trying run command pnpm -r do-dev, pnpm run generate_**
**_The situation is the same when I try to deploy Releasing version_**

root@hoppscotch:/home/hoppscotch# **pnpm install**
Scope: all 6 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
packages/codemirror-lang-graphql prepare$ rollup -c
│ 
│ src/index.js → dist/index.cjs, ./dist...
│ created dist/index.cjs, ./dist in 13.4s
└─ Done in 17.7s
packages/hoppscotch-data prepare$ tsup src --dts
[35 lines collapsed]
│ DTS dist/rest/index.d.ts          3.40 KB
│ DTS dist/graphql/index.d.ts       739.00 B
│ DTS dist/collection/index.d.ts    1.34 KB
│ DTS dist/rawKeyValue.d.ts         1.39 KB
│ DTS dist/rest/content-types.d.ts  462.00 B
│ DTS dist/rest/HoppRESTAuth.d.ts   853.00 B
│ DTS dist/graphql/HoppGQLAuth.d.ts 836.00 B
│ DTS dist/type-utils.d.d.ts        1.00 B
│ DTS dist/utils/eq.d.ts            969.00 B
│ DTS dist/utils/record.d.ts        326.00 B
└─ Done in 17.2s
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 332ms
packages/hoppscotch-js-sandbox postinstall$ **pnpm run build**
[9 lines collapsed]
│ CJS Build start
│ ESM ⚡️ Build success in 97ms
│ CJS ⚡️ Build success in 103ms
│ ESM lib/index.mjs     18.97 KB
│ ESM lib/index.mjs.map 38.94 KB
│ CJS lib/index.js     20.05 KB
│ CJS lib/index.js.map 38.94 KB
│ DTS Build start
│ DTS ⚡️ Build success in 6842ms
│ DTS lib/index.d.ts 2.65 KB
└─ Done in 10s
packages/hoppscotch-app postinstall$ pnpm run gql-codegen
[12 lines collapsed]
│ [07:33:04] Generate helpers/backend/graphql.ts [completed]
│ [07:33:04] Generate helpers/backend/backend-schema.json [started]
│ [07:33:04] Load GraphQL schemas [started]
│ [07:33:04] Load GraphQL schemas [completed]
│ [07:33:04] Load GraphQL documents [started]
│ [07:33:04] Load GraphQL documents [completed]
│ [07:33:04] Generate [started]
│ [07:33:04] Generate [completed]
│ [07:33:04] Generate helpers/backend/backend-schema.json [completed]
│ [07:33:04] Generate outputs [completed]
└─ Done in 8s
root@hoppscotch:/home/hoppscotch# **pnpm run dev**

> hoppscotch-app@2.2.1 dev /home/hoppscotch
> pnpm -r do-dev

Scope: 5 of 6 workspace projects
packages/hoppscotch-app do-dev$ pnpm run dev
│ > hoppscotch-app@2.2.1 dev /home/hoppscotch/packages/hoppscotch-app
│ > pnpm exec npm-run-all -p -l dev:*
│ [dev:nuxt       ] 
│ [dev:nuxt       ] > hoppscotch-app@2.2.1 dev:nuxt /home/hoppscotch/packages/hoppscotch-app
│ [dev:nuxt       ] > nuxt
│ [dev:nuxt       ] 
│ [dev:gql-codegen] 
│ [dev:gql-codegen] > hoppscotch-app@2.2.1 dev:gql-codegen /home/hoppscotch/packages/hoppscotch-app
│ [dev:gql-codegen] > graphql-codegen --config gql-codegen.yml --watch
│ [dev:gql-codegen] 
│ [dev:gql-codegen] [07:33:29] Parse configuration [started]
│ [dev:gql-codegen] [07:33:29] Parse configuration [completed]
│ [dev:gql-codegen] [07:33:29] Generate outputs [started]
│ [dev:gql-codegen] [07:33:29] Generate helpers/backend/graphql.ts [started]
│ [dev:gql-codegen] [07:33:29] Load GraphQL schemas [started]
│ [dev:gql-codegen] [07:33:30] Load GraphQL schemas [completed]
│ [dev:gql-codegen] [07:33:30] Load GraphQL documents [started]
│ [dev:gql-codegen] [07:33:33] Load GraphQL documents [completed]
│ [dev:gql-codegen] [07:33:33] Generate [started]
│ [dev:gql-codegen] [07:33:34] Generate [completed]
│ [dev:gql-codegen] [07:33:34] Generate helpers/backend/graphql.ts [completed]
│ [dev:gql-codegen] [07:33:34] Generate helpers/backend/backend-schema.json [started]
│ [dev:gql-codegen] [07:33:34] Load GraphQL schemas [started]
│ [dev:gql-codegen] [07:33:34] Load GraphQL schemas [completed]
│ [dev:gql-codegen] [07:33:34] Load GraphQL documents [started]
│ [dev:gql-codegen] [07:33:34] Load GraphQL documents [completed]
│ [dev:gql-codegen] [07:33:34] Generate [started]
│ [dev:gql-codegen] [07:33:35] Generate [completed]
│ [dev:gql-codegen] [07:33:35] Generate helpers/backend/backend-schema.json [completed]
│ [dev:gql-codegen] [07:33:35] Generate outputs [completed]
│ [dev:gql-codegen]   ℹ Watching for changes...
│ [dev:nuxt       ] Killed
│ [dev:nuxt       ]  ELIFECYCLE  Command failed with exit code 137.
│ [dev:gql-codegen]   Shutting down watch...
│ ERROR: "dev:nuxt" exited with 1.
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 33.1s
/home/hoppscotch/packages/hoppscotch-app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  hoppscotch-app@2.2.1 do-dev: `pnpm run dev`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
root@hoppscotch:/home/hoppscotch# 

### Steps to reproduce

0. Updated [.env.example] file found in packages/hoppscotch-app with my own keys and renamed it to .env.
1.[Clone this repo] with git https.
2.Install pnpm using npm by running npm install -g pnpm
3.Install dependencies by running pnpm install within the directory that you cloned (probably hoppscotch).
4.Start the development server with pnpm run dev.

### Environment

Production

### Version

Local

**Comment by FirstDev0ps** [comment]
The situation is the same when I try to deploy Releasing version

**Comment by AndrewBastin** [comment]
Can I have your node version ?

**Comment by FirstDev0ps** [comment]
node v14.20.0

**Comment by AndrewBastin** [comment]
Can you update to Node v16 (the current LTS version) and see ?

Also, from the logs you have posted, it seems there is an error code of 137, this usually happens when the Node runtime ran out of memory to allocate to the program. Do you have enough memory to allocate ?

**Comment by FirstDev0ps** [comment]
Ok thanks I have already updated the nodе version. What are the requirements for the machine to normal works?

**Comment by AndrewBastin** [comment]
Well usually we recommend around 1-3GB of free memory remaining to run the dev server with our current codebase.
That requirement should drastically go down once #2553 gets merged.

**Comment by FirstDev0ps** [comment]
Thanks, problem solved.
