### ISSUE TITLE
[feature]: ability to inline edit environment variable

### ISSUE THREAD

**Issue by anwarulislam** [hoppscotch/hoppscotch#2607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When we hover over the variable we see the value. It would be great if we can show an edit button to edit the value inline or at least prompt the user to edit that specific variable in the current modal implementation.

### Why should this be worked on?

It will be a cool feature that will increase developers' productivity. They can easily change the value of the variable

**Comment by TheHollidayInn** [comment]
Has this already been implemented now?
<img width="518" alt="Screen Shot 2022-10-15 at 7 04 37 PM" src="https://user-images.githubusercontent.com/1253400/196013121-2cc49b7a-1d49-46a3-a91d-b2958e27070e.png">

**Comment by anwarulislam** [comment]
@TheHollidayInn no it's not implemented. If you're interested to work on this feature you can take it.

**Comment by franciscoemanuel** [comment]
@anwarulislam Working on a PR for this and planning to submit it today.
