### ISSUE TITLE
[feature]: prompt for a selected text to set as variable

### ISSUE THREAD

**Issue by anwarulislam** [hoppscotch/hoppscotch#2608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If someone selects text we can show a tooltip with a button set as a variable. So, that they can easily set that string/text as the value of a variable.

### Why should this be worked on?

A nice feature to have.

**Comment by AlexHRodrii** [comment]
Can I work on that?

**Comment by liyasthomas** [comment]
Hi @AlexHRodrii, feel free to pick up this feature request. Assigning this to you.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.
