### ISSUE TITLE
[bug]: Can't migrate my GitHub account with my Google account

### ISSUE THREAD

**Issue by thomasbnt** [hoppscotch/hoppscotch#2610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I already have the account on Hoppscotch, one with my Google account (my main) and another one with my GitHub account.

I would like to migrate my GitHub account into my Google settings. But can't.

![image](https://user-images.githubusercontent.com/14293805/186477189-ace4df77-7e9e-4fb4-ac38-089103db7902.png)

When I click to 'Yes' and connect to my Google account, seems not working, because after disconnected and try with my GitHub account, this message show again.

### Steps to reproduce

1. Try to connect with GitHub
2. Got the message (see the screenshot)
3. Click on 'Yes' to connect 
4. Connect with Google account
5. Connected to the main account
6. Disconnect
7. Retry with GitHub account
8. Got the same error

### Environment

Production

### Version

Cloud

**Comment by aitchnyu** [comment]
Confirmed that login with Github returns a `Account exists with different credential - Login to link both accounts` every time. We are looking into it.

**Comment by tanathap** [comment]
is this problem fix? or is there a solution that allows me to login immediately?

**Comment by thomasbnt** [comment]
> is this problem fix? or is there a solution that allows me to login immediately?

Still an issue, you can maybe connect with your account.
