### ISSUE TITLE
[feature]: console.log in the Pre-Script

### ISSUE THREAD

**Issue by darwinsubramaniam** [hoppscotch/hoppscotch#2647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`console.log("HI")`

added console.log into the pre-request script , was expecting it work as it is simple javascript but it returns error 

- > ReferenceError: 'console' is not defined

### Steps to reproduce

1. Open https://hoppscotch.io/
2. Open Pre-request Script Tab.
3. Type in console.log("hi")
4. Send request

### Environment

Production

### Version

Cloud

**Comment by CHCoffman** [comment]
I have been working on this but for the post-request test runner where the response body of the request (or whatever else) can be logged to the console. Ex: pw.log(pw.response.body) to see the response's body. My code in test-runner.ts is 

```
        const logResponse = vm.newFunction("log", (input) => {
          const response = vm.dump(input)

          console.log(response)

          return { value: vm.undefined }
        })

        vm.setProp(pwHandle, "log", logResponse)
        logResponse.dispose()
```

pw-test.json: 
`"log" : "fn(value: ?)"`

Looks like console.log from the test runner to browser is blocked via `pure_funcs: ["console.log", "console.debug", "console.warn"],` in nuxt.config.js. 

When removing "console.log" from pure_funcs, you can now see it in the console. My question: is this important to keep or is this something that can be removed and the log function contributed as a feature?

**Comment by AndrewBastin** [comment]
Umm. We are working on this actually and are working towards implementing this and the other features mentioned in this RFC (#2292). This will take some time, but we are making steady progress which can be tracked over here (#2389)

**Comment by syamsoul** [comment]
hi.. just wondering when this feature will be deployed?

**Comment by ColdCerealAtWork** [comment]
This is one of the features that's keeping me on Postman, I utilize the console heavily.

**Comment by liyasthomas** [comment]
Hoppscotch's pre-request scripts and post-request tests have complete compatibility with [ECMAScript](https://tc39.es/ecma262) hence open the developer tools > console log in your browser (usually by pressing `F12` or `Ctrl/Cmd`+`Shift`+`I`) to view logs.

Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
