### ISSUE TITLE
[feature]: Ability to disable "Save my workspace" and "Login"

### ISSUE THREAD

**Issue by binaryfire** [hoppscotch/hoppscotch#2649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello

Companies often have security policies which prohibit devs from connecting to or logging in to external services. Would it be possible to provide a way to disable the "Save my workspace" and "Login" buttons?

Please note that this isn't related to: https://github.com/hoppscotch/hoppscotch/issues/1817. This isn't about private auth or a self-hosted backend. It's just about disabling the login / workspace save buttons.

Thanks!

### Why should this be worked on?

Security and giving users more control over the behaviour of the software on their local systems

**Comment by mnosov622** [comment]
Hello @binaryfire !

I would love to work on this feature. Could you provide more details, please ? In what situation buttons should be disabled ? 

Thank you.

**Comment by liyasthomas** [comment]
Closing this issue since this is not in our current scope and roadmap.
