### ISSUE TITLE
[feature]: Show raw body request

### ISSUE THREAD

**Issue by kayinleong** [hoppscotch/hoppscotch#2651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Functionality to show raw body request after the request is sent.

### Why should this be worked on?

This will be very helpful in debugging APIs, especially in multipart form.

**Comment by kromate** [comment]
Hi, I would like to work on this. 
Can this be assigned to me

**Comment by anwarulislam** [comment]
Hi @kromate!
Yeah, sure. I'm assigning you on this.

**Comment by kromate** [comment]
Hi @youknowwhoiamky for your feature request, can you explain better because it seem to me that showing raw body request is available already

**Comment by youknowwhoiamky** [comment]
Hi @kromate, for the raw body request, which will be show after the request is sent. I didn't find this feature in Hoppscotch. 

Example: 
![StructureOfAHTTPResponse-660x374](https://user-images.githubusercontent.com/34983642/195990799-0c3f119e-37c6-45f8-991f-139e2b3b2a4c.png)

**Comment by AndrewBastin** [comment]
Oh interesting, I am curious, why you require this feature to exist, the whole idea behind a tool like Hoppscotch is to parse and present this sort of information to use in a more clean manner.

**Comment by youknowwhoiamky** [comment]
I was playing around in Hoppscotch and comparing Hoppscotch with other software like Postman, Hoppscotch do not have an interface to show what is the raw request body after the request is sent. This is one of the examples show in Postman.

![image](https://user-images.githubusercontent.com/34983642/197374719-36db82da-d71b-4bdc-aae4-f89191e38190.png)

It's not really a must feature but it will be better if this feature exists in Hoppscotch.

**Comment by liyasthomas** [comment]
We have a feature that allows you to "Generate code snippets" for various programming languages and frameworks:

1. Click on the drop-down right next to the "**Send**" button to open the options menu.
2. Click on "**Show code**" menu item.
3. Select "**HTTP - HTTP 1.1 Request String**" from the "Generate code" modal.

This displays the current request setup in HTTP 1.1 Request String syntax. Let us know if this suits your use case.

![Step (1)](https://github.com/hoppscotch/hoppscotch/assets/10395817/58fda089-e533-4af8-8640-cd10c260c839)
![Step (2)](https://github.com/hoppscotch/hoppscotch/assets/10395817/a9576d4d-bf9f-40fd-8951-686b20859e69)

**Comment by kayinleong** [comment]
> We have a feature that allows you to "Generate code snippets" for various programming languages and frameworks:
> 
> 1. Click on the drop-down right next to the "**Send**" button to open the options menu.
> 2. Click on "**Show code**" menu item.
> 3. Select "**HTTP - HTTP 1.1 Request String**" from the "Generate code" modal.
> 
> This displays the current request setup in HTTP 1.1 Request String syntax. Let us know if this suits your use case.
> 
> ![Step (1)](https://user-images.githubusercontent.com/10395817/239894496-58fda089-e533-4af8-8640-cd10c260c839.png) ![Step (2)](https://user-images.githubusercontent.com/10395817/239894506-a9576d4d-bf9f-40fd-8951-686b20859e69.png)

Aight, this seems great to me!
