### ISSUE TITLE
[bug]: Env variable with dash in its name doesn't work in JSON body

### ISSUE THREAD

**Issue by aaronz-vipaso** [hoppscotch/hoppscotch#2665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use an env variable with a **dash in its name** in a JSON body, the variable does not become substituted with the actual value. Even though the variable is correctly highlighted green. 
![2022-09-15_09-08](https://user-images.githubusercontent.com/104493365/190339042-d7c79a60-cca1-48e2-9a6b-d410f280d522.png)

However when I use a env variable without dashes in its name in a JSON body, the variable becomes substituted with the actual value as expected.
![2022-09-15_09-10](https://user-images.githubusercontent.com/104493365/190339294-9ddeb392-ad7f-41ed-9641-da256ea3660e.png)

------

https://github.com/hoppscotch/hoppscotch/issues/1834
https://github.com/hoppscotch/hoppscotch/pull/1942

### Steps to reproduce

1. Create an env variable with dashes in its name
2. Create a request with a json body which uses this env variable
3. Send request – variable doesn't become substituted with the actual value

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
@anwarulislam can you take a look into this behaviour?

**Comment by anwarulislam** [comment]
> @anwarulislam can you take a look into this behaviour?

Yeah, looking into it

**Comment by Airomeo** [comment]
Now in 2023. Still not fixed yet.

**Comment by bvwidt** [comment]
Is there any update regarding this issue?
I am experiencing the same with the current version (v2024.6.0).

**Comment by liyasthomas** [comment]
@thetronjohnson can you look into this?

**Comment by liyasthomas** [comment]
I can't reproduce this behavior in the latest Hoppscotch version.

@bvwidt can you try force reloading the tab (command/ctrl + shift + r) and see if the issue persists at your end?

**Comment by bvwidt** [comment]
You are right @liyasthomas. It works without a problem now. Sorry for the circumstances.

I have just found two other very minor problems:

1. There is no dropdown menu in the body showing the variables when I press `CTRL + SPACE` unlike when using variables in the address bar.
2. After initially entering the variable it appears read but it works.
  ![red-variables](https://github.com/user-attachments/assets/532bf5b9-8fd0-4127-8ebb-7002ab5c4e79)
