### ISSUE TITLE
[feature]: Add key binding to toggle preview on response

### ISSUE THREAD

**Issue by vaugenwake** [hoppscotch/hoppscotch#2682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It is quite common during development cycles to want to print some text to the browser for debugging purpose. When this response comes through to hoppscotch currently it renders all the HTML of the page as raw text, there is a button to preview this HTML however currently you have to take your hands off the keyboard and click it to view what was printed.

### Why should this be worked on?

I propose that as you can trigger and configure requests right from the keyboard that being able to switch modes should also be accessible from a simple key shortcut.

This is a cycle most developers could do hundreds of times a day depending on what they are doing and is a simple feature to improve workflow.

**Comment by liyasthomas** [comment]
#2705 supersedes this PR, hence closing.

**Comment by vaugenwake** [comment]
@liyasthomas nice thanks 🤟
