### ISSUE TITLE
[bug]: Profile/teams settings unreachable

### ISSUE THREAD

**Issue by sam-lucas** [hoppscotch/hoppscotch#2713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Can no longer access profile/team settings from the settings page, as [documented here](https://docs.hoppscotch.io/features/collaboration), and can't fine a link anywhere else. The keyboard shortcut to open the profile page is not working for me, checked on both Chrome and Firefox. I can still access the profile and teams settings by navigating directly to https://hoppscotch.io/profile.

### Steps to reproduce

1. Go to https://hoppscotch.io/settings
2. Verify no profile or team settings present, as expected according to the docs

### Environment

Production

### Version

Cloud

**Comment by SerpentBytes** [comment]
I would like to work on this issue. Could one of the maintainers assign it to me? Thank you.

**Comment by liyasthomas** [comment]
Team section has been moved from [Settings page](https://hoppscotch.io/settings) to its dedicated Tab under [Profile page](url). I'll update the documentation to reflect this changes, hence closing this issue.
