### ISSUE TITLE
[feature]: Romanian language update

### ISSUE THREAD

**Issue by alinpisica** [hoppscotch/hoppscotch#2718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

- There are [Romanian translations](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/locales/ro.json) that are not / have not been updated.
- There are Romanian translations that are missing diacritics (e.g. "Curata tot" should be "Curăță tot").

### Why should this be worked on?

Consistent and correct usage of the Romanian language. I'm willing to start working on it if everyone's ok with it.

**Comment by liyasthomas** [comment]
If you'd like to write translations for Romanian language, kindly [consider helping us to improve translations](https://github.com/hoppscotch/hoppscotch/blob/main/TRANSLATIONS.md).

Since this is not a critical issue, I'm closing this issue ticket.
