### ISSUE TITLE
[bug]: UI: Real-time Log Entries `<div>`'s height decreases as the # of logs logged increases

### ISSUE THREAD

**Issue by Pranav-yadav** [hoppscotch/hoppscotch#2738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When the # of logs logged under realtime tab increases the height of the Log Entries container `div` **decreases**<sup>1</sup> in **Vertical Layout**, and becomes **Invisible** after sometime as the height becomes near 0.
Though, one can see all of the logs just by changing the **Layout** to _Horizontal_...

Find steps to repro. this bug, under below subheading.
Also if possible, please confirm and assign this bug to **me** with some hints to fix this UI bug. Would love to fix this bug as part of Hacktoberfest  :)

### Steps to reproduce

1. Go to [https://hoppscotch.io/realtime/websocket](https://hoppscotch.io/realtime/websocket)
2. Make sure you're on **Realtime** Tab
3. Click **Connect** btn. (You may change the URL or keep the default)
4. Make sure you're _connected_
5. Observe how height of the realtime log entries container `<div>` **decreases**<sup>1</sup> as the # of log entries increases.

[1] Height decreases in the _**Viewport**_, tho practically increases :)

### Environment

Production

### Version

Cloud

**Comment by mnosov622** [comment]
Hello @Pranav-yadav !

Can you assign this issue to me, please? I would love to fix this bug :)

**Comment by liyasthomas** [comment]
Hi @mnosov622, feel free to pick up this issue, assigning it to you.

**Comment by mnosov622** [comment]
Thank you @liyasthomas :)

**Comment by mnosov622** [comment]
Hi @liyasthomas !

When I'm setting the project and trying to open it, I get white screen, do you know why it might happen ?
![image](https://user-images.githubusercontent.com/73063742/195236479-14c7dbdb-fbd5-4f87-b934-9cd776130021.png)

**Comment by liyasthomas** [comment]
Hi @mnosov622, have you followed the [local development environment](../#local-development-environment) setup guide as described in our [README](../#developing)?

**Comment by mnosov622** [comment]
Hi @liyasthomas !

I did, but I will do it one more time. Thank you!

**Comment by mnosov622** [comment]
Hi @liyasthomas !

When setting up the project, I have this issue when running `pnpm install`.

![image](https://user-images.githubusercontent.com/73063742/195762899-0b08e066-8914-43ac-92b4-70633a49226b.png)
![image](https://user-images.githubusercontent.com/73063742/195762935-71e67f29-7603-43bf-93b5-84b3c71ad297.png)


What might be an issue ?
