### ISSUE TITLE
[bug]: unable to go to profile page when registering through email

### ISSUE THREAD

**Issue by jerbob92** [hoppscotch/hoppscotch#2745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When logging in through email, you can't go to the profile page because the `ProfilePicture` component can't be rendered.

### Steps to reproduce

1. Login in through email
2. The `ProfilePicture` won't be rendered because there is no `photoURL` and no `displayName`

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@jerbob92 is this causing issues in `hoppscotch.io`/built instances or on dev server only ? I wasn't able to catch it from my end, but we did see this issue popup in our telemetry.

#2742 should fix this.

**Comment by jerbob92** [comment]
@AndrewBastin Wouldn't it be better to use the email as display name? Not `Hoppscotch User`?
