### ISSUE TITLE
[bug]: team environment importing function is not working

### ISSUE THREAD

**Issue by nickwph** [hoppscotch/hoppscotch#2769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

in "team environment" setting, when i am trying to import a json-based (exported from hoppscotch). it shows import successfully. however the environments are not showing up. no errors are shown in the developer console.

### Steps to reproduce

Go to "Rest"
Go to "Environments"
Select  "Teams environments"
Click "Import/Export" icon
Click "Import from Hoppscotch"
Select an exported environment json file
Click "Import"
-> Data is not imported

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
@nivedin, can you look into this.
