### ISSUE TITLE
无法执行预请求脚本啊 总是报错

### ISSUE THREAD

**Issue by wwg2017** [hoppscotch/hoppscotch#2783]
无法执行预请求脚本啊 总是报错
![image](https://user-images.githubusercontent.com/27998578/195819806-c18f9dd4-8831-48f3-91f1-e94dc688abfb.png)

**Comment by liyasthomas** [comment]
Please choose any of the provided [issue templates](https://github.com/hoppscotch/hoppscotch/issues/new/choose) to report bugs, feature requests etc with detailed description and steps to reproduce.

**Comment by wwg2017** [comment]
> Please choose any of the provided [issue templates](https://github.com/hoppscotch/hoppscotch/issues/new/choose) to report bugs, feature requests etc with detailed description and steps to reproduce.

就https://hoppscotch.io/ 这个站点，，随便输入一个js脚本    console.log("str→"); 然后点击发送

**Comment by liyasthomas** [comment]
Pre-request scripts doesn't support `console.log()` at the moment. We're working towards an improved scripting sandbox API via [Scripting revamp RFC](https://github.com/hoppscotch/hoppscotch/discussions/2292). Kindly share your thoughts on that discussion.

For more details on supported pre-request script API, [refer documentation](https://docs.hoppscotch.io/features/pre-request-script).

**Comment by wwg2017** [comment]
> Pre-request scripts doesn't support `console.log()` at the moment. We're working towards an improved scripting sandbox API via [Scripting revamp RFC](https://github.com/hoppscotch/hoppscotch/discussions/2292). Kindly share your thoughts on that discussion.

ok,多谢，还有一个问题就是，，如果文件夹下面的请求多了情况下，打开文件夹会很慢很卡

**Comment by wwg2017** [comment]
> Pre-request scripts doesn't support `console.log()` at the moment. We're working towards an improved scripting sandbox API via [Scripting revamp RFC](https://github.com/hoppscotch/hoppscotch/discussions/2292). Kindly share your thoughts on that discussion.
> 
> For more details on supported pre-request script API, [refer documentation](https://docs.hoppscotch.io/features/pre-request-script).

CryptoJS.MD5(str).toString();  这个函数支持吗
