### ISSUE TITLE
[bug]:  Failed to load schema for "src/helpers/backend/backend-schema.json"

### ISSUE THREAD

**Issue by yashram96** [hoppscotch/hoppscotch#2787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i ran pnpm install 
i got below errors 

packages/hoppscotch-app postinstall$ pnpm run gql-codegen
│ > hoppscotch-app@3.0.1 gql-codegen /home/yashram/apiclient/hoppscotch/packages/hoppscotch-app
│ > graphql-codegen --require dotenv/config --config gql-codegen.yml
│ [STARTED] Parse Configuration
│ [SUCCESS] Parse Configuration
│ [STARTED] Generate outputs
│ [STARTED] Generate src/helpers/backend/graphql.ts
│ [STARTED] Load GraphQL schemas
│ [FAILED] Failed to load schema
│ [FAILED] Failed to load schema
│ Failed to load schema for "src/helpers/backend/backend-schema.json"
│         Failed to load schema from undefined:
│         
│       Unable to find any GraphQL type definitions for the following pointers:
│         
│           - undefined

'
'
'
'
'
│ [STARTED] Generate src/helpers/backend/backend-schema.json
│ [STARTED] Load GraphQL schemas
│ [SUCCESS] Generate outputs
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 1.7s
 ELIFECYCLE  Command failed with exit code 1.

### Steps to reproduce

Run  pnpm install 
you will get error 

### Environment

Deploy preview

### Version

Self-hosted

**Comment by AndrewBastin** [comment]
Copy `.env.example` in `packages/hoppscotch-app` and paste and rename it as `.env`

@liyasthomas update README ?

**Comment by ziyangcommon** [comment]
readme file seems not update yet

**Comment by liyasthomas** [comment]
[Here's the link to README's "Developing" section.](https://github.com/hoppscotch/hoppscotch#developing)

<img width="927" alt="Screenshot 2023-01-11 at 9 18 05 AM" src="https://user-images.githubusercontent.com/10395817/211713510-c8729eae-12a5-4977-ab7e-5ad351db2b8c.png">
