### ISSUE TITLE
[bug]: Team Collections vanished

### ISSUE THREAD

**Issue by kirstyannepollock** [hoppscotch/hoppscotch#2804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

At 10:35 today I used queries from my Team Collections.
One minute later, they were not there, the Collections were empty.
My teammates did not delete them.
Team is still there.
Team Environments are still there.
History is also there and the queries work.
I logged out and in again, but the same issue is still occurring.

Naturally, this is a big deal to us!

### Steps to reproduce

Go to Collections
Click on Team Collections
No collections are listed.

Expected behaviour:
The team collections should be listed

### Environment

Production

### Version

Cloud

**Comment by kirstyannepollock** [comment]
Ok, even stranger, the Team Collections appeared in the list when saving a query, and after saving a query to a Team Collection, the Team Collections were once more visible in the list.

**Comment by AndrewBastin** [comment]
Hi @kirstyannepollock!

Sorry about the issues you are facing, we will look into this incident and will try to resolve this issue.

We will need some additional info to help us track this down though, can you email me at 'andrew [at] hoppscotch [dot] io'.

**Comment by kirstyannepollock** [comment]
Hi Andrew,The issue with the collections not being listed seemed to be a one off- fixed as soon as I saved a query to a collection (which I could still do)More annoying is we found I could not import the collections after a team mate exported them -should I raise a separate issue for that?On 19 Oct 2022 11:20, Andrew Bastin ***@***.***> wrote:
Hi @kirstyannepollock!
Sorry about the issues you are facing, we will look into this incident and will try to resolve this issue.
We will need some additional info to help us track this down though, can you email me at 'andrew [at] hoppscotch [dot] io'.

**Comment by AndrewBastin** [comment]
@kirstyannepollock you can close this issue then, we are tracking intermittent issues like this internally separately.

But if that import issue is consistent, please do feel free to open a new issue.
