### ISSUE TITLE
[feature]: Is the collection feature available for self-hosted hopscotch instances?

### ISSUE THREAD

**Issue by Sand33pSrinivasan** [hoppscotch/hoppscotch#2807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

@liyasthomas Is the collection feature available for self-hosted hopscotch instances?

### Why should this be worked on?

Is the collection feature available for self-hosted hopscotch instances?

**Comment by AndrewBastin** [comment]
This is not a valid issue, questions like these should be opened as Discussions please.

And as for your answer, at the moment, personal collections work on self hosted, teams features do not. We are working on porting it though and hope to release it early next year.
