### ISSUE TITLE
[feature]: Team collections is not available in self hosted hoppscotch

### ISSUE THREAD

**Issue by Sand33pSrinivasan** [hoppscotch/hoppscotch#2808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I tried to self host hoppscotch but the team collection is not working. @liyasthomas Please help on the same .

@AndrewBastin Can you please help me if this available for the same. 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/95906762/197210553-62f89291-43e6-4a73-913e-b90b7b606b8b.png">

### Why should this be worked on?

This is will be more helpful in replacing postman and save a lot of money on the same 🥇

**Comment by LogSpider** [comment]
> Team collections are not available for self-hosted instances at the moment. We’re working towards a self hosted Hoppscotch instance support for Q1 2023. Keep track of the feature on #1817.
> 
> Since the scope of team collections comes under full self hosting support, I’m closing this issue as a duplicate.

#1817 is locked in cause of teh discussion heatage, everything is cloud, on prem should be more present, some data need to stay local, not every like their tokens in the cloud. leaks are present to often...pwned passwords, known tokens of all your api's...."well that escalated quickly"
