### ISSUE TITLE
[bug]: GET Request not using Content-Type application/json Header

### ISSUE THREAD

**Issue by MatheusGrilo** [hoppscotch/hoppscotch#2828]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

My JSON on Body do not send when I use GET method (with and without Header modification):
![image](https://user-images.githubusercontent.com/7491570/198163433-49bd2487-1c1b-46ae-8be8-1cdcdc3e354b.png)
![image](https://user-images.githubusercontent.com/7491570/198162743-e2b4c215-8771-4d96-a32a-972e50b07868.png)
![image](https://user-images.githubusercontent.com/7491570/198162762-f367931c-1d2e-4c4a-8163-bfec598344f7.png)

My console.log(req.body) and everything I want on body:
![image](https://user-images.githubusercontent.com/7491570/198162888-f95fc8cd-a81a-4c03-a1ae-927b08b93f45.png)

Tested on Google Chrome's App and on Hoppscotch.io itself, also tried to remove `<<baseUrl>>` with no success. Tested on localhost and on Heroku. 
Works fine with Insomnia as you can see bellow:
![image](https://user-images.githubusercontent.com/7491570/198162723-8fc19d0f-26e4-4d49-b536-7eec69d51a45.png)
![image](https://user-images.githubusercontent.com/7491570/198163377-230057e4-8f15-4deb-b4a0-6bbd9a1f4ded.png)

My console.log(req.body) and everything I want on body with Insomnia:
![image](https://user-images.githubusercontent.com/7491570/198162954-88ccfac2-05c4-4800-bdca-6072562b0c95.png)

### Steps to reproduce

Use GET Method and try to send a Json Body.
Get **undefined** as result.

### Environment

Production

### Version

Local

**Comment by MatheusGrilo** [comment]
Okay, I will accept that as an answer since I won't use this in production, and was only using in development. Was just an idea since it's possible for tests, but not a real thing.

**Comment by thomas-frantz** [comment]
> Due to implementation limitations of the browser, I don't think we will be able to support/implement it directly. Along with that, sending a body on GET is generally an undefined behaviour in the HTTP spec.
> 
> Welcoming discussions on this.

The only problem with this is when we can't control the APIs. I develop our own company API, and I can do that according to the spec just fine. But I can't control the various other vendors and customers APIs we integrate with who don't do this, many of which do use a body on GET requests. Which essentially makes this unusable for us, unless I'm missing something.
