### ISSUE TITLE
[feature]: disable syncs when hosted locally

### ISSUE THREAD

**Issue by AndrewBastin** [hoppscotch/hoppscotch#2831]
### Discussed in https://github.com/hoppscotch/hoppscotch/discussions/2822

<div type='discussions-op-text'>

<sup>Originally posted by **davew94** October 24, 2022</sup>
Hi,

In my organisation we only want members of staff to sync with hoppscotch using one method (microsoft). Is it possible to disable syncs (github/google) if hoppscoth is hosted within our company network?</div>

**Comment by Tejasvp25** [comment]
Well i think we can use env variable to disable sync if we want to disable sync altogether, If we want to disable specific auth provider we can go with same idea. Let me know what you guys think :)

**Comment by AndrewBastin** [comment]
@Tejasvp25 that is an idea we are going for. We will look into introducing this when we release a self-hosting specific full stack build of Hoppscotch which we are working on.

**Comment by AndrewBastin** [comment]
@Brainpitcher we are currently working on it, but we are aiming for the initial release to be around early 2023.

**Comment by Brainpitcher** [comment]
> @Brainpitcher we are currently working on it, but we are aiming for the initial release to be around early 2023.

thanks for your answer... now we just have to wait

**Comment by GAS85** [comment]
> @Brainpitcher we are currently working on it, but we are aiming for the initial release to be around early 2023.

It is early and it is 2023 😆 I really miss this feature for self hosting.

**Comment by AndrewBastin** [comment]
Hey all,

Thank you for waiting all this time!

Fully Self Hostable Instances of Hoppscotch are now available as a Beta, we would love everyone's feedback to make this more stable! Read more at: https://docs.hoppscotch.io/documentation/self-host/getting-started
