### ISSUE TITLE
There is a problem with the git uploaded to our company

### ISSUE THREAD

**Issue by wwg2017** [hoppscotch/hoppscotch#2834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

There is a problem with the git uploaded to our company

### Steps to reproduce

There is a problem with the git uploaded to our company

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Provide relevant context and use appropriate issue template to create issue tickets.
