### ISSUE TITLE
[bug]: PWA/Webapp freezes when trying to edit a team

### ISSUE THREAD

**Issue by supmanyu** [hoppscotch/hoppscotch#2870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i click on the Edit CTA for a team in the profile > teams tab, the PWA/webapp freezes completely, and has to be force closed. Because of this we are unable to manage permissions and members for our org's team.

### Steps to reproduce

1. Go to your profile from the profile menu in the top-right.
2. Switch to the `teams` tab
3. Click on the `Edit` CTA of a team.
4. App becomes completely unresponsive and has to be force-closed to be useable again.

### Environment

Production

### Version

Cloud

**Comment by amk-dev** [comment]
this should be fixed in #2871
