### ISSUE TITLE
[bug]: Current request uses the previous request's body

### ISSUE THREAD

**Issue by mateo-m** [hoppscotch/hoppscotch#2872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If a user switches between -previously sent- requests using the "History" tab in a specific way (as described in the "*Steps to reproduce*" part), a current request uses the last request's body.

### Steps to reproduce

*I used a **company's private API**, so I'll just describe how I did it with said API, but you can try any API with POST routes using different payloads for each route.*

1. Send a request with `Method` set to `Ping` (let's call that "<ins>payload 1</ins>").
2. Send a request with `Method` set to `GetOrder` (let's call that "<ins>payload 2</ins>").
3. Switch to request used in step **1** (`Ping`) from the "History" tab, then click "Discard changes".  (⚠️ Don't send the request ⚠️)
4. Switch to request used in step **2** (`GetOrder`) from the "History" tab.
5. Change the `Method` field's value to `Ping` (= effectively modifying <ins>payload 2</ins>), then send a request with the updated body.
6. **Bug**: request sent in step **5** is using the body's value of the request in step **4** (which is the same request as the one in step **2**).

<ins>Demonstration video</ins>:

https://user-images.githubusercontent.com/23667794/206548681-c921654c-eed1-44d6-81f5-41621232a9bf.mp4

ℹ️ **The demo video was recorded in guest mode in Brave with no extensions enabled, and I could reproduce the bug on Firefox aswell.**

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
@amk-dev

**Comment by amk-dev** [comment]
@mateo-m thank you for reporting this and making a comprehensive bug report. it should be fixed in #2873

**Comment by mateo-m** [comment]
> @mateo-m thank you for reporting this and making a comprehensive bug report. it should be fixed in #2873

Great, thank you for handling this issue this quick!
Do you know when this PR will be merge/will be available in production ?

**Comment by liyasthomas** [comment]
The fix is now available in production, refresh the app to take effect the latest changes. Kindly reopen this thread if the issues is not resolved.
