### ISSUE TITLE
[feature]: Prettify response

### ISSUE THREAD

**Issue by marc0l92** [hoppscotch/hoppscotch#2877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I call a JSON api that replies with a minified JSON it is really difficult to read the response.
I would be useful to have a prettify feature for the response:
![image](https://user-images.githubusercontent.com/12623073/207164525-da7d937a-23c0-4387-bbbe-6dc5e67c7d65.png)

### Why should this be worked on?

Increase readability of API responses without using external tools to prettify the JSON.

**Comment by anwarulislam** [comment]
@marc0l92 Currently, we prettify JSON before rendering it. There might be an issue with the JSON object when we try to stringify it with space.

**Comment by anwarulislam** [comment]
@AndrewBastin I have checked this. `LJSON.parse()` method is not working with this specific object. But, when I use `JSON.parse()` it works.

**Comment by harish343** [comment]
how can i start work on this issue

**Comment by liyasthomas** [comment]
Hi @harish343, you can look into this feature request.

**Comment by jaysoni-ash42** [comment]
@liyasthomas  updating the version of lossless-json resolves this parsing issue.
