### ISSUE TITLE
[bug]: hoppscotch is still called Postwoman in wiki

### ISSUE THREAD

**Issue by ShahriarKh** [hoppscotch/hoppscotch#2884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

https://github.com/hoppscotch/hoppscotch/wiki/PWA/6dcee74f06c2da5148ac7d012ba9d5ff1afd85ac

### Steps to reproduce

-

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
I’ve patched this issue, hence closing.
