### ISSUE TITLE
[bug]: Time counter doesn't stop (ever) after a request was cancelled

### ISSUE THREAD

**Issue by cpt-westphalen** [hoppscotch/hoppscotch#2897]
This might be a simple issue to solve:

I use the web Hoppscotch app.
If my API has a bug and doesn't respond to a request, Hopp allows me to click the big "cancel" button to stop the listening.

After that, every other request I make happens to -- as fast as the response time is -- never clear the time counter again:

![image](https://user-images.githubusercontent.com/97403327/211075892-c415d03e-a189-46aa-84df-cecf2210855c.png)

The solution is probably just checking the counter function and the cancel button function to see what's missing.

Thank you all for this amazing app, by the way. :)

**Comment by Imaginarybandit** [comment]
Hello, I would like to tackle this issue

**Comment by aitchnyu** [comment]
@cpt-westphalen I'm having a hard time reproducing this bug. Could you describe how to trigger it in steps I can do?

**Comment by cpt-westphalen** [comment]
@aitchnyu This is it:

1. New folder, `npm init -y`, `npm i express`;
2. Create `index.js` file on root;
3. Paste this:

```
// index.js
const express = require("express");
const app = express();

app.get("/", (req, res) => console.log("this wont reply, ever."));
app.get("/reply", (req, res) => res.json({ hello: "world" }));

app.listen(3000, () => console.log("Serving at: http://localhost:3000/"));

```
4. Run `node index.js` on terminal;
5. Open [Hop](https://hoppscotch.io/) on latest Firefox (did not test on Chrome);
6. Configure it to use the Firefox extension to hit the localhost;
7. On Hop, select `GET`, paste/type `http://localhost:3000/reply` and send request. // **=> it will answer with < 100ms.**
8. Keep `GET`, paste/type `http://localhost:3000/` and send request. // **=> it will load for several seconds**
9. Before the loading bar gets to the end, click the blue `Cancel` button to stop listening for response.
10. Keep `GET`, paste/type `http://localhost:3000/reply` and send request. // **=> it will answer with a huge response time**

**Comment by abrahamparayil** [comment]
@cpt-westphalen I tried to reproduce the bug using the steps you have mentioned here but I am unable to reproduce the issue. The second `GET` request mentioned in step 10 responds back almost instantaneously.

Cc: @aitchnyu

**Comment by aitchnyu** [comment]
I can confirm for Firefox. Will check with others.

[Screencast from 2023-02-06 20-08-02.webm](https://user-images.githubusercontent.com/5927706/217001056-fca2599e-b945-4fbb-bcea-78afc25dc198.webm)

**Comment by Vansh-Baghel** [comment]
@aitchnyu I guess that fixes the issue, right?
