### ISSUE TITLE
[feature]: Better environment variable UX/UI

### ISSUE THREAD

**Issue by furier** [hoppscotch/hoppscotch#2906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

As mentioned in #2574 the environment variable UX/UI could definitely improve tenfold. As of now I find it very hard to see at any given time what environment variables I am using, and you need many clicks to check and/or change environment variables.

Support for sub environment variables would also be a great idea.

Similar UI as Insomnia as shown here would be great.
![image](https://user-images.githubusercontent.com/776919/214540341-b68908a4-f3ef-4b17-8c8d-05396c81fb6f.png)

### Why should this be worked on?

I am not sure I can get my colleagues to adopt Hoppscotch because of the simple fact that it is nearly impossible to see what environment you are working on and or change it.

Can live without sub environments but it would be such a nice addition to also have that.

**Comment by liyasthomas** [comment]
Kindly suggest any possible UI improvements in #2574.
Since this issue is traced under #2574, I'm closing this ticket.

**Comment by furier** [comment]
@liyasthomas as commented in #2574 it was kindly asked to split all the feature requests in the issue into their own issues! So I did... Because the issue had been dead for months...
