### ISSUE TITLE
[feature]: 

### ISSUE THREAD

**Issue by Rohittater255** [hoppscotch/hoppscotch#2932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In Postman, There is option to Import New Request API request as Curl But In Hoppscoth I dont see such option
Reference: https://dev.to/stephencweiss/how-to-test-your-api-using-curl-postman-382c

### Why should this be worked on?

This will save a lot of TIme From Dev/QA team as they will be able to add/Import API Request Directly as curl

**Comment by liyasthomas** [comment]
Hi @Rohittater255, you can import a cURL request to Hoppscotch by simply pasting it on URL input bar in REST page. Or alternatively, click on the “More options” drop-down button right next to “Send” > “Import cURL”.
