### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by whyisthatyou** [hoppscotch/hoppscotch#2934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when i clone the responsibility and run "npm install"  ,return the error:
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^0.4.4

### Steps to reproduce

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^0.4.4

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment]
Please look into the README instructions carefully.

An excerpt from the [Developing](https://github.com/hoppscotch/hoppscotch#developing) section:
> 2. Install pnpm using npm by running `npm install -g pnpm`.
> 3. Install dependencies by running `pnpm install` within the directory that you cloned (probably hoppscotch).

Please follow these steps and do a `pnpm install` instead of `npm install`.

**Comment by whyisthatyou** [comment]
pnpm install is ok ,now "pnpm run dev " does not work,error message: 

packages/hoppscotch-web do-dev$ pnpm run dev
│ > @hoppscotch/web@0.0.0 dev C:\Users\whyisthatyou\Desktop\hoppscotch-main\packages\hoppscotch-web
│ 'vite' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ ���������ļ���
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 2s at C:\Users\whyisthatyou\Desktop\hoppscotch-main\packages\hoppscotch-web

**Comment by AndrewBastin** [comment]
Is this the output you exactly received ?
The ASCII output is really weird.
