### ISSUE TITLE
[bug]: Header content type (application/json) is not sent in the request

### ISSUE THREAD

**Issue by ptrkhh** [hoppscotch/hoppscotch#2937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to create a request like this

![image](https://user-images.githubusercontent.com/46017850/222331552-688fdc1c-aa61-4d4b-9d3d-d1ac452a05a7.png)

The response says "Media not support", and when I clicked on "Show code", the value for `Content-Type` is missing

![image](https://user-images.githubusercontent.com/46017850/222331912-38b934a0-fc3b-49fb-bdaf-40892924de1a.png)

### Steps to reproduce

1. Create a new request
2. Go to `Body`
3. Set `Content-Type` to `application/json`
4. Set request type to `POST`

### Environment

Production

### Version

Cloud

**Comment by ajay-vishnu** [comment]
Hello @ptrkhh, I tried to reproduce this scenario but I didn't get this bug. Can you elaborate a bit on how this happened to you?

<img width="674" alt="image" src="https://user-images.githubusercontent.com/52136562/229067938-3613ac10-4843-4bea-a2c9-be199aa828b8.png">

<img width="401" alt="image" src="https://user-images.githubusercontent.com/52136562/229068046-d584abf0-0357-44da-9d38-013a1f6e33c4.png">

**Comment by ptrkhh** [comment]
Weirdly enough, I can't seem to replicate it for now. I'll let you know when I could

**Comment by ajay-vishnu** [comment]
Alright, sure thing.
