### ISSUE TITLE
[feature]:   json collapse 

### ISSUE THREAD

**Issue by linpan** [hoppscotch/hoppscotch#2938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

sometime  big json have embed object or array,  hope support collapse fields.

### Why should this be worked on?

sometime  big json have embed object or array,  hope support collapse fields.

**Comment by linpan** [comment]
hotkey  for collapse json

**Comment by liyasthomas** [comment]
Hoppscotch uses [CodeMirror](https://codemirror.net) under the hood.
CodeMirror 6 supports the folding shortcuts natively (per [foldKeymap](https://codemirror.net/docs/ref/#language.foldKeymap)):

- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> [<kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>[</kbd> on macOS]: Fold the lines that are selected, if possible.
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>]</kbd> [<kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>]</kbd> on macOS]: Unfold folded ranges on selected lines.
- <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>[</kbd>: Fold all top-level foldable ranges.
- <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>]</kbd>: Unfold all folded code.

or click on the gutter to fold a block, again to unfold.

![screely-1677738746735](https://user-images.githubusercontent.com/10395817/222352334-045a021a-1f93-47a4-bdee-df96146b96f9.png)

![screely-1677739457603](https://user-images.githubusercontent.com/10395817/222352365-a2140b1d-654f-45d3-8437-2073183929a1.png)
