### ISSUE TITLE
[feature]: Some modals do not close when clicking outside

### ISSUE THREAD

**Issue by yuriybelike** [hoppscotch/hoppscotch#2945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Closing a modal when clicking outside/on the overlay is such a common pattern for me.

In Hoppscotch, some modals follow this, some do not.

Modals that **do not** close:
- Support 
- Login to Hoppscotch
- New collection
- Collections
- Save as
- ...?

Modals that **do** close:
- Search
- ...?

I understand some of those that do not close should be left as is, [so no data/input is lost](https://ux.stackexchange.com/questions/94423/should-clicking-outside-an-important-modal-close-it), but some (like "Support" or "Login to Hoppscotch") do not have this need.

### Why should this be worked on?

I think it's a very [common pattern](https://ux.stackexchange.com/questions/23043/should-a-popup-lightbox-close-when-a-user-clicks-outside-of-the-box)

**Comment by jaysoni-ash42** [comment]
@yuriybelike  i want to work on this issue but on which modal it should closes and on which it should not can you plz point that out?
