### ISSUE TITLE
[bug] Control+F not working in result from API request

### ISSUE THREAD

**Issue by JulienPerrin** [hoppscotch/hoppscotch#2946]
I haven't found an issue for this. 

When doing control+F after having clicked inside the result of an API request, if I search for text that is hidden, the page will scroll, hide the search input, and not display properly the text search. 

3 steps to reproduce : 

1. to reproduce, from this page (result need to be not fully displayed, there must be a need to scroll) : 

![image](https://user-images.githubusercontent.com/7848947/224097402-e1e4b9c3-dc10-45ba-89dc-35ce14a9cc3b.png)

2. do control+F on "true" : 

![image](https://user-images.githubusercontent.com/7848947/224098208-42bc5bb8-81eb-46c2-a927-d0c6cb44ab22.png)

3. click on next : both top and bottom is wrong : \
control+F input is hidden and "true" is hidden. I can see it if I scroll down one time. 
![image](https://user-images.githubusercontent.com/7848947/224098947-bc3dece4-b3f6-432a-b684-6a604dc1a7a0.png)

"true" was hidden, I see it if I scroll down a bit : 
![image](https://user-images.githubusercontent.com/7848947/224099398-e94a8501-3879-4bf5-a9e1-61c1779497ed.png)

**Comment by win20** [comment]
Hey just wanted to leave a comment and say I was interested in working on this, however I'm having some issues setting up my local environment, after forking and cloning I'm doing pnpm install but it gives me this error:
[[FAILED] Failed to load schema.MD](https://github.com/hoppscotch/hoppscotch/files/11125479/FAILED.Failed.to.load.schema.MD)

Anyone able to help?
Thanks

**Comment by AndrewBastin** [comment]
@win20 thank you for your effort!

The error you are facing is most probably because you haven't set the .env file correctly. Follow the README steps exactly and it should work!

**Comment by win20** [comment]
@AndrewBastin Hi thank you for the response :)
But I'm still a bit confused when it says replace the contents of .env.example with your own, does this mean Ihave to create my own projects in Firebase and GraphQl and hook it up? Wouldn't I have populate them with the appropriate data or set them up accordingly? If so how would I do that please?

PS: I did just test that by creating an api key on firebase and added it which enabled `pnpm install` to work but then when I run `pnpm run dev` I get another error.

**Comment by AndrewBastin** [comment]
@win20 you can use the keys in .env.example itself to test stuff (in localhost:3000).

I would like to see the error you get while running `pnpm run dev` though.

**Comment by win20** [comment]
So I'm trying to just keep everything in .env.example the same and just change the file name to .env but this is the error I get when I run `pnpm run dev` and go to localhost:3000:
![Screenshot 2023-04-02 at 15 32 32](https://user-images.githubusercontent.com/22985058/229359627-1b34f7a3-9136-4bde-84c3-14ed74adf5b3.png)

**Comment by liyasthomas** [comment]
Closing this ticket in favor of #3240. Track the progress of this issue on the successor issue ticket.
