### ISSUE TITLE
[bug]: Wiki button in search bar leads to 404 not found page

### ISSUE THREAD

**Issue by win20** [hoppscotch/hoppscotch#2957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Clicking on the wiki button inside the search bar opens a 404 not found page in a new tab, see below:

### Steps to reproduce

On the main page click the wiki button:
![Screenshot 2023-03-31 at 20 26 21](https://user-images.githubusercontent.com/22985058/229211461-152a308f-a232-4cb9-9c77-4585fb5c6a38.png)

![Screenshot 2023-03-31 at 20 26 47](https://user-images.githubusercontent.com/22985058/229211512-743319c5-f8f9-4fb7-a114-1910f27b1a06.png)

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
We'll be working on fixing these issues leading to 404 page in Documentation site soon. Thanks for reporting the issue.

**Comment by Bazigar69** [comment]
@liyasthomas can I take this issue, Please tell me what is expected behavior, after click it should redirect to https://docs.hoppscotch.io/documentation/getting-started/introduction/ right?
