### ISSUE TITLE
[bug]: When I tried to change the app language  to English with router, it could not take effect 

### ISSUE THREAD

**Issue by 704572066** [hoppscotch/hoppscotch#2959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I tried to change the app language  to English with url, it could not take effect 

### Steps to reproduce

I changed the app language to chinese with url , it took effect.
![image](https://user-images.githubusercontent.com/23404868/229428477-1bd964ff-084f-4f83-b041-6d6459f376db.png)
![image](https://user-images.githubusercontent.com/23404868/229428817-7a3670d7-5c3c-4754-84c8-cb07b015128e.png)
when I changed the app language from chinese to english, it could not take effect.
![image](https://user-images.githubusercontent.com/23404868/229430007-790e7689-ecc9-4dd7-abcd-2c8c09529512.png)
![image](https://user-images.githubusercontent.com/23404868/229429400-998b28e8-5f91-4740-af7b-c2de921ff8f4.png)

### Environment

Production

### Version

Cloud

**Comment by anwarulislam** [comment]
@704572066 Hi, I have tried to reproduce the issue. But, I see it's working fine. Could you please tell me how can I reproduce if the issue still exists?
