### ISSUE TITLE
[bug]: the documentation is wrong or is lack of information about self-hosted

### ISSUE THREAD

**Issue by fuechter** [hoppscotch/hoppscotch#2976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I follow all the steps of doc about self-hosted (https://docs.hoppscotch.io/documentation/self-host/install-and-build), some packages doesn't exist like `packages/hoppscotch-backend` and any services cited to up on docker-compose doesn't exist also. 

```
docker compose up hoppscotch-backend # Runs the backend server up
docker compose up hoppscotch-sh-admin # Runs the self hosted server up (preset opens in port 3100)
docker compose up hoppscotch-app # Runs the main frontend app up
```

### Steps to reproduce

1. Clone the repository `git clone https://github.com/hoppscotch/hoppscotch.git`
2. Copy `.env.example` to `.env` and change the values
3. `cd packages/hoppscotch-backend` on root folder
4. Execute `pnpm exec prisma migrate deploy`

### Environment

Production

### Version

Self-hosted

**Comment by thetronjohnson** [comment]
@fuechter The new self-hosted release is on the way, I will reply here in this thread when the packages are live

**Comment by thetronjohnson** [comment]
@fuechter It's live, you can now self-host Hoppscotch by following the docs

https://docs.hoppscotch.io/documentation/self-host/getting-started
