### ISSUE TITLE
[bug]: Read documentation in Pre-request-script is not redirecting properly

### ISSUE THREAD

**Issue by samuelj90** [hoppscotch/hoppscotch#2981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you click on Read documentation link it is not redirecting properly to the documentation

![image](https://user-images.githubusercontent.com/1846982/231652598-6af8433a-3ae3-43d7-82d4-b14030f49f87.png)

it is redirecting to below screen

![image](https://user-images.githubusercontent.com/1846982/231652843-9eb597ca-266f-4b3e-b73d-7ca400e5c0a5.png)

### Steps to reproduce

1. Open Hoppscotch app
2.  Create a new request / Open an existing request
3.  Click on pre-request script tab
4.  Click on Read documentation link

### Environment

Production

### Version

Cloud

**Comment by samuelj90** [comment]
Is https://docs.hoppscotch.io/documentation/features/scripts is the expected one ?

**Comment by liyasthomas** [comment]
Hi @samuelj90, sorry for the inconvenience caused. We recently updated our documentation site which made few "Documentation and Wiki links" in the platform unavailable. As first reported in #2957, we're working on fixing these issues leading to 404 page in Documentation site. Thanks for reporting the issue.

**Comment by samuelj90** [comment]
Closing this issue in favour of https://github.com/hoppscotch/hoppscotch/issues/2957
