### ISSUE TITLE
[feature]: Generic OIDC option for self-hosted

### ISSUE THREAD

**Issue by binaryfire** [hoppscotch/hoppscotch#3001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Thanks for your hard work on the self hosted version! Would it be possible to add a generic OIDC option for SSO? (in addition to GitHub, Google etc)

### Why should this be worked on?

This will let self-hosters use open source projects like Authentik or Gitlab CE for auth.

**Comment by justsomebody42** [comment]
I'm running keycloak and would very much appreciate this as well :)

**Comment by Coo-ops** [comment]
Need this.

And frankly, it's insane that OpenID Connect is exclusive to GitHub and Google.

**Comment by nikolicjakov** [comment]
This would be so nice to have since i also am running Keycloak as identity provider.

**Comment by becelot** [comment]
I'm currently working on a PR for this, and almost completed the implementation.

Right now I'm waiting for #3200 and #3204 to be merged, since we also want to be able to disable this option. Once they are merged, I will implement add those features as well and submit a PR.

**Comment by Breee** [comment]
@becelot would be nice to also consider #3482  in your implementation

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest Hoppscotch Enterprise Edition release. [Documentation](https://docs.hoppscotch.io/documentation/self-host/enterprise-edition/prerequisites#configuring-openid-connect).

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
