### ISSUE TITLE
[bug]: Privacy policy and terms of service not available

### ISSUE THREAD

**Issue by christian-fries** [hoppscotch/hoppscotch#3004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to read the privacy policy or the terms of service by clicking on the respective links on the login screen, I get a 404 Not Found page.

The links:
* https://docs.hoppscotch.io/terms
* https://docs.hoppscotch.io/privacy

It seems like the pages have been moved to 
* https://docs.hoppscotch.io/support/privacy 
* https://docs.hoppscotch.io/support/terms 

Even though for the terms it still shows a 404.

### Steps to reproduce

1. Open https://hoppscotch.io
2. Hit the login button on the top right
3. Click on the link `Terms of Service` or `Privacy Policy`

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Hi @christian-fries, thanks for reporting.
We've patched this issue in the latest release.
