### ISSUE TITLE
[bug]: environment doesn't default to global 

### ISSUE THREAD

**Issue by tigerinus** [hoppscotch/hoppscotch#3014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Defined variable in Global, but not getting picked up:

![image](https://user-images.githubusercontent.com/7172560/233787417-e38ab712-7f3c-426d-8f79-46f7a64b2843.png)

![image](https://user-images.githubusercontent.com/7172560/233787426-ea5732b5-94b2-46f7-a695-b7ce4a085e6f.png)

Looked at the UI code, it is not picking up due to `selectedEnv` being  `undefined`:

![image](https://user-images.githubusercontent.com/7172560/233787479-71951c0b-0887-4471-b626-d27119aeb07b.png)

### Steps to reproduce

.

### Environment

Production

### Version

Cloud

**Comment by tigerinus** [comment]
workaround:

create a custom environment, so select environment UI shows up, select no environment, then delete the custom environment.

**Comment by liyasthomas** [comment]
We've patched this issue in the latest release. Kindly pull the latest [release](https://github.com/hoppscotch/hoppscotch/releases) tag. Re-open the ticket if the issue still persists.
