### ISSUE TITLE
[bug]: Can't search the collection in team.

### ISSUE THREAD

**Issue by vonhuttri1990** [hoppscotch/hoppscotch#3023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i created the team and collection, and I can't search because the textbox search seems to be disabled.

### Steps to reproduce

1. Go to app
2. Create new team
3. Add new collection
4. And can not search in textbox search.

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
This feature is planned for the next major release. Kindly track the progress of this feature request in #2097.

Closing this issue as duplicate.
