### ISSUE TITLE
[bug]:  pnpm run generate results `ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @hoppscotch/selfhost-web@2023.4.1 do-build-prod: `pnpm run build` Exit status 1`

### ISSUE THREAD

**Issue by liudonghua123** [hoppscotch/hoppscotch#3036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to build the static files via `pnpm run generate`. I always got the following errors.

```
$ pnpm run generate

> hoppscotch-app@3.0.1 generate /workspaces/hoppscotch-app/hoppscotch
> pnpm -r do-build-prod

Scope: 9 of 10 workspace projects
packages/hoppscotch-ui do-build-prod$ pnpm run build
[2 lines collapsed]
│ vite v3.2.4 building for production...
│ transforming...
│ [vite:dts] A error occurred when transform code, maybe there are some inertnal bugs.
│ ✓ 730 modules transformed.
│ rendering chunks...
│ dist/style.css     41.85 KiB / gzip: 5.43 KiB
│ dist/index.es.js   201.98 KiB / gzip: 44.85 KiB
│ dist/index.es.js.map 810.10 KiB
│ [vite:dts] Start generate declaration files...
│ [vite:dts] Declaration files built in 6372ms.
└─ Done in 17.8s
packages/hoppscotch-js-sandbox do-build-prod$ pnpm run build
[9 lines collapsed]
│ CJS Build start
│ ESM ⚡️ Build success in 49ms
│ CJS ⚡️ Build success in 48ms
│ ESM lib/index.mjs     18.97 KB
│ ESM lib/index.mjs.map 38.94 KB
│ CJS lib/index.js     20.05 KB
│ CJS lib/index.js.map 38.94 KB
│ DTS Build start
│ DTS ⚡️ Build success in 3511ms
│ DTS lib/index.d.ts 2.65 KB
└─ Done in 5.5s
packages/hoppscotch-selfhost-web do-build-prod$ pnpm run build
│ > @hoppscotch/selfhost-web@2023.4.1 build /workspaces/hoppscotch-app/hoppscotch/packages/hoppscotch-
│ > node --max_old_space_size=16384 ./node_modules/vite/bin/vite.js build
│ vite v3.2.4 building for production...
│ transforming...
│ transforming...
│ ✓ 1 modules transformed.
│ rendering chunks...
│ Killed
│  ELIFECYCLE  Command failed with exit code 137.
└─ Failed in 31.5s at /workspaces/hoppscotch-app/hoppscotch/packages/hoppscotch-selfhost-web
/workspaces/hoppscotch-app/hoppscotch/packages/hoppscotch-selfhost-web:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @hoppscotch/selfhost-web@2023.4.1 do-build-prod: `pnpm run build`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

```
@liudonghua123 ➜ /workspaces/hoppscotch-app/hoppscotch (8450fb65) $ node -v
v18.16.0
@liudonghua123 ➜ /workspaces/hoppscotch-app/hoppscotch (8450fb65) $ pnpm -v
8.4.0
@liudonghua123 ➜ /workspaces/hoppscotch-app/hoppscotch (8450fb65) $ npm -v
9.5.1
@liudonghua123 ➜ /workspaces/hoppscotch-app/hoppscotch (8450fb65) $ 
```

### Steps to reproduce

1. git clone https://github.com/hoppscotch/hoppscotch.git && cd hoppscotch
2. cp .env.example .env
3. pnpm install
4. pnpm run generate

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
@liudonghua123 This error (137) is caused by Node running out of memory while running a build, this is internally caused by Rollup (which is Vite's bundler for production build) runs out of memory during the build process (https://rollupjs.org/troubleshooting/#error-javascript-heap-out-of-memory). We are looking into ways to fix this issue but at the moment this is prioritised a little bit less.

For the moment, you will have to find a way to allocate atleast 12-16GB of RAM (in our tests) to let the app build with no issues.

Keeping this issue open to tackle this issue later on.

**Comment by liyasthomas** [comment]
Reopening this issue ticket to track the occurrence and progress of this issue.

**Comment by NicklasWallgren** [comment]
> I upgraded the machine type of codespaces from `"2 cores, 4 GB RAM, 32 GB storage"` to `"16 cores, 32 GB RAM, 128 GB storage"`, then the generate script worked without this problem.

It should be sufficient with "only" 6 GB of memory after applying the following patch, https://github.com/hoppscotch/hoppscotch/pull/3148

**Comment by liudonghua123** [comment]
Thanks. 😄
