### ISSUE TITLE
[feature]: Does Hoppscotch have plans to support defining request and response parameter types and descriptions?

### ISSUE THREAD

**Issue by jingxiang** [hoppscotch/hoppscotch#3038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Does Hoppscotch have plans to support defining request and response parameter types and descriptions?

### Why should this be worked on?

I want to include it as part of the documentation specification

**Comment by nguyennm96** [comment]
Upppp

**Comment by fickleness-youth** [comment]
This requirement is very practical and I hope it will be officially supported soon

**Comment by xhwsd** [comment]
Hope for support

**Comment by liyasthomas** [comment]
Possibly a duplicate of #2018, hence closing.
