### ISSUE TITLE
[feature]: Expand All / Collapse All

### ISSUE THREAD

**Issue by linpan** [hoppscotch/hoppscotch#3047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![image](https://github.com/hoppscotch/hoppscotch/assets/6077601/bf50d2f3-f5a3-44d6-ac23-efdea480d0ea)
above it, collapse,  if array show numbers.

### Why should this be worked on?

![image](https://github.com/hoppscotch/hoppscotch/assets/6077601/06713284-b607-4abe-a38d-3941406def1d)

**Comment by liyasthomas** [comment]
<details open>
<summary> &nbsp; This has been already answered in #2938.

https://github.com/hoppscotch/hoppscotch/issues/2938#issuecomment-1451388423

</summary>

Hoppscotch uses [CodeMirror](https://codemirror.net) under the hood.
CodeMirror 6 supports the folding shortcuts natively (per [foldKeymap](https://codemirror.net/docs/ref/#language.foldKeymap)):

- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>[</kbd> (<kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>[</kbd> on macOS): Fold the lines that are selected, if possible.
- <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>]</kbd> (<kbd>Cmd</kbd> + <kbd>Alt</kbd> + <kbd>]</kbd> on macOS): Unfold folded ranges on selected lines.
- <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>[</kbd>: Fold all top-level foldable ranges.
- <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>]</kbd>: Unfold all folded code.

or click on the gutter to fold a block, again to unfold.

![screely-1677738746735](https://user-images.githubusercontent.com/10395817/222352334-045a021a-1f93-47a4-bdee-df96146b96f9.png)

![screely-1677739457603](https://user-images.githubusercontent.com/10395817/222352365-a2140b1d-654f-45d3-8437-2073183929a1.png)


</details>
