### ISSUE TITLE
[bug]: Unable to change GraphQL port inside docker container and when we open GraphQL on 3000 port it shows [405: METHOD NOT ALLOWED] for GraphQL with [ERR_CONNECTION_REFUSED]

### ISSUE THREAD

**Issue by fti-pdangare** [hoppscotch/hoppscotch#3056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently we are using hoppscotch version 2023.4.1, pnpm version 8.5.0, npm version 9.6.6, node version 19.8.1. below are the steps which we follow to use hoppscotch :
1. first we get git clone from hoppscotch version 2023.4.1
2. Change name of .env.example file to .env
3. pnpm install 
4. pnpm run dev
5. after above process done we open the hoppscotch server on port 3000 `http://localhost:3000/`.
6. when we open the url on port 3000 it get's open but graphql which is running on port 3170 get's failed but error message as : 405 Method Not Allowed and ERR_CONNECTION_REFUSED.
7. we are unable to change graphql port which is currently running on 3170.

![image](https://github.com/hoppscotch/hoppscotch/assets/109061933/8ca71983-22c0-4a5d-b66f-9df2954719ca)

![image (1) (1)](https://github.com/hoppscotch/hoppscotch/assets/109061933/55765928-10ff-494e-ad2e-652f5033bd8a)

![image](https://github.com/hoppscotch/hoppscotch/assets/109061933/8a49dc4a-53b9-4490-a9d8-fe8f7feb0087)

### Steps to reproduce

Below are the steps to reproduce this issue:
* Pre perquisites: `hoppscotch version 2023.4.1, pnpm version 8.5.0, npm version 9.6.6, node version 19.8.1.`
1. first we get git clone from hoppscotch github repository --> version 2023.4.1
2. Change name of .env.example file to .env
3. pnpm install (build modules)
4. pnpm run dev
5. after done with above process we open the hoppscotch server on port 3000 `http://localhost:3000/`.
6. when we open the url on port 3000 it get's open but graphql which is running on port 3170 get's failed but error message as : `405 Method Not Allowed` and `ERR_CONNECTION_REFUSED`.
7. we are unable to change graphql port which is currently running on port `3170`.

### Environment

Production

### Version

Local

**Comment by balub** [comment]
@fti-pdangare I believe the steps followed are incorrect, after installing all the dependencies with `pnpm i` we are expected to build the docker containers and then run them. Running `pnpm run dev` does not start the backend or the admin dashboard only the hopscotch app running on port 3000, that's why you keep getting a network error. I would recommend going through our docs [here](https://docs.hoppscotch.io/documentation/self-host/getting-started) for details.
