### ISSUE TITLE
[feature]: Single Sign-On (SSO) authentication support

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Lots of self hosted use SSO as first defense and [Authelia have a great integration using openID](https://www.authelia.com/integration/openid-connect/introduction/), lots of apps is moving to openID because they dont want fixed in big techs, will be nice to have OpenID e support for SSO like Authelia.

### Why should this be worked on?

Fully self-hosted after this.

**Comment by liyasthomas** [comment]
We're actually in the process of adding Single Sign-On (SSO) authentication support to the Hoppscotch Enterprise edition.
If you're interested in this feature, be sure to join our enterprise beta waitlist. By doing so, you'll receive notifications as soon as the feature is ready to roll out. Stay tuned for updates!

[Join enterprise waitlist →](https://hoppscotch.io/beta)

Feel free to share your thoughts on this feature in the comments below.

**Comment by Leon-Luu** [comment]
Hi @liyasthomas , is  Hoppscotch Enterprise edition paid or free?

**Comment by vijenderpanda** [comment]
Hello @webysther ,

I've noticed a feature request concerning the integration of OpenID for Single Sign-On (SSO) support, especially in context with Authelia. Given the growing shift towards open standards like OpenID and the aim to not be tied down to large tech platforms, I believe this feature could significantly benefit the user community.

A brief outline of my understanding:

The desire for self-hosted platforms to integrate SSO as a primary defense mechanism.
Authelia's proven success in integrating with OpenID.
The broader industry trend of applications transitioning to OpenID to maintain independence from large tech corporations.
Achieving a fully self-hosted system upon implementing this feature.
Having reviewed the project's Code of Conduct and contributing guidelines, I wanted to first discuss this feature further. I am eager to contribute to its development and bring this OpenID support to fruition. If it's not already being addressed by someone else, please consider my keen interest in taking up this challenge.

Would there be any specific considerations or prerequisites you'd want to highlight related to this feature? Your guidance would be invaluable as I proceed.

Thank you for considering my proposal. I'm enthusiastic about the chance to enhance the project and look forward to your feedback.

Best regards,

Vijender Panda
[@vijenderpanda](https://github.com/vijenderpanda)

**Comment by webysther** [comment]
Hi Vijender Panda,

I'm not the maintainer but thank you for ask my ideias, hope @liyasthomas join the discussion.

For my point of view, now I use already the Authelia but is not integrated with openID with this project, I think the best way is like mostly projects is doing with Authelia, provide ENV to configure the handshake with a simple page to this process. I think one important step is to have in mind, some projects broke the openid after restart Authelia container, sometimes is necessary to restart the docker to get configuration load in authelia (there no live reload yet) and some integrations fail after this, which is rare but happens, so the token send to authelia need to be check in the authelia api before.

I send this using my mobile, but i ask to look the page of integrations with openid in authelia docs to use similar env vars name to keep a similiar pattern, this will help another users to adopt.

Last but not less important, the project is migrating to a better docker and this will change a few fundamental things, another important move is that auth is get better with a fix to not require the ENV vars for third-party already existent, which is important, this maybe change a few things and make you PR incompatibile, so keep in mind if you want start now you probably need to change a few things in near future, keep in touch with @liyasthomas in the discord for further discussion.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest Hoppscotch Enterprise Edition release. [Documentation](https://docs.hoppscotch.io/documentation/self-host/getting-started).

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
