### ISSUE TITLE
[feature]: Auto-complete recent entries for URL textbox

### ISSUE THREAD

**Issue by U-C-S** [hoppscotch/hoppscotch#3087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Let the URL textbox have autocomplete suggestions of recently typed/used URLs

### Why should this be worked on?

I frequently have to type long API URLs, often same as the recent URL with small modifications, and It is also one thing I have been missing coming from Postman.  This quality of life feature can save me a lot of time. 

I would love to even help in developing this.... Suggestions can be previous 10 entries, maybe even stored within localstorage

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.
