### ISSUE TITLE
[feature]: Remove login type from ui

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Remove the Auth provider if the ENV vars are not provided in ui

### Why should this be worked on?

If have only one provider the app and admin can be skip the provider selection making a better ux.

**Comment by liyasthomas** [comment]
Duplicate of #3211, hence closing. Track the progress of this feature request on #3211.
