### ISSUE TITLE
[bug]: Admin dont support custom location

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3091]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you change the URI on ENV for Admin and build the location os the assets point to root of domain.

This was fixed after build [here](https://github.com/webysther/hoppscotch).

### Steps to reproduce

1. Clone
2. Change domain admin to exmaple.com/admin
3. Change the reverse proxy to use this custom location and point to port of admin
4. Admin work but don't to further because the *.js and *.css point to example.com/

### Environment

Production

### Version

Self-hosted

**Comment by jastisriradheshyam** [comment]
setting `VITE_ADMIN_URL`  in `.env` is not working, it is ignoring the routes and only utilizing the protocol (HTTPS) and domain name as URL.
Tested version: `2023.8.1`

**Comment by balub** [comment]
Subpath Access to services added in release `2023.12.0`.
