### ISSUE TITLE
[feature]: Support change mostly configurations inside settings on app

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Change SMTP, OAUTH and DB on settings in app, persist direct on disk with slite.

### Why should this be worked on?

Fixes the problem of rebuild from source if ENV is changed.

This was fixed (partial) with build [when restart the container here.](https://github.com/webysther/hoppscotch)

**Comment by mirarifhasan** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in a previous release candidate.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
