### ISSUE TITLE
[feature]: Dont need to rebuild every time when a ENV is changed

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Related to [this one](https://github.com/hoppscotch/hoppscotch/issues/3092) but here is about change the way how the static site is built to get ENV from API (Backend) or from a static file like env.js.

### Why should this be worked on?

Fix the problem to have to built from source but without need to change the UX like in [this one](https://github.com/hoppscotch/hoppscotch/issues/3092).

This problem was [reduced here](https://github.com/webysther/hoppscotch) with layers of all needed for the 2 static apps (app/admin) and api (backend). Today take 3-5 minutes to webserver up and running.

**Comment by AndrewBastin** [comment]
Closing this issue as it is fixed in the 2023.8.0 images.
