### ISSUE TITLE
[feature]: Support for SQLite

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Really small teams or hardcore developer with lots of collections will reduce one req to run this stack and keep the collections saved on disk

### Why should this be worked on?

- Mostly self-hosted projects support as a initial start point sqlite and expand to mysql/mariadb/postgres
- Easy to maintain
- Cheap to maintain

**Comment by liyasthomas** [comment]
As per the current roadmap planned for Hoppscotch self-hosted community edition, we don't have any plans to add SQLite database support, hence I'm closing this issue as not planned.

We'll keep a tab open for this feature request to get to know more about the use cases, discuss the accessibility, and how we can improve the self-hosting experience, etc. Feel free to share your thoughts on this feature in the comments below.

**Comment by webysther** [comment]
Actually after take a look on prisma of project i see the type json in most every table, make this project [not compatible with sqlite](https://www.prisma.io/docs/concepts/database-connectors/sqlite) :(

**Comment by vaidis** [comment]
instead of sqlite, lowdb would be nice, as a purely json database

**Comment by webysther** [comment]
https://npmtrends.com/lokijs-vs-lowdb-vs-nedb-vs-sqlite-vs-sqlite3

**Comment by webysther** [comment]
[JSON Column type is a req for this project yet](https://www.prisma.io/docs/reference/database-reference/database-features#misc)
