### ISSUE TITLE
[feature]: Builtin simple auth

### ISSUE THREAD

**Issue by webysther** [hoppscotch/hoppscotch#3095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Simple auth inside app. Maybe support for Reverse Proxy Authentication (Know as [trusted header](https://www.authelia.com/integration/trusted-header-sso/introduction/)).

### Why should this be worked on?

- No need mail server
- No need OAuth
- Simple start point

**Comment by liyasthomas** [comment]
As per the current roadmap planned for Hoppscotch self-hosted community edition, we don't have any plans to add simple authentication support, hence I'm closing this issue as not planned.

We'll keep a tab open for this feature request to get to know more about the use cases, discuss the accessibility, and how we can improve the self-hosting experience, etc. Feel free to share your thoughts on this feature in comments below.

**Comment by fin-ger** [comment]
I do have a very simple use-case for a simple-starting-point.

I would like to use Hoppscotch inside a [Coder Workspace as a Coder-App](https://coder.com/docs/v2/latest/ides/web-ides). This is usually done by installing the app inside the workspace and then proxying the port of the app through Coder.

An example often used with Coder is `code-server`, a web-app for VSCode. An instance of `code-server` would run inside the Coder workspace without any authentication or TLS termination, just plain HTTP on any TCP port (e.g. 13337). Coder then proxies that port through a per-workspace URL and handles TLS-termination and authentication.

If there would be a possibility for Hoppscotch to be started without any authentication configured, one could easily integrate Hoppscotch into a Coder workspace.
