### ISSUE TITLE
[feature]: Collection wise scripting

### ISSUE THREAD

**Issue by crendy** [hoppscotch/hoppscotch#3097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

类似 postman或者apifox 
<img width="898" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/6448115/65c539c2-5474-42fd-b177-64eabe45b72d">

### Why should this be worked on?

同一文件夹下多个接口的 pre-request script 设置的信息都一样。

**Comment by liyasthomas** [comment]
Hi @crendy, can you describe what you expect from Hoppscotch's pre-request script and post-request tests? What are your use cases>

**Comment by zhangtao25** [comment]
> Hi @crendy, can you describe what you expect from Hoppscotch's pre-request script and post-request tests? What are your use cases>

What he means is that he wants postman to be able to configure a script on a folder, and then all requests in the folder will inherit the execution script

**Comment by bappleug-tw** [comment]
That's exactly what I am also looking for

**Comment by liyasthomas** [comment]
Closing this issue, track the progress on #3728.
