### ISSUE TITLE
[bug]: When installed as Chrome PWA the first tab url is always overridden with the default 'https://echo.hoppscotch.io' request

### ISSUE THREAD

**Issue by stefankorun** [hoppscotch/hoppscotch#3098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug behaviour

While using the installed PWA in Chrome (Version 114.0.5735.45 (Official Build) beta (arm64)) when I start or refresh the application, my first tab request is always replaced with `https://echo.hoppscotch.io`:

https://github.com/hoppscotch/hoppscotch/assets/2415410/b38201dc-7668-4fc8-b27c-6a40ff1b2d9f

### Expected behaviour

When using the app via browser, the tab url correctly persists between tab reloads and closing: 

https://github.com/hoppscotch/hoppscotch/assets/2415410/e97dad2d-83c5-4c43-bf9d-68ce95daefa8

### Steps to reproduce

1. Install Hoppscotch as a Chrome application
2. Open the application and change the default url from `https://echo.hoppscotch.io` to any other (e.g. `https://ifconfig.me/`)
3. Reload or reopen the application
4. Url is back to `https://echo.hoppscotch.io` instead of `https://ifconfig.me/`

### Environment

Production

### Version

Cloud

**Comment by stefankorun** [comment]
> Hi @stefankorun, sorry for the inconvenience caused. We were able to reproduce the bug and are working on patching it as soon as possible.

@liyasthomas Awesome, thank you for the quick response. Open to contributing is needed.

**Comment by liyasthomas** [comment]
We've patched this issue in the latest release.
