### ISSUE TITLE
[feature]: Hoppscotch Desktop Application

### ISSUE THREAD

**Issue by scolastico** [hoppscotch/hoppscotch#3101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I propose considering the development of an Electron version of Hoppscotch. Although the current web-based version and browser extensions offer great functionality, an Electron app can provide additional benefits. This would enable a more streamlined local development experience and improve project loading by providing easy access to local files. As mentioned in [Issue #872](https://github.com/hoppscotch/hoppscotch/issues/872#issuecomment-1447578941), the Electron framework could provide an ideal way to package Hoppscotch for desktop use.

### Why should this be worked on?

There are a few compelling reasons for working on this proposal:

1. Local Development Experience: With the current web app, developers need to rely on browser extensions for local development, which can feel less integrated and robust than a dedicated desktop application.

2. Easy Access to Local Files: As an Electron app, Hoppscotch would have direct and easy access to local files, enabling more efficient loading, handling, and management of projects. This would not only improve the user experience but also support use-cases like including project files in Git repositories.

3. Expanded User Base: Providing Hoppscotch as an Electron app could attract users who prefer or require desktop applications, expanding the user base and use-cases for the tool.

4. Greater Consistency across Platforms: Electron apps run on multiple platforms (Windows, Mac, Linux) with consistent behavior, which can lead to a more uniform user experience and potentially simpler troubleshooting.

By offering Hoppscotch as an Electron application, we could retain all the benefits of the existing web app while adding new capabilities and convenience for users.

**Comment by webysther** [comment]
Working as [PWA integrated to browser](https://medium.com/progressivewebapps/chrome-now-supports-pwa-install-experience-551cf896c0f9) maybe a half-way. Need test to see the chrome_proxy to send file will work well.

**Comment by scolastico** [comment]
Thank you for your prompt response. I appreciate the current functionality that Hoppscotch PWA offers. It indeed provides a great degree of accessibility and usability across various platforms.

However, I believe that wrapping Hoppscotch into an Electron application can offer additional advantages and could enhance the user experience in several ways:

1. Improved File System Access: While PWAs have some ability to interact with the local file system, it's not as comprehensive or seamless as what's possible with Electron. This is especially important for users who deal with larger projects or more complex file hierarchies, and want to include their API tests in version-controlled repositories.

2. Deeper Integration with Desktop Environment: Electron apps can more effectively utilize native OS features, such as notifications, background processes, and custom menu options. This can lead to a more coherent and integrated user experience, making Hoppscotch feel less like a web page and more like a part of the user's operating system.

3. Consistency across Platforms: While PWAs are designed to work across different platforms, variations in behavior can still occur due to differences in how browsers implement PWA standards. Electron applications, on the other hand, offer a consistent environment across all platforms, since they are based on Chromium.

4. User Preference and Perception: Despite the advances in PWA technology, some users still prefer desktop applications. These can often be easier to manage (as they don't require a specific browser), are typically perceived as more professional, and can feel more secure as they run outside the context of a web browser.

5. Offline Functionality: Although PWAs can work offline, Electron apps are inherently more reliable in environments with spotty or unstable internet connections.

While the PWA version of Hoppscotch certainly offers a great user experience, I believe the addition of an Electron version could expand and enhance the tool's capabilities and appeal to an even wider user base.

I hope this clarifies my proposal. Thank you for considering this enhancement.

**Comment by scolastico** [comment]
Another reason why PWA's may not be as advantageous is this https://github.com/hoppscotch/hoppscotch/issues/1752 issue I encountered with the Hoppscotch PWA. This problem ultimately led me to uninstall it.

**Comment by BojanOro** [comment]
Ideally this would avoid the need for a browser extension to be installed as well? Generally it's easier to get a desktop app approved in a corporate environment than a browser extension that requires read access to all web pages.

**Comment by liyasthomas** [comment]
We're working on a native Hoppscotch client, stay tuned for product updates.

**Comment by PhillipMwaniki** [comment]
I'm willing to test it with my work when ready. 💪🏽

**Comment by danielniccoli** [comment]
Would be great if I could save workspaces on the local computer, without having to sign in anywhere.

**Comment by scolastico** [comment]
> Would be great if I could save workspaces on the local computer, without having to sign in anywhere.

I hope it supports normal files so I can include my workspaces in my git repositories.

**Comment by cpuccino** [comment]
Yes please!

**Comment by govind84k** [comment]
@liyasthomas do you have a timeline on when the client will be released ? Our company is using Postman now and since they are deprecating the UI, we are evaluating different tools. Currently our company gateway dont allow browser extension and due to which we are not able to use the hoppscotch. A native client will help us here and timeline on this will be helpful for us.

**Comment by liyasthomas** [comment]
We're actively working on the Hoppscotch Desktop App. Internally testing the alpha release candidates as we speak.

**Comment by erazemk** [comment]
@liyasthomas Will the desktop app be based on Electron, Tauri or something else?

**Comment by jimifredjr** [comment]
Hey any update on this? The postman restriction implementation date is approaching and it would be good to know my company has an alternative to use before the restrictions start.

**Comment by liyasthomas** [comment]
Expect a public beta release as early as October last week.

**Comment by hamburml** [comment]
I am already very excited. I need good alternatives that don't want to force an online account.

**Comment by thelazyoxymoron** [comment]
With the [recent user-hostile implosion](https://github.com/Kong/insomnia/issues/6585) of Insomnia forcing users to a cloud service and deleting all local configurations in the process, I'm anticipating lots of users are gonna be looking for a self-hosted alternative like Hoppscotch.

**Comment by driden** [comment]
I am one of the users mentioned by @thelazyoxymoron and very much interested in this project. Will it support importing insomnia collections ?

**Comment by thelazyoxymoron** [comment]
Off topic: it seems a bit disingenuous for the founder of this project to start censoring links to other projects (like the above comment) while keeping other off-topic links/discussions intact (including my own earlier comment).

**Comment by ewertonls** [comment]
I would pretty much appreciate a desktop app as well. Works and feels a lot nicer than a website or pwa

**Comment by choyiny** [comment]
A desktop app will be the final nail in the coffin for Postman, as they recently removed support for local collections with environments. One thing that Hoppscotch missed was it was hard to test websites with strict CORS headers without a proxy, so hopefully the desktop app will make that easy!

**Comment by muuvmuuv** [comment]
> @liyasthomas Will the desktop app be based on Electron, Tauri or something else?

+1 for Tauri for better performance and use of native http libs maybe. They are also pretty stable RN and will provide mobile compatibility in the future.

**Comment by LanguageAgnostic** [comment]
Hey I just want to chime in as it doesn't seem to be mentioned in this particular issue: someone already took that challenge with Tauri - https://github.com/liudonghua123/hoppscotch-app

Originally shared here: https://github.com/hoppscotch/hoppscotch/issues/413#issuecomment-993219870

**Comment by scolastico** [comment]
> At this point I'm not just waiting for the desktop app release, but ask myself, weather one week after that release there will be a shittification update forcing us all to create an account...

If this happens i will start a fork lol, just hope for the best...

**Comment by jimifredjr** [comment]
Would there be a ticket we can track or can we get an updated ETA? This is a HIGHLY sought feature for my company since the Postman and Insomnia account change.

**Comment by liyasthomas** [comment]
@jimifredjr subscribe to this ticket to get updates.

**Comment by jimifredjr** [comment]
@liyasthomas I am already subscribed. Seeing as the last real update was over a month ago, is the desktop solution still expected in the last week of October?

**Comment by fbradyirl** [comment]
I managed to get this fork running locally https://github.com/liudonghua123/hoppscotch-app and imported my Postman collections. However, there seems to be no support for importing Postman Environments which is a bummer.

**Comment by jrnewton** [comment]
https://hoppscotch.com/blog/introducing-hoppscotch-desktop-application

**Comment by LoLo2207** [comment]
Thanks, installing right now 🎉🎉

**Comment by liudonghua123** [comment]
> https://hoppscotch.com/blog/introducing-hoppscotch-desktop-application

wonderful, it's build on tauri  instead of electron.
