### ISSUE TITLE
Import CURL does not work

### ISSUE THREAD

**Issue by orisust** [hoppscotch/hoppscotch#3109]
Hey, 

Trying to import a valid CURL and it does not work, it only sets the method type, and sometimes sets the headers and body, 
and the URL is set to https://echo.hoppscotch.io/

curl --location 'http://my-private-url.test.com' \
--header 'Accept: application/jsonx' \
--header 'Content-Type: application/jsonx' \
--data '{"a":1,"b":2,"c":3}'

the curl imports fine in Postman.

Can you please check and advise? thanks

**Comment by pratyush-pankaj** [comment]
Same issue with me. Please someone fix this

**Comment by bermudi** [comment]
Possibly related https://github.com/hoppscotch/hoppscotch/issues/1159

**Comment by micky2333** [comment]
Yes, I have the same problem Import CURL can't import request header and request body

**Comment by liyasthomas** [comment]
Resolve in #3152.

**Comment by chaoqunya** [comment]
Still cannot import curl command like this one

```shell
curl -s --user 'api:YOUR_API_KEY' -G \
      https://api.mailgun.net/v3/YOUR_DOMAIN_NAME/events \
      --data-urlencode begin='Fri, 3 May 2013 09:00:00 -0000' \
      --data-urlencode ascending=yes \
      --data-urlencode limit=25 \
      --data-urlencode pretty=yes \
      --data-urlencode recipient=joe@example.com
```
