### ISSUE TITLE
[bug]: Rename query not works

### ISSUE THREAD

**Issue by marcin-zajac** [hoppscotch/hoppscotch#3114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to rename the query the name stays the same.

### Steps to reproduce

1. Create new query in collection
2. Save query with some name, eg. "my super query"
3. Duplicate this
4. Try to rename (three dots > Edit)  "my super query - Duplicate" to  "my second super query" Rename should not works

### Environment

Production

### Version

Cloud

**Comment by bastien-snk** [comment]
Same issue for me

**Comment by liyasthomas** [comment]
We've patched this issue in the latest release.
