### ISSUE TITLE
[bug]:   whitelisted_origins for CORS being ignored for proxied URLs for /graphql endpoint

### ISSUE THREAD

**Issue by conall88** [hoppscotch/hoppscotch#3118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When running the backend app with CORS set to production settings, the /graphql endpoint will return HTTP 521 "CORS Missing Allow Origin" even when the relevant path is specified in .env, in cases where a reverse proxy is present.
![image](https://github.com/hoppscotch/hoppscotch/assets/10930485/c2dc21da-f02f-4877-80ad-a1a1e89aec73)

I'm trying to set this up using the docker compose method.

below are the relevent  conf snippets:

.ENV
```
# Hoppscotch App Domain Config
REDIRECT_URL="http://localhost:80"
WHITELISTED_ORIGINS = "http://localhost:3170,http://localhost:3000,http://localhost:3100,https://hoppscotch.conall.org:8443,https://hoppscotch.conall.org:2053,https://hoppscotch.conall.org:2096,https://hoppscotch.conall.org:2087"
```

frontend config:

```
# Backend URLs
VITE_BACKEND_GQL_URL=https://hoppscotch.conall.org:2087/graphql
VITE_BACKEND_WS_URL=ws://hoppscotch.conall.org:2087/graphql
VITE_BACKEND_API_URL=https://hoppscotch.conall.org:2087/v1

```

I've attached a .HAR file incl the response here: [har file.zip](https://github.com/hoppscotch/hoppscotch/files/11667520/har.file.zip) 

Other endpoints seem to work fine so far, and similar cloudflare proxy configuration is working fine for other applications / kubernetes containers.

[Port 2087 ](https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/#:~:text=2083-,2087,-2096)may be used for HTTPS workloads with cloudflare, and i've set the proxy to flexible encryption, meaning encryption between the cloudflare loadbalancer and the browser only.

Let me know if there is a debug log  I can enable to narrow down the issue further. I didn't see anything via info/warn level logs  Thanks.

### Steps to reproduce

set port 2096 for the hoppscotch-sh-admin container in .env
docker compose build
docker compose up -d
expose the hoppscotch-sh-admin container behind a reverse proxy which proxies requests from `http://localhost:2096` to `https://<somehost>:2096`
open https://somehost:2096 in a browser.
see the POST and OPTIONS to /graphql  at `https://<somehost>:2087`  fail.

### Environment

Production

### Version

Self-hosted

**Comment by conall88** [comment]
I just noticed this behaviour affects the default configuration example, and i've been looking for a first issue in an OSS project, so I hope this is welcome:

I see this CORS handling is being done by nestJS as per:
https://docs.nestjs.com/security/cors

First theory is that the the NodeJS env vars aren't being read properly via process.env.<VAR>.split

I've therefore set : 

``` if (process.env.PRODUCTION === 'false') {
    console.log('Enabling CORS with development settings');

    app.enableCors({
      origin: [
        'http://localhost:3170',
        'http://localhost:3000',
        'http://localhost:3100',
      ],
      credentials: true,
    }); 
```

and set 
```
PRODUCTION=false
```
 in .env to test after doing a build.


outcome:

CORS directives are respected and functional:

![image](https://github.com/hoppscotch/hoppscotch/assets/10930485/77261ef5-f99e-4386-b76a-205bb3fe7c3f)

so it looks like https://github.com/hoppscotch/hoppscotch/blob/e3dd9e99a1951f795149b70bcba46295cf09f712/packages/hoppscotch-backend/src/main.ts#LL32  is the culprit.

I haven't been able to solve, but did add some improved logging to show that the env vars are being passed in properly.

Unfortunately I don't seem to have permissions to publish branches to this repo even though it's marked as public...

![image](https://github.com/hoppscotch/hoppscotch/assets/10930485/3538d31a-796b-4be4-8a03-715d6c7a689d)

**Comment by talenta-eg** [comment]
@conall88  Great job bro ,  does you right now can't login via email or Auth through HTTP ?

**Comment by conall88** [comment]
CORS directives do not require auth. the auth functionality isn't the issue, i'm sure they work fine otherwise.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by talenta-eg** [comment]
@conall88 can you help , I spent one week for installation but unfortunately with failure 
i have tried  with http and https both not working 

right now i face this issue 

<img width="1320" alt="Screenshot 2023-06-13 at 2 30 12 PM" src="https://github.com/hoppscotch/hoppscotch/assets/4216438/2e615f3f-c85f-4893-be5c-2bf80814cf4b">

**.env file** 


<img width="1084" alt="Screenshot 2023-06-13 at 2 41 13 PM" src="https://github.com/hoppscotch/hoppscotch/assets/4216438/e90211b0-e9a7-448c-b6e5-14a7b307caba">

**docker file**


<img width="1100" alt="Screenshot 2023-06-13 at 2 42 32 PM" src="https://github.com/hoppscotch/hoppscotch/assets/4216438/46540b7e-01d3-42e8-95de-e706dfeb60e2">


**If you can help me it's pleasure**

**Comment by conall88** [comment]
please edit your post, you should not be sharing your oauth secrets.

they are called secrets for a reason, and i doubt you want a malicious actor taking your token and logging into github as you.

That CORS error you posted is related to sentry APM, not hoppscotch. You need to configure your proxy accordingly.

**Comment by cventastic** [comment]
Hello,

im trying to understand this problem.
My .env - File has the following entries (i replaced my domain for privacy reasons):

```
REDIRECT_URL="http://hoppscotch-frontend.docker-int.mydomain.tld"
WHITELISTED_ORIGINS="http://hoppscotch-backend.docker-int.mydomain.tld,http://hoppscotch-frontend.docker-int.mydomain.tld,http://hoppscotch-dash.docker-int.mydomain.tld"

VITE_BASE_URL=http://hoppscotch-frontend.docker-int.mydomain.tld
VITE_SHORTCODE_BASE_URL=http://hoppscotch-frontend.docker-int.mydomain.tld
VITE_ADMIN_URL=http://hoppscotch-frontend.docker-int.mydomain.tld

# Backend URLs
VITE_BACKEND_GQL_URL=http://hoppscotch-backend.docker-int.mydomain.tld/graphql
VITE_BACKEND_WS_URL=ws://hoppscotch-backend.docker-int.mydomain.tld/graphql
VITE_BACKEND_API_URL=http://hoppscotch-backend.docker-int.mydomain.tld/v1
```
The hoppscotch-app - container has no problems querying the backend:
![image](https://github.com/hoppscotch/hoppscotch/assets/13015146/89e66bbc-5398-44cc-92a6-e13a4dc96f0c)


But when hoppscotch-sh-admin - container tries to query the backend i get:
![image](https://github.com/hoppscotch/hoppscotch/assets/13015146/5aa2e610-9afa-46ed-ba46-302354b00b07)

I tried to set 
```
PRODUCTION=false
```
but looking at the [code](https://github.com/hoppscotch/hoppscotch/blob/release/2023.8.0/packages/hoppscotch-backend/src/main.ts#L31-L45) it doesnt seem to do anything anyway:

What is the difference between the app container querying the backend and the sh-admin container querying the backend?

**Comment by conall88** [comment]
Awesome, il probably build the branch  and check it out a little early,
thanks for your efforts 🙂

**Comment by cventastic** [comment]
for me the problem still exists in 2023.08.0

**Comment by mcmluk-monster** [comment]
Hi all,

I've been using the dockerhub aio image, and seem to be getting the exact same issue as @cventastic  with the CORS error when trying to POST to the graphql endpoint from the admin URL, but the normal frontend url is fine. Looking at dockerhub, this image is also using the 2023.08.0 release

**Comment by jk779** [comment]
Hi, sadly I'm still running in this problem: accessing graphql from the admin

I'm using this https://hub.docker.com/r/hoppscotch/hoppscotch Tag 2023.8.1 and added all domains to the whitelist.

![Bildschirmfoto 2023-10-06 um 20 16 34](https://github.com/hoppscotch/hoppscotch/assets/1104528/ccb38be2-c0be-4b29-8aa7-c142ad2102db)
