### ISSUE TITLE
[bug]: login server internal error 

### ISSUE THREAD

**Issue by talenta-eg** [hoppscotch/hoppscotch#3128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="1336" alt="Screenshot 2023-06-09 at 7 16 44 AM" src="https://github.com/hoppscotch/hoppscotch/assets/4216438/e82c8375-0ee8-49e1-9c24-78c2bd938388">

### Steps to reproduce

I try to login via email but i face this an error , Any Suggestions ?

### Environment

Production

### Version

SelfHosted

**Comment by amishsthapit** [comment]
Did you run the migration? If not please do that. It should fix this issue.

**Comment by talenta-eg** [comment]
@amishsthapit , Awesome right now working i can send an email 
but when open email and click to login i face the following 

<img width="1436" alt="Screenshot 2023-06-09 at 4 05 10 PM" src="https://github.com/hoppscotch/hoppscotch/assets/4216438/99eaa3a3-0a4f-48c6-b694-5e5459ba23f8">

**Comment by balub** [comment]
@talenta-eg The error indicates that you have used to sign-in to another device using a magic-link generated from another device, we do not allow for that to happen.

**Comment by talenta-eg** [comment]
@balub First thanks for reply , i know the error content but i have sign-in from these device with same browser many of times but still issues  showing **i do not know what i cane do to pass this error**

Can you help please ?

**Comment by balub** [comment]
@talenta-eg The device identifier token is saved in your browser's local storage once you initiate the magic-link auth flow, do you by chance have any extension etc that can prevent that from happening?

**Comment by AndrewBastin** [comment]
Closing this issue due to activity. If you still face this in 2023.8.0, please do reopen.

**Comment by krystalcode** [comment]
@balub I have the same issue running the latest (as of today) official AIO container. I do see the `deviceIdentifier` and `emailForSignIn` properties properly stored in local storage. Still getting the "Device identifier not found ..." error.
