### ISSUE TITLE
[bug]: When trying to get graphql schema documentation by connecting it failed.

### ISSUE THREAD

**Issue by appl4e** [hoppscotch/hoppscotch#3135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to connect with our graphql api endpoint to fetch the schema documentation then it fails to fetch the schema. 

By inspecting, I found that it is not sending the Authorization token I used. 
But, when I am clicking on run then it sends a request with my query and gives a successful response. In this case, the bearer token is sent.

In both cases, Authorization Token is set.

![image](https://github.com/hoppscotch/hoppscotch/assets/17544501/1845c111-20e3-46d6-811d-cd9a9c6ef399)

### Steps to reproduce

1. Paste the graphql api ur
2. Set Authorization Token
3. Click Connect button

### Environment

Production

### Version

Cloud

**Comment by anwarulislam** [comment]
Thanks for noticing it, brother.
looking into the issue.

**Comment by liyasthomas** [comment]
Resolved in #3136, hence closing.
