### ISSUE TITLE
[bug]:  TypeError: Cannot create property 'mailer' on string 'smtp.gmail.com'

### ISSUE THREAD

**Issue by Channakeshava-S** [hoppscotch/hoppscotch#3159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

while running this in local getting the above error.

### Steps to reproduce

1. change the env values.
2. install 
3. start

### Environment

Release

### Version

Local

**Comment by balub** [comment]
@Channakeshava-S can you share your env variables.

**Comment by anubhavhazarika** [comment]
+1 for the issue. 

@balub: I am facing the issue while following the instructions here - https://docs.hoppscotch.io/documentation/self-host/community-edition/prerequisites and using [mailcatcher](https://mailcatcher.me/) as a simple SMTP server. 
The relevant env variables section is: 
MAILER_SMTP_URL="smtps://host.docker.internal:1025"
MAILER_ADDRESS_FROM='"Test Email" <example@email.com>'

Thank you.

**Comment by balub** [comment]
@anubhavhazarika Can you replace the `MAILER_ADDRESS_FROM` with your email and remove everything else so it becomes `MAILER_ADDRESS_FROM="user@email.com"`.

**Comment by Sonichigo** [comment]
@balub i'm facing the same issue : 

```
Backend Server | [Nest] 56  - 11/02/2023, 10:54:05 AM   ERROR [ExceptionHandler] Cannot create property 'mailer' on string '"smtps://127.0.0.1:1025"'
Backend Server | TypeError: Cannot create property 'mailer' on string '"smtps://127.0.0.1:1025"'
```
in .env i have :- 
```
MAILER_SMTP_URL="smtps://127.0.0.1:1025"
MAILER_ADDRESS_FROM='user@example.com'

```

**Comment by balub** [comment]
@Sonichigo Can you try the following:
 ```
MAILER_SMTP_URL=smtp://127.0.0.1:1025
MAILER_ADDRESS_FROM=user@example.com
```

basically, remove all the quotes and try with `SMTP` this is a known issue are we are working to find a fix for this.

**Comment by Sonichigo** [comment]
> @Sonichigo Can you try the following:
> 
> ```
> MAILER_SMTP_URL=smtp://127.0.0.1:1025
> MAILER_ADDRESS_FROM=user@example.com
> ```
> 
> basically, remove all the quotes and try with `SMTP` this is a known issue are we are working to find a fix for this.

Thanks @balub it worked! I'm using AIO container, and it keeps throwing multiple errors! I cloned the repo and started using docker run command

```
Backend Server | 
Backend Server | PrismaClientInitializationError: Can't reach database server at `hoppscotch-db`:`5432`
Backend Server | 
Backend Server | Please make sure your database server is running at `hoppscotch-db`:`5432`.
Backend Server |     at r (/usr/src/app/node_modules/.pnpm/@prisma+client@4.16.2_prisma@4.16.2/node_modules/@prisma/client/runtime/library.js:108:2574)
Backend Server |     at async Proxy.onModuleInit (/usr/src/app/packages/hoppscotch-backend/dist/prisma/prisma.service.js:20:9)
Backend Server |     at async Promise.all (index 0)
Backend Server |     at async callModuleInitHook (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
Backend Server |     at async NestApplication.callInitHook (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/nest-application-context.js:210:13)
Backend Server |     at async NestApplication.init (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/nest-application.js:97:9)
Backend Server |     at async NestApplication.listen (/usr/src/app/node_modules/.pnpm/@nestjs+core@9.2.1_@nestjs+common@9.2.1_@nestjs+platform-express@9.2.1_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/nest-application.js:155:33)
Backend Server |     at async bootstrap (/usr/src/app/packages/hoppscotch-backend/dist/main.js:40:5) {
Backend Server |   clientVersion: '4.16.2',
Backend Server |   errorCode: 'P1001'
Backend Server | }
Backend Server | 
Backend Server | Node.js v18.16.0
Backend Server | ELIFECYCLE  Command failed with exit code 1.
Exiting process because Backend Server exited with code 1
```
Now it's throwing this error. my `DATABASE_URL=postgresql://postgres:testpass@hoppscotch-db-1:5432/hoppscotch
` is the default config

**Comment by balub** [comment]
Hey @Sonichigo, replace `hoppscotch-db` with the URL to your postgres DB or something like `host.docker.internal` and check again.
