### ISSUE TITLE
[feature]: Remember the selected sub tab (parameters, body, headers, etc.)

### ISSUE THREAD

**Issue by erkkon** [hoppscotch/hoppscotch#3161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want you to be able to switch between tabs without losing your selected position within each tab independently. Because currently, when you change tabs (parameters, body, headers, etc.) you lose your place in the parameters tab.

### Why should this be worked on?

Because when you want to switch between tabs, you would like to see what you were viewing previously, rather than the parameters sub-tab all the time.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.
