### ISSUE TITLE
[bug]:  Issue with pnpm install in Hoppscotch project 

### ISSUE THREAD

**Issue by goutham639** [hoppscotch/hoppscotch#3167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am encountering an issue when running pnpm install in the Hoppscotch project. The error occurs during the postinstall step of the hoppscotch-backend package and i am running this behind the corporate proxy.

Here's the relevant part of the error message:

Error: request to https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/rhel-openssl-1.1.x/libquery_engine.so.node.gz.sha256 failed, reason: connect EINVAL 0.0.31.144:80 - Local (0.0.0.0:0)
└─ Failed in 878ms at /opt/app/hoppscotch/packages/hoppscotch-backend

I have tried the following troubleshooting steps without success:

1. Checked my internet connection and confirmed that it's working.
2. Tested the URL in question using curl and verified that it's accessible.
3. Removed the node_modules directory and the lockfile (pnpm-lock.yaml), and reinstalled the packages.
4. configured the system proxy and npm proxy 

Despite these efforts, the issue persists.

Please let me know if you need any more information or if there are additional troubleshooting steps I can try.
![hoppscotch_pnpm_error](https://github.com/hoppscotch/hoppscotch/assets/24263814/f073a6de-faa8-4963-9661-1dd9fa24f779)

### Steps to reproduce

Clone repository
Copy .env.example to .env
set system proxy and npm proxy
export http_proxy=proxy.company.com:8080
export https_proxy=proxy.company.com:8080
npm config set proxy http://proxy.company.com:8080
npm config set https-proxy http://proxy.company.com:8080
pnpm install

### Environment

Production

### Version

Self-hosted

**Comment by goutham639** [comment]
i forgot to mention that i am installing it behind the corporate proxy

**Comment by liyasthomas** [comment]
Hi @goutham639, to better understand the issue, can you share the contents of your `.env` file?

> **Note**
> **Please mask any sensitive data from the environment file.**

**Comment by goutham639** [comment]
sure, here you go

#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://postgres:testpass@hoppscotch-db:5432/hoppscotch # or replace with your database URL 

# Auth Tokens Config
JWT_SECRET="*********"
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY= 3
REFRESH_TOKEN_VALIDITY="*********" # Default validity is 7 days (604800000 ms) in ms
ACCESS_TOKEN_VALIDITY="*********" # Default validity is 1 day (86400000 ms) in ms
SESSION_SECRET='*********'

# Hoppscotch App Domain Config
REDIRECT_URL="https://hoppscotch.company.com"
WHITELISTED_ORIGINS = "https://hoppscotch.company.com:3200,https://hoppscotch.company.com,https://hoppscotch.company.com:3100"

# Google Auth Config
GOOGLE_CLIENT_ID="*****"
GOOGLE_CLIENT_SECRET="*****"
GOOGLE_CALLBACK_URL="http://localhost:3200/v1/auth/google/callback"
GOOGLE_SCOPE="email,profile"

# Github Auth Config
GITHUB_CLIENT_ID="*****"
GITHUB_CLIENT_SECRET="*****"
GITHUB_CALLBACK_URL="http://localhost:3200/v1/auth/github/callback"
GITHUB_SCOPE="user:email"

# Microsoft Auth Config
MICROSOFT_CLIENT_ID="*********-****-****-****-******************"
MICROSOFT_CLIENT_SECRET="*********************************************"
MICROSOFT_CALLBACK_URL="https://hoppscotch.company.com:3200/v1/auth/microsoft/callback"
MICROSOFT_SCOPE="user.read"

# Mailer config
MAILER_SMTP_URL="smtps://smtp.it.company.com:25"
MAILER_ADDRESS_FROM='"user" <user@company.com>'



RATE_LIMIT_TTL=60 # In seconds
RATE_LIMIT_MAX=100 # Max requests per IP


#-----------------------Frontend Config------------------------------#


# Base URLs
VITE_BASE_URL=https://hoppscotch.company.com
VITE_SHORTCODE_BASE_URL=https://hoppscotch.company.com
VITE_ADMIN_URL=https://hoppscotch.company.com:3100

# Backend URLs
VITE_BACKEND_GQL_URL=https://hoppscotch.company.com:3200/graphql
VITE_BACKEND_WS_URL=wss://hoppscotch.company.com:3200/graphql
VITE_BACKEND_API_URL=https://hoppscotch.company.com:3200/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/privacy

**Comment by aciokler** [comment]
Hello, any updates on this? I'm facing a similar issue. Trying to self host but stuck in the "pnpm install" step with similar connection issue regarding prisma. Thanks!

**Comment by aciokler** [comment]
I had a similar issue and it got solved after turning off the VPN I was using. So this is likely something in your network.

**Comment by webysther** [comment]
Hi @goutham639 you can skip all these steps using this image: https://hub.docker.com/r/webysther/hoppscotch, hope helps

**Comment by AndrewBastin** [comment]
Closing this as this should be resolved with the updated build steps in 2023.8.0.
