### ISSUE TITLE
[feature]: Access to environment in Tests

### ISSUE THREAD

**Issue by koehler0179** [hoppscotch/hoppscotch#3184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Would be nice if it would be possible to access the environment variables in the tests as it is possible in Postman.

### Why should this be worked on?

 Sometimes you have multiple requests where the next request uses a value of the result from the previous request. Currently if trying to set an environment variable in a test ends up with an error running the test.

pw.env.set("myVar", "some value");

**Comment by liyasthomas** [comment]
Hi @koehler0179, can you share the error logs when you ran the Test scripts?

Hoppscotch Test scripts have support for environment context and can add, append and edit environment variables from test scripts. Documentation: https://docs.hoppscotch.io/documentation/features/scripts#pwenvgetvariable

```javascript
pw.env.set("baseURL", "https://httpbin.org");
```

**Comment by koehler0179** [comment]
Okay, my fault. Value always has to be converted to string to work. Tried to set a bool and that was throuwing an error.

pw.env.set("myVar", true);
or:
pw.env.set("myVar", 1);

Would be nice to have an any type as value that is internal converted to a string.
