### ISSUE TITLE
while running CLI hopp test getting error Malformed ENV file. How to solve this issue? 

### ISSUE THREAD

**Issue by venseenu1975** [hoppscotch/hoppscotch#3186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was able to import collection. Also created the environment. while running CLI hopp test command getting error Malformed ENV file. How to solve this issue? 
<img width="647" alt="Error1" src="https://github.com/hoppscotch/hoppscotch/assets/16758498/403d71c1-4a3c-44b6-bfea-a4ca4da2d0a3">

### Steps to reproduce

<img width="647" alt="Error1" src="https://github.com/hoppscotch/hoppscotch/assets/16758498/61584eb1-3207-4ab2-8783-17fc493ea3d8">

### Environment

Release

### Version

Cloud

**Comment by venseenu1975** [comment]
I have resolved this issue and now I am able to run using CLI hopp test. You can close this issue.

**Comment by liyasthomas** [comment]
Glad it got resolved even before we could assist you with the issue. Feel free to re-open/create a new ticket if you met with any inconvenience or bugs.

**Comment by venseenu1975** [comment]
Hi Liyas Thomas,

Thank you. Could you please let me know whether Postman Pre-request scripts
and Tests Javascript can be used here in hoppscotch?

I was able to check
https://docs.hoppscotch.io/documentation/features/scripts#pwresponse

With Regards,
Srinivasan Venkatesan
Cell: +91 99629 93329
