### ISSUE TITLE
[feature]: Add secrets flag to hide secrets in frontend and cli logs

### ISSUE THREAD

**Issue by danitherex** [hoppscotch/hoppscotch#3195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We would like to be able to set a secrets flag on specific environment variables, that hides them from the frontend and from logs (when running tests in the cli).
![Bild1](https://github.com/hoppscotch/hoppscotch/assets/54203817/a027cc7c-a8f3-43ad-a9ae-50a54a995141)
for example like this

So the values are hidden:
 
![Bild2](https://github.com/hoppscotch/hoppscotch/assets/54203817/aa619dc3-b10a-451f-a754-9ee5f94db01a)

Do you already have this feature in your backlog, or is it possible for us to start working on this feature? We would be pleased to receive your feedback. 

### Why should this be worked on?

These enhancements would improve the privacy of HoppScotch and could be the first step to issue #3183

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in a previous release candidate.

Documentation: https://docs.hoppscotch.io/documentation/features/variables#types-of-variables

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
