### ISSUE TITLE
[bug]: SMTP format is not working in Self host Hoppscotch

### ISSUE THREAD

**Issue by venkatayedidasv** [hoppscotch/hoppscotch#3197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

while executing `pnpm install `, with below .env.example getting error. Have tried multiple ways with Mailcatcher as well. but it does not work 

error:

```
/Users/userapi-testing/hoppscotch/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21
│   throw new Error(errMessage);
│         ^
│ Error: mailer/smtp_url_undefined
│     at throwErr (/Users/user/api-testing/hoppscotch/hoppscotch/packages/hoppscotch-backend/src/utils.ts:21:9)
│     at Object.<anonymous> (/Users/user/api-testing/hoppscotch/hoppscotch/packages/hoppscotch-backend/src/mailer/mailer.module.ts:15:48)
│     at Module._compile (node:internal/modules/cjs/loader:1275:14)
│     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
│     at Module.load (node:internal/modules/cjs/loader:1133:32)
│     at Function.Module._load (node:internal/modules/cjs/loader:972:12)
│     at Module.require (node:internal/modules/cjs/loader:1157:19)
│     at require (node:internal/modules/helpers:119:18)
│     at Object.<anonymous> (/Users/user/api-testing/hoppscotch/hoppscotch/packages/hoppscotch-backend/src/auth/auth.module.ts:5:1)
│     at Module._compile (node:internal/modules/cjs/loader:1275:14)

```

.env.example:
```
# Prisma Config
DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres

# Auth Tokens Config
JWT_SECRET="secret1233"
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY= 3
REFRESH_TOKEN_VALIDITY="604800000" # Default validity is 7 days (604800000 ms) in ms
ACCESS_TOKEN_VALIDITY="86400000" # Default validity is 1 day (86400000 ms) in ms
SESSION_SECRET='mysecretpassword'

# Hoppscotch App Domain Config
REDIRECT_URL="http://localhost:3000"
WHITELISTED_ORIGINS = "http://localhost:3170,http://localhost:3000,http://localhost:3100"

# Github Auth Config
GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=""
GITHUB_CALLBACK_URL="http://localhost:3170/v1/auth/github/callback"
GITHUB_SCOPE="user:email"

# Mailer config
MAILER_SMTP_URL="smtps://user@gmail.com:pass@smtp.gmail.com"
MAILER_ADDRESS_FROM='"Venkata Yedida" <user@gmail.com>'

# Rate Limit Config
RATE_LIMIT_TTL=60 # In seconds
RATE_LIMIT_MAX=100 # Max requests per IP

```

### Steps to reproduce

1. pnpm install
2. error 

### Environment

Production

### Version

Self-hosted

**Comment by venkatayedidasv** [comment]
it is resolved

**Comment by venkatayedidasv** [comment]
i was able to fix it, there is different error as i have am using M1 mac will raise a new one for this

**Comment by NassaDevops** [comment]
> 

How did you resolved it?

**Comment by venkatayedidasv** [comment]
> 

First things i have changed the host of the SMTP server to "smtp://host.docker.internal:1025" as i am running the mailcatcher locally 
and check if you have renamed example.env to .env

**Comment by NassaDevops** [comment]
> > 
> 
> First things i have changed the host of the SMTP server to "smtp://host.docker.internal:1025" as i am running the mailcatcher locally and check if you have renamed example.env to .env

It worked for me changing smtps:// for smtp:// and at the end specifying the port 587.
I was using the smtp.outlook365.com

Thank you

**Comment by ifnotnithya** [comment]
Hi, I am running into the same error. And do not want to use mailcatcher. What is the resolution to use gmail?

**Comment by philippos86** [comment]
> Hi, I am running into the same error. And do not want to use mailcatcher. What is the resolution to use gmail?

Same question here ...

**Comment by suiluj** [comment]
i just want to disable the whoe mail feature and only want to try hoppscotch locally. How to disable unnecessary extra feature for small local tests?

**Comment by NassaDevops** [comment]
This is my configuration for the mailer setup using Outlook.. I guess it should work with the equivalents of gmail SMTP configuration

# Mailer config
MAILER_SMTP_URL="smtp://EMAILADDRESS:PASSWORD@smtp.office365.com:587"
MAILER_ADDRESS_FROM='"NAME" <EMAILADDRESS>'

**Comment by ChuTungLinh** [comment]
> This is my configuration for the mailer setup using Outlook.. I guess it should work with the equivalents of gmail SMTP configuration
> 
> # Mailer config
> MAILER_SMTP_URL="smtp://EMAILADDRESS:[PASSWORD@smtp.office365.com](mailto:PASSWORD@smtp.office365.com):587" MAILER_ADDRESS_FROM='"NAME" '

by "PASSWORD" do u mean the account password or the account's app password ?
