### ISSUE TITLE
[feature]: hoppscotch for linux/arm64 platform 

### ISSUE THREAD

**Issue by venkatayedidasv** [hoppscotch/hoppscotch#3199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I want to Hoppscotch to support the linux/amd64 (Mac with silicon chips) platform , as currently its not working when we self host. node modules are shipped with different platform

### Why should this be worked on?

It will enable linux/amd64 (Mac with silicon chips) platform users self host hoppscotch

**Comment by webysther** [comment]
@venkatayedidasv can I ask you to test this image https://hub.docker.com/r/webysther/hoppscotch? I have added ARM a few days ago and don't have any machine to test here.

**Comment by venkatayedidasv** [comment]
@webysther, sure will be happy to test it

**Comment by balub** [comment]
Hey, @venkatayedidasv we currently support both `linux/amd64` and `linux/arm64` architectures. Please check it out [here](https://hub.docker.com/r/hoppscotch/hoppscotch/tags?page=1&page_size=&name=&ordering=)
