### ISSUE TITLE
[bug]: Self-Hosted Hoppscotch: Workspace import of Postman/Hoppscotch JSON leads to broken folder tree structure, except in team context

### ISSUE THREAD

**Issue by kimseungwook** [hoppscotch/hoppscotch#3208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am experiencing an issue specifically when importing Postman or Hoppscotch JSON files from my Workspace. After the import, the folder tree structure is incorrect and does not reflect the original structure of the imported JSON.

The key issue is that the id of the top-level folder in the userCollection table is being replaced with the collectionID from the userRequest table. This replacement results in a broken folder tree structure.

However, this problem does not occur when I am working within a team organization context. If I organize a team and upload the same JSON file, the import correctly reflects the original structure.

The problem appears only when importing files directly from my Workspace outside of a team organization context. Is this a known issue, or could you offer any advice on how to resolve this?

Thank you for your attention to this matter.

### Steps to reproduce

my Workspace
import postman

### Environment

Production

### Version

Self-hosted

**Comment by ivan-zinchenko** [comment]
fyi, issue is still there with the latest AOI-image

**Comment by JoelJacobStephen** [comment]
@kimseungwook Are you still facing the same issue in the latest build?

**Comment by opctim** [comment]
This issue still persists. See https://github.com/hoppscotch/hoppscotch/issues/4171
