### ISSUE TITLE
[feature]: customize oAuth methods on SelfHosted 

### ISSUE THREAD

**Issue by jmtt89** [hoppscotch/hoppscotch#3211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

All Oath configurations are required, it would be nice if the configuration for a certain platform did not exist in the .env file, that platform would not appear

### Why should this be worked on?

When using a self-hosted instance, a very common scenario is to only allow access to members of my company or custom external invites, not anyone with a Google or Microsoft account.

**Comment by RaHehl** [comment]
take a look at #3200 & #3088

**Comment by balub** [comment]
You can checkout #3204 we are currently working on this.

**Comment by jmtt89** [comment]
thanks!!
