### ISSUE TITLE
[bug]: localhost:3170 auth is not working

### ISSUE THREAD

**Issue by Cybilltek** [hoppscotch/hoppscotch#3212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I tried to create a self-hosted hoppscotch but I'm having issues right now with localhost port 3170. How do I configure this/resolve this issue? Apologies but I'm just new to this kind of environment. 

Will appreciate the help. Thank you!

![image](https://github.com/hoppscotch/hoppscotch/assets/140045722/72fc9fce-3e40-4c29-96d3-d4f1ed09ff7b)

![image](https://github.com/hoppscotch/hoppscotch/assets/140045722/7eb11c36-6bed-4f98-814e-f484dcd51a1a)

![image](https://github.com/hoppscotch/hoppscotch/assets/140045722/834fda66-1c06-4582-8127-c13e18efa53a)

### Steps to reproduce

The only steps I made so far was to
1. compose build the docker and now I am planning to have users login using the EMAIL but having issues with it. 

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
Hey @Cybilltek , could you share your .env file with us so that we can see if anything is proper?

**Comment by Cybilltek** [comment]
Hi @balub , here is the preview of my test local hosted hoppscotch.
![image](https://github.com/hoppscotch/hoppscotch/assets/140045722/2c2fcd23-5ad2-4187-aa7d-1293d1d3daff)

**Comment by balub** [comment]
@Cybilltek next time please gray out or simply just delete when sharing things like secret keys or client secrets.

**Comment by webysther** [comment]
auth don't work without HTTPS, use [this image](https://hub.docker.com/r/webysther/hoppscotch) with .env SCHEMA=http

**Comment by li-xunhuan** [comment]
I also encountered this problem. I modified VITE_BACKEND_GQL_URL and other configurations in the .env file, but the browser console still shows the requested localhost:3100, which is completely different from my settings.

**Comment by webysther** [comment]
> I also encountered this problem. I modified VITE_BACKEND_GQL_URL and other configurations in the .env file, but the browser console still shows the requested localhost:3170, which is completely different from my settings.

Please use my image as a test and read the logs, is expected all ENV changed, but if not probally is a TYPO or a misunderstood.

**Comment by webysther** [comment]
Paste the log output here if the same error persists.

**Comment by mirarifhasan** [comment]
Hi @Cybilltek,
Are you still facing this issue? If not, we will be closing this issue in a few days.
