### ISSUE TITLE
[feature]: 

### ISSUE THREAD

**Issue by stevelix** [hoppscotch/hoppscotch#3218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Could we have an up to date docker image https://hub.docker.com/r/hoppscotch/hoppscotch? The latest one is 5 months ago. 

### Why should this be worked on?

It will be easier to use in cloud.

**Comment by webysther** [comment]
Not a official one, only in few months, you can use this one is update: https://hub.docker.com/r/webysther/hoppscotch

**Comment by liyasthomas** [comment]
Possibly a duplicate of #3069, hence closing.
