### ISSUE TITLE
[feature]: Any plan to support Mysql database

### ISSUE THREAD

**Issue by kings1990** [hoppscotch/hoppscotch#3219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Is there any plan to support the Mysql database

### Why should this be worked on?

A lot of developers use Mysql database

**Comment by webysther** [comment]
Prisma that is used require json which don't is supported by any database otherwise postgres on prisma, sorry.

**Comment by chenjianfei1989** [comment]
https://dev.mysql.com/doc/refman/8.4/en/json.html Mysql 8 supports json type

**Comment by luckyraul** [comment]
https://www.prisma.io/docs/orm/overview/databases/mysql#native-type-mapping-from-prisma-orm-to-mysql
