### ISSUE TITLE
[feature]: Move Fonts and all other packages to the local container - ensure CSP and Data Privacy

### ISSUE THREAD

**Issue by GAS85** [hoppscotch/hoppscotch#3226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I deploy my cool own hosted hoppscotch, in a Network stack I see that there are calls passing to the `fonts.gstatic.com`, `fonts.googleapis.com` and `client.crisp.chat`. This will violate my Data Privacy statement.
![image](https://github.com/hoppscotch/hoppscotch/assets/6813635/eb8cb61d-3425-4fdf-b34c-0a2ba908dd50)

Please add option to move those packages into the container during the build, or do this per default.

### Why should this be worked on?

This is major Data Privacy violation for most self-hosted apps, e.g.: https://www.theregister.com/2022/01/31/website_fine_google_fonts_gdpr/

**Comment by liyasthomas** [comment]
Hi @GAS85, thanks for suggesting this improvement and bringing the same to our attention. We'll soon release a patch with the suggested assets removed/locally bundled with the platform.

**Comment by lwd-temp** [comment]
It would be helpful to allow users to disable Crisp Chat, since this never used in a self-deployed hoppscotch.

**Comment by liyasthomas** [comment]
We're working on removing the in-app chat feature in the self-hosted instance. Expect the same in the next release tag, as early as in next week.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.
