### ISSUE TITLE
[feature]: Subpath Support for self-hosting Version

### ISSUE THREAD

**Issue by GAS85** [hoppscotch/hoppscotch#3231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hello dear community, I find out that I can't use self-hosted hoppscotch if I have it under subpath e.g.: `https://FQDN/hoppscotch`. According to the Documentation `VITE_BASE_URL` was updated before build, but seems it does not make anything. All files still accessible only under root.
Interesting is that `VITE_BACKEND_*_URL` have impact and from the Browser I can see that correct links are called.

### Why should this be worked on?

Seems it was working before: https://github.com/hoppscotch/hoppscotch/issues/315 and https://github.com/hoppscotch/hoppscotch/issues/906 with postwoman.

**Comment by balub** [comment]
Subpath Access to services added in release `2023.12.0`.
