### ISSUE TITLE
Clear content when create new request 

### ISSUE THREAD

**Issue by 838239178** [hoppscotch/hoppscotch#3234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I create a new request, the content of the new request is my last open request. Sometimes I doubt whether I have successfully created it because the form has not changed. I hope the content of the new request is empty, so as to intuitively indicate that I have created a new request.

### Why should this be worked on?

Avoid confusing

**Comment by liyasthomas** [comment]
When you create a new request from **"Collections"** > **"New Request"**, the currently active Tab is set as the request context. This behavior is expected. If you want to create an empty request to Collection, open a fresh New Tab and create a new request from Collections > New Request. Make sure you selected the new Tab while creating the request.

> [!NOTE]
> When you create a new tab, we populate the URL field with the placeholder endpoint: `https://echo.hoppscotch.io`, and set the HTTP method to `GET` by default.

**Comment by 838239178** [comment]
BTW, I deployed by the official docker image which is older version than the GitHub main branch, so it doesn't have "tab" feature. After I build and deploy image by myself with main branch, I no longer have this confusion.
