### ISSUE TITLE
[enhancement]: The Environment selection is contraintuitive and the current environment is not visible during request sending

### ISSUE THREAD

**Issue by dakujem** [hoppscotch/hoppscotch#3235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

It took me over a dozen of minutes to figure out how to "select an environment" in a new collection I have just created.

I would click the 3 dots on each environment, I would search the UI for a global toggle, and to no avail.
![image](https://github.com/hoppscotch/hoppscotch/assets/443067/bb8b0927-9776-41e3-be1d-c7f89c875a63)

I would expect a global toggle, that is **always visible in the UI**, like the "Workspace" toggle.

I may be biased by Postman that I have been using for almost a decade now, but it really is **important** to me to be able to tell what environment I'm running the requests against.  In fact, to see the Environemnt is more important to me than to see the workspace itself.

### Steps to reproduce

Try to guess what environemnt is in use.
Then try to change the environment.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
It seems you're using an outdated version of Hoppscotch.
If you're on [Hoppscotch Cloud](https://hoppscotch.io) instance do a hard refresh (<kbd>CMD</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>) to fetch the latest deployment.

Here's a screenshot of the latest Hoppscotch Cloud instance with an improved Global Environment Selector:

<img width="1470" alt="Screenshot 2023-08-03 at 9 15 07 PM copy" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/b7ea420d-d18d-4583-8b2d-9b4d0dcc4bb3">

**Comment by dakujem** [comment]
Yeah! That worked.... But ... Why did I have to hard reload? 🤔

**Comment by liyasthomas** [comment]
Hoppscotch is a [PWA](https://web.dev/progressive-web-apps), with offline-cache capabilities. Hoppscotch will load the cache-first version of web app and after a refresh it fetches the latest version.

**Comment by liyasthomas** [comment]
Hoppscotch is a [PWA](https://web.dev/progressive-web-apps), with offline-cache capabilities. Hoppscotch will load the cache-first version of web app and after a refresh it fetches the latest version.

**Comment by dakujem** [comment]
I know how it works, the question is, why does it not offer a way to reload to fetch the update? Some sites prompt for update (vue docs), other sites refresh when left inactive (toggle, messenger).
