### ISSUE TITLE
[bug]: XML Body disappearing

### ISSUE THREAD

**Issue by thomashanke** [hoppscotch/hoppscotch#3236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I enter a more complex XML body for a request with content type application/xml and I send some requests, after some time the XML body disappears (Body Tab, Raw Request Body) and is no longer displayed.
The body is still available and sent when I send a request but it is no longer displayed.
I can only change it if I clear the body (with the trashcan icon) and then enter it agan

### Steps to reproduce

1. Create a POST request
2. Go to Body, enter content type application/xml
3. enter a bigger XML as Raw Request Body
4. send the request
5. Save the request
6. Close the request tab, click around in the UI, open the request again
7. Go to the Body tab
8. Raw Request Body is not displayed
9. Send the request and detect that the body is still available but not displayed

### Environment

Production

### Version

Self-hosted

**Comment by thomashanke** [comment]
I also managed to reproduce the issue with the version that is **not** self hosted.
Steps to reproduce:
1. Create a POST request to https://echo.hoppscotch.io with the following body (contains an environment variable)
`<?xml version="1.0" encoding="UTF-8"?>
<msg:RequestMessage xmlns:msg="http://www.foo.com/TC57/2011/schema/message" xmlns:m="http://www.foo.com/TC57/CIM-abc#">
	<msg:Header>
		<msg:Verb>create</msg:Verb>
		<msg:Noun>MeterConfig</msg:Noun>
	</msg:Header>
	<msg:Payload>
		<m:MeterConfig>
			<m:Meter>
				<m:mRID><<Meter>></m:mRID>
				<m:amrSystem>METER_AMR_SYSTEM</m:amrSystem>
				<m:isVirtual>false</m:isVirtual>
				<m:serialNumber>Serial - 10137616</m:serialNumber>
				<m:timeZone>Europe/Berlin</m:timeZone>
				<m:timeZoneOffset>120</m:timeZoneOffset>
				
				<m:lifecycle>
					<m:installationDate>2019-01-01</m:installationDate>
				</m:lifecycle>
			</m:Meter>
			<m:ReadingType>
				<m:Names>
					<m:name>0.0.2.4.1.1.12.0.0.0.0.0.0.0.0.3.72.0</m:name>
					<m:NameType>
						<m:name>NameType</m:name>
						<m:NameTypeAuthority>
							<m:name>NameTypeAuthority</m:name>
						</m:NameTypeAuthority>
					</m:NameType>
				</m:Names>
			</m:ReadingType>			
		</m:MeterConfig>
	</msg:Payload>
</msg:RequestMessage>
>>`

Set the content type of the body to aplication/xml
Add a Pre-Request Script that contains
`pw.env.set("Meter", "value");`

2. Save the request as "Untitled" in a new collection with name "a"
3. Create a second request. The second request is a GET request to https://echo.hoppscotch.io and stored as "Untitled1" in the collection "a"
4. switch to  POST request  "Untitled" 
5. send POST request  "Untitled" 
6. switch to  GET request  "Untitled1" 
7. send GET request "Untitled1"
8. switch to tab Pre-Request Script in  GET request  "Untitled1" 
9. switch to  POST request  "Untitled" and tab "Body"
10. Request Body now is gone!
11. Send POST request  "Untitled". Echo shows received XML, so body is still there but is not displayed.
12. If Body is deleted with trashcan icon, you can add a new body, but you never see the original body again

**Comment by aciokler** [comment]
I get the same issue. Complex xml bodies create errors in the browser console.

```
throwUnobservableError.js:2 Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at DU (throwUnobservableError.js:2:12)
    at pD (innerFrom.js:37:11)
    at GU (from.js:4:54)
    at combineLatest.js:38:34
    at _S (combineLatest.js:67:9)
    at s (combineLatest.js:37:17)
    at combineLatest.js:57:17
    at _S (combineLatest.js:67:9)
    at A._subscribe (combineLatest.js:31:9)
    at A._trySubscribe (Observable.js:38:25)
```

**Comment by windows-2000** [comment]
I am also able to reproduce this locally hosted.  Anyone have a work around?

**Comment by JoelJacobStephen** [comment]
@thomashanke This issue will be closed in a few days as it has been fixed. Please let us know if you are still facing this issue in the latest builds.
