### ISSUE TITLE
[feature]: search bar on request response always present when scrolling

### ISSUE THREAD

**Issue by sawa-ko** [hoppscotch/hoppscotch#3240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently, when trying to search for something, you press CTRL + F, and it works fine, but the problem is that the search bar stays at the top of the request response, and does not follow the scroll, so it's a bit annoying, because I can't use the search controls at the bottom of the request response.

It would be nice if even if you scroll the search bar is always visible.

https://github.com/hoppscotch/hoppscotch/assets/56084970/c81349b0-8b2e-46a0-9e80-9583ec3def1e

### Why should this be worked on?

For better UX, as there are cases where we need to look for something in what is far below the request response.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
