### ISSUE TITLE
[feature]: Support export of a single environment

### ISSUE THREAD

**Issue by cjchand** [hoppscotch/hoppscotch#3248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When clicking the "Export" icon for Environments, there is not an option to choose which environment to export. Instead, all of the Environments are exported in one blob.

When trying to use this file with `hopp test`, it results in a `MALFORMED_ENV_FILE` error.

### Why should this be worked on?

For end users that are less technically savvy, this presents a challenge to export the desired Environment to use for CLI testing (e.g.: running a Collection as a functional test suite).

For any user, it causes additional friction to manually carve up the file for the target Environment.

**Comment by liyasthomas** [comment]
It seems this feature is already available in Hoppscotch, hence I'm closing this ticket.
