### ISSUE TITLE
[bug]: Self hosted Displays Invalid Website Red Button

### ISSUE THREAD

**Issue by giripradip** [hoppscotch/hoppscotch#3278]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The hoppscotch ui app shows big red button on the right bottom corner of the screen which says invalid website.
Also following error has been displayed on the console:
throwUnobservableError.js:2 Uncaught TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable.
    at DU (throwUnobservableError.js:2:12)
    at pD (innerFrom.js:37:11)
    at GU (from.js:4:54)
    at combineLatest.js:38:34
    at _S (combineLatest.js:67:9)
    at s (combineLatest.js:37:17)
    at combineLatest.js:57:17
    at _S (combineLatest.js:67:9)
    at A._subscribe (combineLatest.js:31:9)
    at A._trySubscribe (Observable.js:38:25)

### Steps to reproduce

1. Self hosted environment
2. the main page of hoppscotch app
3. See the bottom right corner of the page
4. Invalid website big red button
5. Check the console

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
This is a known issue, we're working on fixing this as soon as possible.

**Details**
We're using an in-app messaging service to enable users to chat with our support team. Recently we've disabled this service to respect platforms' privacy and ensure 100% on-premise deployments (as reported in #3226).

Expect a release candidate as early as next week which will fix this issue.

**Comment by giripradip** [comment]
Cool. Thank you!
