### ISSUE TITLE
[bug]: Hidden URL on URL input box 

### ISSUE THREAD

**Issue by Vishal7100jain** [hoppscotch/hoppscotch#3281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

On the home page url input div is get overflowed and hide the url when the url is large in length,  and gets hard to edit.

### Steps to reproduce

1. Go to Home page
2. click on url input 
3. input large length url 
4. you will see the overflow gets hidden

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Hi @Vishal7100jain, this is an expected behavior. The URL bar will not expand to fit its content's length instead overflowing part will be hidden at the end. You can still horizontally scroll on such input fields to reveal the hidden or overflowing text.

**Comment by Vishal7100jain** [comment]
<img width="636" alt="Screenshot 2023-08-23 234810" src="https://github.com/hoppscotch/hoppscotch/assets/134675294/38f9735f-cc7e-4dfe-8909-860864a277dc">

Its become more easy to edit it when it can scroll in y axis like this
