### ISSUE TITLE
How to setup https？

### ISSUE THREAD

**Issue by william-ewebs** [hoppscotch/hoppscotch#3302]
How to setup https？
Is there any tutorial or guide？
I don't know how to do this, please help me！

Thanks

**Comment by SamJakob** [comment]
I would recommend using `nginx` as a reverse proxy for SSL termination. So set up hoppscotch in HTTP mode (on some random firewalled port) and then set up nginx and configure nginx to forward requests to it. Incidentally, this is my recommended way for setting up the proxy server with HTTPS.

Doing so is very well supported in principle as such a technique is done by a large portion of the industry for any and all web applications and doing this will give you high levels of flexibility (particularly if you wanted to host multiple web services on one IP/domain and port).

You can read about how this works here: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
