### ISSUE TITLE
[bug]: Import/Export Environments does not have an option to import from Postman

### ISSUE THREAD

**Issue by MustansirM** [hoppscotch/hoppscotch#3303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Clicking on the Import/Export button on Collections works as expected, where import options are listed as Hoppscotch, Postman, OpenAPI, among others. If Postman is selected, a further select file section is shown, which allows for selecting a local json file.

However clicking on the corresponding Import/Export button in the Environments sections only lists Import from Hoppscotch. On clicking the option, a local json file can be selected. If the json file has been generated from Postman, it works correctly.

This seems to be a UI/messaging issue, where despite a Postman exported environment file working correctly, it is not listed as an option. Is this meant to be intentional or are there edge cases where a Postman environment json does not work as expected and hence the option is not shown to the user?

If Postman exported files are supported and only the UI is misleading, I can take up that fix.

### Steps to reproduce

1. Go to the Environments section
2. Click on the Import/Export option

### Environment

Production

### Version

Cloud

**Comment by JoelJacobStephen** [comment]
@MustansirM This issue is solved. Can you confirm once on your end so that I can close this issue?
