### ISSUE TITLE
[bug]: Cannot test APIs when status code is >= 400

### ISSUE THREAD

**Issue by zlojic** [hoppscotch/hoppscotch#3313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I want to test some API on my localhost and I'm using PWA with browser extension as interceptor
[Also tried from browsers: Chrome and Firefox].

Response is shown when response status is 200.
If i change in my application to return status 400, with same data [everything is same except status code]

Then Hoppscotch shows this
<img width="972" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/94617238/5cb4ac6c-cfd4-43ae-9455-ddd38d67b2f0">

If i export curl from Hoppscotch and try it from command line, it gets response without troubles

### Steps to reproduce

1. Use browser extension
2. Send request to any API returning status 400
3. See error

### Environment

Production

### Version

Cloud

**Comment by Fillps** [comment]
I'm seeing the same issue here.

**Comment by njhames** [comment]
Same thing for me as well.

**Comment by cr4ck3r-byte** [comment]
I have to put a console.log(error) to visualize the error.

**Comment by ninjoma** [comment]
The error comes from the extension's axios implementation returning an exception when responseCode >= 400.

I've submitted a PR that hopefully fixes this bug on the extension: https://github.com/hoppscotch/hoppscotch-extension/pull/227

**Comment by zlojic** [comment]
Looks fixed 😺
