### ISSUE TITLE
[feature]: There is no arm version for docker image

### ISSUE THREAD

**Issue by mazlum** [hoppscotch/hoppscotch#3316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

https://hub.docker.com/r/hoppscotch/hoppscotch/tags

Do you think release for arm64?

### Why should this be worked on?

Some users have arm machine. So we can use it.

**Comment by AndrewBastin** [comment]
Closing as this is a duplicate of #3199
