### ISSUE TITLE
[bug]: "Could not send requests" when I use extension and request return a 404 error

### ISSUE THREAD

**Issue by ajotaops** [hoppscotch/hoppscotch#3320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,

I'm encountering an issue while using the browser extension of https://hoppscotch.io/. When I attempt to make requests from certain pages, I receive an error message stating "Could not send requests."

These requests work fine if I do on the browser.

**Additional Information:**

Extension version: v0.25

### Steps to reproduce

1. Go to https://hoppscotch.io/
2. Select browser extension as Interceptor
3. Make GET request to https://api.bitbucket.org/2.0/repositories/tutorials/tutorials.bitbucket.org

### Environment

Production

### Version

Cloud

**Comment by SanskritiHarmukh** [comment]
Hi @ajotaops I tried reproducing the issue. On browser, it gives the following,
```
{
  "type": "error",
  "error": {
    "message": "You may not have access to this repository or it no longer exists in this workspace. If you think this repository exists and you have access, make sure you are authenticated."
  }
}
```

Indicating that you might not have either the correct permission to access the URL or it does not exist. I made a request for `https://api.bitbucket.org/2.0/repositories/tutorials` to inspect further and noticed that `tutorials.bitbucket.org` repo is not present in the `tutorials` workspace, instead `tutorials.git.bitbucket.org` exists.

Can you try the below URL?
`https://api.bitbucket.org/2.0/repositories/tutorials/tutorials.git.bitbucket.org`

**Comment by ajotaops** [comment]
Hi @SanskritiHarmukh ,

I apologize if my previous message was not clear enough regarding the problem I am experiencing. The issue I am seeing is not related to the 404 response of the example.

The link I provided earlier, I already knew it does not return a 200 code, but the problem I want to point out is that when I make a request that receives an error response code, Hoppscotch (only with interceptor extension) does not display the expected response (in this case, the 404). Instead, it shows a generic error message stating "Could not send requests,", a problem of network.

To clarify this, I can provide another example with a less confusing API. When I make a GET request to https://pokeapi.co/api/v2/pokemon/ditto via the extension, I correctly see a 200 response code on hoppscotch.

However, when I make a request to a resource that returns a 404 response code, such as https://pokeapi.co/api/v2/pokemon/noexists, that's when I encounter the "Could not send requests" problem instead of seeing the expected 404. But if I do without the extension I can see 404.

I change the title with the issue.

Thanks for reviewing!

**Comment by SanskritiHarmukh** [comment]
The response that you are getting on executing these requests is not a typical HTTP 404 error

**Comment by ajotaops** [comment]
What do you mean? When I make the request without the Interceptor or with the proxy I do see the 404 request normally:

![404](https://github.com/hoppscotch/hoppscotch/assets/74736404/eff091df-ba0c-42f4-ab9d-759cc444560a)


Only with extension I see "Could not send requests"

**Comment by SanskritiHarmukh** [comment]
Okay I was talking about the BitBucket one. With the other requests I was just checking on my end too

**Comment by SanskritiHarmukh** [comment]
This seems like a problem, I tested with few more endpoints. Thank you for reporting @ajotaops we'll look into w.r.t extention interceptor.

**Comment by ajotaops** [comment]
Sorry i saw this is duplicated 

https://github.com/hoppscotch/hoppscotch/issues/3313

And there is a PR with possible solution https://github.com/hoppscotch/hoppscotch-extension/pull/227 

I close this as duplicated
