### ISSUE TITLE
[bug]: CMD-C on Dvorak keyboard causes Reset Request

### ISSUE THREAD

**Issue by mermerico** [hoppscotch/hoppscotch#3322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The "c" key in the Dvorak keyboard layout is in the position of the "i" key in the QWERTY layout. For some reason when I use a Dvorak layout and press CMD-C, it sends a CMD-I shortcut to Hoppscotch and resets the request. Other shortcuts work as expected.

Maybe this should be filed as a separate bug, but resetting a request cannot be undone, meaning that I lose all my work if I forget about this bug and try to copy some text. If it is difficult to implement undo for this action, I suggest this shortcut be removed since it's such a footgun.

### Steps to reproduce

1. Use a Dvorak layout (on Mac OS)
2. Select some text in the body of a request
3. Press CMD-C

 I've tested this in Firefox, Chrome, and the PWA, but not in other operating systems.

### Environment

Production

### Version

Cloud

**Comment by SanskritiHarmukh** [comment]
@mermerico Thank you for reporting, we'll look into it.

**Comment by mermerico** [comment]
Thank you so much!
