### ISSUE TITLE
[bug]: Cannot access 'o' before initialization

### ISSUE THREAD

**Issue by radrianhp** [hoppscotch/hoppscotch#3338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to access demo project. I want to access URL, but the result not show and showing some error in console.

### Steps to reproduce

1. Access to Demo .
2. Click button test in https://echo.hoppscotch.io/
3. display not showing the result 
how to solve this error ? 
![image](https://github.com/hoppscotch/hoppscotch/assets/15336755/e335ab73-e845-4a57-af0c-23fdea06fa4b)

### Environment

Production

### Version

Cloud

**Comment by sebzz2002** [comment]
I have found the same issue on 
os - ubuntu 20.04
browser - firefox

I am not able to send or recive respone

**Comment by lili21** [comment]
same issue here

**Comment by pupca** [comment]
i have the same issue

**Comment by anubhavhazarika** [comment]
Same issue as well. Self-host, intercepter via browser extension: Chrome

**Comment by shahwan42** [comment]
Same!
Self-host, no extension or with extension. Chrome.

Uncaught ReferenceError: Cannot access 'o' before initialization
![image](https://github.com/hoppscotch/hoppscotch/assets/6496157/2336c6ab-6a31-470f-bffd-763accb4c24c)

**Comment by giosueDelgado** [comment]
> Same! Self-host, with/out the extension. Chrome.
> 
> Uncaught ReferenceError: Cannot access 'o' before initialization ![image](https://user-images.githubusercontent.com/6496157/267292109-2336c6ab-6a31-470f-bffd-763accb4c24c.png)
> 
> Update: Same on Safari after login. Works without login.

Agree with you also for me!

**Comment by AndrewBastin** [comment]
So, from my triages this seems to be a bug with the extension handling code updates. We will get this fixed in an upcoming point release.

But, this error seems to only happen if the app origin is not registered into the extension (which will be the case for Self Hosted). See https://docs.hoppscotch.io/documentation/features/interceptor#browser-extension and follow the steps there to add your self-hosted instance's origin into the extension.

You will know the extension is registered with the app, when you see "Browser Extension: vX.XX" instead of "Browser Extension: Not Reported"

@giosueDelgado @shahwan42 @anubhavhazarika @lili21 @sebzz2002 @radrianhp please verify if so and if the issue still persists, please let me know.

**Comment by shahwan42** [comment]
@AndrewBastin Thanks. Yes, it worked once I added the hosting domain to the origins list in the extension.

**Comment by sebzz2002** [comment]
@AndrewBastin  I am not using a self-hosted version of hoppscotch but the one available freely. I am facing this issue. I also checked the browser extensions and it already has the origin.
Thank you

**Comment by giosueDelgado** [comment]
I'm using the self-hosted behind a Nginx configuration and I have already the issue, I just added the localhost in the extension when I made some tests on the first days.
Thanks for the support, I'm trying to use also for some clients and I think this is a blocking point.

**Comment by mjhcorporate** [comment]
I just tried hoppscotch for the first time, using https://hoppscotch.io/, and ran into this bug. I'm on MacOS 13.5.1 using Edge 116.0.1938.76. 

The timing is really unfortunate -- Postman is sunsetting scratchpad _today_, so I imagine lots of users will be evaluating hoppscotch today!

**Comment by j4k0xb** [comment]
![image](https://github.com/hoppscotch/hoppscotch/assets/55899582/e3f8c96a-e512-4fe1-b406-a9349972b15a)

It works again by turning this off (I don't have the extension installed)

**Comment by IeuanWalker** [comment]
same issue here when trying to use the browser extension to test a local API.

For some reason it doesn't detect the extension - 
![image](https://github.com/hoppscotch/hoppscotch/assets/6544051/ef388aff-3112-425b-beda-17db218e9341)

**Comment by beeant0512** [comment]
![image](https://github.com/hoppscotch/hoppscotch/assets/6050235/88ec96c3-158c-41fc-bb81-b83c3e9a9ed8)

1. click the extension button 
2. click add button

**Comment by giosueDelgado** [comment]
I install the tool on one of my client, we will give you feedback in the next weeks if it works or not
Thanks!
