### ISSUE TITLE
[bug]: No Request debugging / inspections on selfhosted Hoppscotch

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When sending a request, I am unable to view how the raw request I've sent looks. 
Additionally, in the Network tab of the developer tools, there is no information available, and the Inspector feature mentioned in the documentation (https://docs.hoppscotch.io/documentation/features/inspections) is not visible.

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/95207775-dc2e-4b07-85de-0ca3bfa17273)

We are using the Chrome plugin for CORS purpose.

### Steps to reproduce

1. Send a request using Hoppscotch SelfHosted
2. Try to debug it

### Environment

Release

### Version

Self-hosted

**Comment by liyasthomas** [comment]
The inspection menu will be only shown when there's a potential error with the current request setup. Since there's no possible mismatch or error with your current request setup, the inspections menu got hidden. This is an expected behavior.
