### ISSUE TITLE
[feature]: View RAW request

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Like mentioned in #3357 i need to view the send requests for debugging purpose even if the response is HTTP 2xx

### Why should this be worked on?

This makes working on more complex APIs easier

**Comment by liyasthomas** [comment]
Hi @RaHehl, let me know if this comment helps you to view the entire final request object: https://github.com/hoppscotch/hoppscotch/issues/2651#issuecomment-1557056572.

---

We have a feature that allows you to "Generate code snippets" for various programming languages and frameworks:

1. Click on the drop-down right next to the "**Send**" button to open the options menu.
2. Click on "**Show code**" menu item.
3. Select "**HTTP - HTTP 1.1 Request String**" from the "Generate code" modal.

This displays the current request setup in HTTP 1.1 Request String syntax. Let us know if this suits your use case.

![Step (1)](https://github.com/hoppscotch/hoppscotch/assets/10395817/58fda089-e533-4af8-8640-cd10c260c839)
![Step (2)](https://github.com/hoppscotch/hoppscotch/assets/10395817/a9576d4d-bf9f-40fd-8951-686b20859e69)

**Comment by RaHehl** [comment]
@liyasthomas yes this helps thanks, perfect would it be having this as tab next to the response
