### ISSUE TITLE
PWA not retrieving status-400 codes

### ISSUE THREAD

**Issue by Batimius** [hoppscotch/hoppscotch#3361]
### Discussed in https://github.com/hoppscotch/hoppscotch/discussions/3309

<div type='discussions-op-text'>

<sup>Originally posted by **Batimius** September  1, 2023</sup>
Hello there. So, I was testing a local application (an app running on `http://localhost:3000`), and in my application, I return a status-400 response when the user does not provide the appropriate data to the API endpoint. When running the requests through Hoppscotch, any request that would end up in a status-400 response would give me a "Could not send request" screen. It wouldn't give me the response itself, but it would rather just display that it could not send the request.

I am unsure whether this is an intended behavior or not. I am using the extension and I have whitelisted `http://localhost:3000`, so I am unsure why this is an issue. If there is a way for me to fix this, please let me know. I am running Hoppscotch as a PWA from hoppscotch.io. That is all. Thank you for your time and help, they are truly appreciated.</div>

Just like mentioned in the discussion above, status-400 codes are never processed by the Hoppscotch application (PWA). Any status-400 request ends up in a "could not send request" screen. Since this seems to be unintentional, I decided to open an issue thread. Please let me know if this is a known issue or not. Thank you for the time and support.

**Comment by liyasthomas** [comment]
Thanks for submitting the issue. We have an open PR to fix this issue on our Browser Extension repository: https://github.com/hoppscotch/hoppscotch-extension/pull/227.

Expect a hotfix as early as next week. Thanks for being patient.

**Comment by Batimius** [comment]
> Thanks for submitting the issue. We have an open PR to fix this issue on our Browser Extension repository: [hoppscotch/hoppscotch-extension#227](https://github.com/hoppscotch/hoppscotch-extension/pull/227).
> 
> Expect a hotfix as early as next week. Thanks for being patient.

Thank you for the fast reply. Please @ me (or reply / close this issue) when this is fixed so I know when I can start using Hoppscotch again. Cheers!

**Comment by liyasthomas** [comment]
We've recently patched this issue, hence closing the ticket. Updated the browser extension to the latest version.

Feel free to re-open if the issue persists. cc: @Batimius
