### ISSUE TITLE
[feature]: Do not show telemetry settings in user settings if telemetry is globally disabled

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Telemetry is globally disabled:

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/816e1ef3-8a19-4f51-b3cc-9b72279d3548)

But Settings are still shown in user settings:

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/4ac624c5-4dda-4d66-8cb3-6f326b1acca1)

### Why should this be worked on?

Leads to questions from irritated users in enterprise environments

**Comment by liyasthomas** [comment]
Possibly a duplicate of #3364.

**Comment by RaHehl** [comment]
I wouldn't say it's a duplicate, but this https://github.com/hoppscotch/hoppscotch/issues/3364#issuecomment-1728840934 would also resolve this request.
