### ISSUE TITLE
[bug]: I cannot log in on admin. always redirect to home admin 

### ISSUE THREAD

**Issue by jams008** [hoppscotch/hoppscotch#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I cannot log in on admin. always redirect to the home admin page again after login Authorization callback.

I try using EMAIL and GitHub auth, but some redirects to home admin again.

![kevet issue](https://github.com/hoppscotch/hoppscotch/assets/26858550/6b1f48bf-49d8-42ab-b1aa-ffb435971f0f)

### Steps to reproduce

1. goto admin page 'example.com:3100'
2. i login using email or github
3. redirect to home again as in the picture.

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
@jams008 Is your instance secured over `HTTPS`? We use `HTTP` secure cookies for auth so if your instance is over `HTTP` the cookies wont get set in your browser.

**Comment by jams008** [comment]
oh yes, i use http.

**Comment by balub** [comment]
@jams008 As mentioned in our docs, you have to use `HTTPS` for it to work.

**Comment by jams008** [comment]
@balub sorry my bad, thanks for help me. Can you refer me to the doc? 
I can try again to night.

**Comment by owlpro** [comment]
i have the same issue, always redirected to env.REDIRECT_URL after login

**Comment by jams008** [comment]
@owlpro Have you tried using tls / https ?
I check in recommendations this doc. But i don't try agin today.
https://docs.hoppscotch.io/documentation/self-host/community-edition/prerequisites#oauth

**Comment by raphaelSm** [comment]
Hi @All I expected the same problem, with redirecting from all auth services and magic link to home page  via **http** . Verify method response return error in this case. Switching to **https** solve problem to me, doc mentions this at the very end in the link that you provided @jams008 . I wouldn't have find solution without this topic, so thanks for guidance.

![obraz](https://github.com/hoppscotch/hoppscotch/assets/45426478/d192eefa-12a2-4595-a601-f62d531d7f03)


``` js
// Error from auth response
{
    "errors": [
        {
            "message": "auth/cookies_not_found",
            "extensions": {
                "code": "FORBIDDEN",
                "response": {
                    "statusCode": 403,
                    "message": "auth/cookies_not_found",
                    "error": "Forbidden"
                }
            }
        }
    ],
}
```
