### ISSUE TITLE
[feature]: Add env variable unset

### ISSUE THREAD

**Issue by rabbittsoup** [hoppscotch/hoppscotch#3398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I’d like to be able to unset environment variables to help cleanup unused variables in scripts.

pw.env.set(var, null)
or
pw.env.unset(var)

or similar

### Why should this be worked on?

In some tests, I create a lot of env variables, and these can make the environment variables difficult to maintain manually.  An unset capability allows the script to clean up after itself.

**Comment by liyasthomas** [comment]
If you want to set an empty string as the environment value, you could use the following script;
```
pw.env.set("my_env_variabble","")
```
Let me know if this is what you're asking.

**Comment by rabbittsoup** [comment]
No.  I want to delete the variable from the environment entirely.

**Comment by rabbittsoup** [comment]
Is there anything new I can add to help this request move forward?

**Comment by ajmalmohad** [comment]
> Is there anything new I can add to help this request move forward?

I have raised a PR including this feature in the js-sandbox, which'll work in pre-request and test scripts

**Comment by rabbittsoup** [comment]
Thank you

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.

**Comment by rabbittsoup** [comment]
Verified in the wild.  Works great!  Thank you!
