### ISSUE TITLE
[feature]: Setting the default opening tab in the API

### ISSUE THREAD

**Issue by ashin-kk** [hoppscotch/hoppscotch#3403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Current behaviour: Whenever we open/ create an API, the default tab shows is Parameter. (As per internal policy, we do not use **Parameters** in the API. Instead, only the **Body** is used.)

Expected behaviour: The user can set the default tab to open when creating or opening an API.

### Why should this be worked on?

This makes it very easy for the developer to make necessary changes or check the request parameters without having to switch between tabs.

**Comment by liyasthomas** [comment]
We're working on a feature that will persist the last active Tab. So, if you switch to the Body tab, we'll persist it and the next time you open the API playground, the Body tab will be active.

**Comment by ashin-kk** [comment]
Glad to know you are already working on it. Just to know, when can we expect this feature?

**Comment by liyasthomas** [comment]
We've recently implemented a feature that will persist the last active tab on the Request panel. Hence closing this ticket.

**Comment by ashin-kk** [comment]
Hi,
I have checked it thoroughly, but unfortunately, it doesn't seem to be working as expected.
