### ISSUE TITLE
[bug]: Cannot set custom method

### ISSUE THREAD

**Issue by KAIYOHUGO** [hoppscotch/hoppscotch#3406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to set custom request method , `[Vue warn]: Error in 1: "TypeError: e.method is undefined"` pop up in console. And I can't set custom request method.

### Steps to reproduce

1. Set custom method
   ![image](https://github.com/hoppscotch/hoppscotch/assets/41114603/7cf0039d-30a7-4760-9823-c9f478e020e7)
2. Click Send
3. Custom method disappear & not working
  ![image](https://github.com/hoppscotch/hoppscotch/assets/41114603/151712d0-4696-4e34-a329-1fcaa3d84cbe)
  ![image](https://github.com/hoppscotch/hoppscotch/assets/41114603/4ef664f2-4cc1-4a3a-87a4-779067aa7b3d)

### Environment

Production

### Version

Local

**Comment by Substancia** [comment]
If this is open, I would like to take this up.

**Comment by dreygur** [comment]
HI @KAIYOHUGO fixed the issue and made a PR.
