### ISSUE TITLE
[feature]: Group request by tag when importing OpenAPI

### ISSUE THREAD

**Issue by Igorgro** [hoppscotch/hoppscotch#3411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Requests in OpenAPI can be grouped  using tags, for example:
![image](https://github.com/hoppscotch/hoppscotch/assets/22894169/1ee91f89-523d-4eba-a424-aca03fdca2dc)

But Hoppscotch imports them as a one flat structure:
![image](https://github.com/hoppscotch/hoppscotch/assets/22894169/53b415bb-ffb7-4f74-bf02-b8de0c86b493)

It will be a good idea to make a folder for each tag in OpenAPI document

### Why should this be worked on?

It can be hard to work with a big ungrouped collection which is generated form OpenAPI

**Comment by titanventura** [comment]
I'd like to pick this up. Please assign !

**Comment by pierre-borckmans** [comment]
I opened a PR for this: #3478

**Comment by aakrem** [comment]
can we please prioritise this one. looks like a pr is already done for it !
It will help importing from openai especially when we have a lot of requests.

btw @pierre-borckmans thanks for the pr!

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in a previous release candidate.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
