### ISSUE TITLE
[feature]: Make body tab default instead of params

### ISSUE THREAD

**Issue by Igorgro** [hoppscotch/hoppscotch#3424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I found that hoppscotch always switches to "parameters" tab when switching between requests and I'm findind this behaviour very inconvenient. I mostly send POST requests, so i use body tab most of the tab. Possible solutions are:
1. Make body tab globally default
2. Make a setting to reorder tabs or set the default one
3. Simply keep last selected tab in cookies (or local storage) and keep it selected when switchin between requests

### Why should this be worked on?

The software must be more adaptable to every user's workflow

**Comment by iagocarmona** [comment]
Hello, I would like to work on this, can assign me ?

**Comment by liyasthomas** [comment]
We're working on persisting the last active tab in #3367.

**Comment by liyasthomas** [comment]
Since we've added the ability to persist the last active tab on a tab group has landed on v2023.8.2 I'm closing this issue. Hope this feature will help you better navigate between request's tabs.
