### ISSUE TITLE
[feature]: Keep the currently selected tab active when switching between requests

### ISSUE THREAD

**Issue by jimmycallin** [hoppscotch/hoppscotch#3433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When moving between requests, I would like for the latest selected tab to be active in the newly selected request.

### Why should this be worked on?

I have an API that heavily utilizes request bodies, similarly to Elasticsearch's API, and it is quite annoying having to always reselect the Body tab when moving around.

**Comment by liyasthomas** [comment]
This feature has been implemented in [v2023.8.2](https://github.com/hoppscotch/hoppscotch/releases/tag/2023.8.2), hence closing the ticket.
