### ISSUE TITLE
[bug]: New request duplicates last opened

### ISSUE THREAD

**Issue by Igorgro** [hoppscotch/hoppscotch#3436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating new request, it copies data from current opened tab.

### Steps to reproduce

1. Create two requests with different bodies, let's name them A and B.
2. Open these request in two tabs
3. Create new request (C). If the selected tab is A, then the info for new request (including name) is copied from A, If the selected tab is B, then info is copied from B.

**Expected behavior**

New request is empty and is not a copy of existing one

### Environment

Production

### Version

Cloud

**Comment by owlpro** [comment]
i have the same issue in AIO self-hosted:2023.8.1

**Comment by liyasthomas** [comment]
This is an expected behavior. New request save the current active tab. To save a new empty request, open a new tab and save it to the collection.
