### ISSUE TITLE
[feature]: Add statusText next to error code instead of the default one

### ISSUE THREAD

**Issue by Batimius** [hoppscotch/hoppscotch#3458]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

When making a request, the status text it displays for your request status is the default one. For instance, a 400-status code will say "400 • Bad Request" and nothing more. Although this is good, it would be nice if instead of defaulting to the default one, it only uses the default text when no statusText is present. For instance, if I return a status text of "No cookie" along with my 400-statuts response, it would be much nicer for it to display "400 • No cookie" instead of "400 • Bad response." Right now, I am using different status text for each "rejection," so the generic message is very unhelpful.

### Why should this be worked on?

It helps with debugging and overall a better understanding of every request. If it is possible for this to be implemented, then it should be. There isn't really much of a reason on why it shouldn't.

**Comment by mazkaaa** [comment]
Hi, I'd like to work on this issue! could you please provide the screenshot of the requested feature? @Batimius

**Comment by Batimius** [comment]
> Hi, I'd like to work on this issue! could you please provide the screenshot of the requested feature? @Batimius

@mazkaaa Sure thing! Below is an example of what I'm talking about.

![image](https://github.com/hoppscotch/hoppscotch/assets/56501846/f7c9c10b-3368-4942-8475-47aadfd4a099)
(Test request using Thunder Client in VS Code)

![image](https://github.com/hoppscotch/hoppscotch/assets/56501846/f1e44c4c-84c3-45d5-89da-69aee3e92290)
(Same request using Hoppscotch)

As you can see, in Thunder Client, it gives me the response status plus the response text, meanwhile in Hoppscotch, it only gives me the response status and a generic response.

If this was to be implemented, the Hoppscotch response could look something like this:

![image](https://github.com/hoppscotch/hoppscotch/assets/56501846/5d2374ae-84f8-4651-bf21-7463ff3dc5b6)

I just think that it would make debugging x100 times easier if the response status was also attached to the response code, since many applications (including mine) rely on status messages for a better description of the problem.

**Comment by liyasthomas** [comment]
Assigning this to you @mazkaaa.

**Comment by mazkaaa** [comment]
> Assigning this to you @mazkaaa.

Thank you!

**Comment by mazkaaa** [comment]
> > Hi, I'd like to work on this issue! could you please provide the screenshot of the requested feature? @Batimius
> 
> @mazkaaa Sure thing! Below is an example of what I'm talking about.
> 
> ![image](https://user-images.githubusercontent.com/56501846/276728525-f7c9c10b-3368-4942-8475-47aadfd4a099.png) (Test request using Thunder Client in VS Code)
> 
> ![image](https://user-images.githubusercontent.com/56501846/276728608-f1e44c4c-84c3-45d5-89da-69aee3e92290.png) (Same request using Hoppscotch)
> 
> As you can see, in Thunder Client, it gives me the response status plus the response text, meanwhile in Hoppscotch, it only gives me the response status and a generic response.
> 
> If this was to be implemented, the Hoppscotch response could look something like this:
> 
> ![image](https://user-images.githubusercontent.com/56501846/276729133-5d2374ae-84f8-4651-bf21-7463ff3dc5b6.png)
> 
> I just think that it would make debugging x100 times easier if the response status was also attached to the response code, since many applications (including mine) rely on status messages for a better description of the problem.

Thank you! working on it🚀

**Comment by mazkaaa** [comment]
@liyasthomas is this allowed? https://github.com/hoppscotch/hoppscotch/pull/3466 i mean I working on it first... and I'm asking to this issue to be assigned...

**Comment by mazkaaa** [comment]
![image](https://github.com/hoppscotch/hoppscotch/assets/5271698/de683749-1e23-4df7-9ee1-047f8ea60652)

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Feel free to reach out if you encounter any further concerns.
