### ISSUE TITLE
[bug]: Parameters are truncated when requesting an import as cURL command

### ISSUE THREAD

**Issue by shipko** [hoppscotch/hoppscotch#3461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I prepare POST request with application/x-www-form-urlencoded and with parameter name "test", value  `{"firstName":"Test","lastName":"last name Test"} ` 
When I generate cURL code I see code with clipped parameter.
 
```
curl --request POST \
  --url https://echo.hoppscotch.io/ \
  --header 'content-type: application/x-www-form-urlencoded' \
  --data 'test="{\"firstName\"'
```

<img width="1049" alt="Снимок экрана 2023-10-19 в 13 07 00" src="https://github.com/hoppscotch/hoppscotch/assets/1519243/de55dbe9-e61f-434d-9fc8-1b3098066e36">

<img width="524" alt="" src="https://github.com/hoppscotch/hoppscotch/assets/1519243/974c5248-0aa5-44e3-bba3-94f4e0dac59f">

### Steps to reproduce

1. Create new POST request
2. Input URL https://echo.hoppscotch.io
3. Define form type as application/x-www-form-urlencoded
4. Add parameter name as `test` with value `{"firstName":"Test","lastName":"last name Test"} ` 
5. Click on Show code
6. Make sure that not all parameters are filled in

### Environment

Production

### Version

Cloud

**Comment by JonasRafael16** [comment]
I would like to contribute to the project, can you sign for me?

**Comment by liyasthomas** [comment]
Assigning this to you @JonasRafael16.

**Comment by shipko** [comment]
@JonasRafael16 Hi! Any news?

**Comment by JonasRafael16** [comment]
> @JonasRafael16 Hi! Any news?

Sorry I couldn't solve the problem

**Comment by dhanesh12twice** [comment]
Ive reproduced the bug and yess it needs fix . Can i work on this ?? @shipko

**Comment by shipko** [comment]
@dhanesh12twice  of course!

**Comment by shipko** [comment]
@liyasthomas please, assigning to @dhanesh12twice this issue

**Comment by ajmalmohad** [comment]
Hey, I've came up with a solution for this, opened a PR now

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Feel free to reach out if you encounter any further concerns.
