### ISSUE TITLE
[bug]: can not download environment files

### ISSUE THREAD

**Issue by coding-umr** [hoppscotch/hoppscotch#3462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to download environments to run collection, it is taking too much time to download. After I cancel, next time it is not downaloding at all.

### Steps to reproduce

Go to environments
Click on vertical 3 dots
Click on Export as JSON

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
I couldn't reproduce this behaviour at my end, @coding-umr can you produce a screen record of the issue you're facing.

**Comment by coding-umr** [comment]
may be a temporary issue. Able to download now.
