### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by UBT-FJ** [hoppscotch/hoppscotch#3469]
Hello,

is it possible to have the login page without having the main page accessable? so anyone lands on the URL they would need to login first so they can use the system.

**Comment by thetronjohnson** [comment]
@UBT-FJ Hi, could you explain a bit more on the use case here?
The current approach enables user's to easily get started with API testing as soon as they land on hoppscotch.io

**Comment by balub** [comment]
@UBT-FJ the behaviour you are asking for is currently not available in the Hoppscotch app.

**Comment by UBT-FJ** [comment]
@balub I got that it is not available but maybe there is a way to add it!

@thetronjohnson what I would want is to have a user database and add people that I want to access the first page, then allow them to access the selfhost hoppscotch, then inside there it should be as it is.

**Comment by thetronjohnson** [comment]
@UBT-FJ , understood.

The community edition of Hoppscotch self-hosted works the same way as hoppscotch.io, with an additional admin dashboard. Therefore, there is no way to restrict access to approved users only. You might have to host your instance under a VPN to prevent unauthorized access.

However, we offer this feature in our self-hosted enterprise edition, where only users approved by the admin can access the app.

**Comment by prom00** [comment]
> @UBT-FJ , understood.
> 
> The community edition of Hoppscotch self-hosted works the same way as hoppscotch.io, with an additional admin dashboard. Therefore, there is no way to restrict access to approved users only. You might have to host your instance under a VPN to prevent unauthorized access.
> 
> However, we offer this feature in our self-hosted enterprise edition, where only users approved by the admin can access the app.

I'm kind of surprised by this, as this is offered as open source. The pricing on the enterprise is even higher than the 'original' Postman. This is being advertised as great for small teams and commercial projects. How can this be used for a small team, where everybody can access this without having to login?

![image](https://github.com/hoppscotch/hoppscotch/assets/46184489/9edd5158-dc85-4df8-ab76-a15722b3e41a)

**Comment by AurelienConte** [comment]
Totally agree with @prom00, i am testing to add this to my enterprise and after fully setuped my self hosted instance it is a red flags since everyone can access it without any login page.

The current community edition must be used under a VPN but for startups and small teams this can be difficult to maintain.

I would love to have the possibility to restrict the landing page with a login page.

**Comment by liyasthomas** [comment]
This is a feature for organizations and enterprises. Consider self-hosting our enterprise edition that has private Hoppscotch Self-Hosted instances support that only allows authorized login-only users.

Documentation: https://docs.hoppscotch.io/documentation/self-host/enterprise-edition/getting-started
Enterprise Store: https://enterprise.hoppscotch.com

**Comment by liyasthomas** [comment]
Access control protection and team login protection options are available on Enterprise plan.

In Hoppscotch self-hosted community edition, users can control allowed authentication providers, or control site access by IP address or location or via firewall traffic rules or by any external means.

Hoppscotch enterprise edition has inbuilt access control mechanisms to secure access to the self-hosted instances. Enterprise edition includes more features like SSO authentication, audit logs, etc and the license is priced at $19/user/month.

**Comment by prom00** [comment]
So basically we are using an open source project where people are encouraged to pay for good security?

**Comment by liyasthomas** [comment]
Hoppscotch enterprise edition is built on top of the open-core community edition for those who want additional features like SAML-based Single-Sign-On, identity and access management, audit logs, dedicated support, etc.

All work product on the community edition is provided "AS IS". This includes unlimited collections, unlimited teams, and collaborators, an admin dashboard, community support, etc.

Since access control mechanisms are already available in the enterprise edition and are not planned for the community edition, I'm closing this ticket.

**Comment by bigghe** [comment]
Hello @liyasthomas 
I don't know if you are the correct person to ask about, but one thing.

I see that the issue #3447 is open asking more or less the same thing, a way to authenticate as users in the selfhosted version of Hoppscotch.
But then in a latest issue, #4232, I see a possible bug in authenticate to the selfhosted version through Microsoft.

Then it's not really clear to me, is the authentication (also a basic one, just username/password), possible or not in the selfhosted version of the app?

Thanks!

**Comment by liyasthomas** [comment]
Hi @bigghe,
As of now, Hoppscotch doesn't have a username + password authentication mechanism. Both Hoppscotch Cloud and Hoppscotch Self-Hosted Editions prefer OAuth Authentication over Basic Authentication, along with Passwordless Authentication using email links.
