### ISSUE TITLE
[bug]: Import cURL doesn't recognize paratheses and quotes

### ISSUE THREAD

**Issue by zhzy0077** [hoppscotch/hoppscotch#3485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when importing below cURL
```sh
curl localhost/Entity(\'123\')
curl localhost/Entity('123')
```

I see hoppscotch put this to URL:
```
http://localhost/Entity123
```

### Steps to reproduce

1. Go to "Import cURL"
2. Put `curl localhost/Entity('123')`
3. See URL.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Feel free to reach out if you encounter any further concerns.
