### ISSUE TITLE
[feature]: Request / Response Examples

### ISSUE THREAD

**Issue by 3zrv** [hoppscotch/hoppscotch#3496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

An exact replica of postman's request / response example.
![image](https://github.com/hoppscotch/hoppscotch/assets/73386311/61d48797-f342-401a-9aa9-8b4c5eb453a5)

### Why should this be worked on?

From a personal perspective, it feels like a really important, major feature that will elevate the product's experience to match up against something like postman, I'm personally willing to work on it.

Having examples on an API it as important as having written documentation for any API for mainly:
* They provide concrete demonstrations of API usage in real-world scenarios, aiding developers in understanding input formats, request and response structures, and overall API interaction.
* Examples serve as quick start guides, allowing us to kick-start their integration process without extensively studying documentation.
* By showcasing error handling and troubleshooting approaches, examples help troubleshooting issues.

**Comment by 3zrv** [comment]
@baek-sang exactly

**Comment by liyasthomas** [comment]
Possibly a duplicate, hence closing this in favor of #1875.
