### ISSUE TITLE
[bug]: Desktop immediately closing after start on Windows 10

### ISSUE THREAD

**Issue by Torjas** [hoppscotch/hoppscotch#3524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Trying to start the Hoppscotch.exe, either directly or via the shortcuts created during installation does not work. A blank window opens for ~1 second and then closes again. 
Task manager shows a Hoppscotch task which also exits again immediately.

What I expect is that the window stays open so that I can interact with it and use the program.

OS: Microsoft Windows 10 Enterprise
Version: 10.0.19045 Build 19045

### Steps to reproduce

1. Open Hoppscotch.exe
2. A blank window with the title `Hoppscotch` and the Hoppscotch logo opens
3. The window closes immediately

### Environment

Production

### Version

Local

**Comment by nguyenkien** [comment]
Remove unwrap make it work. (I'm no expert on rust)

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x80070057), message: "The parameter is incorrect." }', src\win\window.rs:51:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1110/092811.279:ERROR:window_impl.cc(120)] Failed to unregister class Chrome_WidgetWin_0. Error = 0
`

**Comment by RihanArfan** [comment]
Experiencing the same

```
Edition		Windows 10 Enterprise
Version		22H2
OS build	19045.3570
Experience	Windows Feature Experience Pack 1000.19052.1000.0
```

**Comment by ryanmichaelsmith** [comment]
Also seeing this issue on Windows 10 21H2.

I'm not seeing any logging or error output. I'd be happy to help test or any other way I can.

**Comment by bungcip** [comment]
Reporting the same problem. 
```
edition Windows 10 Pro
version 22H2
Os Build 19045.3693
Experience Windows Feature Experience Pack 1000.19053.1000.0
```

**Comment by eunrui** [comment]
still crash now

**Comment by LewisBango** [comment]
Just installed and also getting this problem 

Edition: Windows 10 Enterprise
Version: 22H2
OS Build: 19045.3803
Experience: Windows Feature Experience Pack 1000.19053.1000.0

**Comment by mishalalex** [comment]
I got the same issue; 
first of all when I downloaded the msi file, I couldn't install it because the windows had blocked it straight away stating an issue from unknown publisher. From the properties I had to unblock it to proceed to install. 
Then once after installing the application, it just opens a white window for like a second and then it closes automatically. I retried installing it multiple times after downloading the installer multiple times. Its all the same.

**Comment by liyasthomas** [comment]
We're testing out our desktop app across various Windows versions while it's in the alpha stage. Thanks for your patience and cooperation.

**Comment by SrinivasGogineni17** [comment]
@liyasthomas Is there an update on this issue?

**Comment by federicorosso1993** [comment]
I don't know why they even release it since it does not work anywhere for what I tried... This is not alpha, this is just as good as a fake exe.

**Comment by AlanDevise** [comment]
Same problem...

```
Edition: Windows 10 Enterprise
Version: 21H2
OS Build: 19044.1288
Experience: Windows Feature Experience Pack 120.2212.3920.0
```

But it works well on Win11 and macOS.

**Comment by arapoport** [comment]
I have them same problem with v23.12.6-1 on Windows 10.

**Comment by eduardo-amaro-maciel** [comment]
Same problem here...

**Comment by bahag-gugelm** [comment]
Same.

**Comment by ThijmenDam** [comment]
Same problem in Windows 10.

**Comment by JobsLee0** [comment]
Same problem in Windows 10 Enterprise Version 22H2.

**Comment by eduardozf** [comment]
Same problem in Windows 10.

**Comment by thetronjohnson** [comment]
Hi everyone,
I apologize for the delay in responding. We launched the alpha version of the desktop app in November 2023, with the initial goal of achieving a stable release by March 2024. Unfortunately, this timeline was delayed. We've been tracking all issues with the desktop app and are now aiming to resolve them and release a stable version by early May this year :)

**Comment by rrab-0** [comment]
Same problem but on win 11

```
Edition: Windows 11 Home Single Language
Version: 23H2
OS build: 22631.3447
Experience: Windows Feature Experience Pack 1000.22688.1000.0
```

**Comment by jobslee0** [comment]
Good job! Thanks for all. I have been able to use it with the new version!

**Comment by ShixAJ** [comment]
I'm facing the same problem using Version 24.3.3.0 of the app. 
```
Edition: Windows Server 2019 Datacenter
Version: 10.0.17763
```

**Comment by AbidKhairyAK** [comment]
i found a fix for this, so hoppscotch desktop is built using tauri, and tauri need webview2. newer version of windows come with built in webview2 but if for any reason it's installation is screwed (like trying to uninstall Edge), you can try to reinstall it.

**Comment by eduardoanjo** [comment]
Same here.

Hoppscotch v2024.10.1
Windows 11 Pro 21H2 - 22000.2538

**Comment by davimachado011** [comment]
is there a fix already? 
i've tried uninstall and install again but it doesn't work...

**Comment by davimachado011** [comment]
Guys, my work collegue found a fix for it!

> Force stop hoppscotch at windows task manager;
> So go to C:\Users\"your user"\AppData\Local and then delete de folder named "io.hoppscotch.desktop" (i think it saves cache in there);
> After that start hoppscotch again.

But there is another thing: if login your account again the problem will return, so you cannot login.

It worked for me, i'm not logged to my account on hoppscotch desktop and it's ok by now.

Hope it works for you guys.

**Comment by botondberes** [comment]
Why has this been closed? The issue still persists.

**Comment by GiselleArroyoRuiz** [comment]
I have the same issue, help
