### ISSUE TITLE
[feature]: Signed Hoppscotch Desktop App for Windows OS

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/7d73eb4f-3a0c-488a-9233-605db05e5c8d)
I'm unable to start Hoppscotch Desktop because it seems not to be signed.
Because my Windows is company managed, its not possible to overide this.

And +1 for the other issues asking for a portable version, that doesn'r require admin permisions for installing.

### Why should this be worked on?

make it work

**Comment by liyasthomas** [comment]
Thanks for testing out the Hoppscotch Desktop App alpha release candidate and reporting the issue. We've prioritized fixing this issue in the upcoming stable release candidate.

**Comment by RaHehl** [comment]
Hi @liyasthomas we're still unable to use the Desktop App

Tauri has a documentation regarding this topic https://tauri.app/v1/guides/distribution/sign-windows/

Maybe this is a quickfix?

**Comment by RaHehl** [comment]
app is signed
