### ISSUE TITLE
[feature]: Ability to convert JSON responses into programming language interface/types

### ISSUE THREAD

**Issue by InDIOS** [hoppscotch/hoppscotch#3551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Would be great to have an option to export/copy JSON responses as interface/type in the programming language of choice like ThunderClient does or this website [quicktype.io](https://quicktype.io/)

### Why should this be worked on?

Some other REST Clients implement this feature an it is very useful in some cases where you are unable to get to the response interface

**Comment by liyasthomas** [comment]
[quicktype](https://github.com/glideapps/quicktype) looks good. @AndrewBastin if we don't have this scoped to our Q4 roadmap we can assign this to community contributions right?

**Comment by AndrewBastin** [comment]
Sure we can see. You can pick this up @rajdip-b

**Comment by rajdip-b** [comment]
On it!

**Comment by rajdip-b** [comment]
Hey, can anyone help me with the component for this section? I can't seem to find it :(
![image](https://github.com/hoppscotch/hoppscotch/assets/83924254/d6f5adf2-0737-453f-8bb2-dce08127af78)

**Comment by liyasthomas** [comment]
That would be: https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-common/src/components/lenses/renderers/JSONLensRenderer.vue

**Comment by rajdip-b** [comment]
@liyasthomas @AndrewBastin Guys, does this look ok?
![image](https://github.com/hoppscotch/hoppscotch/assets/83924254/1d26662a-1464-4a95-ad95-06f013fc7e7e)

**Comment by AndrewBastin** [comment]
@rajdip-b please open a PR (draft PR if incomplete) to receive feedback on the implementation.

**Comment by rajdip-b** [comment]
Sure thing!

**Comment by rajdip-b** [comment]
@AndrewBastin I've linked a PR to the issue. Would you please review it?

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Feel free to reach out if you encounter any further concerns.
