### ISSUE TITLE
[bug]: SVG is not rendered correctly

### ISSUE THREAD

**Issue by kidonng** [hoppscotch/hoppscotch#3565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/hoppscotch/hoppscotch/assets/44045911/01184086-028f-4761-bd7b-5f6ef9c77cf8)

[ImageLens is enabled for SVG](https://github.com/hoppscotch/hoppscotch/blob/23afc201a12e221c01f79d731513fcfeff928fdd/packages/hoppscotch-common/src/helpers/lenses/imageLens.ts#L6-L9) but [the actual renderer](https://github.com/hoppscotch/hoppscotch/blob/23afc201a12e221c01f79d731513fcfeff928fdd/packages/hoppscotch-common/src/components/lenses/renderers/ImageLensRenderer.vue) doesn't handle it correctly (still treats it as a blob instead of rendering it directly)

### Steps to reproduce

1. Open Hoppscotch
2. Send a GET request to SVG files, e.g. https://upload.wikimedia.org/wikipedia/commons/b/bd/Test.svg
3. See broken output

### Environment

Production

### Version

Cloud

**Comment by rajdip-b** [comment]
@AndrewBastin can I give it a try?

**Comment by rajdip-b** [comment]
Hey, I went through the code and couldn't find anything that's suspicious. I feel that it's the application data of some SVG images that are impacting the dispaly.

**Comment by Xyndra** [comment]
I have the same problem with manually coded SVGs. It seems like it has something to do with loading other raw image types as bytes while loading SVG as clean Text

**Comment by shuaixr** [comment]
https://github.com/hoppscotch/hoppscotch/blob/e9e1366cc8a0f6d3116cb4ab5a44b964d1d36128/packages/hoppscotch-common/src/components/lenses/renderers/ImageLensRenderer.vue#L89-L103

It looks like passing the type parameter when creating the blob can fix this bug. @AndrewBastin , I would like to work on this
