### ISSUE TITLE
[bug]: Property 'teamCollection' does not exist on type 'Omit<PrismaClient<PrismaClientOptions, never, RejectOnNotFound | RejectPerOperation, $Extensions.DefaultArgs>, runtime.ITXClientDenyList>'

### ISSUE THREAD

**Issue by cherking** [hoppscotch/hoppscotch#3579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/hoppscotch/hoppscotch/assets/11309371/f1a16e9f-b398-4438-beb0-bf3333561fd7)

### Steps to reproduce

1.clone
2.cp .env.exmple .env
3.pnpm install

### Environment

Production

### Version

Cloud

**Comment by FeiPengDev** [comment]
@cherking Excuse me, can you please tell me how to solve this? I also encountered this problem.

**Comment by cherking** [comment]
> @cherking Excuse me, can you please tell me how to solve this? I also encountered this problem.
我没有解决哦 bro
