### ISSUE TITLE
Team owner email address validation need improve

### ISSUE THREAD

**Issue by WestFarmer** [hoppscotch/hoppscotch#3581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

for example :
```
fanguogang@itps.xxx.com
```

this is a valid email address, but when input it as owner email when creating team in admin dashboard.

client side validation  shows 'please enter a valid owner email'

maybe this is caused by third level domain name in email address ?

this is blocking administrator  to create team.

### Steps to reproduce

1. go to admin dashboard
2. create a new team with owner email provided above.

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
`fanguogang@itps.xxx.com` doesn't seem like an invalid email ID pattern.

@balub is this because the user email is not found in the users' table — can you check?

**Comment by balub** [comment]
There is a chance the regex we use may consider this as an invalid email. It's just a theory that we will test it out then we'll know for sure.

**Comment by liyasthomas** [comment]
If that's the case, if it's a front-end validation error, loop in @JoelJacobStephen to fix.

**Comment by WestFarmer** [comment]
> If that's the case, if it's a front-end validation error, loop in @JoelJacobStephen to fix.

it's front-end, no request made to backends yet. @liyasthomas

**Comment by WestFarmer** [comment]
from the [source code](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-sh-admin/src/components/teams/Add.vue). 

only checking for non-empty value for owner email:
```
if (ownerEmail.value.trim() === '') {
    toast.error(`${t('teams.valid_owner_email')}`);
    return;
  }
```

I closed  the modal and retried, it works now.

here is the reproduce steps:

1. input a valid email as owner email
2. input a invalid team name( eg: a name with length under 6)
3. submit, seeing error  team name too short
4. input valid team name 
5. submit again
6. seeing 'please enter valid owner email' 

@liyasthomas

**Comment by WestFarmer** [comment]
> > 5. submit again
> 
> @WestFarmer when you submit again, is the email input field empty or not? Does it actually have a valid email ID at that time?

of course, the email remains there.

**Comment by JoelJacobStephen** [comment]
@WestFarmer I have raised a PR to fix the issue and have validated the fix from my end. Can you let me know if this PR properly fixes your issue?

**Comment by WestFarmer** [comment]
> @WestFarmer I have raised a PR to fix the issue and have validated the fix from my end. Can you let me know if this PR properly fixes your issue?

How can I help to verify ? Do I need to checkout PR and build locally ?

**Comment by balub** [comment]
@WestFarmer Yes, you can checkout to the branch the PR is raised against build run it locally and try.

**Comment by JoelJacobStephen** [comment]
@WestFarmer I will be closing this issue in a few days as this has been fixed. Please let us know if you are still facing the same issue in the latest build.
