### ISSUE TITLE
[feature]: Adding documentation

### ISSUE THREAD

**Issue by baek-sang** [hoppscotch/hoppscotch#3583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add documentation in markdown to collection/folder/request

### Why should this be worked on?

<img width="726" alt="hopp-doc" src="https://github.com/hoppscotch/hoppscotch/assets/69100154/6df99a3e-f6bb-4cbf-a41e-a231c22256db">
<img width="726" alt="hopp-doc2" src="https://github.com/hoppscotch/hoppscotch/assets/69100154/d4515a1b-8546-4c03-a79b-810bbde72198">

**Comment by liyasthomas** [comment]
Possibly a duplicate of #2018, hence closing.
