### ISSUE TITLE
Prettier for RAW responses

### ISSUE THREAD

**Issue by spiderock98** [hoppscotch/hoppscotch#3584]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

When server response data is array of object . It cannot be format as JSON pretty version. I found in setting and docs but cannot find any config for this. Thank you for review

![image](https://github.com/hoppscotch/hoppscotch/assets/28623503/5d0527b8-d626-44a7-babb-4ce6e8f1cbc5)

### Why should this be worked on?

I think this is a basicly feature

**Comment by spiderock98** [comment]
> This might be because the response has an incorrect `Content-Type` header. Usually, JSON responses have a `Content-Type: application/json` which we check internally to prettify and format the response.
> 
> Can you confirm the response headers list has a proper `Content-Type` associated with JSON?

I have re-check and realize it just plain/text . I still hope there will parse json pretty despite of plain/text . because Postman and Insomnia still prettier plaintext data . btw Hoppscoth is super lightweight and fast ❤️

**Comment by marlonbasten** [comment]
I will add something to that which may be a bit off-topic. This probably wouldn't have happened if you could set default headers at collection level. This is the main thing keeping me away from Hoppscotch. It's unusable if you have to define the Response type and API key for every single request. Imagine changing your api key on a collection with 300 requests.

**Comment by liyasthomas** [comment]
Hi @marlonbasten, we’re working on collection level headers and authorization feature, expected to be released by December. Track its progress on #2259.

**Comment by spiderock98** [comment]
> I will add something to that which may be a bit off-topic. This probably wouldn't have happened if you could set default headers at collection level. This is the main thing keeping me away from Hoppscotch. It's unusable if you have to define the Response type and API key for every single request. Imagine changing your api key on a collection with 300 requests.

I add middleware to modify response header and it all works fine now

**Comment by jackdewhurst** [comment]
Is there any scope to add auto detect or an override feature to response formatting? Similarly to how Postman/Insomnia do it? 

I don't want to have to add middleware in order to have my HTML response formatted as JSON.

**Comment by Issac-v** [comment]
Hi @liyasthomas, I believe this issue has not been resolved. Setting request headers at the collection level does not solve the problem of response body formatting for non-JSON response headers. Could you please reopen this issue?

**Comment by lukepighetti** [comment]
a lot of json endpoints return the wrong content type, we should still try to format them, imo

**Comment by linto11** [comment]
do we have a fix for this?

**Comment by Phaired** [comment]
Is there still no workaround or fix? This is very annoying for a poorly designed API.
