### ISSUE TITLE
[feature]: Adjusting the collection panel width

### ISSUE THREAD

**Issue by baek-sang** [hoppscotch/hoppscotch#3597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I'd like to reduce the width of the collection panel a bit more, it's wasting space. 
Double-clicking on the vertical divider line should change it to the minimum width of the collection, not make it wider.

### Why should this be worked on?

<img width="478" alt="hop" src="https://github.com/hoppscotch/hoppscotch/assets/69100154/d6aa1465-ac87-4af4-bddc-505c075bdcd7">

Wasted space

**Comment by liyasthomas** [comment]
Have you tried dragging the pannel spacer maximum to the right? We do allow adjusting the panel width to an adequate minimum depending on the viewport width. Furthermore, you can completely hide the sidebar by clicking on this button in the app footer - let me know if that works.

<img width="521" alt="Screenshot 2023-11-27 at 4 06 05 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/9392a963-06cb-414c-b087-8dd03bf72533">

**Comment by liyasthomas** [comment]
The sidebar and specifically the collections panel tends to have nested collections and sub-folders which require an adequate amount of width, hence we don't have plans to further allow a sidebar width of less than 25% of the viewport.
