### ISSUE TITLE
[bug]: Unable to browse file for multipart form data

### ISSUE THREAD

**Issue by kiranmurali93** [hoppscotch/hoppscotch#3601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to upload a file for multipart/form-data, I'm not able to browse file. When i click on the browse button, the option to upload the file is not showing up.

interceptor: Browser extension v0.25
Browser: Firefox

### Steps to reproduce

- Select Body content type as multipart/form-data
- Click on the Browse file button.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Hi @kiranmurali93, I can't reproduce this behavior at my end. To better understand the issue can you try the following and let me know?

- Make sure you give the necessary file permissions for the browser to access the local drive.
- Try opening the Hoppscotch app in a new incognito window and try to reproduce the error.
- Try opening the Hoppscotch app in a different browser and see if the error persists.

If the issues still persist, I'd appreciate it if you could produce a screen recording of the entire process.
