### ISSUE TITLE
[feature]: I would like to contribute to the hoppscotch common locales [es]

### ISSUE THREAD

**Issue by AlxChuc** [hoppscotch/hoppscotch#3608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I don't think it is a feature, but I would like to contribute.
I saw that the Spanish translation is incomplete, so I would like to fix it. How can I procede?

### Why should this be worked on?

The project can be use for the spanish speakers who don't speak english.

**Comment by liyasthomas** [comment]
[Read our translation guide](https://docs.hoppscotch.io/documentation/i18n) to contribute to our i18n.
