### ISSUE TITLE
[bug]:  blocked by CORS policy if we try to send the request

### ISSUE THREAD

**Issue by Ankush-Hegde** [hoppscotch/hoppscotch#3613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![Screenshot (12)](https://github.com/hoppscotch/hoppscotch/assets/93759468/0806cb6e-ad1d-4444-b778-31752ce94622)

### Steps to reproduce

1. just made an api with the php laravel 
2. when i requested the response from the api i get this error in the browser but the request is not sent to the back end.
3. in the desktop app the request is recived to the back end but still i get no respnse.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Follow the guide to [Setup Hoppscotch to test locally deployed APIs](https://docs.hoppscotch.io/documentation/getting-started/setup#locally-served-apis) from documentation.

Alternatively, you can download our [Desktop App](https://hoppscotch.com/download) which doesn't require any additional setup to test locally deployed APIs.

Let me know if the issue persists.
