### ISSUE TITLE
[bug]: ES local incomplete

### ISSUE THREAD

**Issue by AlxChuc** [hoppscotch/hoppscotch#3617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The spanish translation is incomplete.

### Steps to reproduce

You can see it in some parts of the app.

![Captura de Pantalla 2023-12-01 a la(s) 14 24 25](https://github.com/hoppscotch/hoppscotch/assets/40218932/e682cc77-7b85-4cf9-a964-0dc800900400)

### Environment

Production

### Version

Cloud

**Comment by AlxChuc** [comment]
How can I work on this?

**Comment by liyasthomas** [comment]
Hi @AlxChuc i18n translations are community-contributed hence there might be possibilities for grammatical and typographical mistakes. I welcome you to raise a PR to fix such errors. Follow [our TRANSLATIONS guide](https://docs.hoppscotch.io/documentation/i18n) to learn how.
