### ISSUE TITLE
[feature]: Persist wrap lines settings

### ISSUE THREAD

**Issue by umardev500** [hoppscotch/hoppscotch#3641]
I need to report about wrap line is always reset to default on every request

**Comment by ajmalmohad** [comment]
There seems to be a lot of line wraps in various places.

Should we handle each of them separately or group the similar ones together ?

For eg: HTTP response and JSON Response for REST should be separate or grouped?

@liyasthomas

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in a previous release candidate.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.
