### ISSUE TITLE
[bug]: Show Code Modal Overflowing on Large Code

### ISSUE THREAD

**Issue by ajmalmohad** [hoppscotch/hoppscotch#3642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I press `Show Code` for the request and choose a language which generates large code like `Go`. The modal is overflowing and the buttons `Copy` and `Dismiss` are completely inaccessible. 

### Steps to reproduce

1. Open a request tab with some URL
2. Click on `Show Code` in the send button options
3. Choose a language like `Go`
4. Observe the overflow

[Screencast from 12-12-23 12:13:02 PM IST.webm](https://github.com/hoppscotch/hoppscotch/assets/55492635/d61c0d8f-25f2-4ecf-bd4b-12acfd2f2746)

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Feel free to reach out if you encounter any further concerns.
