### ISSUE TITLE
[bug]: Choose Language Drop Down in Generate Code Overlap

### ISSUE THREAD

**Issue by ajmalmohad** [hoppscotch/hoppscotch#3648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The `Choose language` drop down search field in `Generate Code Modal` overlaps with the options when scrolled up

### Steps to reproduce

1. Go to a REST Request
2. From options on the `Send` button select `Show Code`
3. Select the `Choose language` drop down
4. Scroll down and observe overlap

![Screenshot from 2023-12-13 10-56-00](https://github.com/hoppscotch/hoppscotch/assets/55492635/2961a31b-7107-4d5d-9b9d-634039856a6c)

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This is an expected behavior since that search field is a sticky element. The search bar will stick to the top while scrolling for easy access.
