### ISSUE TITLE
[bug]: Unclear error for non-empty body in GET requests [Browser extension interceptor only]

### ISSUE THREAD

**Issue by flleeppyy** [hoppscotch/hoppscotch#3682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Making a request to an endpoint with GET using the browser extension interceptor, with a body (aka, something other than "None"), will report an uninformative error saying "Could not make request. Unable to each the API endpoint. Check your network connection or try a different interceptor and try again".

What's not being told here to the user is that you cannot make a GET request with a body. By default when creating a new request, the method is GET and the body does not default to "None".

This is the error that's shown in the devtools console when you make a GET request with a body. It is not shown to the user in any shape or form.
```
TypeError: Window.fetch: HEAD or GET Request cannot have a body. [index-0a547439.js:4314:244] (https://hoppscotch.io/assets/index-0a547439.js)
    o moz-extension://0e209b0f-3b49-44c9-87db-63f6cfc01682/index.js:2
    N moz-extension://0e209b0f-3b49-44c9-87db-63f6cfc01682/index.js:2
    mgn https://hoppscotch.io/assets/index-0a547439.js:4314
    runRequestOnExtension https://hoppscotch.io/assets/index-0a547439.js:4310
```

When setting the body to "none" and making the request, it goes through successfully. 

--

Unsuccessful request
![image](https://github.com/hoppscotch/hoppscotch/assets/18307183/078fc879-07de-4284-abc2-0181d8e2db2b)

Successful request
![image](https://github.com/hoppscotch/hoppscotch/assets/18307183/3472fa42-8094-40ca-85cf-f1b984f8d24f)

To be clear, this issue happens when you use the browser extension interceptor. It does not happen when you have no interceptor selected.

### Steps to reproduce

1. Create a new request
2. Select the browser extension interceptor
3. Make sure the method is set to GET and body is set to something other than "None"
4. Make the request, and check the devtools console for the error.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
This is a known issue in v0.28 (#241). We've patched this in v0.29 which should be out in a couple of hours.

https://github.com/hoppscotch/hoppscotch-extension/issues/241#issuecomment-1863815379
