### ISSUE TITLE
[bug]: hoppscotch-backend always restarting with migration not found error

### ISSUE THREAD

**Issue by wendellli99** [hoppscotch/hoppscotch#3696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm installing the 2023.12.0 release. After running `docker-compose up`, I the hoppscotch-backend container immediately starts restarting with the below error.

```
Backend Server | [Nest] 37  - 12/24/2023, 6:04:19 AM     LOG [RouterExplorer] Mapped {/auth/verify/admin, GET} (version: 1) route +1ms
Backend Server | Initialize PubSub
Backend Server | /usr/src/app/packages/hoppscotch-backend/dist/utils.js:14
Backend Server |     throw new Error(errMessage);
Backend Server |           ^
Backend Server | 
Backend Server | Error: Database migration not found. Please check the documentation for assistance: https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build#running-migrations
Backend Server |     at throwErr (/usr/src/app/packages/hoppscotch-backend/dist/utils.js:14:11)
Backend Server |     at InfraConfigService.initializeInfraConfigTable (/usr/src/app/packages/hoppscotch-backend/dist/infra-config/infra-config.service.js:89:38)
Backend Server |     at async InfraConfigService.onModuleInit (/usr/src/app/packages/hoppscotch-backend/dist/infra-config/infra-config.service.js:28:9)
Backend Server |     at async Promise.all (index 0)
Backend Server |     at async callModuleInitHook (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)
Backend Server |     at async NestApplication.callInitHook (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/nest-application-context.js:223:13)
Backend Server |     at async NestApplication.init (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/nest-application.js:100:9)
Backend Server |     at async NestApplication.listen (/usr/src/app/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.6.0/node_modules/@nestjs/core/nest-application.js:169:33)
Backend Server |     at async bootstrap (/usr/src/app/packages/hoppscotch-backend/dist/main.js:42:5)
Backend Server | 
Backend Server | Node.js v18.16.0
Backend Server | ELIFECYCLE  Command failed with exit code 1.
Exiting process because Backend Server exited with code 1
```
Becuase the backend container is always restarting, it's nearly impossible to run migration inside it. 
But I got lucky once and ran `prisma migrate deploy` just before it crashes and saw this error.
```
root@hoppscotch:~/hoppscotch# docker exec -it hoppscotch-backend /bin/sh
/usr/src/app/packages/hoppscotch-backenpnpx prisma migrate deploy
Packages: +6
++++++
Progress: resolved 6, reused 6, downloaded 0, added 6, done
Environment variables loaded from .env
Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
```

### Steps to reproduce

1. pnpm install
2. docker compose build
3. docker compose up -d

### Environment

Release

### Version

Self-hosted

**Comment by Tolk2402** [comment]
Same problem.
I was lucky to be able to run only an AIO container in which I was able to run this command.
The hoppscotch-backend is constantly restarting and is too fast for me to migrate

**Comment by pushpulldecoder** [comment]
Temporarily you can start container without auto restarting and let it fail once. Start again with `podman run -it --entrypoint sh --env-file .env docker.io/hoppscotch/hoppscotch:latest` and let it initialize/migrate database.

**Comment by wendellli99** [comment]
> Temporarily you can start container without auto restarting and let it fail once. Start again with `podman run -it --entrypoint sh --env-file .env docker.io/hoppscotch/hoppscotch:latest` and let it initialize/migrate database.

@pushpulldecoder  Is this command for AIO only? Do I just run it? I'm using the individual container approach.

**Comment by balub** [comment]
@wendellli99 You can use the following command to `exec` into the containers to execute the migration.
For AIO.
`docker run -it --entrypoint sh --env-file .env hoppscotch/hoppscotch:latest`

For Individual containers, you only need to do this in the backend container.
`docker run -it --entrypoint sh --env-file .env hoppscotch/hoppscotch-backend:latest`

**Comment by hxgqh** [comment]
Not fixed issue. Cause AIO/backend will stop on error "Error: Database migration not found", and command "pnpx prisma migrate deploy" will not be executed.

**Comment by hxgqh** [comment]
```bash
docker run -it -p 3000:3000 -p 3100:3100 -p 3170:3170 --entrypoint sh --name hoppscotch --env-file .env --restart unless-stopped hoppscotch/hoppscotch
```

**Comment by Tanmoy037** [comment]
Simple solution to this problem -
```docker run -it --entrypoint sh --env-file .env hoppscotch/hoppscotch-backend ```
then 
```pnpx prisma migrate deploy```
and exit it using ```exit```
then 
```docker run -p 3170:3170 --env-file .env --restart unless-stopped hoppscotch/hoppscotch-backend```

**Comment by Quadrubo** [comment]
How is this image closed? When I run `docker compose up` the container should start without any issues. Why does one have to apply the migration themselves? Anyone got a working docker-compose file as an example?

**Comment by lifang218c** [comment]
the same problem
i do not handle it.....  the container always restart with the error: Error: Database migration not found

**Comment by pilinux** [comment]
This is how I did it.

`docker pull hoppscotch/hoppscotch-backend:2024.6.0`

`docker run -it --entrypoint sh --env-file .env hoppscotch/hoppscotch-backend:2024.6.0`

`pnpx prisma migrate deploy`

`exit`

Example `docker-compose.yml` file:

```
name: hoppscotch
services:
  hoppscotch-backend:
    image: hoppscotch/hoppscotch-backend:2024.6.0
    container_name: hoppscotch-backend
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .env
    ports:
      - '127.0.0.1:3170:3170'
```

`docker compose up -d`

`docker compose log -f`

**Comment by musuyaba** [comment]
I am using the following command to create a temporary hoppscotch-be container, run the database migrations, and then delete the hoppscotch-be container afterward:

```bash
docker run --rm --name hoppscotch-be -it --env-file .env --entrypoint sh hoppscotch/hoppscotch-backend -c "pnpx prisma migrate deploy"
````

**Comment by chaoqunxie** [comment]
> 我使用以下命令创建一个临时 hoppscotch-be 容器，运行数据库迁移，然后删除 hoppscotch-be 容器：
> 
> ```shell
> docker run --rm --name hoppscotch-be -it --env-file .env --entrypoint sh hoppscotch/hoppscotch-backend -c "pnpx prisma migrate deploy"
> ```

I am in an intranet environment with no internet access. Can I obtain the table structure and data on a machine that has internet access, and then transfer this information into my database to bypass this step?

**Comment by balub** [comment]
@chaoqunxie Yes you can, just use `pnpm` instead of `pnpx` to run the migrations.

```
docker run --rm --name hoppscotch-be -it --env-file .env --entrypoint sh hoppscotch/hoppscotch-backend -c "pnpm prisma migrate deploy"
```
