### ISSUE TITLE
[bug]: Auth cookies are not removal from selfhost-web after expired it

### ISSUE THREAD

**Issue by shipko** [hoppscotch/hoppscotch#3701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I log into my account, I wait for the expiration of the refresh_token JWT (specified in the REFRESH_TOKEN_VALIDITY parameter). After that, I log into the selfhost-web component and see that my account is still active, but any GraphQL method  related with account is not working.

I expect that after expiration refresh token I will be logout and my cookie will be removed.

### Steps to reproduce

1. Log in into my account through selfhost-web component
2. Waiting for the expiration of the cookie parameter JWT refresh_token 
3. Open page of the selfhost-web component
4. See that account is still be active.

### Environment

Production

### Version

Self-hosted

**Comment by shipko** [comment]
@liyasthomas I want to fix it.

**Comment by liyasthomas** [comment]
Feel free to give it a try, and open a PR - I'll assign @balub to review it.
