### ISSUE TITLE
[feature]: Add Doc section for every API

### ISSUE THREAD

**Issue by giosueDelgado** [hoppscotch/hoppscotch#3747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I think a new section that can be very useful is that in the hoppscotch request configured in the various tab we add a "Doc" section

Where inside it there is a description (I suggest tu use markdown format)

I see this very useful for example inside insomnia api:

![image](https://github.com/hoppscotch/hoppscotch/assets/11545723/918158ab-59da-4729-aa34-e9e2173f934d)

### Why should this be worked on?

This is usefult for many reason:

- To explain to a not so technical person what the API do
- To write some notes shared in the team that work on a single api
- To write a mock for example before the api is available in the backend so the FE team can mock the request.

**Comment by liyasthomas** [comment]
We've planned to implement the API documentation feature this quarter. Stay tuned for updates on #2018. Since this ticket is possibly a duplicate, I'm closing the ticket.
