### ISSUE TITLE
[bug]: i have facing issue with the google auth the client id passing in header is ******* but in my continaer have all envs, i check it with docker inspect command

### ISSUE THREAD

**Issue by alchemist123** [hoppscotch/hoppscotch#3756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

google client secret pass in header as ***** to from my env

### Steps to reproduce

i treid with AIO with env file

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Hi @alchemist123 can you share your `.env` file, you can redact any sensitive data in it.

**Comment by JoelJacobStephen** [comment]
@alchemist123 Are you still facing this issue in the latest builds? If so, please provide additional information regarding the same so that we can debug the problem. If not, we will be closing the issue in a few days.

**Comment by pmaoui** [comment]
Clear the table `InfraConfig` helped me here.
