### ISSUE TITLE
[bug]: I use email , but I am unable to log in

### ISSUE THREAD

**Issue by pigzhuzhu55** [hoppscotch/hoppscotch#3757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/hoppscotch/hoppscotch/assets/7320822/dd93e63d-f7e5-404d-bff7-f6957c89a14c)
![image](https://github.com/hoppscotch/hoppscotch/assets/7320822/316b9d41-6ae6-4a52-949d-b18555269006)
![image](https://github.com/hoppscotch/hoppscotch/assets/7320822/5aef7a3f-7046-4c86-8acd-9153ffbcb6e5)
![企业微信截图_17054919271406](https://github.com/hoppscotch/hoppscotch/assets/7320822/b75435b8-6642-4b96-9e4a-cdea8658f63c)
![image](https://github.com/hoppscotch/hoppscotch/assets/7320822/2fef9083-fd86-4304-be4b-8bd6d30b1116)

### Steps to reproduce

When I logged in using email, I received a link in my webpage email. By clicking on the link, I was redirected to the page and did not successfully log in.
But I can see 2 account records in the database.

### Environment

Production

### Version

Self-hosted

**Comment by TungTePao** [comment]
I may have had the same issue as you.  i tracked with burp proxy,and found that the cookie of response from magic link was not saved. after Manual copying the two cookie value : access_token,refresh_token, hoppscotch show i am Logged in。

**Comment by balub** [comment]
@pigzhuzhu55 Hoppscotch uses `HTTPS` secure cookies to authenticate itself with the backend because you are running Hoppscotch on just an `HTTP` network even if you successfully log in the cookies ultimately won't be saved by the browser

@TungTePao I believe this is the same reason for your end too.

**Comment by TungTePao** [comment]
> @pigzhuzhu55 Hoppscotch uses `HTTPS` secure cookies to authenticate itself with the backend because you are running Hoppscotch on just an `HTTP` network even if you successfully log in the cookies ultimately won't be saved by the browser
> 
> @TungTePao I believe this is the same reason for your end too.

3ks！you are right. i solved with configured nginx as an https reverse proxy.
The latest docker image of backend does not expose 443 port, it's hard to think of does not support http.

**Comment by ccx19930930** [comment]
i have using nginx as an https proxy, it can login, but it cannot send http request anymore.is it need using proxy when send request?

**Comment by balub** [comment]
Closing this issue has it has been resolved.
