### ISSUE TITLE
[bug]: How do we increase font size in desktop app?

### ISSUE THREAD

**Issue by aniketraj1947** [hoppscotch/hoppscotch#3771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using graphQL environment in Desktop app for mac and there's apparently no way to increase font size !?

### Steps to reproduce

NA

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Thanks for testing out our alpha release candidates of the Hoppscotch desktop app.

This is a known issue which we're currently working on. Expect this to be solved in the stable release.

Closing this issue in favour of #3545.
