### ISSUE TITLE
I cannot log in as User and Admin on my own server. [bug]: 

### ISSUE THREAD

**Issue by eminelvinli** [hoppscotch/hoppscotch#3772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

You can test this test server as you wish.
User Login: http://65.109.111.15:3000/
Admin Login: http://65.109.111.15:3100/
Mail: http://65.109.111.15:1080/

I tried for 2 weeks, but I could not run this code on my own server.

Please see the video.

https://github.com/hoppscotch/hoppscotch/assets/12297976/deff361d-ad93-449a-820e-ef35e91d5bd3

### Steps to reproduce

I set up everything correctly, but for some reason I can't log in. When I go in and try to do it, it stays as is. Please help me, Thank you.

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
@eminelvinli Hoppscotch uses HTTPS secure cookies to authenticate itself with the backend because you are running Hoppscotch on just an HTTP network even if you successfully log in the cookies ultimately won't be saved by the browser. Might I suggest you try getting some `TLS` certificates and trying again.

**Comment by JoelJacobStephen** [comment]
> @eminelvinli Hoppscotch uses HTTPS secure cookies to authenticate itself with the backend because you are running Hoppscotch on just an HTTP network even if you successfully log in the cookies ultimately won't be saved by the browser. Might I suggest you try getting some `TLS` certificates and trying again.

@eminelvinli I hope the suggestion has helped you. I will be closing this issue in a few days. If you are still facing an issue, please let us know.
