### ISSUE TITLE
[bug]: Tab-key not working in body or header fields

### ISSUE THREAD

**Issue by Chrissi2812** [hoppscotch/hoppscotch#3789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently the Tab-key does nothing inside the body or header editor.
![hoppscotch_tab_bug](https://github.com/hoppscotch/hoppscotch/assets/6141652/45385229-ebaf-493e-b95c-cb605c6e5f0b)

But if I remove the keydown event listeners from the `div.cm-content` of the field it works (but that comes with other issues like enter key now generating new lines in the field)
![hoppscotch_tab_bug_intended](https://github.com/hoppscotch/hoppscotch/assets/6141652/e3f8fd0b-a924-4d57-8b77-ae73dc0de922)

### Steps to reproduce

1. Go to any request
2. try to edit the body (in form view) or the header
3. Press Tab inside form field

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Hi, @Chrissi2812 thanks for noticing the UX issue. This was a known issue and we've patched this in #3754 - expect the fix to be rolled out in the next release candidate scheduled for this week. Thanks for your patience.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Feel free to reach out if you encounter any further concerns.
