### ISSUE TITLE
[feature]: search or filter in Admin Dashboard

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have a larger, self-hosted instance and when I search for a user (or Team) in the non-alphabetical list, I have to click "Show more" multiple times, which results in me being redirected back up.

A better user/admin experience would be to search the list by name or email address.

### Why should this be worked on?

Makes Hoppscotch even better and administration less painful :)

**Comment by thetronjohnson** [comment]
Thanks for letting us know. We're currently in the process of solving this! 

We're working on implementing the ability to search and filter users, as well as enabling admins to select and perform bulk actions on the selected users.

**Comment by ighoshsubho** [comment]
Hi can I work on this issue?

**Comment by liyasthomas** [comment]
Hi @ighoshsubho, thanks for showing interest in contributing to Hoppscotch.

This issue is currently being tracked internally by our core developers hence you can pick another open issue ticket for contribution.

**Comment by ighoshsubho** [comment]
Sure, no problem.

**Comment by RaHehl** [comment]
Search was added
