### ISSUE TITLE
[bug]: Hoppscotch is not opening a desktop app

### ISSUE THREAD

**Issue by tatyana-b-ma** [hoppscotch/hoppscotch#3800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I press open in Hoppscotch desktop app button in Google Chrome - it is closing my tab and nothing opening. 
I installed everything - extension and app, but can't find it. 
As well it is not working for my another teammate. 
Chrome version Version 121.0.6167.85 (Official Build) (x86_64)
Console in browser (F12) is disappearing with a tab as well when I wish to provide a screenshot. 

### Steps to reproduce

1. Go to https://hop.infra-moonactive.net/
2. Click Open in app
3. Tab is closed, nothing happens

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
The deployment `https://hop.infra-moonactive.net` is not associated with Hoppscotch hence we can't assist with this issue ticket.

We’re happy to occasionally help with the basics, but we can’t troubleshoot complex custom installations. Let me know if you've any issues with our [official deployment](https://hoppscotch.io).

[Hoppscotch Cloud](https://hoppscotch.io) &nbsp; | &nbsp; [Documentation](https://docs.hoppscotch.io)

**Comment by tatyana-b-ma** [comment]
Many thanks ! Could you please delete this tread and better to delete my massage ? @liyasthomas
