### ISSUE TITLE
[bug]: It is impossible to click “Edit” in the variable popup

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I hover over a variable in the URL, a popup appears with an edit button, but as soon as I move the mouse pointer from the URL towards the popup, it disappears before I can click on anything.

### Steps to reproduce

1. Hover a variable
![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/60d6d29f-19cf-4a9a-975b-bc900d8c7cef)

2. try to click it

### Environment

Production
Chrome,Safari,Edge

### Version

Self-hosted

**Comment by ankitzm** [comment]
Can I work on this issue.

**Comment by RaHehl** [comment]
This is fixed with 2013.12.4
