### ISSUE TITLE
[bug] Post-Login Localhost Connection Issue on Desktop App for Mac Silicon Chip

### ISSUE THREAD

**Issue by juno1020** [hoppscotch/hoppscotch#3811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, thank you for providing such a great service.
I am currently using the desktop app, and I've noticed that after logging in, methods that require a connection to localhost are not working. Are you aware of this issue?

### Steps to reproduce

1. App Install
2. Login
3. Google, Microsoft, Github
4. See connection to localhost

### Environment

Production

### Version

Cloud

**Comment by ash-eng-spin** [comment]
I am on v2023.12.4 and also not able to connect to local host from Hoppscotch desktop. "Could not send request"

**Comment by HeIIow2** [comment]
This maybe has something to do with #3721

**Comment by juno1020** [comment]
Oh, I apologize. I hadn't proceeded further, so I wasn't aware. When proceeding with Google login, localhost opens, and when the account login button is pressed in that state, the Google login popup opens, and upon completion, the app is in a logged-in state.

However, since this is a server that is in commercial use, I thought there was an issue with it opening in localhost. Since it is functioning properly, I will close this issue.
