### ISSUE TITLE
[bug]: Edit environment tooltip hiding too soon.

### ISSUE THREAD

**Issue by alenpaulvarghese** [hoppscotch/hoppscotch#3816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/hoppscotch/hoppscotch/assets/38587581/a9f69927-26e5-416f-ad7d-f23e39989852)

The popup will vanish when we move the cursor to the pen icon.

https://github.com/hoppscotch/hoppscotch/assets/38587581/c2956661-742d-4e2d-8185-46358c997532

### Steps to reproduce

1. Set a environment variable
2. In the URL Input box add the environment variable
3. Try to edit it using the tool tip

Tried on Firefox and Brave both are having the latest version.

### Environment

Production

### Version

Cloud

**Comment by alenpaulvarghese** [comment]
duplicate to #3808

**Comment by JoelJacobStephen** [comment]
@alenpaulvarghese I am not able to reproduce this issue. This is fixed in the latest builds. Can you verify once if it's working as expected on your end?

**Comment by alenpaulvarghese** [comment]
Yeah its working as intended now.
