### ISSUE TITLE
[feature]: How to stop `Would you like to restore your workspace` message from showing every time app is started..

### ISSUE THREAD

**Issue by nikitavoloboev** [hoppscotch/hoppscotch#3824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

<img width="1067" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/6391776/fbf66795-71e4-431d-afa8-52f81fd31693">

### Why should this be worked on?

It's annoying and I don't get how to make it go away. Happens every time I restart the app.

**Comment by zachtrong** [comment]
Check for showSyncToast() function in hoppscotch-common/src/pages/index.vue
