### ISSUE TITLE
[feature]: add health check checking the DB connection

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I need a health check that also checks whether the database is accessible.
The current "ping" does not check whether the DB is reachable packages/hoppscotch-backend/src/app.controller.ts

A simple SELECT 1 would be enough

I currently have the problem that Hoppscotch is no longer accessible when the DB credentials are updated automatically, and the health check does not activate the new ones by restarting the pod because the health check is still successful.

### Why should this be worked on?

see above

**Comment by balub** [comment]
@RaHehl Could you give us more clarity on the expectations of this feature.

**Comment by RaHehl** [comment]
@balub 
this does not necessarily have to be /ping, e.g. /health
would be OK too. I currently have the problem that my current health check only checks whether the "web server" is running, not whether the backend is "healthy". The health check currently does not check whether the backend can establish a connection to the database.

Perhaps a clean solution would be to integrate Terminus, as described in the NestJS example:

https://docs.nestjs.com/recipes/terminus#healthchecks-terminus

https://github.com/nestjs/terminus/blob/master/sample/012-prisma-app/src/health/health.controller.ts

**Comment by balub** [comment]
@RaHehl understood, I just wanted to make sure we were on the same page when talking about we wanted a way to check if the backend can talk to the database. We will look into Terminus looks promising.
