### ISSUE TITLE
[bug]: keyboard shortcuts not respecting different keyboard layout, e.g. dvorak 

### ISSUE THREAD

**Issue by whudwl** [hoppscotch/hoppscotch#3833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I'm using dvorak keyboard layout, so the `.` key on my keyboard is actually `v`.  
When I press CTRL and this key, hopscotch says `copied to clipboard`, while I intended to paste.  
Hopscotch obviously thinks I pressed `CTRL+.`, but that's not the case. 

### Steps to reproduce

1. Switch your keyboard layout to dvorak (I'm using windows)  
2. Open hopscotch 
3. Press CTRL and the key with `.` printed on it.  (so to an ousider, to someone who's watching you behind your shoulder, you are pressing `CTRL+.`, but what you are really pressing is `CTRL+v`)  
4. Hopscotch shows `copied to clipboard` 

### Environment

Production

### Version

Local

**Comment by MrBns** [comment]
I am also facing this problem.. 
I don't know how they have implemented this. but it should work according to key  not by keycode..

**Comment by posva** [comment]
Also facing this. It's really hard to use when copy pasting doesn't work on inputs. The bug comes from keybinding checking the `code` property instead of the `key`

**Comment by posva** [comment]
@jamesgeorge007 I started using hoppscotch recently and really liked it! I just wish there wasn't this issue so I submitted a PR: #3978

**Comment by posva** [comment]
It seems to work now! ❤️
