### ISSUE TITLE
[bug]: Error when connecting to local WebSocket endpoint

### ISSUE THREAD

**Issue by mathaimon** [hoppscotch/hoppscotch#3890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While trying to connect to a local WebSocket endpoint i get get and error saying that ws:// cannot be accessed because the page was loaded over HTTPS.

![image](https://github.com/hoppscotch/hoppscotch/assets/64730205/ef6e12c0-fc71-4dc0-9011-4ec31a7c9ce0)

### Steps to reproduce

1. Go to Realtime -> Websocket
2. Connect to local websocket server

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Can you try the `WSS` protocol instead of `WS` and see if the issue persists?

**Comment by liyasthomas** [comment]
The prefixes `wss://` indicate that the connection is secured using TLS/SSL encryption. The prefixes `ws://` indicate the connection is unsecured.

As of now, Hoppscotch requires secured API endpoints for its testing playground.

Feel free to create another issue ticket if anything goes wrong.

**Comment by mathaimon** [comment]
is there any way that  i can use hoppscotch to test local `ws` endpoints without ssl.

**Comment by mathaimon** [comment]
Also its not mentioned in the docs.
