### ISSUE TITLE
[bug]: Backend Server | Error: ENOENT: no such file or directory, open '/usr/src/app/packages/hoppscotch-backend/dist/mailer/templates/user-invitation.hbs'

### ISSUE THREAD

**Issue by mgl-pub** [hoppscotch/hoppscotch#3949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

login with email

### Steps to reproduce

click login and input email send 

### Environment

Release

### Version

Self-hosted

**Comment by edereagzi** [comment]
same issue

**Comment by liyasthomas** [comment]
cc: @balub

**Comment by m-amiri** [comment]
same issue

**Comment by taylorwhipp-gp** [comment]
I'm not entirely sure why, but even though my docker setup was setup to pull latest, it had like a 2 month old cached build it was pulling from.  I went to docker hub and just grabbed the latest and used   `image: hoppscotch/hoppscotch:2024.3.2` in my docker compose.  Once i updated and the service rebuilt, I didn't have this issue. Hope this helps...

**Comment by balub** [comment]
This issue has been fixed with the latest version of Hoppscotch, request all users to update their respective versions.
