### ISSUE TITLE
[bug]: The URL text input didn't make words wrap which made it hard to edit when URL is long.

### ISSUE THREAD

**Issue by qwsdcv** [hoppscotch/hoppscotch#3955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/hoppscotch/hoppscotch/assets/5683808/b43f8477-fd42-42e4-8226-9559357ae470)

### Steps to reproduce

Input a long URL.

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Hi @qwsdcv, single-line input components like the URL bar don't have line wrapping. You can scroll horizontally inside such text inputs to reveal the overflow text.
