### ISSUE TITLE
[bug]: POST http://localhost:3170/graphql net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by CharkiAbdelillah** [hoppscotch/hoppscotch#3958]

**Comment by liyasthomas** [comment]
cc: @balub

**Comment by balub** [comment]
Hey @CharkiAbdelillah can you share your .env file you use.

**Comment by CharkiAbdelillah** [comment]
okay @balub 
#-----------------------Backend Config------------------------------#
# Prisma Config
DATABASE_URL=postgresql://postgres:abdo2@hoppscotch-db:5432/hoppscotch # or replace with your database URL
# Auth Tokens Config
JWT_SECRET=secretcode123
TOKEN_SALT_COMPLEXITY=10
MAGIC_LINK_TOKEN_VALIDITY=3
REFRESH_TOKEN_VALIDITY=604800000
ACCESS_TOKEN_VALIDITY=86400000
SESSION_SECRET=anothersecretcode123

# Hoppscotch App Domain Config
REDIRECT_URL=http://localhost:3000
WHITELISTED_ORIGINS=http://localhost:3170,http://localhost:3000,http://localhost:3100
VITE_ALLOWED_AUTH_PROVIDERS=GOOGLE,GITHUB,MICROSOFT,EMAIL

# Google Auth Config
#GOOGLE_CLIENT_ID=*****
#GOOGLE_CLIENT_SECRET=*****
#GOOGLE_CALLBACK_URL=http://localhost:3170/v1/auth/google/callback
#GOOGLE_SCOPE=email,profile

# Github Auth Config
GITHUB_CLIENT_ID=b13a98f********
GITHUB_CLIENT_SECRET=0749e5e70dff19bfdcd6***********
GITHUB_CALLBACK_URL=http://192.168.0.107:3170/v1/auth/github/callback
GITHUB_SCOPE=user:email

# Microsoft Auth Config
#MICROSOFT_CLIENT_ID=*****
#MICROSOFT_CLIENT_SECRET=*****
#MICROSOFT_CALLBACK_URL=http://localhost:3170/v1/auth/microsoft/callback
#MICROSOFT_SCOPE=user.read
#MICROSOFT_TENANT=common

# Mailer config
MAILER_SMTP_URL=smtp://127.0.0.1:1025
MAILER_ADDRESS_FROM=abdo@test.com

# Rate Limit Config
RATE_LIMIT_TTL=60
RATE_LIMIT_MAX=100

#-----------------------Frontend Config------------------------------#

# Base URLs
VITE_BASE_URL=http://localhost:3000
VITE_SHORTCODE_BASE_URL=http://localhost:3000
VITE_ADMIN_URL=http://localhost:3100

# Backend URLs
VITE_BACKEND_GQL_URL=http://localhost:3170/graphql
VITE_BACKEND_WS_URL=wss://localhost:3170/graphql
VITE_BACKEND_API_URL=http://localhost:3170/v1

# Terms Of Service And Privacy Policy Links (Optional)
VITE_APP_TOS_LINK=https://docs.hoppscotch.io/support/terms
VITE_APP_PRIVACY_POLICY_LINK=https://docs.hoppscotch.io/support/privacy

ENABLE_SUBPATH_BASED_ACCESS=false

**Comment by CharkiAbdelillah** [comment]
@balub i shared my .env

**Comment by CharkiAbdelillah** [comment]
@balub

**Comment by JoelJacobStephen** [comment]
@CharkiAbdelillah Can you update your description with the issue you are facing in detail, along with steps to reproduce the behaviour?

**Comment by CharkiAbdelillah** [comment]
@JoelJacobStephen thanks for your reply, already solve it and this issue already exists in the issues 
since i was working on localhost you need to use your private ip address instead of localhost because i was using a VM in my host 
then you will face a problem with HTTP hopscotch work only with https so it is better to use HTTPS from the beginning

**Comment by JoelJacobStephen** [comment]
@CharkiAbdelillah Glad that your issue is resolved. You can get more context on the prerequisites for self hosting [here](https://docs.hoppscotch.io/documentation/self-host/community-edition/prerequisites#support-for-standard-https-ports). 

I will be closing this issue. If you face any further issues, feel free to raise it on our issues section.
