### ISSUE TITLE
[bug]: Latest update (2024.3.0) broke Api Key authentication passed as query params

### ISSUE THREAD

**Issue by devegied-lamabpo** [hoppscotch/hoppscotch#3963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I use Authorization of type `API key` with `Pass by` method of `Query params` Authorization Key and Value fields are discarded and not sent to the server.
Expected behavior: Authorization Key and Value field should be sent as query params
[feature]: Api Key based authentication #2000
[implemented as]: pull request #2021 feat: (authentication) Api key based authentication [#2000] 
latest version with good behavior: 2023.12.6

### Steps to reproduce

1. open https://hoppscotch.io/
2. create new GET request to the https://echo.hoppscotch.io
3. add Authorization of type `API key`
4. Enter `APIKey` in the Key field
5. Enter `123456789` in the Value field
6. Choose `Query params` for the `Pass by`
7. Click `Send`

Expected HTTP request
```
GET /?APIKey=123456789 HTTP/1.1
Host: echo.hoppscotch.io
```
Factual HTTP request in 2024.3.0 version
```
GET / HTTP/1.1
Host: echo.hoppscotch.io
```

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
cc: @amk-dev
