### ISSUE TITLE
[bug]: Unable to import to workspace

### ISSUE THREAD

**Issue by billriess** [hoppscotch/hoppscotch#3975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When attempting to import a collection to a Workspace I get an error: `Unable to import: format not recognized` but works fine in my "Personal Workspace"

### Steps to reproduce

1. Select a shared workspace.
2. Import from Insomnia, Postman, Hoppscotch
3. Error pops up "Unable to import: format not recognized"

---

I'm able to import the same file into my personal workspace just fine. I even tried exporting my personal workspace and then re-importing to my shared workspace using import from hoppscotch and I get the same error.

---

Error happens on cloud PWA and local installable version.

### Environment

Production

### Version

Cloud

**Comment by lin-mt** [comment]
Maybe it's similar to this issue https://github.com/hoppscotch/hoppscotch/issues/3975
