### ISSUE TITLE
[feature]: If the response is HTML, show the HTML preview by default or remember the preference

### ISSUE THREAD

**Issue by subins2000** [hoppscotch/hoppscotch#3981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

If the response is HTML, it makes sense to show the rendered HTML as the default rather than the raw HTML

https://subin-siby.neetorecord.com/watch/a4d6857c-d952-4c09-b48a-cd574db94fc5

While making the video above, noticed that the HTML preview is not working proper too

### Why should this be worked on?

Because HTML is by default supposed to be rendered unlike JSON or XML

**Comment by Yuniac** [comment]
Yeah... that would really be useful.

**Comment by rajatsandeepsen** [comment]
HTML preview kanan browseril oru tab open akiya pore 😂

**Comment by nivedin** [comment]
fixed by this [PR](https://github.com/hoppscotch/hoppscotch/pull/4177)
