### ISSUE TITLE
[bug]: Hoppscotch Desktop App can not work

### ISSUE THREAD

**Issue by liuyongAlive** [hoppscotch/hoppscotch#3998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Windows 11, install the app [Hoppscotch Desktop App](https://docs.hoppscotch.io/documentation/clients/desktop) 
After running, only a empty window, open the DevTools saw the error :
![image](https://github.com/hoppscotch/hoppscotch/assets/3905416/d1ea1a75-251a-4a16-b4a4-4a6b0488a8e5)

### Steps to reproduce

1. install the last version , open and get the error as above.
2. But  the  v24.3.0-1 is work.

### Environment

Production

### Version

Local

**Comment by WillianSugiyama** [comment]
Same error on MacOS m3.

![image](https://github.com/hoppscotch/hoppscotch/assets/16587394/3b2148f5-ca48-41fe-9249-a4714348b365)

**Comment by masudur-rahman-niloy** [comment]
Same on macOS intel
<img width="1121" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/77866740/9bfb5fdf-a796-4e60-bed0-3051d74c722b">

**Comment by thetronjohnson** [comment]
Hi, apologies for the inconvenience caused, we're working on a fix for this issue.

**Comment by thetronjohnson** [comment]
Hi, we've rolled out a fix, you should have received popup to update to the desktop app :)

**Comment by liyasthomas** [comment]
Can you restart the app to update it to the latest version or download the newest build from [download page](https://hoppscotch.com/download).

**Comment by TrimA74** [comment]
@thetronjohnson Stii not workng on my side after update + restart

<img width="299" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/14110741/a4288fe8-eea4-4b5c-9ffe-ae3232f65d94">

**Comment by thetronjohnson** [comment]
@TrimA74 could you tell me what OS you're on?

**Comment by TrimA74** [comment]
@thetronjohnson macOs

**Comment by TrimA74** [comment]
@thetronjohnson Same error on https://hoppscotch.io/

<img width="829" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/14110741/c0bc2a9a-3140-41d9-91fe-7b0b60852aa1">

**Comment by liyasthomas** [comment]
This error log doesn't seem to be connected to the Desktop App bug. @TrimA74 can you open a [new bug report](https://github.com/hoppscotch/hoppscotch/issues/new/choose) to better help us track and fix this error?

**Comment by liyasthomas** [comment]
@liuyongAlive feel free to re-open this ticket if the error persists on the latest build.

Restart the app to update it to the latest version or download the newest build from [download page](https://hoppscotch.com/download).
