### ISSUE TITLE
[bug]: MacOS - Hoppscotch desktop latest version does not work

### ISSUE THREAD

**Issue by kunkka19xx** [hoppscotch/hoppscotch#3999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I updated Hoppscotch latest version on my Mac (Pro 14 - M2), It does not work, I tried to restart my PC but it still does not work.

### Steps to reproduce

1. Update Desktop version
2. Open the App
3. Dark screen is showed as in image
<img width="636" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/53131553/d0b9f1cc-87cc-49e5-93a6-32167fc76367">

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
@kunkka19xx we've identified a bug that might've caused this behavior. A hotfix has been deployed. Can you restart the app to update it to the latest version or download the newest build from [download page](https://hoppscotch.com/download).

**Comment by kunkka19xx** [comment]
> @kunkka19xx we've identified a bug that might've caused this behavior. A hotfix has been deployed. Can you restart the app to update it to the latest version or download the newest build from [download page](https://hoppscotch.com/download).

Latest version from [download page](https://hoppscotch.com/download) worked fine. 
Thanks @liyasthomas 🙇

**Comment by kunkka19xx** [comment]
Thanks for your kind support
