### ISSUE TITLE
[feature]: Support OAuth2/OIDC Refresh Token

### ISSUE THREAD

**Issue by julien4215** [hoppscotch/hoppscotch#4017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Hoppscotch currently does not support Refresh Token. The feature should be the same as for Postman (see this blog https://blog.postman.com/oauth-2-0-token-refresh-and-id-token-support/)

This was already asked in the issue #337 but the part about Refresh Token was not implemented.

### Why should this be worked on?

It would be much faster to use the refresh token than having to generate each time a new token.

**Comment by pavelicii** [comment]
+1, was very surprised it is not supported.

**Comment by KamranKhorsandi** [comment]
Unfortunately, it is supported, but only in the Self-Hosted Enterprise version.

**Comment by Grasiella** [comment]
commenting on engagement, it's being a problem here too
