### ISSUE TITLE
[feature]: Choose default authorization type in a collection

### ISSUE THREAD

**Issue by julien4215** [hoppscotch/hoppscotch#4018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

By default, in a collection all requests have the authorization type set to None. It would be nice if there was an option to set the authorization type to inherit instead.

### Why should this be worked on?

This is especially useful when importing a collection from OpenAPI.

**Comment by julien4215** [comment]
Why was this issue closed ?

Is it because I didn't explain clearly the issue or because you are not interested in adding this feature ?

In case this was misunderstood, I know that the inherit option already exist but what I am asking in this issue is a way to automatically set all endpoints to the inherit option so that you don't have to do it by hand for each endpoint.

**Comment by nivedin** [comment]
Now a new request saved will have "inherit" as the default authorization and not "none" which have been implemented in the previous release so closed the issue. Overriding a already saved auth type to inherit is not a good flow. If this does not solve your issue please free to open another issue.

**Comment by julien4215** [comment]
I see, I explained the issue poorly. I'll make a new one.
