### ISSUE TITLE
[bug]: Google OAuth Login Error - Invalid Client ID in Docker Setup

### ISSUE THREAD

**Issue by Sahil624** [hoppscotch/hoppscotch#4038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Issue Description
When attempting to login using Google OAuth with the Docker version of Hoppscotch, I encounter an "Access blocked: Authorization Error" with the message that "The OAuth client was not found." Despite correctly setting the GOOGLE_CLIENT_ID in the Docker command, the system still defaults to using an incorrect or placeholder client_id value.
Setup the .env file with the necessary Google OAuth configurations.
## Run Docker command:
bash
Copy code
docker run -p 3000:3000 -p 3100:3100 -p 3170:3170 --env-file .env -e GOOGLE_CLIENT_ID='515484039189-bqi4q7jm9s6n1iq0u15q0mme9m95mk39.apps.googleusercontent.com' --restart unless-stopped hoppscotch/hoppscotch
Attempt to login via Google OAuth.
## Configuration Details
Client ID: ##############.apps.googleusercontent.com
Callback URL: http://localhost:3170/v1/auth/google/callback
All other sensitive information has been properly configured.

## Expected Behavior
The login should proceed without errors, recognizing the provided GOOGLE_CLIENT_ID.

## Actual Behavior
The login process fails with an authorization error indicating that the OAuth client was not found. The URL opened indicates that a default or placeholder client_id is being used.

## Additional Information
No relevant errors found in the Docker container logs.
Browser console does not show additional errors.
Google Cloud Platform OAuth settings have been double-checked for accuracy.
## Attempts to Fix
Verified .env file format and location.
Directly passed the GOOGLE_CLIENT_ID in the Docker command.
Checked Google Cloud Console settings for any discrepancies.
Request
I am looking for assistance in resolving this issue as it seems the environment variables are not being correctly utilized within the Docker setup. Any insights or suggestions would be greatly appreciated.

### Steps to reproduce

* Setup the .env file with the necessary Google OAuth configurations.
* Run Docker command:
```bash
docker run -p 3000:3000 -p 3100:3100 -p 3170:3170 --env-file .env -e GOOGLE_CLIENT_ID='################.apps.googleusercontent.com' --restart unless-stopped hoppscotch/hoppscotch
```
* Attempt to login via Google OAuth.

### Environment

Production

### Version

Local

**Comment by khairul169** [comment]
Have you tried resetting the server configuration?
```bash
docker exec -it <db_container_id> psql -d hoppscotch -c "TRUNCATE \"InfraConfig\";"

```

https://docs.hoppscotch.io/documentation/self-host/community-edition/admin-dashboard#hard-reset-configurations

**Comment by Sahil624** [comment]
Thanks, it worked. Closing as this is void then

**Comment by mir1198yusuf** [comment]
@khairul169 I am facing same issue & tried resetting config too but still getting same error, I have double checked my client id as well
