### ISSUE TITLE
[bug]: Tried to initialize service with no container (ID: LICENSING_SERVICE)

### ISSUE THREAD

**Issue by argoyle** [hoppscotch/hoppscotch#4047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When upgrading from 2024.3.1 to 2024.3.2 makes frontend throw the error in the title.

### Steps to reproduce

Just changing the version of the docker image from 2024.3.1 to 2024.3.2 and then reloading the UI

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment]
@argoyle We have fixed this issue with the latest `2024.3.3` release, could you please update to the latest version and try again.

**Comment by argoyle** [comment]
Seems to work fine! Thanks!
