### ISSUE TITLE
Option/setting to change the sidebar position.

### ISSUE THREAD

**Issue by sparrowsl** [hoppscotch/hoppscotch#4056]
The sidebar is kinda stuck only on the right (in vertical layout),
can we get an option to move it or resize it down even more.

**Comment by liyasthomas** [comment]
@sparrowsl are you referring to the ability to move the sidebar to the left and right of the screen? This is already possible, go to [Settings](https://hoppscotch.io/settings) page and toggle "Show sidebar on the left".

<img width="816" alt="Screenshot 2024-05-10 at 10 20 25 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/f7ba1308-fd5e-4e83-a14c-c044756e34e2">

---

Also, it is possible to completely hide the sidebar from the interface by clicking on the "Collapse sidebar" button at the right end of the screen in the footer bar. Click again to expand the sidebar back to its original width.

<img width="523" alt="Screenshot 2024-05-10 at 10 24 10 PM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/dadf2da3-9760-438d-b919-0b45f7b2c898">

**Comment by sparrowsl** [comment]
Thanks for the setting suggestion,
Only pain point now will be to resize it down more 😃😃
but I can live with it.
