### ISSUE TITLE
[bug]: Interceptor not saving selected option

### ISSUE THREAD

**Issue by KyleOrth** [hoppscotch/hoppscotch#4059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

As of https://github.com/hoppscotch/hoppscotch/pull/4051 the default interceptor has changed to Proxy instead of using the browser extension. This is affecting IP Addresses in requests being made.

Changing the setting back to Use browser extension resolves this issue. But after closing and reopening Hoppscotch, that setting is not saved and it reverts back to the Proxy, which is not working in my scenario.

### Steps to reproduce

1. Go to Settings
2. Change Interceptor to Use the browser extension to send requests
3. Send requests as needed
4. Close and re-open Hoppscotch
5. Observe settings has reverted back to using the Proxy again

### Environment

Production

### Version

Cloud

**Comment by thetronjohnson** [comment]
hi @KyleOrth are you a logged-in user or are you using the app without an account?
I reproduced this and found that this issue is only present for non-logged in users, just wanted to confirm

**Comment by JulienPerrin** [comment]
Hi, 
I reproduce the issue on PWA. 
When I open the app, the option "Use the browser extension to send requests (if present)" is no longer checked even though I checked it before. 
![image](https://github.com/hoppscotch/hoppscotch/assets/7848947/f3d48ae6-1f11-4495-8b07-88b8e49577e1)

To reproduce : 
1. check "Use the browser extension to send requests (if present)"
2. close the PWA app, reopen it
3. see that it is no longer checked.

**Comment by nivedin** [comment]
@JulienPerrin @KyleOrth thank's for reporting the issue, it should be fixed with #4060
