### ISSUE TITLE
[feature]: Record the day of the last login

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#4062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

In order to see how many active users there are on the self-hosted instance, it would be useful if we could see in the admin dashboard when a user last logged in, the date would be completely sufficient, the time is not needed.

### Why should this be worked on?

We currently cannot see how many users are actively using Hoppscotch. There are also users who have only tried Hoppscotch once and we would like to clean it up after some time.

**Comment by balub** [comment]
@RaHehl We have a small confusion we'd like you to help us out with. Could you mention what is it you are looking for?

1) Show when the user last logged into the platform.

![image](https://github.com/hoppscotch/hoppscotch/assets/14091627/4a648b8c-b439-405e-90c8-3b8a1688dcc5)

2) Show when the user was last active on the platform.

![image](https://github.com/hoppscotch/hoppscotch/assets/14091627/319d4a0a-d9a4-423b-b091-88e113597f97)

**Comment by ubaish01** [comment]
Can i pick this one ??
