### ISSUE TITLE
[bug]: When Json is beautified, the precision of long integer values ​​is lost

### ISSUE THREAD

**Issue by xiangwenx** [hoppscotch/hoppscotch#4083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When Json is beautified, the precision of long integer values ​​is lost.
It seems to be caused by the accuracy problem of the front-end script.

However, using double quotes can avoid this problem, but it will be troublesome when the JSON content is large.

### Steps to reproduce

![image](https://github.com/hoppscotch/hoppscotch/assets/56824497/045db99f-b91b-4ae6-808a-ffb1e6eab824)

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment]
Can't we use lossless-json for beautify here? @nivedin can you pick this up?
