### ISSUE TITLE
[feature]: Hopp CLI Junit report

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#4085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

For better CI/CD integration, it would be helpful to generate JUnit reports from the hopp test executions, for example by integrating junit-report-builder.

https://www.npmjs.com/package/junit-report-builder

**Comment by jamesgeorge007** [comment]
Hi, this is now released in [Hoppscotch CLI v0.10.0](https://github.com/hoppscotch/hoppscotch/blob/40f93fc7f44f25ac607eb7aace16a715f8f42255/packages/hoppscotch-common/src/pages/graphql.vue#L62-L68). Let us know if you have any feedback.
