### ISSUE TITLE
Confidential Information is stored in plain text in the DB

### ISSUE THREAD

**Issue by Breee** [hoppscotch/hoppscotch#4117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

It's simple, confidential stuff like

-  `public.Account.providerAccessToken`  (the JWT token of a user) is stored in plain text
- `MAILER_SMTP_URL` is stored in plain text which can contain credentials
- `MICROSOFT_CLIENT_SECRET` is stored in plain text, which, if someone uses a priviledged client for *some reason* , can wipe whole azure accounts in the wrong hands. 

There are probably more cases like this and I don't like it.

### Why should this be worked on?

if passwords are in plain text, the security would be compromised by anyone having a glance at it. simple

**Comment by mirarifhasan** [comment]
Hi @Breee 
Thanks for raising this concern! It has been addressed in PR #4212. I'm closing this issue as it is now resolved.

**Comment by mirarifhasan** [comment]
Hi @Breee
Thanks for raising this concern! It has been addressed in PR #4212. I'm closing this issue as it is now resolved.
