### ISSUE TITLE
[feature]: Hopscotch is a great tool, but I want to use the SOAP protocol. Is it supported?

### ISSUE THREAD

**Issue by chenjianfei1989** [hoppscotch/hoppscotch#4118]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

Hopscotch is a great tool, but I want to use the SOAP protocol. Is it supported?

### Why should this be worked on?

There is still a considerable demand for using the SOAP protocol currently.

**Comment by Fonzie-byte** [comment]
This should be possible by making a POST request to the webservice's URI, and setting the Body's type to `application/xml` or `text/xml` according to the documentation of the webservice you want to use.
You may need to add the `SOAPAction` header and possibly some other headers.

[This guide for Postman](https://learning.postman.com/docs/sending-requests/soap/making-soap-requests/) works as-is on Hoppscotch; the same URI, body type and content and headers are supported in Hoppscotch.

@Lyxnode does this solve the issue for you?
