### ISSUE TITLE
[bug]: Multiple collections/requests can be created on repeated Enter key presses from the create modal

### ISSUE THREAD

**Issue by jamesgeorge007** [hoppscotch/hoppscotch#4134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While creating collections/requests in a team workspace, repeatedly pressing the enter key while at the create collection modal will create multiple collections/requests. The click action on the button is disabled during the loading state, which should also be extended to the keypress action.

### Steps to reproduce

1. Open a team workspace
2. Click `+ New` from the collection panel to create a new root collection.
3. When the modal opens, give it a name
4. On clicking save, press enter multiple times till the modal closes
5. Duplicates of the same collection are created. The number of them created equals the number of times you pressed the Enter key before the modal closed.

This applies to creating folders/requests as demonstrated in the recording below.

  https://github.com/hoppscotch/hoppscotch/assets/25279263/da9e3c38-5402-410c-9ffa-7413a99ade6f

> While working on a fix, ensure to verify the create collection action via [spotlight](https://docs.hoppscotch.io/documentation/features/spotlight#spotlight) which opens the same modal.

### Environment

Production

### Version

Applicable to both Cloud & SH

**Comment by xLansang** [comment]
Hello! i'd love to take this issue on. Please let me know if I can be assigned.

**Comment by SanskritiHarmukh** [comment]
Hey @xLansang , Thank you for showing interest. Assigning the issue to you.

**Comment by xLansang** [comment]
Sounds great, I'll keep you updated on my progress!

**Comment by ayushmatkar** [comment]
Hii, I would love to work on this issue. Please let me know if it is to be assigned later anytime.

**Comment by xLansang** [comment]
Hello @jamesgeorge007. my solution is to add these two lines in the primary.vue file in the ui repository. My understanding is that this file contains the implementation for the "HoppButtonPrimary" button. This is my first time coding in typescript, so I wanted to test if the implementation is correct. Please let me know if I am missing something or if this would possibly cause issues. 
![image](https://github.com/user-attachments/assets/10340c2e-30ec-4bfc-ba14-e09c327bfcce)

**Comment by xLansang** [comment]
Hello @jamesgeorge007, thanks for the response! I see this approach handles both scenarios where either the smartInput or PrimaryButton is in focus. I'll raise a PR now accounting for the above cases using this approach.

**Comment by SanskritiHarmukh** [comment]
Hey @jamesgeorge007 , is this issue completely resolved? Should we go ahead and close it?

**Comment by jamesgeorge007** [comment]
The PR has been merged and scheduled for the upcoming major release. I was thinking of closing the issue once the release is out, but we can go ahead and close this now.
