### ISSUE TITLE
[bug]:  JSON response body disappears intermittently when filtering response using JSONpath.  

### ISSUE THREAD

**Issue by MutasemAlfattal** [hoppscotch/hoppscotch#4148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When typing a Jpath query, the JSON response disappears. 
This happens almost always but intermittently while im writing a query.
I need to click on Raw and click back on Json to see the response again, doing this will require me re writing the query.

https://github.com/hoppscotch/hoppscotch/assets/162300287/e4c3126c-1d58-4574-9767-6695bc0b527f

  

### Steps to reproduce

1.Click on filter button
2.Start typing a Jpath Query

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
@nivedin can you look into this?

**Comment by nivedin** [comment]
@MutasemAlfattal thank you for reporting the issue, it should be fixed with #4151

**Comment by MutasemAlfattal** [comment]
@nivedin Of course, and thank you for resolving the matter

**Comment by MutasemAlfattal** [comment]
This issue has reoccurred!

**Comment by nivedin** [comment]
@MutasemAlfattal the fix has not been merged to production yet.. will be live soon
