### ISSUE TITLE
[feature]: add 【send and download】 ability

### ISSUE THREAD

**Issue by lwxk** [hoppscotch/hoppscotch#4158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

add 【send and download】 ability

### Why should this be worked on?

add 【send and download】 ability

**Comment by lwxk** [comment]
i mean  download file api

**Comment by liyasthomas** [comment]
Click the "Download" icon in the response panel to download the API response as a file to your local drive.

<img width="1040" alt="Screenshot 2024-07-02 at 8 40 11 AM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/3fe6d94c-bb12-4ea2-8b0f-d2bc37ff3f5f">
