### ISSUE TITLE
[bug]: Not show button PWA

### ISSUE THREAD

**Issue by cesxhin** [hoppscotch/hoppscotch#4159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

A PWA button should appear near the search how your website official demo.

This installation is self-hosted with AIO

### Steps to reproduce

No visible

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment]
Can you look into the [install criteria](https://web.dev/articles/install-criteria#criteria) for PWAs?

**Comment by cesxhin** [comment]
I respected all the pwa criteria, maybe it's https that I manually generated the certificate even though it is not valid?

**Comment by liyasthomas** [comment]
That could be a reason.

> For a PWA to be installable it must be served using the https protocol, or from a local development environment using localhost or 127.0. 0.1 — with or without a port number.
> [Making PWAs installable](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable)

**Comment by Leon-Luu** [comment]
@liyasthomas I could see this issue on latest hoppscotch (2025.2.3) on Chrome. We where able to install on Chrome earlier now it is not. If I change browser to Edge I can see the install button. Something is changed here.
