### ISSUE TITLE
[bug]: pc app not network when choose mulitpart/form-data

### ISSUE THREAD

**Issue by lwxk** [hoppscotch/hoppscotch#4162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://github.com/hoppscotch/hoppscotch/assets/32501171/e6393342-d55d-4b94-86f5-7498410654c8)
### Steps to reproduce

it work when clean contentType, my controller is 
  @PostMapping("/import")
   public Response importFile(MultipartFile file, Long mId) {
       return fileService.importFile(file, mId);
    }

### Environment

Production

### Version

Local

**Comment by Ghosthh2** [comment]
![image](https://github.com/hoppscotch/hoppscotch/assets/41540922/21b6f5ea-0a45-4ed2-bf91-2f24eacb0a17)
我也出现了同样的问题
When the request body format is multipart/form-data, the issue occurs only when a file is selected. Strings, however, do not cause any problems.
