### ISSUE TITLE
[bug]: Command + return on mac should not add a newline to body, instead only send the request

### ISSUE THREAD

**Issue by alexander-williamson** [hoppscotch/hoppscotch#4164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I am editing the request body, when I hit Cmd + Enter / Return on Mac the request is sent **and also a newline is added which is unexpected behaviour**.

I expect no newline to be added, but the request should be sent, since that's the shortcut for send request.

### Steps to reproduce

Create a new request e.g., POST
Enter some sensible defaults for the request URL
Add body, hit Cmd + Enter
A newline is added (unexpected)
The request is sent (expected)

### Environment

Production

### Version

Local

**Comment by nivedin** [comment]
@alexander-williamson  thank you for reporting the issue we have a [fix](https://github.com/hoppscotch/hoppscotch/pull/4108), will be merged to production soon.
