### ISSUE TITLE
[bug]: Response Body content not showing using widget

### ISSUE THREAD

**Issue by jubu02** [hoppscotch/hoppscotch#4170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Earlier versions of Hoppscotch Widget displayed any response JSON by default but with current version there is this one liner where you can download the response but not display it within the widget in any way.. 

![Screenshot 2024-07-04 121220](https://github.com/hoppscotch/hoppscotch/assets/8514212/96949000-b10c-458e-87af-7da9718c70c1)

### Steps to reproduce

1. Visit tppvalidation.com 
2. Click send in any widget on the page
3. Response(s) not showing up (in this case as JSON) .. only the line that says there is this response body that can be downloaded.

(this somewhat replicates the behavoiur of attachments in the request body - they are also not visible in raw/code) - but that has been so in the past as well. 

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
@nivedin can you look into this?

**Comment by nivedin** [comment]
@jubu02 the bug is fixed, feel free to re-open this if the issue still persists.
