### ISSUE TITLE
[feature]: Use comments in request body

### ISSUE THREAD

**Issue by maierw1** [hoppscotch/hoppscotch#4193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Requesting the ability to add comments within the JSON request body in Hoppscotch to enhance readability and facilitate better collaboration among team members.

### Why should this be worked on?

Adding support for comments in the request JSON would greatly enhance collaboration and documentation within Hoppscotch. Comments allow developers to leave notes and explanations directly in the payload, improving team communication and understanding. This feature also aids in debugging and maintaining code by providing context for temporary changes or potential issues. Additionally, it aligns Hoppscotch with other development tools that support comments, offering a more familiar and user-friendly experience. Overall, this enhancement would make Hoppscotch a more powerful and versatile tool for developers.

**Comment by PRIZZA21** [comment]
Hi @maierw1 , I would like to work on this issue

**Comment by moonlitusun** [comment]
any progress？

**Comment by gabrielrufinof3** [comment]
+1

**Comment by gabrielrufino** [comment]
+1

**Comment by liyasthomas** [comment]
We've opened a [PR](https://github.com/hoppscotch/hoppscotch/pull/4335) that will add support to JSON with comments on editor instances. Expect this to be delivered in the next release candidate.
