### ISSUE TITLE
[bug]: Variables not populating when sending request

### ISSUE THREAD

**Issue by Maxgamerboy1** [hoppscotch/hoppscotch#4208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I set the Authorization tab on a request to a secret variable defined in Global Environment, it seems no substitution is being made.

### Steps to reproduce

1. Make a secret global variable
2. Set it in the Authorization tab (Basic Auth. for example)
3. Make a request which requires this to be populated
4. See the variable ins't replaced with it's value.

Here's an example request and response we use.
With secret variables - 
![Screenshot 2024-07-23 at 16 54 34](https://github.com/user-attachments/assets/b625ac90-7db7-4b8e-b6b9-444476a1778d)

With regular variables - 
![Screenshot 2024-07-23 at 16 56 11](https://github.com/user-attachments/assets/c113c375-6798-434a-a224-bba4bf0a4579)

May be related to - #4180

### Environment

Production

### Version

Cloud

**Comment by thomas-haufe** [comment]
On 2024.6.0, this bug seems to occur only for environment secrets, not for global secrets.

**Comment by Maxgamerboy1** [comment]
Verified on 2024.7.0, working now! Thanks!
