### ISSUE TITLE
[bug]: CLI cannot override content-type

### ISSUE THREAD

**Issue by hafizahsanraza** [hoppscotch/hoppscotch#4220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can send a WSDL request as text/xml in app, but after exporting the test as collection and trying to execute via hoppscotch-cli, the request is always sent as application/xml and not with the header I requested. In case, if I try to specify `"contentType": "text/xml"` an error _Please check the collection data._ is thrown.

### Steps to reproduce

1. create a POST request
2. under "Body" select application/xml and paste your XML content
4. under "headers" add Content-Type: text/xml
5. verify on app by sending the request if it is working fine
6. export the test as collection
7. execute the test with hoppscotch-cli
8. verify on the server-side or via network tool if the text/xml is used

### Environment

Production

### Version

Self-hosted

**Comment by jamesgeorge007** [comment]
This is patched in [Hoppscotch CLI v0.10.2](https://www.npmjs.com/package/@hoppscotch/cli/v/0.10.2). Please let us know if the issue persists. Also, `text/html` is added to the list of supported content types.
