### ISSUE TITLE
[feature]: enhance new infra api

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#4228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Thanks for implementing the new infra api.

I would kindly suggest to mention in the documentation (https://docs.hoppscotch.io/documentation/self-host/community-edition/admin-dashboard) that the InfraTokens needs to be added as Bearer Token Auth, i had to check the guard code to figgure this out.

And i would like to ask if you could add a DELETE method for Particular Users already existing.
Like "View a Particular User GET	<base-url>/v1/infra/users/{uid}" the same i would require for DELETE

And if possible it would be greate to get the "last active" of a user via api.

### Why should this be worked on?

-

**Comment by balub** [comment]
#4231 

Hey @RaHehl the additions requested were added in this PR, expect it to me be merged soon and out in the next patch release.

**Comment by balub** [comment]
@RaHehl merged, will be out in the next patch release.
