### ISSUE TITLE
[bug]: import curl missing query parameters

### ISSUE THREAD

**Issue by dungmv** [hoppscotch/hoppscotch#4262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

impor curl with query

### Steps to reproduce

```
curl -X GET 'http://localhost:8080/api/public-url' \
  --url-query 'ttl=60' \
  --url-query 'role=admin' \
  --header 'secret-key: 123456'
```

### Environment

Production

### Version

Self-hosted

**Comment by tasnim0tantawi** [comment]
```
curl -X GET "http://localhost:8080/api/public-url?ttl=60&role=admin" \
-H "secret-key: 123456"
``` 
Tried this way and it works

**Comment by dungmv** [comment]
Why can't Hoppscotch parse cURL syntax and automatically populate query parameters?

**Comment by Gaket** [comment]
@dungmv, I'd say that your example is not a valid terminal command:
<img width="739" alt="image" src="https://github.com/user-attachments/assets/0de6bff9-0de1-4ab1-9b78-b12f0de20dc6">

Though I guess it shouldn't be so hard to fix it, I wouldn't expect any tool to export requests to curl formatted this way.

**Comment by dungmv** [comment]
@Gaket sorry, it miss slash at the end of the line,
