### ISSUE TITLE
[bug]: cancel button disappear

### ISSUE THREAD

**Issue by wms-why** [hoppscotch/hoppscotch#4271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i send a  request  in tab1, the button "send" changes to "cancel ". Before the request finished , i check to tab2, and then i check back to tab1, the "cancel" button disappear

### Steps to reproduce

1. go to tab1 and send a request (you can use a delay api for better affect),  the "send" change to "cancel"
2. before the request finished, check to another tab, the "cancel" change to "send". This is normal.
3. now , go to tab1 , you can find "send" not "cancel" , i think it's wrong.

### Environment

Production

### Version

Local

**Comment by jamesgeorge007** [comment]
Hi, this is patched in [v2024.7.2](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.7.2). Please let us know if the issue persists.
