### ISSUE TITLE
[bug]: The inherit header is not showing in code snippet

### ISSUE THREAD

**Issue by leozhao0709** [hoppscotch/hoppscotch#4286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If we have a inherit header, the code snippet is not showing that header

<img width="1357" alt="Snipaste_2024-08-22_12-02-57" src="https://github.com/user-attachments/assets/97a7f0a6-124f-4dad-a502-c9b575f505fd">

### Steps to reproduce

1. Create a new collection
2. In top collection, add collection properties. Add a header here.
3. Create sub collection and add some request.
4. See the generate code snippet

### Environment

Production

### Version

Cloud

**Comment by Loznerol** [comment]
Hello, I would love to take a look at this issue if possible!

**Comment by jamesgeorge007** [comment]
Fixed in [v2024.12.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.12.0).
