### ISSUE TITLE
[bug]: Generate code button is not working

### ISSUE THREAD

**Issue by HabibMollah** [hoppscotch/hoppscotch#4314]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

The "Generate Code" button (with `<>` icon) in the side bar should show the code for the request.
In the latest version (24.8.0-0 at this moment) it's not working as expected

https://github.com/user-attachments/assets/e42e729a-a873-4c2c-9f93-2e668391ce74

### Steps to reproduce

1. go to https://hoppscotch.io/ or [download version 2024.8.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.8.0)
2. Click the "Generate code" button (with an icon similar to `<>`)
3. There's no code generated

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment]
Thanks for reporting this bug, we've opened a PR which will fix this issue. Hoping to release a hotfix as soon as possible.

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Please feel free to reach out if you have any other concerns.
