### ISSUE TITLE
[bug]: request shortcut (edit, duplicate, delete) not working

### ISSUE THREAD

**Issue by isnakode** [hoppscotch/hoppscotch#4319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

in request menu, there is shortcut hint to delete, edit etc, but nothing work

### Steps to reproduce

use D, E, Delete shortcut (not working)
use ctrl+D, ctrl+E shortcut (not working)

### Environment

Release

### Version

Local

**Comment by nivedin** [comment]
@isnakode this issue is not reproducible at our end, the shortcut only works when the menu is open, can you check again with the latest release.
