### ISSUE TITLE
[bug]: "Set as variable" overlays the text to the point that it's difficult to edit the text

### ISSUE THREAD

**Issue by subins2000** [hoppscotch/hoppscotch#4327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Video: https://subin-siby.neetorecord.com/watch/3f73b18e-8169-439b-bdde-723703f2fee4

Related to #4055, it's more annoying because it doesn't close 

### Steps to reproduce

Video: https://subin-siby.neetorecord.com/watch/3f73b18e-8169-439b-bdde-723703f2fee4

### Environment

Production

### Version

Cloud

**Comment by jamesgeorge007** [comment]
This is addressed in the [v2024.8.2](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.8.2) release. Feel free to let us know if you have any feedback.
