### ISSUE TITLE
[feature]: Allow test reports to be copied

### ISSUE THREAD

**Issue by rabbittsoup** [hoppscotch/hoppscotch#4328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like to be able to highlight and copy the text in Test Results.

### Why should this be worked on?

I would like to copy the Test Results text for various purposes, like sending to colleagues, or including in other reports, or using result data in debug situations.

**Comment by Pranay-Pandey** [comment]
@rabbittsoup @AndrewBastin 
Would exporting the `HoppTestResult` as JSON be good enough for now?

**Comment by jamesgeorge007** [comment]
#4419 released in [v2024.10.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.10.0).
