### ISSUE TITLE
[bug]: Desktop app launch after build stuck on perpetual loading spinner

### ISSUE THREAD

**Issue by pab-hue** [hoppscotch/hoppscotch#4348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I’m trying to get a local patch running for our company’s internal integration workflow.

After running `pnpm tauri build`, the build process succeeds and creates several artifacts in `hoppscotch-selfhost-desktop\src-tauri\target\release\bundle`. Installing the `.msi` creates a shortcut on the desktop. Launching the app shows a blank window first, then it moves to the center of the screen and displays a loading spinner. The process gets stuck at this point, with the spinner continuing indefinitely.

OS: Win 11, Deb 12.0, Ubuntu 24.04

Same thing happens on Linux variants too.

### Steps to reproduce

Clone the repo
Go to the project dir: `packages\hoppscotch-selfhost-desktop`
Build the application: `pnpm tauri build`
Locate the build in `hoppscotch-selfhost-desktop\src-tauri\target\release\bundle`
Install the '.msi' or '.deb' file
Launch the application using the created desktop shortcut
Observe the perpetual loading spinner

### Environment

Production

### Version

Local

**Comment by cometw** [comment]
@CuriousCorrelation Thank you so much for your help with #4352 issue. I hope you don't mind me reaching out again, but I've also encountered this same problem. Would you be able to offer any insights on this issue as well?

**Comment by CuriousCorrelation** [comment]
Hi @cometw https://github.com/hoppscotch/hoppscotch/pull/4365 should fix this!
