### ISSUE TITLE
[bug]: Label does't match when Environment quick edit

### ISSUE THREAD

**Issue by wck821829906** [hoppscotch/hoppscotch#4380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

<img width="692" alt="image" src="https://github.com/user-attachments/assets/0f892d61-f021-47d5-b3da-46a5d56b25d1">

<img width="1125" alt="image" src="https://github.com/user-attachments/assets/f1972e7c-34aa-4383-b502-0446d8ef8116">

### Steps to reproduce

1. Click "Environment Quick Peek"
2. Click "edit" in Environment variables

### Environment

Production

### Version

Local

**Comment by ayushjaswal** [comment]
Hi there, it seems that it fails to check which environment is being edited. Can I work on this issue?
