### ISSUE TITLE
[bug]: Poor contrast of highlighted text in request body

### ISSUE THREAD

**Issue by 0xSiO** [hoppscotch/hoppscotch#4389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using Hoppscotch 24.8.3 on macOS, variables in the request body result in highlighted text that is difficult to read in dark mode. Perhaps making the text white inside the highlighted portion would provide better contrast.
<img width="747" alt="Screenshot 2024-09-30 at 9 54 07 AM" src="https://github.com/user-attachments/assets/b008e374-6b87-4a13-b299-518697e728dd">

### Steps to reproduce

1. Create a request and enter any variable name enclosed in angle brackets (<< >>) inside a JSON request body
2. The red or green highlighted text is difficult to make out.

### Environment

Production

### Version

Local

**Comment by krishnakashyap03** [comment]
can you assign this issue to me, should I change the color to white or  suggest something

**Comment by jamesgeorge007** [comment]
#4464 released in [v2024.10.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.10.0).
