### ISSUE TITLE
[bug]: The send button is not working 

### ISSUE THREAD

**Issue by Emiryungul** [hoppscotch/hoppscotch#4404]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

https://github.com/user-attachments/assets/c6e4f25b-c9f3-4d03-8ac9-225b8eca9605

### Steps to reproduce

ive tried removing from task manager dowloading again after removing and restarting the pc (postman and similar applications work)

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment]
Hi there, we believe this might be related to #4403 .

Please keep an eye on it.

For the time being, please do downgrade to the previous release from the installers using this URL: https://github.com/hoppscotch/releases/releases/tag/v24.8.3-0

**Comment by Emiryungul** [comment]
yeah downgrading worked for those whos interested

**Comment by jamesgeorge007** [comment]
Hi, we have a [patch release](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.9.1) out. Please let us know if the issue persists.

**Comment by hugo082** [comment]
It seems to be back in the `24.9.2-0 (20241014.201907)`

**Comment by jamesgeorge007** [comment]
> It seems to be back in the `24.9.2-0 (20241014.201907)`

Hi, can you launch the dev tools and see if any errors are getting logged? Also, could you try clearing `Local Storage`, reloading the Desktop app, and checking again?

**Comment by hugo082** [comment]
I fixed it by clearing the cache, injected env variables were not up to date. Thank you !
