### ISSUE TITLE
[bug]: WebSocket connection fails due to mixed content when using HTTPS

### ISSUE THREAD

**Issue by keepdying** [hoppscotch/hoppscotch#4409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When cloud page loaded with HTTPS, it fails to connect local websocket clients over HTTP.
```
WSConnection.ts:33 Mixed Content: The page at 'https://hoppscotch.io/realtime/websocket' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.1.5:3000/'. This request has been blocked; this endpoint must be available over WSS.
```
Browser: Arc 129.0.6668.90 (Official Build) (arm64) 

### Steps to reproduce

try to connect a http websocket client (preferably local) on [https://hoppscotch.io/realtime/websocket](https://hoppscotch.io/realtime/websocket)

### Environment

Production

### Version

Cloud

**Comment by keepdying** [comment]
added given websocket url to here.
chrome://settings/content/insecureContent

seems browser related so closing, sorry 🙏

**Comment by Ayysz** [comment]
> added https://hoppscotch.io/realtime/websocket url to here. chrome://settings/content/insecureContent
> 
> seems browser related so closing, sorry 🙏

but how you do in desktop application then?
