### ISSUE TITLE
[bug]: I keep getting MALFORMED_COLLECTION trying to run a collection in CLI

### ISSUE THREAD

**Issue by SuthidaL** [hoppscotch/hoppscotch#4425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I got MALFORMED_COLLECTION trying to run a collection in CLI.

`MALFORMED_COLLECTION cm237iuhl016g41pea5pj7nep
Please check the collection data.`

### Steps to reproduce

1. Create a collection and request
2. Click run collection -> copy the script and use it in CLI
3. got the error

Some collections ran just fine, but some got stuck. I used to be able to run it days ago...

Thanks for any support in advance.

### Environment

Production

### Version

Cloud

**Comment by jamesgeorge007** [comment]
Hi, can you try exporting the collection and running it from the CLI via supplying the export file path and confirm if the issue persists? Also, to assist with debugging, could you share a sample collection export with sensitive contents redacted?

**Comment by ayushmatkar** [comment]
Is this issue solved? 
If not can you assign it to me?

**Comment by SuthidaL** [comment]
Hi,
I want to update that the issue has been solved by updating the CLI version. (I used 0.11.0.)

Thank you so much for the help.
