### ISSUE TITLE
[feature]: Improved Collection Runner CLI for Load Testing

### ISSUE THREAD

**Issue by shobanrajm** [hoppscotch/hoppscotch#4469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The current Collection Runner CLI lacks the ability to perform iterative runs or utilize data files for parameterized testing. This limits its usefulness for basic load testing scenarios.

### Why should this be worked on?

This feature request proposes adding command-line options to specify:
	• --iterations <number>: The number of times to run the collection.
	• --data <path>: A CSV file containing data to be used for each iteration (e.g., different user inputs).
	
	Benefits: This enhancement would significantly improve the tool's ability to perform basic load testing, enabling users to quickly assess API performance under load without needing to integrate with more complex load testing tools.

**Comment by jamesgeorge007** [comment]
This is now released in [Hoppscotch CLI v0.13.0](https://www.npmjs.com/package/@hoppscotch/cli/v/0.13.0).
