### ISSUE TITLE
[bug]:  Imported Postman environment secrets are visible under Variables. 

### ISSUE THREAD

**Issue by shobanrajm** [hoppscotch/hoppscotch#4470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, secrets within imported Postman environments are treated as regular variables. We need to correctly import and mask these secrets to maintain security.

### Steps to reproduce

1. Create a Postman environment with a secret variable.
2. Import this environment into Hoppscotch.
3. Observe that the secret variable is visible as a regular variable, not masked.

<img width="1331" alt="image" src="https://github.com/user-attachments/assets/65bac8bd-396b-4e73-9c2a-7cf4f24a8b59">

### Environment

Production

### Version

Cloud

**Comment by jamesgeorge007** [comment]
#4474 released in [v2024.10.0](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.10.0).
