### ISSUE TITLE
[bug]: pnpm tauri build  generate code something wend wrong

### ISSUE THREAD

**Issue by 188** [hoppscotch/hoppscotch#4503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

cd packages/hoppscotch-selfhost-desktop
pnpm tauri build

<img width="1322" alt="iShot_2024-10-31_18 29 55" src="https://github.com/user-attachments/assets/fc34f5bd-ccd3-49f8-a300-3c079f6d8a7f">

Root directory：
pnpm dev

generate code is normal

### Steps to reproduce

pnpm tauri build

Install the software.

Generate Code show ： Something went wrong

### Environment

Release

### Version 24.9.3

Local

just change this in vite.config.ts.
from
const ENV = loadEnv("development", path.resolve(__dirname, "../../"), ["VITE_"])
to
const ENV = loadEnv("example", path.resolve(__dirname, "../../"), ["VITE_"])

If this code is not changed, an error will occur：Cannot read properties of undefined (reading 'endsWith')

**Comment by 188** [comment]
message: "(0, querystring_1.stringify) is not a function. (In '(0, querystring_1.stringify)(request.queryObj)', '(0, querystring_1.stringify)' i…"

sourceURL: "http://localhost:3000/node_modules/.vite/deps/@hoppscotch_httpsnippet.js"

stack: "@http://localhost:3000/node_modules/.vite/deps/@hoppscotch_httpsnippet.js:11897:5…"

<img width="1105" alt="iShot_2024-10-31_19 32 12" src="https://github.com/user-attachments/assets/c2e52709-6195-4cef-a520-5817d61a21d7">

**Comment by 188** [comment]
cd packages/hoppscotch-selfhost-desktop
pnpm tauri dev or  cd pnpm tauri build  

Both of these methods produce the same error.

**Comment by pab-hue** [comment]
@188 Did you copy over `.env.example` to `.env` in the project root? The steps are at https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build

**Comment by 188** [comment]
> @188 Did you copy over `.env.example` to `.env` in the project root? The steps are at https://docs.hoppscotch.io/documentation/self-host/community-edition/install-and-build
> 
> Try that, clean `node_module` and then run dev builds, or maybe clone anew and then follow the above steps and then try again, might fix it.

@pab-hue It still doesn't work. Adding .env file only means that I don't have to change "development" to "example" anymore, but the generated code still has the same error.

**Comment by 188** [comment]
versions:24.9.3 or  main  Both versions have the same problem, is there any configuration that needs to be changed

**Comment by 188** [comment]
error：
e: TypeError: (0, querystring_1.stringify) is not a function. (In '(0, querystring_1.stringify)(request.queryObj)', '(0, querystring_1.stringify)' is undefined)

column: 54

line: 11897

message: "(0, querystring_1.stringify) is not a function. (In '(0, querystring_1.stringify)(request.queryObj)', '(0, querystring_1.stringify)' i…"

sourceURL: "http://localhost:3000/node_modules/.vite/deps/@hoppscotch_httpsnippet.js"

stack: "@http://localhost:3000/node_modules/.vite/deps/@hoppscotch_httpsnippet.js:11897:5…"

**Comment by 188** [comment]
pnpm i querystring

After executing the command
