### ISSUE TITLE
[bug]: Collection Authentication token is not inherited in nested collection requests

### ISSUE THREAD

**Issue by JonasEtzold** [hoppscotch/hoppscotch#4513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I set up OAuth2.0 settings in a collection and generate a token, the direct child requests in this collection work. However, the requests in a nested collection fail because of missing authentication, even though the request Authentication method is set to `inherit ` and the text states `Inherited OAuth 2.0 from parent collection XYZ`.

I expect the collection authorization token to be used in all subsequent requests and nested collections. However, this only works for requests on the root level of a collection.

### Steps to reproduce

1. Go to the settings of a collection
2. Set up OAuth 2.0 authorization for this collection, generate a token
3. Open a root request of that collection and in the Authorization tab set the "Authorization Type" to `Inherit`
4. Trigger the request, verify that the Authorization works
5. Create a new collection within the existing collection, go to properties and in the "Authorization" tab select `Inherit` as the Authorization Type as depicted in the screenshot:
![Screenshot 2024-11-05 084826](https://github.com/user-attachments/assets/1de02e6b-844b-4ddb-9510-474ad54499bb)
6. Create a request inside the new collection, and set the "Authorization Type" also to `Inherit`
7. Trigger the request and see that it returns an `Unauthorized` error as depicted in the screenshot:
![Screenshot 2024-11-05 085207](https://github.com/user-attachments/assets/8791e818-9487-4319-92f9-97b86f0248e2)

 

### Environment

Release

### Version

Self-hosted

**Comment by JonasEtzold** [comment]
Seems to be a caching issue on our side...closing it

**Comment by keliansb** [comment]
Are you sure it was due to cache? Because I'm facing the same issue, with the `API Key` Authorization Type.
