### ISSUE TITLE
Unable to create a team

### ISSUE THREAD

**Issue by elieobeid7** [hoppscotch/hoppscotch#4541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Im using the web and desktop version on Windows, not a self hosted version

The wiki says the button to create a team should be located in the settings, I checked the settings and the profile, can't find it

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/5f933c61-3b14-436f-99cd-589a8df6441c">

I'm using the latest version, just downloaded it yesterday

### Environment

Production

### Version

Cloud

**Comment by elieobeid7** [comment]
@liyasthomas is the concept of a workspace the same as a team in hopscotch? because postman they are two different concepts.

We're trying to migrate the company team members from postman to hopscotch, in postman we setup a team and we have team members and workspaces and we share collections between team members.


How's that workflow in hopscotch? we should create a workspace everytime and invite the same emails? can't we have them as members of the team?

**Comment by liyasthomas** [comment]
Consider a workspace as a Team inside Hoppscotch. You invite team members to the workspace, members have different sets of role access. Collections created inside a workspace will be available for all team members restricted by access roles given to them. To switch the context you can switch between workspaces.

**Comment by liyasthomas** [comment]
I’m afraid that isn’t possible. Email addresses will not be auto-filled across different workspaces. Even though it requires a one-time effort, you must manually type the invitee's email address when sending an invitation.

Additionally, it's important to recognize that different companies have varying approaches to team collaboration. Hoppscotch Workspaces typically serve as isolated spaces for team members who are working on a mission-oriented workflow.

Usually, a workspace is created for a specific project. You should only create a new workspace if the list of team members differs or if different access mechanisms are required for each team. If the same members are collaborating on multiple projects and need different access roles for each, the best solution is to create a separate workspace for each project.

**Comment by elieobeid7** [comment]
Alright then closing the ticket but I hoped that teams exist so that our team could transition seamlessly from postman without any learning curve but I'll report back what you said to me and tell them about the workspace workaround.

Thank you for your help and fast reply.
