### ISSUE TITLE
[bug]: Got an error trying to run hopp cli

### ISSUE THREAD

**Issue by SuthidaL** [hoppscotch/hoppscotch#4580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hopp used to work on my computer but now when I try to run the 'hopp' command in my terminal I got this error.

`file:///Users/suthidal/.nvm/versions/node/v18.20.5/lib/node_modules/@hoppscotch/cli/dist/index.js:5284
    body: a.instanceof(File).nullable().catch(null)
                       ^

ReferenceError: File is not defined
    at file:///Users/suthidal/.nvm/versions/node/v18.20.5/lib/node_modules/@hoppscotch/cli/dist/index.js:5284:24
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)`

I've tried uninstalling and reinstalling both hopp and node. Is there anything else I should try?

Sorry if there's already a solution in the community and I missed it. 
Also, thank you in advance for any supports.

### Steps to reproduce

1. run 'hopp'

### Environment

Production

### Version

Cloud

**Comment by jamesgeorge007** [comment]
Hi, the minimum supported Node.js version for the CLI is Node.js `v20`. If you prefer to stay on Node.js `v18`, please downgrade to `v0.11.1` of the CLI.

```bash
npx @hoppscotch/cli@0.11.1

# Install globally
npm install -g @hoppscotch/cli@0.11.1
```
