### ISSUE TITLE
[feature]: zoom in zoom out feature

### ISSUE THREAD

**Issue by swastkk** [hoppscotch/hoppscotch#4593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Need a feature for the zoom out/zoom out feature

### Why should this be worked on?

Because it is necessity.

**Comment by liyasthomas** [comment]
We'll add the zoom feature to our desktop applications soon. You can track its progress on #3545.

Since this ticket is possibly a duplicate, I'll close this ticket.
