### ISSUE TITLE
[feature]: Hoppscotch Test Enhancements: Numeric & Response time Assertions 

### ISSUE THREAD

**Issue by praveenk-78** [hoppscotch/hoppscotch#4620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This enhancement request is to introducs new assertion functions for numeric value i.e. toBeGreaterThan, toBeLessThan, toBeGreaterThanOrEqual &toBeLessThanOrEqual to Hoppscotch's API testing framework, along with the ability to assert against response duration.

### Why should this be worked on?

Current Hoppscotch testing lacks the granularity to easily perform numerical comparisons and response time validations. These additions are crucial for robust API testing, allowing developers to verify not just the correctness of data but also the performance of their APIs.

**Comment by ddierickx** [comment]
Thanks a lot @praveenk-78 , this seems like a nice addition, any idea when this would be merged and released? 🙌
