### ISSUE TITLE
Swagger aka OpenAPI support

### ISSUE THREAD

**Issue by ac2epsilon** [hoppscotch/hoppscotch#470]
Swagger aka OpenAPI support are more then possible. However I suggest not to act in a rush, and formulate some Request SChema to all WSDL alike services to use common repo and data format as possible.  AND I suggest to work thru detailed Request format and UI, which will then easily map on REST methods or visa versative. Same is true for gRPC/ ALSO all UI considerations should be suspended to final framework decision.

**Comment by liyasthomas** [comment]
This will be an awesome enhancement. Let me look up on this.

https://inspector.swagger.io/builder does the job pretty neatly. Let see how we could implement them side by side to REST requests.

**Comment by ChrisGarrett23** [comment]
It would definitely be great to have this. Right now Postman can import them, but their values are pretty wonky. Would be great to import something from testing and have it set values like "<integer>" as something that can be edited for testing. Right now Postman reads them in a way where this isn't possible.

**Comment by codeasashu** [comment]
I was trying to attempt to do the same by converting postman to openapi schema myself. Repo: https://github.com/codeasashu/openman

However, I wanted something like postman which had web support, self hosted solution so that I can be assured it won't change overtime (or atleast I can know about it). 

This project has given me a hope in right direction and I can now focus on working on this. Will give it a try

**Comment by ruruiye** [comment]
can't wait for this feature.

**Comment by asirota** [comment]
The ability to import openapi definitions from sites like swagger hub will greatly improves the possibilities for hoppscotch. 

To be sure their open source web API tester at [swaggerii](https://swagger.io/tools/swagger-ui/) already is decent but hoppscotch is a lot more handy and pretty.

**Comment by christopheblin** [comment]
Just to add my 2 cents here : i am a postman user but postman is becoming more and more (too much) oriented for the usage of postman paid platform and more and more RAM consuming.
I've tried hoppscotch and it does a decent jobs for my needs except it does not support OpenApi

**Comment by liyasthomas** [comment]
We're able to finish Team collaboration feature and or next focus is on OpenAPI support. Keep an eye out on project board: https://github.com/hoppscotch/hoppscotch/projects/6#card-53163283 for latest updates.

**Comment by KillDozerX2** [comment]
@liyasthomas I'm new around here, have quite some experience with open api(mostly codegen), I'd love to help out, is there a way you can guide me?

**Comment by liyasthomas** [comment]
Hi @KillDozerX2 , feel free to [join our public community channels](https://github.com/hoppscotch/hoppscotch#contact) too get started with contribution.

**Comment by J3m5** [comment]
I'm was evaluating hoppscotch and it has all we need except openAPI support.
Being able to generate collections and their requests is a must have for us.

**Comment by liyasthomas** [comment]
Hoppscotch now supports importing Open API and Swagger specification files.

Goto Collections > Import / Export window > Import Open API

**Comment by soracoder** [comment]
That's a fantastic feature, but It will be awesome if it can get the OpenAPI json from a URL instead of having to download the file and load it manually.

**Comment by liyasthomas** [comment]
Track the feature request to import collections from URL here: #2020.
