### ISSUE TITLE
Add support for teams

### ISSUE THREAD

**Issue by AdityaAnand1** [hoppscotch/hoppscotch#580]
Postman teams for postwoman.

More details in #507 (which is sort of a prequel for this issue)

**Comment by liyasthomas** [comment]
Noted. Currently we have support for for individual account and sync. Teams is next priority :rocket:

**Comment by car520120** [comment]
request non ajax url is ok?  Submit url to get results? For example get url: http://www.yandex.com

**Comment by tonycody** [comment]
https://github.com/brookshi/Hitchhiker

Teamwork
Personally feel the best, the postman environment does not distinguish between collections

**Comment by zhangzhaohong** [comment]
What time could you merge the code about the ability of creating a team?

**Comment by liyasthomas** [comment]
Track progress here: https://github.com/liyasthomas/postwoman/pull/879

**Comment by ziaulrehman40** [comment]
Following this issue for long time, eagerly waiting for this thing.

**Comment by tttao7** [comment]
> Following this issue for long time, eagerly waiting for this thing.

Me too !!!

**Comment by dalexanco** [comment]
Hi :)
I really love hoppscotch, the approach is modern and agile. 
But hoppscotch is a different product than postman and it should stay different.
With postman, they are trying to make money and their team feature is the best way to do it.
They designed it with this goal in mind. 

But I don't think it's the best opportunity for hoppscotch... 
I found many references to draw.io in other comments and for me, that is the best path for hoppscotch : sync files with a local/cloud folder.
Let the storage provider handle the team feature (local git repository, shared folder on google drive...). 

I read the hoppscotch code, I understand that the project is growing at a point that it's become harder and slower to add features. I'm afraid to see it becoming too complex for features that does not rely to request management. I mean, handle teams is an open door to : ACL, file conflict management and it make hoppscotch attached to a backend. 

Please keep this project as we love it : simple and not attached to a specific platform (github or firebase). 

That was the humble opinion of a regular hoppscotch user (and probably a futur contributor :D)

**Comment by AndrewBastin** [comment]
Hi @dalexanco,

Thank you for sharing your thoughts. We have already thought about many of the points you brought forward.

We are already almost done with Teams and we are introducing our own backend architecture to support it.

We have a couple of reasons for choosing a self-hosted backend architecture over the other options.

We wanted to keep the Teams features easy to use and adopt. As per our research and experimentations we found out that the experience (using files) seemed a bit lacking. We want to bring in the ability to sync up changes and work as frictionless as possible. With the self hosted backend we are able to introduce an effortless experience with more features like access control and permissions and this also allows us to introduce more fine-grained controls later on.

But at the same time, we are looking into secondary solutions as well to provide better experience and still provide a file based implementation. With the [File System API](https://web.dev/file-system-access/) and similar web stuff on the horizon and gaining support we will eventually be able to bring it forth and utilize.

As of now though, we are working on a overhauling of the state system to allow for implementing a proper Workspace feature which allows you to bring in and export your entire Hoppscotch configuration as a file which can load and switch to from. There is also significant work going on to try implementing a native app.

Thank you for using (and loving!) Hoppscotch. We are trying our best to support independent features but at the same time we want to uphold our philosophy of being an easy to use and quick platform that people can leverage to test, build and implement APIs on.

We are looking forward to seeing your awesome contributions!

**Comment by shadiramadan** [comment]
@AndrewBastin is there a status update or ETA on teams?

**Comment by AndrewBastin** [comment]
> @AndrewBastin is there a status update or ETA on teams?

Hopefully in the coming days!

Maybe even coming tomorrow 😙

**Comment by liyasthomas** [comment]
Hi everyone,

### **Today we're excited to announce that the most awaited "Teams collaboration" feature is now out for [Beta users](https://forms.gle/XPYDMp8m6JHNWcYp9).**

# **[Join Hoppscotch Teams β waiting list now →](https://forms.gle/XPYDMp8m6JHNWcYp9)**

We'll be accepting 100 users per week ❤️ 

Closing this PR on behalf of #1641

**Comment by ziaulrehman40** [comment]
This is cool @liyasthomas , the most awaited feature, finally made it in! You guys are awesome 🎉 

Any timeline/plan (even tentative) for its final release out of beta?

**Comment by liyasthomas** [comment]
If everything goes alright - probably within a week.

**Comment by AndrewBastin** [comment]
I would like to use this opportunity to thank, @oshhh @IshaGupta18, @rohanrajpal and @raghav0307 for their amazing work on helping make Teams a reality! They worked on the implementation of Teams in the Hoppscotch web app.

Thank you so much guys! 🥰

**Comment by rohanrajpal** [comment]
> I would like to use this opportunity to thank, @oshhh @IshaGupta18, @rohanrajpal and @raghav0307 for their amazing work on helping make Teams a reality! They worked on the implementation of Teams in the Hoppscotch web app.
> 
> Thank you so much guys!

It was a great learning experience. Loved working on it.

**Comment by davew94** [comment]
Have been eagerly waiting for this feature for a while and great work for delivering. Any news on how beta has went and when this will be moved into production?

**Comment by liyasthomas** [comment]
@davew94 we're working on delivering the best experience for our users. Please join the [beta program](https://hoppscotch.io/beta) and give us your feedbacks.

You can expect the Teams feature release in couple of weeks.

**Comment by liyasthomas** [comment]
### Teams are now out of closed beta.

✅   Unlimited teams

✅   Unlimited shared collections

✅   Unlimited team members

✅   Role-based access control

✅   Cloud sync

✅   Multiple devices

[Read more](https://liyasthomas.hashnode.dev/create-teams-for-collaboration-in-hoppscotch)

**Comment by binaryfire** [comment]
> @OnekO there'll be Teams support in self-hosted instances.

Hi. Just wondering if this has changed? It’s been almost 12 months since the closed beta ended and it’s still not available for self-hosted instances
