### ISSUE TITLE
[feature]: Tabs/Projects/Workspaces support

### ISSUE THREAD

**Issue by anragab** [hoppscotch/hoppscotch#690]
**Is your feature request related to a problem? Please describe.**
When you have multiple projects added to the collections the environment tab get cluttered easily as you would either create an environment per project/environment or you will prefix environment variables with project name  

**Describe the solution you'd like**
I would like to have postwomen segmented per "project"/"workspace" where I can have an isolated setup for my collections and environments and can switch across these "projects"/"workspaces" easily

**Describe alternatives you've considered**
I prefix environment variables with the project name

**Additional context**
https://learning.postman.com/docs/postman/workspaces/intro-to-workspaces/

**Comment by liyasthomas** [comment]
Tabbed instances of workspaces are in our roadmap. You can simultaneously access multiple workspaces (tabs) isolated from one another.

**Comment by tonycody** [comment]
It is recommended to refer to hitchhiker
https://github.com/brookshi/Hitchhiker

**Comment by fmiras** [comment]
Is this related to requests tabs as well? My only concern is that I can't see 2 responses at the same time to compare for example (like I do in Postman)

**Comment by tonycody** [comment]
您的来信我已收到，我会尽快回复您！！！

    ------------------------------------------------------

**Comment by nitz-iron** [comment]
Is there eta for this?

**Comment by AndrewBastin** [comment]
> Is there eta for this?

Well, for the time being we are not planning to tackle this issue. So, I will say this will be implemented when we get around to implementing it. Currently our focus is to round off the Teams experience and rework the architecture so we can provide a fully self-hostable instance of Hoppscotch, which may take a while for the transition to complete.

So the ETA will be "it will be done, when its done".
Of course, we invite the community to give it a shot if interested.

**Comment by CosmicTiger** [comment]
Hello everyone. I would like to actually help on this from the aspect of having multiple tabs for requests. For me Hoppscotch is a good tool but unfortunately been in the situation to check the `History` option in right panel is a real headache. I would love to have like a global history for all the requests the user already made and individual history for each request. In that way could help improve UX for people like me that is actually looking through multiple routes that interacts between the platform you are working on.

**Comment by AndrewBastin** [comment]
Tabs are now implemented for the REST Editor (as of 2023.4). Other editors may receive tabs support down the line based on the requirements of it. Hence, I am closing the issue.

**Comment by tonycody** [comment]
您的来信我已收到，我会尽快回复您！！！

    ------------------------------------------------------
