### ISSUE TITLE
Set Custom OAuth Provider to the Postwoman App

### ISSUE THREAD

**Issue by MarcelPa** [hoppscotch/hoppscotch#793]
**Is your feature request related to a problem? Please describe.**
Logging in to postwoman is currently possible with GitHub and Google. While this is perfectly suitable for a public instance such as postwoman.io, on a "private" instance, supplying other OAuth2 Identity Providers would be cool. 

**Describe the solution you'd like**
Allowing me to set custom OAuth2 providers in a config or something like that.

**Describe alternatives you've considered**
I am not fluent in go, hence I have not tried to find it in the code. I guess it is somewhere hidden in the firebase API? If someone could point me to the right direction, I could try to get it working and report back what is needed to get an own OAuth2 provider up and running ;-) (If I succeed that is)

**Additional context**
I work at a university, our team is fed up of those postman "You have now requests left for your team, upgrade now" messages and archiving of collections. We have an OAuth2 provider at the university we could use to allow authentication and anticipate that team feature once it lands :-)

**Comment by liyasthomas** [comment]
> I am not fluent in go, hence I have not tried to find it in the code. I guess it is somewhere hidden in the firebase API?

Postwoman is written in Javascript.

Currently we use [Firebase Auth](https://firebase.google.com/docs/auth) for authentication. As of now, we've implemented Google and GitHub sign in. Many other providers are available including OAuth.

Kindly checkout Firebase [config file](https://github.com/liyasthomas/postwoman/blob/master/functions/fb.js) and play with it.

**Comment by MarcelPa** [comment]
> > I am not fluent in go, hence I have not tried to find it in the code. I guess it is somewhere hidden in the firebase API?
> 
> Postwoman is written in Javascript.

Obviously, I mixed that up with the proxy server. My bad :see_no_evil: 

> Currently we use [Firebase Auth](https://firebase.google.com/docs/auth) for authentication. As of now, we've implemented Google and GitHub sign in. Many other providers are available including OAuth.
> 
> Kindly checkout Firebase [config file](https://github.com/liyasthomas/postwoman/blob/master/functions/fb.js) and play with it.

Thanks for the hint, will do! I guess this requires me to set up a firebase project and configure our custom OAuth provider in it. But I'll see where I land messing around with `fb.js`.

**Comment by liyasthomas** [comment]
Just mentioning some references to a complete solution for this feature.

1. [Authenticate with Firebase in JavaScript Using a Custom Authentication System](https://firebase.google.com/docs/auth/web/custom-auth)
2. [Programmatically configure OAuth identity providers for Firebase Authentication](https://firebase.google.com/docs/projects/provisioning/configure-oauth)
3. [Samples: Sign In Firebase with additional auth providers using Custom auth tokens](https://github.com/FirebaseExtended/custom-auth-samples)
4. [StackOverflow: Firebase custom OAuth authentication](https://stackoverflow.com/a/37941202)

Might be helpful to @MarcelPa or anyone who's interested in working on this feature. And as of now, there's no plan to add support for custom OAuth providers to Hoppscotch (Postwoman) - hence closing this issue.
