### ISSUE TITLE
Import of Postman collection with Nested folders is failing

### ISSUE THREAD

**Issue by nabsha** [hoppscotch/hoppscotch#850]
**Describe the bug**
If there are more than 1 level of sub folders in postman collection, then import fails without errors.
[parent-folder-3.postman_collection.txt](https://github.com/liyasthomas/postwoman/files/4593909/parent-folder-3.postman_collection.txt)

**To Reproduce**
1. Import the attached file which is in postman format 2.1 version 
2. See error

**Expected behavior**
File to be imported successfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browser chrome
 - Version : master

**Comment by liyasthomas** [comment]
@JacobAnavisca

**Comment by mahoriR** [comment]
@liyasthomas  Looks like @JacobAnavisca  is already working on this. I would be happy to contribute. I can work on weekends.

**Comment by AndrewBastin** [comment]
@JacobAnavisca are you still working on this ?

@mahoriR if you are interested, you could take this up!

**Comment by mahoriR** [comment]
> @mahoriR if you are interested, you could take this up!

@AndrewBastin  Sure. Thanks.

**Comment by liyasthomas** [comment]
Hi @mahoriR is there any updates in this issue? Let me know if you need any help from our side.

**Comment by mahoriR** [comment]
> Hi @mahoriR is there any updates in this issue? Let me know if you need any help from our side.

I'll be working on this 13th Sept onwards.  Unfortunately blocked with office work till them.

**Comment by exussum12** [comment]
Hoppscotch doesnt seem to support sub folders like this. Ive got the import working, but the front end stops working.

So its not really a postman import issue, its more a limit of Hoppscotch.

**Comment by liyasthomas** [comment]
Yes, as of now we don't support nested subfolders. Any idea how we can toggle this issue or will think about adding nested folders.

**Comment by exussum12** [comment]
I can't see another ticket for nested sub folders, This ticket would need to be put on hold until that happens. The import completely stops the front end working currently and you need to clear the local storage to continue.

Obviously thats not a great solution, so I think implement nested folders, and then look at this issue again. Whats your thoughts on that ?

**Comment by liyasthomas** [comment]
Yes, you're right. Nested subfolders should be a feature.

**Comment by exussum12** [comment]
For now, ive started a tool to convert thefolder structure.

The example here looks like this when imported

![image](https://user-images.githubusercontent.com/1102850/92299186-0fcd0680-ef48-11ea-94c1-38b3b869de02.png)


Basically everything is now in the top level prefixed with its path eg

sub1/sub2/sub3/sub4/request

will now be 
sub1 sub2 sub3 sub4/request  (so there is only 1 level deep) 

Is that useful to anyone else until the multi folders are sorted ?

**Comment by liyasthomas** [comment]
I guess that would somewhat fix current issues. Thanks @exussum12. Feel free to open a PR.

**Comment by liyasthomas** [comment]
Fixed in #1150
