### ISSUE TITLE
[feature]: Support disabling TLS certificate validation

### ISSUE THREAD

**Issue by GauthierPLM** [hoppscotch/hoppscotch#882]
**Is your feature request related to a problem? Please describe.**
I want to call an API deployed on localhost which can only be called with HTTPS but does not have any certificate. Postwoman is unable to connect to this address.

cURL has the option `--insecure` to disable TLS certificate verification.
Postman has a setting to disable TLS certificate verification.

**Describe the solution you'd like**
I would appreciate to have a setting similar to Postman' one which allow me to request HTTPS addresses without a certificate.

**Describe alternatives you've considered**
I did not find any alternative in Postwoman, so I switched to cURL (with --insecure) and Postman.

**Comment by liyasthomas** [comment]
Hi @GauthierPLM, I made a quick deploy preview with a toggle to Turn off TLS certificate validation. Kindly check whether it works.

1. Goto: https://deploy-preview-884--postwoman.netlify.app
2. Turn off the "Reject Unauthorized" toggle to accept unauthorized requests.

> ![image](https://user-images.githubusercontent.com/10395817/82352413-91416d00-9a1b-11ea-99f3-6bbe7f31fa26.png)

3. Make request and see whether it works

**Comment by GauthierPLM** [comment]
Thank you for the quick implem !
I tested it and got the following error :

> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://127.0.0.1:8082/integration/…/countries. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.

(Cross Origin Request blocked because the Same Origin policy does not allow to retrieve the resource at …
CORS header "Access-Control-Allow-Origin" is missing.

**Comment by liyasthomas** [comment]
If you're testing endpoints served locally (`localhost`), make sure you've installed Browser extension. Find links to install extension from readme.

**Comment by GauthierPLM** [comment]
I installed it, made sure the extension use is enabled in settings, disabled the verification, but the issue still occurs.

**Comment by liyasthomas** [comment]
Okay  I'll debug and let you know.

**Comment by fedemengo** [comment]
Any hacks to workaround this?

**Comment by manuman94** [comment]
Hi! We are waiting for this too. Self-signed certificates will throw an error.

Thanks!

**Comment by adrinerandrade** [comment]
There's a lot of scenarios that the development environment uses self-signed certificates. We make available http endpoints too in dev environments, to workaround, but will be really interesting this feature.

**Comment by liudonghua123** [comment]
No updates about this recently? I will make a pr later to support it.

**Comment by watchingfun** [comment]
same request

**Comment by rodrigovazquez-tc** [comment]
Is this enabled yet?

**Comment by samirmsallem** [comment]
> No updates about this recently? I will make a pr later to support it.

Hi, is there anything new? I dont see any PR related to this issue.

**Comment by Aeolun** [comment]
With the desktop application now released this has become more relevant. My local applications often run with certificates that were made for production, and validation fails.

**Comment by lpotherat** [comment]
Hi, +1 for disabling ssl verification on demand or by configuration, it is very common to have local self-signed https for development purpose.

**Comment by apofic** [comment]
+1 for skipping TLS certification validation. This app doesn't have a use-case for me without it.

**Comment by rvz420** [comment]
This missing feature is a real dealbreaker, it's the best postman alternative that  I've found but without this feature i'm unable to use it on any of my projects

**Comment by samirmsallem** [comment]
Maybe it would be a good starting point to rework the current request structure. I have experimented a bit with the cURL import feature to figure out if it is possible to add the "--insecure" flag to the request manually, to allow skipping TLS validation. This is not possible as Hoppscotch does not allow importing requests with this flag. Same goes for "-k" flag. Maybe we can adjust the cURL importer, so that there is at least a manual option to disable TLS certificate validation.

**Comment by rvz420** [comment]
> Maybe it would be a good starting point to rework the current request structure. I have experimented a bit with the cURL import feature to figure out if it is possible to add the "--insecure" flag to the request manually, to allow skipping TLS validation. This is not possible as Hoppscotch does not allow importing requests with this flag. Same goes for "-k" flag. Maybe we can adjust the cURL importer, so that there is at least a manual option to disable TLS certificate validation.
> 
> FYI, you may use https://badssl.com/ to test different certificate scenarios.

where did you touch to modify the request?

**Comment by samirmsallem** [comment]
> > Maybe it would be a good starting point to rework the current request structure. I have experimented a bit with the cURL import feature to figure out if it is possible to add the "--insecure" flag to the request manually, to allow skipping TLS validation. This is not possible as Hoppscotch does not allow importing requests with this flag. Same goes for "-k" flag. Maybe we can adjust the cURL importer, so that there is at least a manual option to disable TLS certificate validation.
> > FYI, you may use https://badssl.com/ to test different certificate scenarios.
> 
> where did you touch to modify the request?

Below the „Send“ button there is the option to show the cURL of the current request. Copy it and then in the same menu dialog click on „Import cURL“. Paste the command. I then tried to add the „—insecure“ flag but Hoppscotch did not import the request and instead just opened the default Hoppscotch request. If Hoppscotch would accept this flag and store it accordingly then we would have a workaround here.

**Comment by GuilhermeLimaSP** [comment]
4 years waiting for this feature, is it really that complicated?

**Comment by liudonghua123** [comment]
Well, I tried to investigate the deep implementation, after modified a few lines of tauri [code](https://github.com/liudonghua123/tauri/commit/0f04875fdc2df0d121ae490249c3a2af3f098fb6) and tauri app [code](https://github.com/liudonghua123/hoppscotch-app/commit/b50467026ab5378e673a4793eaf9e582fc4d03a4), I tested ok with some tests https://badssl.com/ now.

![image](https://github.com/hoppscotch/hoppscotch/assets/2276718/7ebdac0c-22e1-4775-8e09-9a6d2f5ff2a7)

Anyone interested could download the binaries from https://github.com/liudonghua123/hoppscotch-app/releases/tag/23.12.3.

See also https://github.com/tauri-apps/tauri/issues/4039#issuecomment-1923280579.

**Comment by ddnomad** [comment]
> 4 years waiting for this feature, is it really that complicated?

Why needs this feature anyway? /s

**Comment by seungick** [comment]
I solved this issue using proxyscotch, a simple proxy server for hoppscotch.
I create a patch file for proxyscotch becasuse the proxyscotch does not support skipping insecure TLS verification.
you can also apply the attached patch file to proxyscotch.

[Usage]
added a new server option: verify-sslcert <-- true or false
```
$ ./out/darwin-server/proxyscotch-server-darwin-amd64-v0.1.1 --host=xxx.xxx.xxx.xxx:xxxx --verify-sslcert=false
```


[0001-add-a-new-server-option-to-turn-ssl-certificate-veri.patch](https://github.com/hoppscotch/hoppscotch/files/14822964/0001-add-a-new-server-option-to-turn-ssl-certificate-veri.patch)

**Comment by cbolsen** [comment]
+1 for this issue. It is the only reason our dev/qa teams haven't switched from postman yet...

**Comment by sebastiangrg** [comment]
I found that the easier and more secure work-around in this case is to add the rejected certificate (in my case, a self-signed server certificate) to the browser certificate manager (trusted list). I found that this works when using the browser extension.
This solution is also suitable for less technical people that want to switch to Hoppscotch.

**Comment by Obirah** [comment]
> I found that the easier and more secure work-around in this case is to add the rejected certificate (in my case, a self-signed server certificate) to the browser certificate manager (trusted list). This works when using the browser extension. This solution is also suitable for less technical people that want to switch to Hoppscotch.

Please note that in some enterprise environments, you're not able to do that because of least privilege approaches and locked down browsers/operating systems.

**Comment by murilo-gabtech** [comment]
> I found that the easier and more secure work-around in this case is to add the rejected certificate (in my case, a self-signed server certificate) to the browser certificate manager (trusted list). This works when using the browser extension. This solution is also suitable for less technical people that want to switch to Hoppscotch.

This worked for me when hitting localhost with HTTPS. When I generate the SSL key-cert pair with openSSL, I had to add `keyUsage=digitalSignature,keyCertSign` and `basicConstraints=CA:TRUE` so my cert could be accepted by the certificate manager (Google Chrome).

Here follows how I generate my SSL pair:
```
openssl req -x509 -out localhost.crt -keyout localhost.key \
      -newkey rsa:2048 -nodes -sha256 \
      -subj '/CN=localhost' -extensions EXT -config <( \
      printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature,keyCertSign\nbasicConstraints=CA:TRUE\nextendedKeyUsage=serverAuth")
```
On top of that, the browser extension is mandatory to resolve locally served APIs. Thanks @sebastiangrg for providing the missing piece here :rocket:

**Comment by jibinge0rge** [comment]
I have a server hosted within my network that uses a local IP address and doesn't have SSL. In Postman, I can simply disable SSL verification to make the API work. How can I do the same in Hoppscotch?

**Comment by liyasthomas** [comment]
Hi @jibinge0rge, you can disable SSL verification in [Hoppscotch Desktop App](https://hoppscotch.com/download) > Settings > Interceptor section > Turn off "Verify SSL Certificates"

<img width="1470" alt="Screenshot 2024-09-17 at 1 07 24 PM" src="https://github.com/user-attachments/assets/9a563513-e750-41db-b34c-322e03d121eb">

**Comment by liyasthomas** [comment]
Thanks for your patience and valuable feedback. This feature has been implemented in the latest release.

Closing this ticket as this feature is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Comment by jibinge0rge** [comment]
When will this be available in the web interface? I am unable to install the Hoppscotch desktop app because it requires admin privileges. I only want to install the application for the current user, similar to how it's done with Postman.

**Comment by sebastiangrg** [comment]
Should we open a new issue for the same feature request in the PWA? We much prefer the web version over the desktop one.

**Comment by jibinge0rge** [comment]
This would be very helpful. I’m currently using Hoppscotch in a client environment where we have minimal control over installing applications. I believe many users might face similar challenges. I would recommend including an SSL Verification on/off option in the PWA, as well as enabling installation of the application without requiring admin privileges.

Right now, I can't even test the APIs because the SSL Verification toggle isn't available in the PWA, and I am unable to install the desktop app due to the lack of admin rights.

**Comment by s55ma** [comment]
how's the progress?

**Comment by rivolity** [comment]
Rebuild the Docker image of the Proxyscotch with your custom CA certificates.
You don’t need to modify the source code — simply adding your CA certificates to the image will resolve the issue. The application will automatically use the system’s CA bundle to verify SSL connections.

Here is the Custom `Dockerfile`

```
FROM golang:1.23.7-alpine3.21 AS builder
WORKDIR /etc/proxyscotch
COPY . /etc/proxyscotch
RUN ./build.sh linux server


# Final container
FROM alpine:3.21.3
LABEL maintainer="support@hoppscotch.io"

EXPOSE 9159/tcp

# Copy binary
COPY --from=builder --chmod=755 /etc/proxyscotch/container_run.sh /usr/bin/run_proxyscotch
COPY --from=builder /etc/proxyscotch/out/linux-server/proxyscotch-server-linux-* /usr/bin/proxyscotch

# ---- Add and register your CA certificate ----
# Copy your CA file into the image and register it
# (replace "root-ca.crt" with your actual filename)
COPY root-ca.crt /usr/local/share/ca-certificates/root-ca.crt
RUN apk add --no-cache ca-certificates \
    && update-ca-certificates

CMD ["run_proxyscotch"]
```

**Comment by christopinka** [comment]
Just used hombrew upgrade hoppscotch 26.2.0-0 -> 26.2.1-0

I don't see this feature.

<img width="1206" height="674" alt="Image" src="https://github.com/user-attachments/assets/9a7dc28d-35ca-4ba3-9114-7ac9e90e655a" />

It's now, turn off

<img width="514" height="217" alt="Image" src="https://github.com/user-attachments/assets/b158c93e-efcc-4e33-9849-b8800f14c502" />
