### ISSUE TITLE
env var objects

### ISSUE THREAD

**Issue by jgroom33** [hoppscotch/hoppscotch#902]
No code should be required to support access to environments

Env vars should allow objects

![image](https://user-images.githubusercontent.com/3970574/82898298-3f667e80-9f16-11ea-8449-dfd0b1238161.png)

**Comment by UdattaChowdhury** [comment]
Hey!! What exactly needs to be done?

**Comment by badsketch** [comment]
would be interested in tackling this. Is this still up for grabs?

**Comment by liyasthomas** [comment]
Yes, @badsketch feel free to pick this up if it excites you. Assigning this to you.

**Comment by liyasthomas** [comment]
Environments now support nested variables (since  https://github.com/hoppscotch/hoppscotch/commit/7fc757d79469d7bb72d8737aa87387fc693e4ac5), hence closing.
